### ISSUE TITLE
git sub-modules error requires manual wiping

### ISSUE THREAD

**Issue by fire** [gocd/gocd#10062]
##### Issue Type
Bug Report

##### Summary

When a git sub-modules is specified but missing a hash it can not be fixed without deleting the checkout manually or wiping the image.

###### Basic environment details

* Go Version: "21.3.0 (13067-4c4bb4780e…acfc4cfcc0b07e2eaf0595)"
* JAVA Version: `JVM version: | 15.0.2`
* OS: Linux 5.11.16-300.fc34.x86_64
* Browser vendor and version (if relevant): Not applicable

##### Steps to Reproduce

1. Fetch a git repo where the submodue is valid but the hash is non existent or incorrect url
2. Cannot clear ithe git repo without wiping the agent.

##### Expected Results
Resetting a repository should work.
##### Actual Results
Requires wiping the agent.

##### Possible Fix
No idea.

**Comment by chadlwilson** [comment]
Are you able to provide more specific steps to replicate, ideally with an example public repo and configuration?

**Comment by fire** [comment]
I find it hard to recreate. If you have any suggestions?

It happens sporadically in our configuration when a git revision with a submodule without a corresponding commit is added.

**Comment by chadlwilson** [comment]
Unfortunately I'm not clear from the above what you mean by "cannot clear the git repo" since there are no logs included, or description of what the specific error is that leads to a persistent reset failure, or any other concrete detail that would allow us to narrow it down.

Is it the git reset GoCD tries to do to a target revision? Or something it specifically does on the submodule? What is the specific "sub-modules error" and sequence that is logged when it fails?

To fix anything, we need to be able to correlate what you are describing to a specific step that GoCD takes with a given git material configuration leading to a specific error, but there's not really enough detail here for me to figure this out.

**Comment by fire** [comment]
I'll try to gather some logs. Let me get back to you.

When a git repo repository is linked to invalid hash in a submodule, I have to wipe the agent drive.

**Comment by fire** [comment]
[Uploading failure_to_reset.log…]()

**Comment by chadlwilson** [comment]
Can you please try and describe what I am actually seeing in these logs? Please spell it out as if I'm an idiot since I don't understand your setup.

The logs in this reset is not trying to "clear the git repo" though, it's just GoCD trying to ensure it hard resets to build a given commit hash which it has detected as the most recent change, but then seemingly cannot find that commit on the given branch of your repo. It does this before it does anything with the submodules.

- what does `06bc952fd3bc6a7211303e7237ea37a4d052da22` correspond to for you? it doesn't seem to exist [in your repo at all](https://github.com/V-Sekai/godot/commit/06bc952fd3bc6a7211303e7237ea37a4d052da22). Are you rebasing or otherwise rewriting history on whatever branch GoCD is building?
- what's the material configuration in GoCD here - anything special?
- which dirs are submodules and what is relevant to submodules in the logs? Is there a reason you think submodules are relevant? (I can't see anything there)
- what type of change triggered this particular build that failed?

**Comment by fire** [comment]
Sorry I can't reproduce the submodules error. I'll post more when I need do a wipe.
