### ISSUE TITLE
Read only mode Go server issues

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#1008]
~~1) Try to delete some 'notification filters' from the Preferences screen. It gives a blank screen and does not give any error in go-server logs~~

2) Post api's - even though they fail, they give no message to tell user that the operation did not complete successfully for so and so reason

3) The disabled buttons look completely washed out like here -
![disabled-buttons](https://cloud.githubusercontent.com/assets/6175869/7022957/ca08c992-dd4e-11e4-989b-dcf4bc10c507.png)

**Comment by arvindsv** [comment]
Ok, about the washed out buttons, even though it is possible to make them look better, I don't think we should spend time on that since this is not going to be seen most of the time. Is that ok?

About the blank pages, etc. is it ok if those show a message (just an empty page with a message in the font "Courier New") or should it show an error page, like the :( page that shows. Both are possible. Let me know.

**Comment by arikagoyal** [comment]
> Is that ok?
Yes

> Since in most cases, when things don't work we end up showing :( page so that's a more preferred option with the appropriate error message below it.

**Comment by arvindsv** [comment]
Ok, I've done that in #1024. Take a look.

**Comment by arikagoyal** [comment]
Issue 1 is fixed in 15.1.0(1813-b9604e0416eff3). Other issues would be addressed later

**Comment by arvindsv** [comment]
Closing. Maintenance mode has been revamped completely.
