### ISSUE TITLE
Safari - UI shifting to the left when clicked

### ISSUE THREAD

**Issue by drulmc** [gocd/gocd#10216]
##### Issue Type

Bug Report

##### Summary

On the latest Safari and macOS, when any of the stages buttons are clicked, the element is shifted all the way to the left.

Please look at the screenshots

##### Environment

GOCD v21.4.0

###### Basic environment details

* Go Version: `21.4.0`
* JAVA Version: `15.0.2`
* OS: `Linux 5.4.170+t`
* Browser vendor and version (if relevant): `macOS 12.2.1 - latest safari + safari technology preview (140)`

##### Steps to Reproduce

1. click a pipeline stage
2. button moves to the left, sometimes off screen

##### Expected Results

Buttons stay where they are.
Modal opens in correct place.

##### Actual Results

Buttons + modal shifts to the left

##### Code snippets/Screenshots

<img width="295" alt="Screenshot 2022-02-24 at 14 40 41" src="https://user-images.githubusercontent.com/21034587/155547139-a59d5732-d61e-4459-ab95-a9a8e63ea5da.png">

<img width="344" alt="Screenshot 2022-02-24 at 14 40 50" src="https://user-images.githubusercontent.com/21034587/155547136-6d342217-5679-4545-93db-1fe7fd68ea8b.png">

<img width="290" alt="Screenshot 2022-02-24 at 14 41 01" src="https://user-images.githubusercontent.com/21034587/155547132-4c516fdd-8d79-440c-bdd9-ebdac6947281.png">

<img width="624" alt="Screenshot 2022-02-24 at 14 40 20" src="https://user-images.githubusercontent.com/21034587/155547146-42501e0b-d1b8-40b0-8cbb-3fbce89d09d9.png">

<img width="746" alt="Screenshot 2022-02-24 at 14 40 29" src="https://user-images.githubusercontent.com/21034587/155547141-67310c2b-d934-46ef-b6f7-6f4e589e2cb4.png">

**Comment by chadlwilson** [comment]
Do you know what changed that made this observable to you? The Safari version? Or the GoCD version was upgraded? In other words, which combinations do you think this was working OK on?

**Comment by chris-gillatt** [comment]
@chadlwilson I work with @druchavda FYI.

We've done a lot of upgrades recently to get ourselves up to date, and we believe this issue has arisen over the last two or three upgrade hops we needed to perform in order to maintain service. 

The versions we think issue was introduced in is between v20.8.0 and 21.1.0. We only upgraded to 21.4.0 today and this issue was observed before that hop. We jumped from v20.8.0 to 21.1.0 previously. 

The bug does not appear to affect Firefox or Chrome currently. If you need the full upgrade path we took, please let me know.

**Comment by chadlwilson** [comment]
Yeah, seems some some webkit CSS quirk as a result of opening the overlay I guess (alas CSS is not my forte). On the dashboard and pipeline activity at least, if I manually "touch" the css in the inspector with the overlay open it corrects itself on re-render, but closing and re-opening the overlay will re-trigger the problem.

I'm guessing it might not help to dig back that far unless it can be pinpointed to a specific GoCD version upgrade (or Safari upgrade, which you don't appear to think it is).

**Comment by chadlwilson** [comment]
After a bit more digging, I'm pretty confident this is a Safari/webkit bug with their flexbox implementation. 

Bit more technical detail, but it seems to be including the width of the `position: absolute` popup in the flex box it belongs to, which it should not based on my spec interpretation. This is causing it to flow the item to the next row or add a whole lot of stretching space it should not.

**Safari 15.3** (broken):
![image](https://user-images.githubusercontent.com/29788154/155754917-cf5637b2-3ded-4542-a07c-e8655b396c5f.png)
It's also broken in Safari 12/13/14 based on some quick browserstack testing.

**Chrome 98** (correct)
![image](https://user-images.githubusercontent.com/29788154/155755037-60636631-418b-4ccb-9814-4cc346d359be.png)

**Firefox 97** (correct):
![image](https://user-images.githubusercontent.com/29788154/155755567-7e971aba-37d4-44f7-bd74-6247adb548ab.png)


For **Pipeline Activity** view, it's even _more_ buggy and weird on production `15.3` build than it is on Safari Technology Preview 140 (targetting `15.4`). It seems they are [actively fixing some flex box problems](https://developer.apple.com/safari/technology-preview/release-notes/) but since this seems to have been around for a while, I guess they might not fix it. Hmm.

Safari/webkit seems to do pretty poorly in the flexbox tests suites it seems... https://wpt.fyi/results/css/css-flexbox/abspos?label=master&label=experimental&aligned

The only workaround I have so far is fixing the width of the flex container, which kind-of defeats its purpose as a flex container. Will have to have a think.

**Comment by drulmc** [comment]
Hey, just wanted to know if there's been any more progress on this issue? 
I don't think apple are going to fix this from their end 🤣

**Comment by chadlwilson** [comment]
Unfortunately I don't know of any practical workaround here, but CSS isn't my strong suit and I couldn't figure out whether something changed on GoCD side at some point - so PRs or suggestions welcome.

**Comment by chadlwilson** [comment]
Believe it or not, this appears to be fixed in Safari Technology Preview 161, so my guess is it will make its way into Safari 16.3. Here's hoping....

**Comment by chadlwilson** [comment]
The next preview build of Safari `16.4` (Safari Technology Preview `162`) has been released, and the problems remain fixed on both Dashboard and Pipeline Activity with no noticeable regressions elsewhere.

I think it seems safe to say that this will be fixed with Safari `16.4` which I would guess Apple will release in the next 4-6 weeks (Safari `16.3` was just released alongside Ventura `13.2`)

Will re-open if they end up reverting the changes for some reason.

**Comment by chadlwilson** [comment]
FWIW MacOS Ventura 13.3 and Safari 16.4 are out now, and have confirmed it's still fixed in the release version.
