### ISSUE TITLE
Notification plugins should not be loaded when error happens during startup

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1027]
When the plugin API is not able to handle the "notifications-interested-in" go plugin api request. It should disable the plugin.

**Comment by arvindsv** [comment]
Let's talk about the impact of this (to decide whether this should go into 15.1 or later). If it is not disabled, what happens?

1. During notifications-interested-in, if it fail to respond properly, does Go handle that properly, and not register that plugin for any notifications? If so, I think we can move this out of 15.1.

2. If not, and it fails, I think we can handle it properly on the Go side, and either disable the plugin or not. I don't mind either. I'd actually vote for not disabling it. I think we should allow multiple plugin endpoints to be registered by one plugin. When that happens, disabling a whole plugin because of this could cause problems.

**Comment by zabil** [comment]
The error during 'notifications-interested-in'  gets logged on go-server no further requests go to the plugin as it's not registered (i think).

I agree on point 2. If the plugin handles multiple end points then disabling it is wrong.

**Comment by arikagoyal** [comment]
For now, error getting logged in go-server.log seems to be decent enough thing. Moving it out of 15.1

**Comment by zabil** [comment]
Closing this because the plugin may handle multiple end points
