### ISSUE TITLE
Same material on different pipelines: can't set different configuration.

### ISSUE THREAD

**Issue by ciscox83** [gocd/gocd#1033]
1. set up two pipelines A, B
2. configure on pipeline A a material X as a git repo and make it poll for change.
3. try to configure on pipeline B the same material X and this time configure to DO NOT pull for changes.

What you'll get:

```
Material of type Git (git@xxx) is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of the a material should have the same value for this attribute.
```

**Comment by arvindsv** [comment]
Yes, this is not a bug. It's intended behavior. As it says, "All copies of the a material should have the same value for this attribute". Reason: In Go, unique materials are decided, and they're polled or not polled based on the autoUpdate attribute. If the same material has both autoUpdate true and false, then it will need to be polled (for the true) and not polled (for the false). That doesn't make sense.

If we were to somehow make this happen, pipeline B would trigger every time pipeline A found that material X has a new commit.

If you're looking to turn off polling, so that pipeline B does not trigger automatically. If that's the case, you can keep material X with polling turned on (in both) and make pipeline B's first stage manual.

**Comment by srinivasupadhya** [comment]
... or you can use blacklist - [discussion thread](https://groups.google.com/d/topic/go-cd/rBouLywo3a4/discussion)

**Comment by matt-richardson** [comment]
Sounds like an implementation issue, rather than a design decision.

Materials appear to be at a higher level than pipelines. So material polling is done before deciding which pipeline to trigger. This does not match what the UI suggests.

I would suggest that this is a valid "bug" - in terms of "the effects of the implematation are not ideal". I dont think this should be closed.

**Comment by arvindsv** [comment]
What should happen, then, when the same material is set to poll and not poll?

Yes, materials are at a different level. A commit needs to be found, before deciding that a pipeline needs to be triggered. That's the cause for a pipeline trigger. So, it's happens before the trigger.

I don't mind reopening this issue, but without a broader rethink of materials and the UI around them, this is not going to help, in its current form. I can, if you care about it a lot. But, someone will need to work on it, sometime. It's not going to get "fixed", otherwise. :)

**Comment by ciscox83** [comment]
Thanks @arvindsv for the reply. The solution you propose does not actually work for me. I do have two materials per pipeline X, Y. I do need to trigger the pipeline for every update on Y but not on X. Setting the first stage as manual it means we are not doing anymore CD :) Could be just that you always poll for changes, but you apply them only on the workspaces (because every pipeline use a different one) which have the autoPolling set to 'true'?

Thanks @matt-richardson I agree with you.

**Comment by arvindsv** [comment]
> Could be just that you always poll for changes, but you apply them only on the workspaces (because every pipeline use a different one) which have the autoPolling set to 'true'?

Yes, that would make sense. However, the way it is today, autoPolling is an attribute of the material, and doesn't have any effect on the pipeline trigger. You are proposing changing it to mean something like: "triggerWhenChanged".

**Comment by ciscox83** [comment]
Yes. In the end this is the reason why you let enable or disable the autopolling on materials: to have some sort of control on the automatic pipelines triggering (at least to my point of view).

**Comment by arvindsv** [comment]
From what I know of it, it was meant to be used with manual stages, and to reduce the effect of too many materials polling a repo (or many repos) too often.

I think the broader issue is that the material information (such as URL, branch, etc) should really be at a higher level (common across pipelines), but information such as whether to trigger, how often to poll, etc. should be at a pipeline level. The fact that those two are not separated is why all of this happens.

**Comment by srinivasupadhya** [comment]
@matt-richardson like @arvindsv mentioned materials are at level higher than pipelines. We are trying to make that evident on the UI & Config. We have `<repositories />` & `<scms />` at top level of the config & the UI reflects that. I hope some day all built-in scms are moved out as plugins, that way they all move a level higher.

> to have some sort of control on the automatic pipelines triggering (at least to my point of view).

@ciscox83 you can use [black-list](http://www.go.cd/documentation/user/current/configuration/admin_add_material.html#blacklist) as i have mentioned before.

**Comment by ciscox83** [comment]
@srinivasupadhya can you explain better? Dou mean that I should put autopolling to true on all the pipelines and then blacklist all the project that I want to not to be triggered? If so this sounds like a workaround rather than a proper solution. But can actually work.

**Comment by srinivasupadhya** [comment]
@ciscox83 yes thats what im suggesting. `autoUpdate` or "poll for new changes" is to control wether Go should poll the material for new changes.

'blacklist' was created to give control of what file changes the pipeline should trigger. You would basically be using it to say "for no file change". I don't see it as a work-around.

**Comment by Ehekatl** [comment]
Same problem, we have a group of agents working on different environment (eg. UAT, Staging), so UAT could be a upstream pipeline for Staging, but we only wanna they use the same material, which means UAT pipeline always fetch but Staging pipeling don't.

**Comment by bpwells** [comment]
What's the status of this?  This is a pain in that, even if I want to turn off polling, I cant, due to this error message.  It's telling me both pipelines have to have the same attribute value for polling, therefore if I have two pipelines pointing to the same GitHub repo, I can't change the value at all.  Very inconvenient.  Generally speaking there are too many rules baked into Go that end up painting you into a corner.  I understand this is by design but the design needs to be rethought.

**Comment by ckaushik** [comment]
The workaround I've found is to create a another GoCD material with a new ID to poll the same repository. I use this plugin for doing that - https://github.com/TWChennai/gocd-git-path-material-plugin.git

**Comment by wThomas84** [comment]
Hi,
regarding to @arvindsv last comment;
would it be possible to implement the decision whether to fetch an update of a material by a logical AND combination of all pipelines' "poll for changes" settings?

**Comment by tateexon** [comment]
I am having this issue as well. It would probably be best to give the user the option of using the existing Material but have the option of creating a new one. I am currently in the situation where I have 4 pipelines using the material in polling mode but I want to set up a webhooks for a single pipeline. We want to go the route of using the webhooks instead of polling and slowly convert the rest of the pipelines as we go. Can't currently do this with the way it works now because we need to get at least one job working to prove it does work and build up confidence before moving the other pipelines. Feel like I am backed into a corner and I either have to leap blindly or not leap at all.

**Comment by arvindsv** [comment]
@tateexon If you change the URL slightly, by adding a `/` or something, it'll start seeing it as a different material. It's an option for you to consider. For instance: `https://www.github.com/abc/def` is a different material from `https://www.github.com/abc/def/` which is different from `https://www.github.com/abc/def.git`.

You'll have to think about whether you really want to do this, because for fan-in purposes as well, it'll be considered different. However, since you mentioned being backed into a corner, thought I'd mention this.
