### ISSUE TITLE
How the output of the stage can be used for the next stage

### ISSUE THREAD

**Issue by liuwenzhi0318** [gocd/gocd#10380]
Example：
    I have two stages in a pipeline. The task of the first stage is to compile and generate a compiled file, and the task of the second stage is to get the compiled file to make a docker image.
The problem now is that I haven't found a solution. How to get the product file of the first step in the second step

**Comment by liuwenzhi0318** [comment]
In the first stage, the build product is to upload the file to the gocd-server, so can the gocd-server download the product in the second stage?

**Comment by chadlwilson** [comment]
It would probably be better to ask these kind of "howto" questions on the [Google Groups user list](https://groups.google.com/g/go-cd/) or GitHub [discussions](https://github.com/gocd/gocd/discussions) rather than here, since this is primarily for feature/bug tracking.

To achieve what you are trying to do, you would specify an "[artifact upload](https://docs.gocd.org/current/configuration/managing_artifacts_and_reports.html)" configuration in your first stage's job, and then add a **fetch artifact task** to your second stage's job to "fetch" that artifact. This whole process has some [documentation here](https://docs.gocd.org/current/introduction/concepts_in_go.html#artifacts).

Artifacts used this way are stored/managed by the GoCD server.

**Comment by liuwenzhi0318** [comment]
谢谢
