### ISSUE TITLE
Support Plastic SCM

### ISSUE THREAD

**Issue by fire** [gocd/gocd#1040]
It doesn't seem like go supports plastic scm. My plan is to look at the perforce material code and support plastic.

https://www.plasticscm.com/home.html

**Comment by srinivasupadhya** [comment]
great :) consider creating a [SCM plugin](http://www.go.cd/documentation/developer/writing_go_plugins/scm_material/scm_material_plugin_overview.html) instead of adding it to core.

sample plugins - [git](https://github.com/gocd/go-plugins/tree/master/plugins-for-tests/test-scm-plugin), [github](https://github.com/ashwanthkumar/gocd-build-github-pull-requests)

**Comment by krysis09** [comment]
Very interested in this plug-in for Go.CD as well. I was thinking of working on this when I found this issue.

**Comment by fire** [comment]
If you want to attempt to make one, feel free. I've been distracted by work.

**Comment by fire** [comment]
Has there been any changes I should be aware of in the current build?

**Comment by arvindsv** [comment]
Closing this, as it has nothing to do with GoCD core directly. As @srinivasupadhya mentioned, an SCM plugin can do this.
