### ISSUE TITLE
GOCD extreme slow perfomance cpu 

### ISSUE THREAD

**Issue by u001920** [gocd/gocd#10480]
Hello guys

My scenario is as follows:

We have about 1000+ pipelines in 1 single repository

Sometimes we have performance issues to update the issues and also to trigger the pipeline.

I noticed that the CPU thread is always at 200% to 300% on a single thread.

Today we use an aws instance: `m5d.16xlarge`

I`m checked memory and disk stats

What can I do to find out where my problem is?

```
Go Server Version: | 21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)
JVM version: | 15.0.2
OS Information: | Linux 5.4.172-90.336.amzn2.x86_64
Usable space in artifacts repository: | 116.43 GB
Pipelines Count: | 5330

AWS instance: m5.16xlarge - 250GB memmory and 64 Cores
```

##### Expected Results

Make configrepository efficiently and triggers faster

##### Actual Results
1. Currently putting a configrepository to update takes about 1h , when there are more than 10 configrepo updating gocd takes about 3h

2. Pipeline trigger takes 40 minutes to start

![image](https://user-images.githubusercontent.com/99207749/171044152-7402aeac-f130-4cf4-ad0f-f11605037381.png)
![image](https://user-images.githubusercontent.com/99207749/171044171-ef45ff3e-0176-4327-bf5b-dcaf8ed0140b.png)

**Comment by chadlwilson** [comment]
I think I'd need a more specific description of what the "performance issues" are to give any suggestions. Is it completely locked up for periods and then comes OK? Is it just slow for a period? Is it slow at all times? How slow? Which things are still fast/normal and which things are slow? Can you explain what you mean by "update the issues"?

One thing that strikes me about that screenshot is that you are allocating an absolutely huge amount of memory to the JVM - allowing in the range of 16GB to 256GB. Your heap is using at least 43GB of that. I suspect the JVM will not perform so well with such a configuration as it gives it a huge amount of garbage to manage and clean up. While I don't know the appropriate/optimal memory usage for your environment, I would normally not suggest such a large heap. It can make things worse rather than better due to time spent managing memory, depending on your machine's spec. However, right now we don't have evidence that is your main problem.

Other than that
* please supply the information requested in [the issue template](https://github.com/gocd/gocd/issues/new). GoCD version, environment etc etc.
* And which database are you using? H2 database or separate Postgres/mysql DB?
* the results from `/go/api/support` may also help (please review and redact any private information)

**Comment by u001920** [comment]
Thank you very much for the information

I'm updating the title with more information about my environment,

The complete log file at this link:

https://gist.github.com/u001920/ec7ddf1df18b8aaba12631db72f5160f

**Comment by u001920** [comment]
UP! Can someone help me?

**Comment by chadlwilson** [comment]
In general you might get more "eyes" if you ask such questions on [the Google Group](https://groups.google.com/forum/#!forum/go-cd) rather than this issue tracker, since this is mainly focused around development issues/bugs.

Unfortunately, I asked a few questions to gain more understanding of your setup that I don't have answers for. But here are my observations. Since the Gist is just a single snapshot of the state of GoCD, it can be difficult to draw conclusions though.

1. You have a **very** large number of schedulable materials (`5166`).
2. You are using the third party `gocd-build-github-pull-requests` PR build plugin (in feature-branch mode), which is possibly creating a lot of these materials in terms of branch builds.
3. There are quite a lot of errors in server health from checking these feature branch materials. Are you overloading or hitting rate limiting of requests to the target Git repository service? Are these commands timing out and failing and having to be retried over and over?
4. The workers that check for material/Git updates are mainly blocked waiting for Git Commands to exit, however they are not all busy in this snapshot.
5. The workers that check config repositories in that snapshot are mainly blocked trying to save/update your GoConfig configuration it seems.
6. You have a large instance, using the H2 database, rather than a separate Postgres or Mysql DB. This might not be the root of the problem, however 
7. You seem to have historically set `GO_SERVER_SYSTEM_PROPERTIES` to increase threads for material updates (to `64` each, which is quite large) at some point, but these increased values are _not taking effect_. This env var was changed some time ago to no longer be respected in GoCD `19.6.0` (see #6627). If these values used to be helpful, and you saw this performance decrease after upgrading to GoCD 19.6+, you might want to try re-applying them correctly via the wrapper config.

I would suggest a few things you could try and do.
* If you think config repos are the main problem (rather than regular material checks for repos) you could try increasing `config.material.post.update.threads` (default: 2) and/or `material.config.check.threads` (default: 2) to a larger value (as noted in #8565). If this doesn't improve things, the contention is probably elsewhere (database or Go Config file)
* Review the plugin logs from the `gocd-build-github-pull-requests` plugin to see if you can find out if requests are failing extremely often.
* Can you do anything to increase the disk speed for the place that your GoCD config and H2 DB are stored?
* Assess how fast your Git access is. If the modification checks are faster, then GoCD will get less blocked. Speed of material checks could be affected by 
    * the disk speed of the GoCD server
    * network speed/latency to your Git repository manager.
* Generally try and reduce the number of materials you have. Do you really need 5,000? How many of these are branch/PR builds? Are the branches being deleted when they are merged so the materials disappear?
* Consider whether you can move to [webhook based notifications](https://api.gocd.org/current/#webhook) from Bitbucket -> GoCD rather than polling Git repos for materials. This will scale much better with 5,000+ materials. I'm not sure if that works with that PR/feature branch plugin though - I am not familiar with it.

**Comment by chadlwilson** [comment]
Since this doesn't appear to be a defined issue with GoCD that can be addressed, I'm going to close this now, but happy to continue the conversation.
