### ISSUE TITLE
Null parameter causes invalid command on Windows

### ISSUE THREAD

**Issue by manuelxmarquez** [gocd/gocd#10521]
##### Issue Type
- Bug Report

##### Summary

When using a parameter in a template job that is not set in the pipeline, the command path is incorrect.
```'C:\Program' is not recognized as an internal or external command```

This used to work. Last updated about a year ago.

##### Environment

Go Server: Windows 7
Go Agent: Windows 7 and Windows 10

###### Basic environment details

* Go Version: GoCD Version: 22.1.0 (13913-f4c9c1650e2e27fe0a9962faa39536f94f57e297).
* JAVA Version: 17.0.2
* OS: Windows 7 6.1

##### Steps to Reproduce

Create a template that uses a property as an argument.
Create a pipeline using the template and leave the property unset.

I have not tested this in GoCD but trimmed a config file that produces the error.

```
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="139">
  <pipelines group="TestGroup">
    <pipeline name="TestPipeline" template="TestTemplate">
      <params>
        <param name="Property1">/p:TestValue=Test</param>
        <param name="Property2" />
      </params>
    </pipeline>
  </pipelines>
  <templates>
    <pipeline name="TestTemplate">
      <stage name="TestStage">
        <jobs>
          <job name="TestJob">
            <tasks>
              <exec command="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe">
                <arg>#{Property1}</arg>
                <arg>#{Property2}</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
</cruise>
```

##### Expected Results

Command should execute the full path correctly.

##### Actual Results

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

##### Possible Fix

Set a dummy property value that does not affect the actual command

```<param name="Property2">/p:Dummy=Dummy</param>```

**Comment by chadlwilson** [comment]
The config above isn't valid, but I think I get the idea.

Have you confirmed that setting the property value actually fixes/works around this? I'm not sure the issue here relates to either templates or parameters - it seems to be to do with the command having an absolute path with spaces in it.

Seems the same as #4173 - you might want to try and workaround in https://github.com/gocd/gocd/issues/4173#issuecomment-596109199

**Comment by manuelxmarquez** [comment]
```The config above isn't valid, but I think I get the idea.```

That's correct, it's a sanitized version of my config file to give you an idea of to reproduce the issue.

```Have you confirmed that setting the property value actually fixes/works around this?```

Yes, I have been able to fix the issue by setting a dummy value as shown above.

```I'm not sure the issue here relates to either templates or parameters - it seems to be to do with the command having an absolute path with spaces in it.```

I don't think it relates to templates but that is how my config is set up so I just posted what I had tested in case it is related. It does seem to be more related to the spaces than anything.

```Seems the same as https://github.com/gocd/gocd/issues/4173 - you might want to try and workaround in https://github.com/gocd/gocd/issues/4173#issuecomment-596109199```

I had read through that post but it didn't seem to conclude what the actual issue was. I did not try that solution since my config had worked before I updated and it was not as ideal (required more changes and testing).

I had also tried the following config fixes:

```<param name="Property2"></param>```
Same result as ```<param name="Property2" />```

```<param name="Property2"> </param>```
Adds ```" "``` to the args list but fails.

![image](https://user-images.githubusercontent.com/30425852/173586137-b78b068f-eccf-477c-9774-8d8e933027a1.png)
![image](https://user-images.githubusercontent.com/30425852/173586156-65264c2a-7604-4ebb-998b-71654739cf4d.png)

**Comment by chadlwilson** [comment]
I can't replicate what you've described above. Whichever values I set for the parameters, I get the `'C:\Program' is not recognized as an internal or external command` failure (which is caused by the linked issue - failure to properly escape values with spaces in them when launching commands).

The specific content of the arguments/parameters and the dummy values is probably important to whether there is some workaround for the root problem, so if you have redacted the values in the config example I think I'd need an actual example that demonstrates values for arg/parameters that when present somehow "fixes" the entire command and allows it to work.

**Comment by chadlwilson** [comment]
OK, EDIT - I think I can replicate it now. Was confused by the completely bizarre way Windows/`cmd` parses the command if the binary doesn't exist at the chosen location and there are spaces in the path. 🤦‍♂️ After switching to a binary that _does exist_ on my system I think I can replicate the same weirdness above. Seems related to #4173 (strange command arg parsing) but a bit different.

Are you suggesting that blank/empty args should be ignored, or should otherwise fail somewhere else?

Can you clarify what you mean by `This used to work. Last updated about a year ago.` above? You mean you think it used to allow blank/empty args without creating the error above on `21.2.0` but now doesn't on `22.1.0` which you updated to recently?

**Comment by manuelxmarquez** [comment]
Thanks for looking into this!

I have a few agents that have been building this config file for a couple years with no issues. I recently updated GoCD server and all agents within the last couple weeks and started seeing this error. I can view the successful logs from before the update but I cannot find a version anywhere. However, I usually save the installation files just in case I need to revert. This is what I have:

```
go-agent-20.8.0-12213-jre-64bit-setup.exe
go-agent-21.2.0-12498-jre-64bit-setup.exe
go-agent-22.1.0-13913-jre-64bit-setup.exe
go-server-20.8.0-12213-jre-64bit-setup.exe
go-server-21.2.0-12498-jre-64bit-setup.exe
go-server-22.1.0-13913-jre-64bit-setup.exe
```

So I must have been on 21.2.0 when it worked and started to see the error once I updated to 22.1.0.

My particular use case is I have over 30 pipelines that build websites and desktop applications. I created a couple templates so I don't have to copy/paste a bunch of configs and made more of a generic template to build all projects. For example, websites are uploaded to an FTP server in a job. The host address and configuration details are passed to MSBuild on the command line. Desktop applications don't get uploaded though, so those properties are left blank and the job runs but does nothing.

So I would expect blank or empty properties to be ignored or have no effect (like string concatenation of a zero length string).

For example, given the config snippet below:
TestWebsite would run the command
```"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /p:ConfigFilePath=WebSite.targets /p:FtpHost=ftp://ftp.example.com```

TestApp would run
```"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /p:ConfigFilePath=App.targets```

```
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="139">
  <pipelines group="TestGroup">
    <pipeline name="TestWebsite" template="TestTemplate">
      <params>
        <param name="BuildSettings">/p:ConfigFilePath=WebSite.targets</param>
        <param name="FtpSettings">/p:FtpHost=ftp://ftp.example.com</param>
      </params>
    </pipeline>
    <pipeline name="TestApp" template="TestTemplate">
      <params>
        <param name="BuildSettings">/p:ConfigFilePath=App.targets</param>
        <param name="FtpSettings" />
      </params>
    </pipeline>
  </pipelines>
  <templates>
    <pipeline name="TestTemplate">
      <stage name="TestStage">
        <jobs>
          <job name="TestJob">
            <tasks>
              <exec command="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe">
                <arg>#{BuildSettings}</arg>
                <arg>#{FtpSettings}</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
</cruise>
```

Hope that clears things up.

**Comment by chadlwilson** [comment]
Thanks. Hmm, can't think of anything obvious that might have changed to cause that (other than the underlying/default Java version) but doesn't mean something didn't...
