### ISSUE TITLE
Trigger pipeline without configrepo update

### ISSUE THREAD

**Issue by pereiratps** [gocd/gocd#10560]
##### Issue Type

- Feature proposal

##### Summary

Option to disable configrepo update in manual pipeline trigger. It could be on the UI (Trigger without configrepo update) or even on the server for all pipelines.

Updating configrepo is time consuming, especially if you have many configrepos or pipelines. This feature would help to improve the experience of using the tool.

**Comment by chadlwilson** [comment]
I'm not sure I understand what you're asking for and what "Option to disable configrepo update in manual pipeline trigger.". Not sure what triggering  a pipeline has to do with updating config repos or in what specific configuration that is a problem.

Would it be possible to please follow the issue template and instead describe the steps to follow and what you observe happening, and then what you instead expect to see happening with the proposed feature?

**Comment by chadlwilson** [comment]
OK, I think I see what you are talking about - thanks.

It looks like this is intentional for consistency based on https://github.com/gocd/gocd/commit/228dfe46b53a26e10388fbe430d4e102c77cb73f

In the ideal world, this wouldn't be a slow process. In a previous setup I have probably had a similar situation with you in terms of # of pipelines in the config repo. How long is it taking for this update of the config repo?

Do you have a server log you could share of what it's doing during this time before it actually starts your pipeline after the material updates?

**Comment by sriramnrn** [comment]
On Fri, 1 Jul 2022 at 5:57 AM, Thiago Pereira de Souza <
***@***.***> wrote:

> At peak times, I had to wait two hours. And after finishing the configrepo
> update the pipeline starts immediately.
>
> I think the core of the problem is that there are about 5600 pipelines
> spread over about 50 configrepos. When a file starts to update it even
> finishes in a short time, about 3~4 minutes. But, it takes a while to start
> loading.
>

Just checking - do these pipelines have more than one stage?

Context of my question: I have seen folks organise GoCD pipelines ( a
sequence of stages that must run together) like Jenkins stages ( jobs that
are strung together by a plug-in) or like Team City Build Chains.

I’m asking this question just to help reduce the number of pipelines if
possible.

>
>
