### ISSUE TITLE
Rename pipelines and templates 

### ISSUE THREAD

**Issue by luisxkimo** [gocd/gocd#10590]
##### Issue Type

- Feature proposal
- Feature enhancement

##### Summary

Regarding to this previous "autoclosed without response" issue: https://github.com/gocd/gocd/issues/221

Are there news about options to rename, at least, display names of pipelines?

**Comment by chadlwilson** [comment]
I'll re-open the old issue to retain history and discoverability, but there is no news on this or ability to do this. The pipeline names are unfortunately effectively the "key" and there are many changes required to make it work due to some original decision decisions, which is probably why it has never been done.
