### ISSUE TITLE
Dragging outside of the web config dialogs closes the dialog without saving

### ISSUE THREAD

**Issue by chrisb2244** [gocd/gocd#10669]
##### Issue Type
- Feature enhancement

##### Summary
I often click and drag to select text in textboxes in the configuration dialogs. Dragging the mouse beyond the edge of the dialog closes the dialog and loses unsaved changes.
This is pretty irritating :/

###### Basic environment details

* Go Version: `22.1.0`
* JAVA Version: `17.0.2`
* OS: `Windows 10`
* Browser vendor and version (if relevant): `Chrome 103.0`

##### Steps to Reproduce

~~1. Open some configuration dialog (e.g. "Add material" to a pipeline
2. Type something in e.g. Repository URL (with the default `Git` selected as Material Type)~~
3. Click and drag inside the box, text is selected as expected
   a. Release inside the box. No problem
   b. Release outside the 'Add material' dialog. No material is added, the dialog closes.

Whilst reproducing this, I found that it doesn't happen with the `Add material` dialog.
It does occur in the Task configurations (tested with `Custom Command`, 'Command' and 'Arguments' boxes, and `Fetch Artifact`, 'Pipeline' and 'Artifact Id' boxes).

##### Expected Results
Nothing, maybe - select to the beginning/end of the box and don't close the dialog

##### Actual Results
The dialog closes

![image](https://user-images.githubusercontent.com/7201433/183012832-41fa10d3-409f-4866-9b79-e8826eed12ab.png)

##### Possible Fix
Unknown

**Comment by chrisb2244** [comment]
As a related comment, being able to directly click outside to close and reset changes is quite useful... it's only the dragging and accidentally closing that's a pain...

**Comment by chadlwilson** [comment]
This is happening due to this code behaving differently across browsers it seems.

https://github.com/gocd/gocd/blob/5c7c6c226dc2caa1fe729f5142536634912e795a/server/src/main/webapp/WEB-INF/rails/webpack/views/components/modal/modal_manager.tsx#L85-L90

On Firefox the click+drag's `event.target` is the original text area you clicked (`mousedown`) in, whereas on Chrome (and Safari, fwiw) it considers the target the eventual overlay area at (`mouseup`), so closes the modal. I guess there is a need to somehow distinguish a click from a click+and+drag in some browser independent way.
