### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1071]
I'm seeing this error consistently every time I start go -

```
NameError (uninitialized constant ServiceCache::Spring):
  lib/services.rb:5:in `get_service'
  lib/services.rb:18:in `server_health_service'
  app/controllers/application_controller.rb:80:in `populate_health_messages'
```

More info about my system -

```
[vagrant@localhost ~]$ uname -a
Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@localhost ~]$ cat /etc/system-release
CentOS release 6.5 (Final)

[vagrant@localhost ~]$ curl http://localhost:8153/go/api/support -s | grep Version -B2 -A3

=================
Go Server Version
=================

15.1.0(1863-42e58c22aefd03)
--
Spec Name - Java Virtual Machine Specification
Spec Vendor - Oracle Corporation
Spec Version - 1.7
```

**Comment by ketan** [comment]
@arvindsv @srinivasupadhya @arikagoyal - Have you seen this error before? Is this something that can be ignored?

**Comment by arvindsv** [comment]
I've seen it, but not consistently. I think it happens like this:

1. Have a browser open, pointed to the Go dashboard.
2. Restart the server, or install a new version.
3. This happens sometimes.

I think there is a race condition between when Spring is loaded and ready, and when a request comes in. In this case, since the browser is open, and it keeps trying to make an AJAX request to get those server health messages, one of those requests gets through and tries to load the server health service ([here](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/lib/services.rb#L5)) and fails, since Spring (actually spring.rb) is not yet loaded. That's my hypothesis.

If this is true, an explicit ```require "spring"``` in ```services.rb``` might help. Otherwise, not opening the port till everything is loaded might help too.

Typically, the issue goes away in a few seconds, once the server loads up completely and ```spring.rb``` gets loaded.

**Comment by arvindsv** [comment]
Haven't seen this happen recently. Closing till it is seen again.
