### ISSUE TITLE
Times displaying incorrectly for elastic agent status reports

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#10736]
Haven't investigated, but noticed that ECS Agent Launch times, and container created at/started times at are displaying as

```
 {{ 1661012400000 | date:"MMM dd, yyyy hh:mm a"}}
```

On the ECS Plugin Status report. Could be related to the plugin or to something on GoCD side, but needs investigation.

**Comment by arvindsv** [comment]
:) Ah, ok. We should be able to make a change without bringing that back, right?

**Comment by chadlwilson** [comment]
I hope so, but might test the limits of my knowledge of the current bundling setup. 😅 Will give it a go.

Anything peripheral ike this mysteriously depending on that massive globally namespaced rails application.js scares me, however maybe that's a problem for another day.

**Comment by arvindsv** [comment]
No one knows bundling now, like you do. :) Let me know if you need help.

**Comment by chadlwilson** [comment]
Well there's (#10737) a hack 😅

The real plugins are a bit of a pain to test, need to find an easy elastic agent one to validate with, or see if there is a dummy elastic agent plugin somewhere that renders a status report.

**Comment by arvindsv** [comment]
I couldn't find one with a status report as well. I quickly hacked (badly) the skeleton plugin to reproduce this bug. See https://github.com/arvindsv/elastic-agent-skeleton-plugin/tree/hack-to-show-plugin-status-page

If you build it and access this page (http://localhost:8153/go/admin/status_reports/com.example.elasticagent.foocloud) as soon as the server comes up, you'll see the bug reproduced.

In 21.4.0, I see:  `Aug 20, 2022 05:20 PM`

In 22.2.0, I see: `{{ 1661012400000 | date:"MMM dd, yyyy hh:mm a"}}`

**Comment by arvindsv** [comment]
I suspect you meant the agent status report or the cluster status report though. I don't see the ECS plugin supporting the plugin status report (which is access from the plugins page). Sorry, it's confusing terminology. No matter, I think if one works, they'll all work.

I also a found [a bug](https://github.com/gocd/plugin-api.go.cd/pull/815/files)!

**Comment by chadlwilson** [comment]
Thanks for the tips there, that was really helpful. Unfortunately looks like that elastic-agent-skeleton-plugin wasn't in the best state and needed a bit of work. At risk of "dirtying" the skeleton a bit, I added some dummy code to generate a dummy status report which the regression tests can sanity check as part of the plugin SPA tests. Details in #10737.

![image](https://user-images.githubusercontent.com/29788154/187075071-158d7a0d-7929-418a-b3c2-8c6793c774fb.png)

In retrospect, it probably would have been better to have a dummy plugin as part of https://github.com/gocd/go-plugins but unfortunately it doesn't seem there is an existing elastic agent plugin to base from there, unless I missed it?

**Comment by chadlwilson** [comment]
And we're back (on build.gocd.org):

![image](https://user-images.githubusercontent.com/29788154/187075543-5d63d499-85f7-4d39-893d-740dabc9f5ff.png)

**Comment by arvindsv** [comment]
﻿﻿> Unfortunately looks like that elastic-agent-skeleton-plugin wasn't in the best state and needed a bit of work. At risk of "dirtying" the skeleton a bit, I added some dummy code to generate a dummy status report which the regression tests can sanity check as part of the plugin SPA tests.

That's what I was seeing too. In my ideal world, the skeleton plugin will be a properly working plugin, with (searchable) messages everywhere. That way, someone can try it out, see it working (but not _doing_ anything) and then search for messages to know what to change to make it a real plugin. This one wasn't in that state. That's why I put in those hacks. Thanks for making those (better) changes you eventually committed.

> In retrospect, it probably would have been better to have a dummy plugin as part of https://github.com/gocd/go-plugins but unfortunately it doesn't seem there is an existing elastic agent plugin to base from there, unless I missed it?

Yes, I checked there as well. What I recalled later was that the go-plugins bit was used to mostly check for invalid scenario which would be hard to test in other ways. It wasn't a full functional test of the specific plugin extension, which is what would have caught this regression.
