### ISSUE TITLE
Task silently fails if material doesnt exist

### ISSUE THREAD

**Issue by caljnj** [gocd/gocd#10739]
##### Issue Type

- Bug Report

##### Summary

If i try to run a task where the material doesnt already exist then the task silently fails 
Visually - i click the button in the GUI, buttons are grayed out for a few seconds, then the button proper color returns again.

It's a bit of a noob error, but I think many will/might make the assumption that as long as e.g. the "stuff" needed to run that task exists (in my case github repo, or source image) then the task should just run. 

I even ended up enabling debug logs in server/agent for this but i didnt get any output

##### Environment

- Go Version: 22.1.0 (13913-f4c9c1650e2e27fe0a9962faa39536f94f57e297)
- JAVA Version: 17.0.2
- OS: Linux 4.18.0-372.19.1.el8_6.x86_64

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. clean installation of server/agent with new/empty database, artifacts etc etc. but a fully configured config.xml
2. config.xml must have a task with a material configured (material is a previous task that has not been run yet)
3. run the task
4. buttons on task will go grayed out for a few seconds then go back to normal
5. no DEBUG logs in server/agent to show what happens

**Comment by caljnj** [comment]
i'd be happy to just add this as a case in the "fixing common issues" gocd docs
https://docs.gocd.org/current/faq/fixing_common_issues.html

**Comment by arvindsv** [comment]
@caljnj Yes, if you feel like that's the first place you would try to look for help, then please submit a PR here: https://github.com/gocd/docs.go.cd/blob/master/content/faq/fixing_common_issues.md

Out of curiosity, did you see any errors in the "Errors & Warning" button on the top-right?

You're right thought. It would be better if the error showed near the pipeline. This was discussed in a few issues such as https://github.com/gocd/gocd/issues/3882, but there were some implementation challenges with categorizing errors etc. due to which it wasn't done. Currently, no one is working on that area.
