### ISSUE TITLE
Config Changes popup in Stage Details should show only related changes

### ISSUE THREAD

**Issue by ciotlosm** [gocd/gocd#1081]
Config Changes popup in Stage Details should show only changes related to the Pipeline or Stage from which you are looking. 

The Config Changes popup was extremely useful when we had few pipelines and few admins, however now it became completely irrelevant. This is because most of the time the Diff is not useful at all. 

Would be nice to see "Config changed" entries only if something changed for that specific Stage. This would make this feature useful again. 

In contrast, if this can't be achieved, to have an "Admin" view where to see a better "timeline" of changes.

**Comment by srinivasupadhya** [comment]
The problem is that the changes are for a file & figuring out that a particular change is for a particular pipeline/stage/job is hard.

> if this can't be achieved, to have an "Admin" view where to see a better "timeline" of changes.

This could be achieved rather easily. We already have an API for [listing revisions](http://www.go.cd/documentation/user/current/api/configuration_api.html#config-repository-modification-listing-api) & getting [config for a revision](http://www.go.cd/documentation/user/current/api/configuration_api.html#retriving-historical-configuration-snapshot) or getting just the [diff between revisions](http://www.go.cd/documentation/user/current/api/configuration_api.html#config-repository-modification-diff-api).
