### ISSUE TITLE
Task Plugins - configuration time needs to environment variables details in request body

### ISSUE THREAD

**Issue by kamlesh0606** [gocd/gocd#10843]
Hello gocd team,

Any options there for Task Plugins - configuration time needs to environment variables details in request body ?

Currently I am making tasks plugin for input of pipe line. In ui, i need to show details with helps of environment variables for user details like next version, ongoing details , client name.

**Comment by chadlwilson** [comment]
I'm not really sure I understand what you are trying to do. Can I request that you start a discussion on the Google Group at https://groups.google.com/g/go-cd where there are more folks who have built and used various plugins?

In general I would say that environment variables are something that is generally considered to be a higher level of abstraction to a task, since these are an operating system/process concept.

If you want to capture configuration values in your plugin, and then promote these to environment variables when your GoCD plugin task launches a sub-process, you should be able to do that though.

I would consider whether you really need to write a task plugin for what you are trying to achieve though. Often times you can achieve much more, with more flexibility by just using a script or command task that either calls a source controlled script that operates on environment variables, or calls a dedicated build automation tool (make, rake, gradle, npm etc). That wont give you the UI interactivity you might desire, but it might be more suitable for promoting pipelines as code, with the benefits that can give you.

**Comment by kamlesh0606** [comment]
Hello @chadlwilson 

Thanks for the reply.

 i made a task plugin and also loaded in gocd .it is working fine.


When **configuration** Request name comes at that time i need environment variables. Currently the **requestbody** object is null values come.

Is it possible to pass environment variables in requestbody with **configuration** Request name ?


And also the same way inside **view** , **validation**  Request name ?


Ref. Links 
https://plugin-api.gocd.org/current/tasks/#requests-from-gocd

Why need environment variables in above 3 Request name ? -- i need to show details which is taking from environment variables in HTML page. Like client name, last deploy version, method of deployment. This all data management in side environment variables.


Thanks

**Comment by chadlwilson** [comment]
No, environment variables are only known at execution time i.e in https://plugin-api.gocd.org/current/tasks/#execute-task

Some set by GoCD are dynamic such as the pipeline number etc.

Not sure why you'd need them at configuration time, the idea is when your task executes it is supplied everything it needs to work on its own, including the configuration values, environment etc.

**Comment by kamlesh0606** [comment]
Hello @chadlwilson 

Just show display some details at configuration ui time.

Based on it, devops person will enter right details so.

Otherwise some devops person will put wrong data in configuration time. 

If possible, please pass environment variables.

Otherwise no problem.

Gocd tool is good tool for end to end pipe line with any complex work.

Thanks for gocd team.

**Comment by chadlwilson** [comment]
I don't really understand what you are specifically trying to do, so excuse my ignorance if so.

My perspective is that GoCD's design philosophy here is that if you want this kind of control, that you should do so within the way folks express their pipelines as code, or if you are writing a custom task plugin, when it is run/triggered you could inspect the environment variables and apply whatever rules you would like to them to fail the task if it doesn't meet requirements.

If you want to require certain data or enforce certain config rules at configuration time vis the UI you can do so and then ignore/remove environment variables at runtime if you'd like.

As I've explained it does not make sense to pass env vars at config time as they change depending on your environment - they are dynamic. If you want something at config time, use config cars and write logic to validate the environment vars at runtime.
