### ISSUE TITLE
Why when using multiple config repositories are pipeline names required to be unique?

### ISSUE THREAD

**Issue by agileturret** [gocd/gocd#10840]
##### Issue Type

- Feature enhancement

##### Summary

Allow developers to use the same pipelines workflow for different applications. The idea that we had was to have multiple config repositories with the same delivery pipeline structure and to use this to delivery different applications.

For example:

- To delivery Application A, which uses git repository "Application A", we have a few pipelines defined, e.g. "provision", "destroy".
- To delivery Application B, which uses git repository "Application B", we have a few pipelines defined, e.g. "provision", "destroy".

A developer can then see the same pipeline structure (which is common after all) for all applications.

_Unfortunately this is not supported and we get exception that the pipeline name must be unique._

##### Environment

Latest version running on K8S.

##### Steps to Reproduce

1. Create a config repository for ApplicationA add simple pipeline with the name "mypipeline", group name "mygroupA".
2. Add config repository for ApplicationA to GoCD instance.
3. Create a config repository for ApplicationB add simple pipeline with the name "mypipeline", group name "mygroupB".
4. Add config repository for ApplicationB to GoCD instance.

##### Expected Results

- ApplicationA pipelines defined and displayed correctly in dashboard within "mygroupA" and the key has should be generated within the merged configuration as mygroupA-mypipeline.
- ApplicationB pipelines defined and displayed correctly in dashboard within "mygroupB" and the key has should be generated within the merged configuration as mygroupB-mypipeline.

##### Actual Results

pipeline names required to be unique exception.

##### Possible Fix

Add pipeline group to pipeline name key hash.

##### Code snippets/Screenshots

I ended up having to do this as work around.

![Screenshot at 2022-09-19 11-26-59](https://user-images.githubusercontent.com/106150466/190998603-1f3191fd-a8c2-4f2d-a18b-8d7ea0f410a3.png)

**Comment by chadlwilson** [comment]
For better or worse, it's a part of the original design that pipelines are keyed by name (not a composite key of `(group, pipelineName)` nor some other surrogate key/id, and thus must be globally unique. Config repositories don't really change this in any way, because the pipelines defined by config repos still need to be merged into the "overall configuration".

See #221 for the closely related issue of ability to rename pipelines.

I doubt this will be changed in the way you suggest, as it would be a massive breaking change. Everywhere that refers to a pipeline by name (e.g fetching an artifact from upstream on a VSM) would somehow also need to refer to the group that pipeline was in to disambiguate things.

**Comment by chadlwilson** [comment]
Most folks I have seen prefix or suffix the pipelines with the component/team/group that they are relevant to (and often environment) as it also makes it easier to search/filter for.
