### ISSUE TITLE
Rescheduled Jobs not being marked as completed on completion

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1089]
Jobs that are rescheduled needs to be marked as complete once the job passes/fails. A cache issue is causing the job to be shown as rescheduled. 

Restarting the server displays the job as complete.

**Comment by zabil** [comment]
Picking this up

**Comment by chopraapooja** [comment]
STEPS to reproduce :-
1) Have two agents connected to the server.
2) Create a pipeline with a job that will end up longer [to get time to disconnect agent before job completes] say "sleep 120".
3) when job is in the middle of execution, just disconnect the building agent.
4) Job will get rescheduled to another agent after some time. 
5) Keep eye at the job details page . It should show the correct status (without refreshing) and also check console logs.

You should get jobstatus in this order :-
Scheduled,
Assigned
Preparing
Building
Rescheduled,
Scheduled,
Assigned
Preparing
Building
Completing,
Completed

This is the ideal behaviour. But the bug is that job details page stop showing updated status after job gets Reschedule and hang upon "Reschedule" state. 
**Note**:-
To check whether status is updating **without refresh** it is recommended that you should stay on the job details page throughout job execution cycle , don't go back and forth. Use another browser window or tab if you want to goto another page.

**Comment by juhijariwala** [comment]
I reproduced the scenario as above, but it is **not showing the rescheduled state.**

### Current Job status order ###
Scheduled
Assigned
Preparing
Building (killed the assigned agent)
Scheduled
Assigned
Preparing
Building
Completing
Completed

Observed on **15.2.0(2067-07d65665c731a6) **

**Comment by juhijariwala** [comment]
Verified with 15.2.0-2067 (07d65665c731a615f6a6943cce0fd03440eb4a9e).This works as expected.
