### ISSUE TITLE
Latest Go Server release (15.1) fails to Launch on Mac OS X

### ISSUE THREAD

**Issue by ohbeanz** [gocd/gocd#1093]
Latest release of Go Server complains about Java 1.7 or newer (1.8 installed) not being installed when run on my Mac OS X 10.9.5 machine. Also, the link displayed in the error message points to a non-existent page (404 error). I did notice a previous issue about needing to support 1.8, so perhaps this is why the error is being displayed. 

![screen shot 2015-05-03 at 2 31 47 pm](https://cloud.githubusercontent.com/assets/12222884/7446279/51e2507a-f1a1-11e4-8144-527e98273187.png)

![screen shot 2015-05-03 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/12222884/7446281/587754bc-f1a1-11e4-9db3-2fd16efa1a52.png)

**Comment by zabil** [comment]
We don't support go on JDK 1.8. 
Can you try installing 1.7 to get it running?

**Comment by ketan** [comment]
@arvindsv - did you happen to complete this doc?

**Comment by srinivasupadhya** [comment]
yes he has. here - https://github.com/gocd/documentation/pull/115

**Comment by ketan** [comment]
That seems to have not been merged in and published. Can you merge it and push it out?

/cc @mdaliejaz

**Comment by arvindsv** [comment]
@ohbeanz: You can either try installing 1.7 as @zabil said, or you can set the GO_JAVA_HOME environment variable, and try with 1.8 (it'll be worth trying, even though 1.8 is unsupported at this point).

What's happening is that you've installed Oracle Java 1.8, which is actually just a browser plugin. That's why it is in /Library/Internet Plug-Ins. It will not be found when Go tries to find it (meaning ```/usr/libexec/java_home -v 1.7+``` will not find it). So, you can set GO_JAVA_HOME to that version of Java you have:

```
GO_JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home" open "/Applications/Go Server.app"
```

I'll get that documentation page up soon. It was still a PR till now, as @srinivasupadhya said.

**Comment by arvindsv** [comment]
@ohbeanz: The page at http://www.go.cd/documentation/user/current/installation/troubleshoot_installer.html#mac_java is now available. It says, more or less, what I mentioned above.

I'll close this issue for now. Let me know if it doesn't work. Thank you!
