### ISSUE TITLE
Experimental builds available via RPM/DEB repositories

### ISSUE THREAD

**Issue by thenathanjones** [gocd/gocd#1102]
As asked in #1076, is there a way we can have both experimental and supported releases available in the RPM/DEB repositories? I've got Chef recipes for standing up Go but I'm unable to use them for both experimental and supported releases.

Ideally I'd like to just specify the version and pull down the correct one.

**Comment by arvindsv** [comment]
Sorry for the delay. As I'd said in the other conversation (1076), I don't think we can use bintray for that, since the artifacts are quite large (about 900MB per version, in total) and bintray doesn't seem setup to do that. Even with a paid tier, the limits are quite low. There is some talk going on with the bintray support team about this.

So, I feel it needs to be done on the other download server, where all the intermediate builds are. The structure of the download there is:

/path/to/root/15.1.0-1894/go-server-15.1.0-1894.deb
/path/to/root/15.1.0-1896/go-server-15.1.0-1896.deb
...

I'd like to keep the structure and path the same, but have a parallel index built for the debian packages, possibly with symbolic links to the real files. Might need some small changes in the web server config as well, to allow following of those symlinks.

I think just running dpkg-scanpackages on the current structure will not work. Can try it. Another small issue is that the current server is a CentOS box. Anyway, bottom line is, this is possible and useful. Needs a little work.

**Comment by ketan** [comment]
> I think just running dpkg-scanpackages on the current structure will not work. Can try it. Another small issue is that the current server is a CentOS box. Anyway, bottom line is, this is possible and useful. Needs a little work.

`dpkg-scanpackages` is provided on centos by `dpkg-devel` package, I've tried it in the past and it works as expected.

Here's a quick script - https://gist.github.com/ketan/f167f22fef7d01aafdc7
Here's the build output - https://snap-ci.com/ketan/ant_jetty_minimal/branch/master/logs/defaultPipeline/7/EditMe?back_to=build_history

**Comment by arvindsv** [comment]
@ketan: I believe this is done now. Can you provide some details about how to set this up, and then close this issue?
