### ISSUE TITLE
After rebuild gocd server, the pipeline console log show twice

### ISSUE THREAD

**Issue by Xyz426** [gocd/gocd#11098]
##### Issue Type

- Bug Report

##### Summary

The gocd pipeline history console log store in the  **/godata/artifacts/pipelines/** folder, and we mount the volume in AWS EFS.

Last time we rebuilt gocd server, and mount **/godata** path in the same AWS EFS. But the history of the pipeline doesn't show it, and if we trigger pipeline, it will show twice console log.

We know the problem is we have the old history file, because the pipeline build_id start with 1 after rebuilding the gocd, It will append the console log to the old history file, so it will show twice.

So, we want to know is there any way to recover an old history console log? 

![image](https://user-images.githubusercontent.com/44676710/206663378-6da336a5-6bad-4c2d-b065-4f7b94ec9211.png)

**Comment by chadlwilson** [comment]
I don't really know if I understand what you are asking, but if your build IDs reset to 1 it sounds like you did not restore the old GoCD database (or did not do so correctly) correctly.

If you are using the default H2 database and you and running inside a container (you've supplied no info so I am guessing), the DB would normally be in `/godata/db/h2db`. You'd want to make sure that was stored on your EFS volume (or in any backup you had) and that it was correctly picked up on your new install.

The reason for it not picking up that DB could be many reasons. For a start, when you rebuilt your server did you rebuild with the same GoCD version as your "old" server?

Please share more information about your installation. The [issue template](https://github.com/gocd/gocd/issues/new) has these questions so that people know enough information to help you without having to ask lots of questions back-and-forth.
