### ISSUE TITLE
Guard against OOM errors for extremely long log lines

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#11100]
##### Issue Type

- Feature enhancement

##### Summary

GoCD can run into Out Of Memory errors when handling build output consisting of extremely long lines. I'm wondering if we can find an effective way to guard against this.

Recently, our GoCD instance crashed with an Out Of Memory error because a build produced console output where a single line was 350 MB in size. When GoCD tried to display the console log in the UI, it crashed handling this extremely long line. Of course we are going to correct this build, since such a long line is virtually useless for human consumption anyway.

Nonetheless, I was wondering if we can guard against such crashes in the future. We have many different teams working with GoCD, and accidents can always happen again, and such crashes cause quite a lot of disruption. We can (and have in the past) increased the heap size available to GoCD, but that only goes so far. It would be nicer if GoCD guards against reading extremely long log lines.

I investigated briefly, but it doesn't look entirely trivial:
* Line-wise loading doesn't only happen when displaying the log in the GUI, but in other places as well, for example while transmitting the log from agent to server.
* Bounded line reading is harder than it seems, based on searching for existing solutions. At least when considering the many types of input streams and input data in the generic case. Not to mention losing out on the efficient implementation provided by the JDK.
  * https://stackoverflow.com/questions/5960554/maximum-line-length-for-bufferedreader-readline-in-java
  * https://bugs.openjdk.org/browse/JDK-4107821
  * https://github.com/seantmalone/BoundedBufferedReader
* What would be a good bound to begin with? Should it be configurable by the operator?
* What should happen when the bound is reached? If the line is truncated, how does the user know? If the line is split into two, it doesn't represent the reality anymore and could cause confusion.

My minimalist, egotistical ("works for us") approach would be to fail fast at the source: the StreamPumper class responsible for reading command process output could read lines in a bounded fashion and throw an error if the bound is exceeded. I'd rather make our teams aware that their builds are doing something bad, by failing the build, than trying to deal with the log all over the place.

Any thoughts on this are much appreciated.

**Comment by chadlwilson** [comment]
Putting aside "how" to do it right now, it seems to me a conservative approach would be to
* define a default limit, intended to be imposed at agent level
* allow it to be overridden with a server-side system property (there is an existing mechanism to propagate such properties to all agents)
* if the limit is reached, crop the line, and then prepend or append something like `... [ cropped by GoCD ]` to every such line.
* arguably, add a toggle for something like `toggle.agent.command.fail-build-on-long-console-lines` (which would allow opt-in to fail-fast behaviour)
* dealing with it at-source (within the agent `StreamPumper`) likely means not having to worry about it anywhere else.

Not quite sure what a sensible bound would be. Might need some research as to how other tools that deal with command output approach it and what type of bounds they set.

Personally I would say logging such excessively long stuff to the console doesn't deserve any particularly "friendly" handling due to how, err, silly it is to do, so I could be convinced we should not bother cropping, and make it fail fast by default if we felt confident we could reach an reasonable initial bound size and communicate the failure reason back to the user in the build/console log.

**Comment by sandro-h** [comment]
Thanks for the quick answer!

> Personally I would say logging such excessively long stuff to the console doesn't deserve any particularly "friendly" handling due to how, err, silly it is to do

Agreed :)

> Might need some research as to how other tools that deal with command output approach it and what type of bounds they set.

I had a look around, but found surprisingly little information in the space of CI/CD providers:
* Travic CI has an overall log size limit of 4MB: https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded
* GitLab also has a 4MB log size limit _by default_: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section (`output_limit`)
* Did not find any information for GH actions, except this open issue which implies there's either no limit or a rather high limit (or maybe just that things become CPU-bound before they hit memory limits): https://github.com/actions/runner/issues/1031

I also ran some numbers on our instance, for what it's worth:

**Overall log size:**
| Metric        | Value |
| ------------ | ------|
| Median | 48 KB |
| P90 | 1.8 MB |
| P99 | 10.3 MB |
| Maximum | 67 MB |

Sample size: 2127 logs
The 350M log which caused our crash has been removed of course.

**Longest lines (only checking logs above 4MB in overall size):**
| Metric        | Value |
| ------------ | ------|
| Median | 3.5 KB |
| P90 | 23 KB |
| P99 | 18 MB |
| Maximum | 23 MB |

---

GoCD has a lot more capacity than users reading the logs, so I think we could pick a relatively generous default limit, compared to what's actually useful for users. Based on all these numbers, for example 10 MB per line seems plenty. This would break some of our builds, but I'm happy to inform the teams about their silly logs 😋 We could go even higher to, say 50 MB which is still unlikely to cause an OOM memory on its own in a well provisioned instance.

At the end of the day it's still guesswork though. We could also invert it and make the default *unbounded*, but allow configuring a limit, if there's too much concern about breaking existing instances.

**Comment by sandro-h** [comment]
@chadlwilson, if you agree with the general direction, I have a PR to offer with a simple approach:
* Crop lines on agent side in `CommandLine.runScript`, appending `...[ cropped by GoCD ]`
  * Lines are cropped **after** being read by the `StreamPumper`. No special guard against reading too much on the agent itself.
* The maximum line length is configurable with `go.console.log.max.line.length`
  * Set to `0` by default at the moment, meaning unbounded lines -> TBD
  * Can be propagated from server to agents via `gocd.agent.extra.properties` mechanism

**Comment by chadlwilson** [comment]
@sandro-h Sorry for the slow reply. That sounds good, or at least a good starting point for us - happy to collaborate on a branch, so feel free to open a draft PR.

> * The maximum line length is configurable with `go.console.log.max.line.length`
>   
>   * Set to `0` by default at the moment, meaning unbounded lines -> TBD

I think it would be fine for us to introduce a sensible default rather than `0`. Say 1 MB or something. Even 10MB seems crazy! I'm suppressed your P99 is that high and am a bit shocked by even your median. 1% of logs are above 18MB!? 

Can dig more for some inspiration for the default limit later anyway.

>   * Lines are cropped after being read by the StreamPumper. No special guard against reading too much on the agent itself.

This might need to be done in the [SafeOutputStreamConsumer](https://github.com/gocd/gocd/blob/master/util/src/main/java/com/thoughtworks/go/util/command/SafeOutputStreamConsumer.java) or **after** it. I don't fully understand the scope of this secrets redacting logic (does it apply on custom commands/scripts and check for all "secure variables", or is it more targeted?).

If it's the more generic case, one edge case risk of this model (which the dumb/naive model isn't subject to) is leaving a secret partially exposed, because it was cropped part way through and thus the logic to redact known secrets doesn't work. Yes, this is pretty edge case stuff, and while even the secrets redacting seems to best effort at the best of times[1], working around that on cropped output without some "read ahead" complexity is probably messy. We'd also possibly need to validate which cases use this this consumer and whether we are leaving some cases un-cropped which we are concerned with.

Also worth noting that some of these utility classes are used by the server too to execute standard commands (mainly for SCM) so we'd need to consider effect there, depending on where the limit is introduced.

As for the "purist" model that avoids creating all the massive buffers and garbage of reading the huge line, modifying further something like this [BoundedBufferedReader](https://github.com/davidmoten/io-extras/blob/master/src/main/java/org/davidmoten/io/extras/BoundedBufferedReader.java) would probably get us there. Looks like that is a hack on the original JDK `BufferedReader` and just immediately crops the line at the maximum with no indication; but might not be hard to
- accept an input with `Optional<String> cropIndicationAppendText`
- crop to `maxLineLength - cropIndicationAppendText.map(::length).orElse(0)`
- add back `cropIndicationAppendText` before moving to the next line.

But given the implicit risks on the secrets redacting, I'm not sure if it will be worth the effort, despite the technologist in me being intrigued...

[1] multi-line secrets or secrets mutated by a tool and then spat back onto output etc etc...

**Comment by sandro-h** [comment]
Thanks for the feedback and useful info! I plan to start work on a PR soon, just dealing with a flood of new year work first.
