### ISSUE TITLE
Option to disable X-Frame-Options

### ISSUE THREAD

**Issue by kuckchuck96** [gocd/gocd#11432]
In some cases Developers want to embed GoCD in **iframe** be it in Angular or React apps. Is it possible to provide options similar to grafana to disable **X-Frame-Options**?

**Comment by chadlwilson** [comment]
A more appropriate modern approach would probably be removal of this header and some configurability of Content Security Policy since X-Frame-Options is a legacy header.

Can't quite understand the use case for embedding GoCD like this though, and don't think we'd want to get into ensuring everything else works in these scenarios with respect to browser cross origin policies and such.

Since you need to reverse proxy GoCD to secure it with TLS you could presumably strip or modify  repsonse headers there any way you like (at your own risk!).
