### ISSUE TITLE
Ability to store/retrieve session state within GoCD plugins to facilitate secure OIDC

### ISSUE THREAD

**Issue by JamesMcNee** [gocd/gocd#11629]
##### Issue Type

- Security Enhancement
- Feature proposal

##### Summary

For an OIDC (Open ID Connect) authentication flow to be truly secure, one must verify that the user who initiated the authentication flow is the same one from whom the callback is coming. In order to do this, OIDC has the concept of a `state` param, and often a `nonce`, these should be used by the client (the one implementing the flow) to check that the user remains consistent. The mechanism for doing this is storing some state against either the end user (e.g. Cookies, LocalStorage) or the session (server state) and then later verifying it.

Ideally when an OIDC flow is initiated a `state` and `nonce` value are generated and stored using one of these technologies against the current user, then on the callback, the IdP (Identity Provider) will pass these values back in the response. The OIDC client can then verify that the values match those that have been previously stored. This protects against CSRF attacks, [this Medium article is good at explaining further](https://medium.com/keycloak/the-importance-of-the-state-parameter-in-oauth-5419c94bef4c).

Currently the GoCD plugin API does not expose any mechanism in order to store state against the end user or the active session, therefore Authorization plugins that are using OIDC/OAuth are not able to do this additional validation step. Take the Google Authentication plugin as an example, although [it sets the state param on the flow](https://github.com/gocd-contrib/google-oauth-authorization-plugin/blob/789a26de9a448138304d5af50cc8d5a8885f7ce7/src/main/java/cd/go/authorization/google/GoogleApiClient.java#L66), it never verifies it, therefore not benefiting from the additional protection it provides.

##### Possible Fix

~My proposed fix is to add a mechanism onto the `GoPluginApiRequest` that will allow for access to a session context. This map will be scoped to the plugin, and will be backed by the HTTP Session, there would be a `String get(String key)` method and a `void set(String key, value)` method in order to store and retrieve context.~

Moved away from the above as not all requests to a plugin are attached to a HTTP request, so it feels a little to broad to add to the `GoPluginApiRequest` interface. 

Maybe something more localised to the Authentication plugin would work... Potentially if a response body is provided on the `go.cd.authorization.authorization-server-url` request, it could be stored against the session and then passed back as an additional property in the request body of `go.cd.authorization.fetch-access-token`.

This would allow for the OIDC flow to complete the verification and would make this change be localised to the Authorization plugin infrasturcture.

Obviously happy to hear your thoughts on how this might be implemented best as I am by no means familiar with the GoCD codebase at large.

##### Any other info

I am happy to contribute code in order to implement this addition to the plugin API, if it is something that you would be happy to have added to GoCD.

**Comment by chadlwilson** [comment]
Hi James - thanks for raising this. I am pretty familiar with OAuth2/OIDC and the threat model, but not the depth of GoCD's authorization plugins and some of the design goals, which admittedly make things like OAuth2 auth code/redirect flows (especially with all the varieties) a bit of a challenge to deal with.

Ideally there would not be different plugins for each OAuth2 server/provider (that confuses me personally) as well, which would make such things easier to get ones head around as wouldn't be faced with updating `N` plugins.

One of the challenges here is that the authorization plugins are (somewhat) agnostic to the authorization style (OAuth2 etc), although it generally understands the concept of redirect-based login flows. The question is how much the server should/could do, and how much should be delegated to plugins.

I thought through the various options and contemplated some easier approaches which might allow the server to do some validation on behalf of the plugin, but any options there wouldn't support `nonce` (since that is only on ID tokens, and only within the plugin) and would otherwise involve loose/weird contracts between the server and plugins (e.g the server has some magic looking specifically for a `state` parameter in the `authorization_server_url`).

> Maybe something more localised to the Authentication plugin would work... Potentially if a response body is provided on the `go.cd.authorization.authorization-server-url` request, it could be stored against the session and then passed back as an additional property in the request body of `go.cd.authorization.fetch-access-token`.

I think this is probably the only way forward here that's practical.

So https://plugin-api.gocd.org/current/authorization/#authorization-server-url gets extended to allow an optional response like

```json
{
  "authorization_server_url": "http://external_auth_server_url/login?redirect_url=http://my_go_server/go/plugin/my_plugin_id/authenticate&client_id=hdfjh3r&state=ABCDEF&nonce=123456"
  "authorization_session_vars": { // <-- NEW
    "state": "ABCDEF",
    "nonce": "123456"
  }
}
```
This would have to be done somewhere near here
https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/server/src/main/java/com/thoughtworks/go/server/newsecurity/providers/WebBasedPluginAuthenticationProvider.java#L109-L115


During `go.cd.authorization.fetch-access-token` [request to plugin](https://plugin-api.gocd.org/current/authorization/#fetch-access-token) the server passes these through:

```json
{
  "auth_configs": [{
    "id": "github_oauth",
    "configuration": {
      "url": "http://git_hub.com",
      "client_id": "jd9no0f",
      "client_secret": "0njfg8fgmfvufv"
    }
  }],
  "authorization_session_vars": { // <-- NEW
    "state": "ABCDEF",
    "nonce": "123456"
  }
}
```
Although not well documented, I believe on this request the plugin already gets the request parameters and headers to verify these against which would contain the `state` (and `code` as seen for the [Google plugin here](https://github.com/gocd-contrib/google-oauth-authorization-plugin/blob/789a26de9a448138304d5af50cc8d5a8885f7ce7/src/main/java/cd/go/authorization/google/GoogleApiClient.java#L66))

I guess this would have to be done somewhere here
https://github.com/gocd/gocd/blob/3ec98138e5f309666bca72873cad8e0a7a39783e/server/src/main/java/com/thoughtworks/go/server/newsecurity/controllers/AuthenticationController.java#L120-L126

Some wider things to think about
- if there is any need to ensure one-time use for things, we'd need either a convention for the server to erase the plugin session state, auto-expire it as a mitigation, or have the plugin tell it what to erase.
- is there a relationship to requests like https://github.com/gocd/gocd/issues/11331 or things [`is-valid-user`](https://plugin-api.gocd.org/current/authorization/#is-valid-user) needs to do? Possibly not?
- while not strictly necessary for a server side app like GoCD, would this also be sufficient to support [PKCE](https://oauth.net/2/pkce/)? I believe so, because instead of storing `state` in the session vars the plugin would store `code_verifier`. It would not need to compare `state` to what was in the session, but instead extract `code_verifier` and pass on to the IdP during token exchange, who is responsible for verifying it.

**Comment by JamesMcNee** [comment]
Hi @chadlwilson, thanks for the detailed response! I agree that it is slightly confusing as to why there is a plugin for each IdP provider (Google, Github) as ideally there would just be a single one that provided enough configuration options to facilitate them all; ironically, I encountered this issue while implementing an Azure/Microsoft authentication plugin 😁...

In terms of the suggested implementation, that is exactly what I had in mind. I was thinking that  `auth_session` would just be an arbitrary `Map<String, String>` and not explicitly call out `state` and `nonce`, is this what you had in mind too? 

In terms of your points around wider thinking:
> If there is any need to ensure one-time use for things, we'd need either a convention for the server to erase the plugin session state, auto-expire it as a mitigation, or have the plugin tell it what to erase.

Yes I was considering this too; although in this instance it would not really make a difference if the values remained in the session, it may be nice to clear them out. I was thinking this could happen after the execution of the handler that is implementing `go.cd.authorization.fetch-access-token`, as after this those values should have been consumed.

There is a chance that the user doesn't actually complete the login journey and gives up halfway through. In such cases, context against the session from the go.cd.authorization.authorization-server-url handler would remain, which could be cleared out at the beginning of the call into this handler to prevent any bleeding of state between auth flows for a given user.

> is there a relationship to requests like https://github.com/gocd/gocd/issues/11331 or things [is-valid-user](https://plugin-api.gocd.org/current/authorization/#is-valid-user) needs to do? Possibly not?

Interesting issue, I don't believe that this context will be useful for the `is-valid-user` handler, although I do think that the way this verification happens (username matching) could potentially be improved. I think generally the choice in the plugin API to describe things as `headers`, `body` and `params` can lead to confusion in that developers may think that they are being passed the underlying HTTP headers, body and params from the client, and can then subsequently alter what is returned.

> while not strictly necessary for a server side app like GoCD, would this also be sufficient to support [PKCE](https://oauth.net/2/pkce/)? I believe so, because instead of storing state in the session vars the plugin would store code_verifier. It would not need to compare state to what was in the session, but instead extract code_verifier and pass on to the IdP during token exchange, who is responsible for verifying it.

Yep, I agree that this should also facilitate this use case too!

---

Assuming you're happy for me to, I'll have a look to see if I can get anywhere with implementing this functionality and hopefully will be able to raise a PR for it! It should be a non breaking change and therefore wouldn't require a version bump of the auth plugin API.

**Comment by chadlwilson** [comment]
> Hi @chadlwilson, thanks for the detailed response! I agree that it is slightly confusing as to why there is a plugin for each IdP provider (Google, Github) as ideally there would just be a single one that provided enough configuration options to facilitate them all; ironically, I encountered this issue while implementing an Azure/Microsoft authentication plugin 😁...

I've had a thought to create one-plugin-to-rule-them-all for some time, but just haven't had the energy (and testing them across IdPs is challenging) or personal use case to figure out the lowest common denominator as a starting point. There are so many variations and optional pieces of the specs which some providers treat as mandatory (for security reasons) that I can see how it would become difficult to handle them all and still make it easy enough for users to configure. One would probably need to have configuration profiles for major providers which pre-configured all the relevant pieces for, say Google vs Github vs Okta vs etc etc.

> In terms of the suggested implementation, that is exactly what I had in mind. I was thinking that `auth_session` would just be an arbitrary `Map<String, String>` and not explicitly call out `state` and `nonce`, is this what you had in mind too?

Yeah, that's what I was meaning also - those were just examples.

> > If there is any need to ensure one-time use for things, we'd need either a convention for the server to erase the plugin session state, auto-expire it as a mitigation, or have the plugin tell it what to erase.
> 
> Yes I was considering this too; although in this instance it would not really make a difference if the values remained in the session, it may be nice to clear them out. I was thinking this could happen after the execution of the handler that is implementing `go.cd.authorization.fetch-access-token`, as after this, those values should have been consumed.

For this type of use case that would work I guess. Gets messier if you start thinking about aspects like redirects back to client/relying party including `state` parameters alongside `error_code`s, although I don't think the plugins actually tend to handle those properly per spec? :-)

> There is a chance that the user doesn't actually complete the login journey and gives up halfway through. In such cases, context against the session from the `go.cd.authorization.authorization-server-url` handler would remain, which could be cleared out at the beginning of the call into this handler to prevent any bleeding of state between auth flows for a given user.

Seems sensible. it's also possible that user could switch login style as well.

I actually have never really got my head fully around how GoCD manages its sessions (pre-login, post-login and longer term). For example, there is a requirement on many routes to `reauthenticate` the user as well (defaults to 30 minutes) which I believe sends the user through [authenticate-user](https://plugin-api.gocd.org/current/authorization/#authenticate-user) again.

If we aiming for something more generic rather than this specific `state`/`nonce`/`code_verifier` OAuth2 problem, we might need to think about which parts of the auth session state may actually be needed "longer term" as well. (e.g what would it mean to try and store refresh tokens (https://github.com/gocd-contrib/google-oauth-authorization-plugin/issues/192) and be able to use them for re-authentication if the original `credentials` or access token from the IdP has expired?) This is an area I think most plugins probably just ignore though (including probably ignoring any stated expiries within bearer tokens).

> > is there a relationship to requests like #11331 or things [is-valid-user](https://plugin-api.gocd.org/current/authorization/#is-valid-user) needs to do? Possibly not?
> 
> Interesting issue, I don't believe that this context will be useful for the `is-valid-user` handler, although I do think that the way this verification happens (username matching) could potentially be improved. I think generally the choice in the plugin API to describe things as `headers`, `body` and `params` can lead to confusion in that developers may think that they are being passed the underlying HTTP headers, body and params from the client, and can then subsequently alter what is returned.

Yeah, in some cases I guess you really **DO** get the request headers and query params but I believe that is literally only for the redirect-based authorization plugins. If you have a suggestion to reword I am happy to fix them or make it clearer though ([PR or not](https://github.com/gocd/plugin-api.go.cd/tree/master/source/includes/authorization)). 

> Assuming you're happy for me to, I'll have a look to see if I can get anywhere with implementing this functionality and hopefully will be able to raise a PR for it! It should be a non breaking change and therefore wouldn't require a version bump of the auth plugin API.

I am certainly interested - just be a bit patient with me reviewing things and trying to get some other input given it's a security-sensitive area, and some of the flows are rather confusing. Went down a bit of a rabbithole trying to sort out https://github.com/gocd/gocd/pull/11317 a while ago but still feel I have more to understand 😀

Feel free to ask on the Google Forums or Github discussions if you need some tips getting dev environment going - there can be a few niggles but I have generally tried to keep the [basic docs](https://developer.gocd.org/current/) updated.

**Comment by JamesMcNee** [comment]
Hi @chadlwilson -- PR raised here: https://github.com/gocd/gocd/pull/11633

I do however note the:
> just be a bit patient with me reviewing things and trying to get some other input given it's a security-sensitive area, and some of the flows are rather confusing

on your previous reply. Absolutely take the necessary time to review and seek council; massively appreciate the effort you put into keeping GoCD... going 😁 

I will follow up with a PR to update the documentation shortly too 👍

**Comment by JamesMcNee** [comment]
Draft PR for documentation (draft until the point that this code is actually merged): https://github.com/gocd/plugin-api.go.cd/pull/846

**Comment by arvindsv** [comment]
Sorry about joining late. Thanks Chad for the call-out. Excuse anything below which you both have already talked about.

From an idea perspective, your approach makes sense to me. I took only a brief look at the change and was wondering if the `SessionUtils.removePluginAuthSessionContext` call should be in a finally block. I haven't thought too deeply about it -- but something to consider.

I am a little worried that AuthorizationMessageConverterV2.java is changing. I do see that backward compatibility is taken care of, and I see that there is a test as well. However, [this change](https://github.com/gocd/gocd/pull/11633/files#diff-9c370388beb60553862f12ac6ed94f2a2f4aeb1539af70ba7c33eeb9e7e46661R178) to the interface is sort-of incompatible. I understand that it's an additive change and you would expect plugins to ignore that, but we could have a discussion about whether it makes sense to create a v3 for this change, instead of changing v1 and v2. I can be persuaded that we don't need it -- but I'd like to see what you both think about it.

------

[Historical note] Looong time ago there used to be an ability for a plugin to request the GoCD server to store some state. That was supposed to be for a use-case like this:

https://github.com/gocd/gocd/commit/679bd107ff572dd345f14968863a7343c54c3d1b

https://github.com/gocd/gocd/commit/f4ef06d76457dde6482fbce05abb38c2dd438954#diff-0586a9fb5eb23d68f29baef3b1f609906ccbf23f74c34775001c752691f2d4feL82

https://developer.gocd.org/18.7.0/writing_go_plugins/go_application_accessor/user_session/version_1_0/put_into_user_session.html

At that time, if I remember right, requests were more directly passed in to the plugin. So, it could use headers etc. Not sure if that functionality would have been useful for this case.

**Comment by JamesMcNee** [comment]
Hi both,

Have been thinking more on this over the past few days...

In terms of my previous comment:
> Rather than explicitly extending the authentication flow request/response it could be added back as a request from the plugin -> server.

I have grown less and less keen on this after thinking it through, my main issue is the disconnect between the session and the plugins authentication flow when using the `GoApplicationAccessor` mechanism.

Plugins get provided a `GoApplicationAccessor` at instantiation, they can then hang onto this for later use if desired. AFAIK it's possible for a plugin to use this class at any time to get information from the server, such as version etc. My issue with using this for handling session state is that it's not guaranteed by the server that there will actually be an active session to store information against (or retrieve from). 

Let's say for example that in my plugin, I decide to create a new thread to do some work and within this new thread make a call to set some session state, would this actually work? I don't believe it would as the session is somewhat thread bound (I could be wrong on this though). 

For me, it does feel cleaner to bake it into the authentication flow itself as originally discussed and implemented as it's obviously binding the values to the user who initiated the flow.

I have not had time to check this out yet:
> It may be prudent to test a few of the common auth plugins (Github, Google) for compatibility with this change

but I will try to find some time to do this shortly, although I am not against bumping the Auth plugin API to V3, if this is something you both would be willing to support too.

Interested in hearing both your thoughts on the above.

**Comment by chadlwilson** [comment]
Personally I don't think the v3 is necessary, and am more interested in figuring out whether we can get rid of v1, or avoid touching it 😅 To be honest, I have never delved into plugin API compatibility other than to observe that that there is some confusing stuff in the plugin XML structure regarding this :-)

I believe basically all plugins I have seen use a liberal GSON binding/parsing approach and I think it's entirely reasonable to expect new fields to be ignored by plugins ("be conservative in what you send, be liberal in what you accept") to reduce the overhead of "expand and contract". However I do observe that historically GoCD in its web APIs used to bump versions even for these kinds of changes.

Haven't thought about the other bits yet or found a dedicated block of time to think through anything we might have missed in terms of session lifecycle. Daresay @JamesMcNee understands more of this area than me right now 😅

**Comment by arvindsv** [comment]
If the simplest and right thing to do is to use v2 and use the original
idea you had, that’s fine with me! Don’t let my comment derail this
conversation!

I don’t have any major concerns with the implementation being that way.

**Comment by JamesMcNee** [comment]
Hey @chadlwilson,

I [added a test to the Github Auth plugin](https://github.com/gocd-contrib/github-oauth-authorization-plugin/pull/278) to double-check compatibility, as we thought additional arbitrary properties are ignored. Whilst doing a little bit of research I found that it's not actually built into Gson to fail on unknown properties, I am much more familiar and used to working with Jackson, which does support this functionality, so assumed Gson would too.

I thought I might as well go ahead and commit the test I wrote on the GitHub plugin, because why not 😁 

Let me know if I can do anything to help with anything in order to get this issue resolved, again though, I totally appreciate the fight for your time!

**Comment by chadlwilson** [comment]
@JamesMcNee do you happen to know if any of the plugins you've taken a look at are (intentionally or not) depending on the v1 API?

My brief recollection is that to 'choose' a version a plugin either has to expose the plugin capabilities API and respond to the server, or possibly one of the fields in the plugin XML uses it (otherwise I assume server assumes latest version)

**Comment by JamesMcNee** [comment]
Hey @chadlwilson, I have not seen any that support the V1 API on my travels.

Plugins state the version(s) that they support within their '[identifier](https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/dc12798e4027934c37c0c18c8fbcb7f47e82294c/src/main/java/cd/go/authorization/github/Constants.java#L31)' which is exposed via one of the methods that [must be implemented](https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/dc12798e4027934c37c0c18c8fbcb7f47e82294c/src/main/java/cd/go/authorization/github/GitHubPlugin.java#L90-L93) on the base plugin class. A plugin can list support for multiple API versions and internally handle requests from different versions (presumably to support backward compatibility). There [is (some slightly convoluted 😅) code](https://github.com/gocd/gocd/blob/bb759b45c17381750899f0a53a18e230c3fb57e2/plugin-infra/go-plugin-infra/src/main/java/com/thoughtworks/go/plugin/infra/DefaultPluginManager.java#L161-L176) in the plugin handler code that then picks the latest version declared by the plugin that is also recognised by the server.

So in terms of:
> My brief recollection is that to 'choose' a version a plugin either has to expose the plugin capabilities API and respond to the server, or possibly one of the fields in the plugin XML uses it (otherwise I assume server assumes the latest version)

I believe that specifying supported version(s) is always an explicit act.

I assume you ask as you're trying to get rid of V1 (which will make the code less tidier 😁, let me know if I can be of assistance 👍

**Comment by chadlwilson** [comment]
> Hey @chadlwilson, I have not seen any that support the V1 API on my travels.

Yeah, I can't find any that support v1 but NOT also V2 (at least within the `gocd` and `gocd-contrib` ecosystem which is my primary concern)

> Plugins state the version(s) that they support within their '[identifier](https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/dc12798e4027934c37c0c18c8fbcb7f47e82294c/src/main/java/cd/go/authorization/github/Constants.java#L31)' which is exposed via one of the methods that [must be implemented](https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/dc12798e4027934c37c0c18c8fbcb7f47e82294c/src/main/java/cd/go/authorization/github/GitHubPlugin.java#L90-L93) on the base plugin class. A plugin can list support for multiple API versions and internally handle requests from different versions (presumably to support backward compatibility). There [is (some slightly convoluted 😅) code](https://github.com/gocd/gocd/blob/bb759b45c17381750899f0a53a18e230c3fb57e2/plugin-infra/go-plugin-infra/src/main/java/com/thoughtworks/go/plugin/infra/DefaultPluginManager.java#L161-L176) in the plugin handling mechanism that then picks the latest version declared by the plugin that is also recognised by the server.

Thanks a lot for clarifying and jogging my memory. Oh my goodness, so many different mechanisms, and I am completely confused it seems. I was thinking of the below, but technically a single plugin can implement multiple plugin API extensions (which would each have an implementation of different extensions) so the one below wouldn't have made sense. 🤦‍♂️

https://github.com/gocd/gocd/blob/bb759b45c17381750899f0a53a18e230c3fb57e2/plugin-infra/plugins/valid-plugin-with-multiple-extensions/plugin.xml#L18

> I believe that specifying supported version(s) is always an explicit act.

Yeah, it seems you are right, thanks!

> I assume you ask as you're trying to get rid of V1 (which will make the code neater for sure 😁), let me know if I can be of assistance 👍

Indeed, always nicer to reduce testing surface area. Normal HTTP APIs were regularly incremented, deprecated and removed with some decent automation support as it was so frequent, but I think plugin APIs were a bit more neglected since they underwent less churn, so this one might have been forgotten.

Looks like v1 might have been the version that **didn't** have the support for use of GoCD's own API access tokens (introduced in `19.2.0`) for users authorized via the plugin (terminology **very** confusing here, as "access token" is used different in two different contexts). In theory I think it'd be fine to drop support for plugins that don't at least handle the failure, but it looks like this would be "late" failure, since the access token would be issued, but then later when verifying it, it would fail if the plugin doesn't support it?

https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/api/api-access-token-v1/src/main/java/com/thoughtworks/go/apiv1/accessToken/CurrentUserAccessTokenControllerV1.java#L80-L86

https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/server/src/main/java/com/thoughtworks/go/server/newsecurity/providers/AccessTokenBasedPluginAuthenticationProvider.java#L76-L95

Bit annoying that this wasn't implemented using plugin capabilities as seems that'd be easier:

https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/plugin-infra/go-plugin-domain/src/main/java/com/thoughtworks/go/plugin/domain/authorization/Capabilities.java#L24-L29

And at least one plugin that does not support it (Google OAuth Authorization Plugin) implements V2, but then will fail late due to not handling the `is-valid-user` [plugin API call](https://plugin-api.gocd.org/current/authorization/#is-valid-user).

The plot thickens 🤦‍♂️

**Comment by JamesMcNee** [comment]
Hey Chad,

> Oh my goodness, so many different mechanisms, and I am completely confused it seems. I was thinking of the below, but technically a single plugin can implement multiple plugin API extensions (which would each have an implementation of different extensions) so the one below wouldn't have made sense. 🤦‍♂️

There are quite a few mechanisms at play 😂 I do agree to have this exposed through the 'Capabilities API' might have been a better choice to keep all of this centralised!

In terms of
> And at least one plugin that does not support it (Google OAuth Authorization Plugin) implements V2, but then will fail late due to not handling the is-valid-user [plugin API call](https://plugin-api.gocd.org/current/authorization/#is-valid-user) (see https://github.com/gocd-contrib/google-oauth-authorization-plugin/issues/60)

I actually think in this case we are fine; whilst I have been working on creating an auth plugin myself, I did not implement the `is-valid-user` handler until very recently. When the plugin doesn't respond to the `is-valid-user` request it seems that Go will simply treat that functionality as disabled. The UI (as described in that issue) states that access tokens are not supported by the auth plugin that has been used to login.

I am not sure that the following is actually an issue
> but it looks like this would be "late" failure, since the access token would be issued, but then later when verifying it, it would fail if the plugin doesn't support it?

since the ability to generate a token for a user who has logged in via the plugin will not be enabled.

**Comment by chadlwilson** [comment]
> I am not sure that the following is actually an issue
> 
> > but it looks like this would be "late" failure, since the access token would be issued, but then later when verifying it, it would fail if the plugin doesn't support it?
> 
> since the ability to generate a token for a user who has logged in via the plugin will not be enabled, it should not be possible to get into a position where a token needs to be verified.

Yeah, possibly via the UI it prevents that, so maybe it's just requesting an access token via the API that needs thinking about. Seems they use two different mechanisms:

UI (is via trying `is-valid-user` empirically)
https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/AccessTokensController.java#L81-L84

[API](https://api.gocd.org/current/#create-token-for-current-user) (seems via "dumb" plugin extension version check)
https://github.com/gocd/gocd/blob/29b88f59b1e08190ca46d030e636647775dc8f28/plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/AuthorizationExtension.java#L232-L235

Not sure why there are two different mechanisms (maybe as via API there is not the same user/session context?), but the second would have to be altered a bit I guess, at least to `version >= "2.0"` or equivalent since it currently refers to V1 classes.
