### ISSUE TITLE
Upgrade the version of apache shindig for mingle gadgets

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1169]
https://gitter.im/gocd/gocd?at=556c25448d1a52c22e86e4e3

**Comment by ketan** [comment]
@jyotisingh said she had a partial patch sitting somewhere to upgrade shindig. I know that part of the code, so I can finish it off quickly.

This would also be a good opportunity for someone to pair with me and get to know a bit more about gadgets.

**Comment by jyotisingh** [comment]
>> @jyotisingh said she had a partial patch sitting somewhere to upgrade shindig

Well what I said was while trying to introduce a library for json schema validations, I faced some runtime dependency conflict with shindig which would require upgrading shindig. I think I did make an attempt at upgrading shindig, but that also required upgrading gadgets which I wasn't keen on diving into at that point so that's where I stopped.

**Comment by arvindsv** [comment]
If you have that, at the point you stopped, let's finish it off? I don't mind pairing with you and learning about it. I know a bit of it, but there's lots I don't know.

**Comment by arvindsv** [comment]
If you don't, that's ok. We can start on it and get to that point.

**Comment by zabil** [comment]
Make this a plugin and remove it from core

**Comment by ketan** [comment]
Closing, not relevant anymore.
