### ISSUE TITLE
Ability to have empty material

### ISSUE THREAD

**Issue by Neko-Box-Coder** [gocd/gocd#12221]
##### Issue Type

- Feature proposal

##### Summary

I have just integrated into gocd.  While existing materials work great for the most part, there are some use cases where any of the material doesn't fit.

Having an empty material will allow this flexibility (using API call via CURL or manual trigger) which will avoid unwanted triggering by existing materials.

I know there's an option for setting manual trigger/webhook trigger but that's also problematic for other pipelines that use webhook as well.

Some use cases include but not limited to:
- A pure timer base pipeline by just using the cron timer (i.e. git tagging or updating github issue comments).
- A "shared" pipeline that is triggered by API where it can do the same thing for different branches or even different repo
- A pipeline that is triggered by an external API call (i.e. Github Action) for doing certain actions.
- A pipeline that requires special actions before cloning / checking out (i.e. Obtain authentication tokens to establish connection  to the repository maybe? idk)
etc...

###### Basic environment details

* Go Version: `23.4.0 (17731-4deb96d823b921419680560be080588e900d406e)`
* JAVA Version: `17.0.9`
* OS: `Linux 6.4.4-arch1-1`
* Browser vendor and version (if relevant): `Firefox but doesn't matter`

###### Additional Environment Details

n/a

##### Steps to Reproduce

n/a

##### Expected Results

An empty material that allows unwanted triggering.
Having an option to run a script/command and run the pipeline based on the return value is also nice

##### Actual Results

Must choose from any of the source control materials, no way to bypass it.

##### Possible Fix

See **Expedted Results**

##### Log snippets

n/a

##### Code snippets/Screenshots

n/a

##### Any other info

n/a

**Comment by chadlwilson** [comment]
> Having an empty material will allow this flexibility (using API call via CURL or manual trigger) which will avoid unwanted triggering by existing materials.

Can you describe what "unwanted triggering" you are referring to with an example?

> I know there's an option for setting manual trigger/webhook trigger but that's also problematic for other pipelines that use webhook as well.

I'm not following - can you elaborate on why this is problematic?

> Some use cases include but not limited to:
> - A pure timer base pipeline by just using the cron timer (i.e. git tagging or updating github issue comments).
> - A "shared" pipeline that is triggered by API where it can do the same thing for different branches or even different repo
> - A pipeline that is triggered by an external API call (i.e. Github Action) for doing certain actions.
> - A pipeline that requires special actions before cloning / checking out (i.e. Obtain authentication tokens to establish connection  to the repository maybe? idk)

I don't really understand the motivations for any of these and why they cannot be handled by the existing setup. These cases all sound to me like they could be just as well modelled with a source controlled scripts/commands as the material for actually do the described pipeline work. I don't see why an empty material would help - it sounds like you

In any case, you could try and write your own material plugin for some kind of "no-op" material if you want: https://plugin-api.gocd.org/current/scm/#extension-information

**Comment by Neko-Box-Coder** [comment]
> Can you describe what "unwanted triggering" you are referring to with an example?

Since a pipeline **must** have at least one material, I am **forced** to choose a material if I find myself in a situation where any existing material **doesn't work** for my use case.

Since I **have to** choose a material, the best bet for me is to choose a material (let's say git) bind to a repo, and tick the manual & webhook checkbox instead.

In this situation, I have lost the ability to use webhook for the binded repo if I want to create a second pipeline with it since it will "accidentally" trigger the first pipeline. That's what I meant with "unwanted" triggering since the material is not meant for the first pipeline in the first place

---

> Can you describe what "unwanted triggering" you are referring to with an example?

A very simple example would be

#### Time-based git tagging
If I just want to push a tag (or maybe some other git stuff) (let's say) every Friday at 5pm for (a) branch(es), there's no clean way to do that on GoCD at the moment.

This is because the pipeline has to have a material that is binded to a repo as said previously with manual/webhook checked. And if I do that, I literally can't use a webhook trigger pipeline for that repo for another pipeline because it will trigger this timer pipeline.

---

A more complex example would be

#### Sharing pipeline between internal (trusted) branches and forked PR (untrusted) branches
If I want the pipeline to ask permission for only untrusted branches, there's no clean way to do it with multiple materials.

So the cleanest solution would be to have two "trigger" pipelines with the git material and PR material respectively with the pipeline that has the PR material will ask for permission. 
These "trigger" pipelines will then trigger the "main" pipeline via API and environment variables. Where the "main" pipeline will then clone the correct branch according to the environment variables set by the "trigger" pipeline.

In this case, it doesn't make sense for any material to be applied for the "main" pipeline since I don't want it to be triggered other than API or manual trigger. 

And the git material doesn't really make sense since it is used by the "trigger" pipeline. 

Although having an empty material in this case is not the root fix, it is certainly better than being forced to choose a material.

---

> In any case, you could try and write your own material plugin for some kind of "no-op" material if you want

Yes, I can but it would be nice if this is something that could be provided officially out of the box. 

Having this will greatly increase the flexibility of GoCD because it will now in theory works on anything as long as you can do it with bash/batch script.

---

I don't know if this clears up some if not all of my points, if not please let me know.

**Comment by chadlwilson** [comment]
Overall, I believe the challenge here is that you are thinking about pipelines in a way that is completely different to the GoCD philosophy - and not thinking about how to design these workflows in ways that allow you to use GoCD's modelling approaches to watch changes flow along pipelines.

GoCD can do things that other tools cannot do (e.g "proper" version-consistent fan-in) precisely because it is "material first" and thinks in terms of traceability between inputs and outputs and flows in ways that other tools cannot -  even if they are more flexible.

> > Can you describe what "unwanted triggering" you are referring to with an example?
> 
> Since a pipeline **must** have at least one material, I am **forced** to choose a material if I find myself in a situation where any existing material **doesn't work** for my use case.
> 
> Since I **have to** choose a material, the best bet for me is to choose a material (let's say git) bind to a repo, and tick the manual & webhook checkbox instead.
> 
> In this situation, I have lost the ability to use webhook for the binded repo if I want to create a second pipeline with it since it will "accidentally" trigger the first pipeline. That's what I meant with "unwanted" triggering since the material is not meant for the first pipeline in the first place

There is no unwanted triggering here - if you simply choose a material relevant to the pipeline in question, not one you want to use for a different purpose/pipeline. Or use something like the [gocd-git-path-material-plugin](https://github.com/TWChennai/gocd-git-path-material-plugin) to base triggers off sub-sets of repos rather than the entire thing if you're trying to not create dummy repos.

> > Can you describe what "unwanted triggering" you are referring to with an example?
> 
> A very simple example would be
> #### Time-based git tagging
> 
> If I just want to push a tag (or maybe some other git stuff) (let's say) every Friday at 5pm for a branch / branches, there's no clean way to do that on GoCD at the moment.
> 
> This is because the pipeline has to have a material that is binded to a repo as said previously with manual/webhook checked. And if I do that, I literally can't use a webhook trigger pipeline for that repo for another pipeline because it will trigger this timer pipeline.

I don't think this is accurate that there is "no clean way".

If you don't want **any** of your pipelines to be polling for changes, you can turn polling off on the material definition entirely.

Additionally, I believe if you add a **Denylist** of, say `**/*` to the "timed" pipeline's material definition, it may behave the way you desire without being triggered from the webhooks. Have you tried this?

While some may differ on whether that is "clean" enough, it still allows the "thing to do" (say pushing a tag) to be modelled next to the thing it is tagging (the underlying repository).

> A more complex example would be
> #### Sharing pipeline between internal (trusted) branches and forked PR (untrusted) branches
> 
> If I want the pipeline to ask permission for only untrusted branches, there's no clean way to do it with multiple materials.

You're not really supposed to "share" a pipeline between different branches in GoCD, so the premise is a bit off here. While this is the more common approach in other tools, it's not really the canonical GoCD approach.

GoCD is heavily designed around trunk-based development, not long-lived branch oriented flows. These use cases have never been a major priority for GoCD design, however there have been going efforts with various approaches back as far as articles like [this](https://www.gocd.org/2015/04/27/Feature-Branch-Support/) and https://github.com/gocd/gocd/issues/6123.

Having said this, this specific problem is addressed in many ways that dont require an "empty material".
1) Add a manual/approval stage/pipeline with a dummy task as the root pipeline for the "untrusted" pipelines, requiring something to manually trigger it. 
2) You can then use [groovy-dsl-config-plugin](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin) with or without pipeline templates to avoid duplication in your pipeline config between various PR/branch based pipelines

> So the cleanest solution would be to have two "trigger" pipelines with the git material and PR material respectively with the pipeline that has the PR material will ask for permission. These "trigger" pipelines will then trigger the "main" pipeline via API and environment variables. Where the "main" pipeline will then clone the correct branch according to the environment variables set by the "trigger" pipeline.

This is not correct modelling in GoCD, and I don't agree this is the cleanest solution. If you clone different branches based on an env variable, you are sidestepping all material knowledge by GoCD, so GoCD does not know anything about the nature of the changes being built and propagated by these pipelines, undermining its goals in improving traceability to understand, say, which specific change caused a branch build to fail when deployed later on to some test environment (for example).

If you are thinking of modelling on GoCD in this kind of way, you are losing most of the benefits of GoCD, reducing it to an arbitrary task runner, and are probably best to use some other tool whose mental model fits your own.

It feels like you are trying to think about GoCD in the same way as other tools where cloning a repo is just another "task" for the job to complete. GoCD thinks about things differently by modelling materials as first class citizens. It's not a design goal to undermine that, which empty materials would seem to do to me.

> In this case, it doesn't make sense for any material to be applied for the "main" pipeline since I don't want it to be triggered other than API or manual trigger.

Without a material you are declaring that the pipeline has no important "inputs" that will lead to an "output", which is not the case. The source code is the input, or alternatively the logic to actually run the build could/should be source controlled into a material rather than defined in GoCD tasks. Either or both of those are valid materials for the "main" pipeline - modeled differently.

> And the git material doesn't really make sense since it is used by the "trigger" pipeline.

I think this is a misconception. Having two pipelines in a value stream with the same material is actually quite common in that it allows providing the integrity guarantees GoCD offers on version consistent for dependency pipelines.

The issue here is that your proposed design (triggering via an API) doesn't allow GoCD to understand or visual the VSM at all (traceability for who triggered at which revision - which lead to which branch/PR build outcome). It breaks the modelling of flow.

A more canonical way is to model `main` as having a dependency material to `trigger`, and with the same (git) material as inputs so that you can ensure consistency. GoCD itself uses this approach for PR branches:

![image](https://github.com/gocd/gocd/assets/29788154/64951682-10a6-496b-8272-7f041c41f1a1)

> > In any case, you could try and write your own material plugin for some kind of "no-op" material if you want
> 
> Yes, I can but it would be nice if this is something that could be provided officially out of the box.

I can't see anything here that can't be done with other approaches more consistent with GoCD's philosophy and 'good practice' for pipeline design. Personally I don't see the reason for this, and without more help and discussion this is unlikely to happen anyway.

> Having this will greatly increase the flexibility of GoCD because it will now in theory works on anything as long as you can do it with bash/batch script.

It already can do anything you can do with a bash/batch script. You can always just source control that and use that as your material rather than using GoCD itself to store your "steps to run".

I'm going to close this, as at the moment this doesn't seem necessary or consistent with the project goals given # of maintainers available to give input - nor compelling enough to warrant a whole new material that might have all sorts of unintended consequences compared to the current design.

If you're newish to GoCD and still are interested to continue with it, I'd encourage you to spend more time investigating various plugins and approaches to modelling rather than trying to apply the exact same concepts from other tools. Perhaps it would be useful to ask "what's the best way to model/achieve X?" in questions to the community rather than starting with a proposed solution and working backwards to the actual problems you are trying to solve?
