### ISSUE TITLE
Unable to pick stage from Add Material menu in Chrome on MacOS Sonoma

### ISSUE THREAD

**Issue by chris-gillatt** [gocd/gocd#12305]
##### Issue Type

- Bug Report

##### Summary

In Chrome Version 119.0.6045.159 (Official Build) (arm64) on a Mac, there appears to be a bug in the Upstream Pipeline selection drop-down. 

Screenshot: 

<img width="840" alt="image" src="https://github.com/gocd/gocd/assets/9963006/e933c18c-bbcd-4a7c-9f40-676461763c44">

Video

https://github.com/gocd/gocd/assets/9963006/68194810-8598-43c2-a27e-ed2f6609d32a

As can be seen in the video, selecting the stage blinks on screen and closes too fast for the user to be able to select it.  As a work around, you can use the keys on the keyboard to select the desired stage.  Once the workaround has been performed, the stage can be selected normally.  The functionality appears to work fine with Safari and Firefox. 

###### Basic environment details

* Go Version: `23.4.0`
* JAVA Version: `17.0.9`
* OS: `Linux 5.15.120+`
* Browser vendor and version (if relevant): `Chrome Version 119.0.6045.159 (Official Build) (arm64)`

##### Steps to Reproduce

1.  Open up a material of an existing pipeline
2. Add a material from a pipeline
3. Select material type "another pipeline" 
4. Attempt to select upstream stage

##### Expected Results
Should be easy to select the chosen stage

##### Actual Results
Drop down immediately closes so that you can't select the chosen stage. 

##### Workaround
Just use the up/down keys once the drop down is selected and you can once again select the right stage.  Another workaround is to use Safari or Firefox.

**Comment by chadlwilson** [comment]
Presumably it was working OK with Chrome 118 or some earlier version?

**Comment by chris-gillatt** [comment]
On further investigation, I think that this could actually be related to the recent rollout of MacOS `Sonoma 14.1.1` in my business, rather than Chrome or GoCD.

I've run a bunch of tests, and I see the issue with Chrome all the way back to Chrome v105, and GoCD versions back to `23.1.0-16079`. I can also confirm that one of our users who does **not** see the issue, is on Chrome `v117.0.5938.149` on MacOS `Ventura 13.2.1`.  Unfortunately I don't have a test Mac to roll back the OS on to investigate further on that point, and my Mac is on Sonoma.

**Comment by chadlwilson** [comment]
Ok, no worries - at least I should be able to replicate as long as it's not dependent on any particular Chrome extensions, and that's also a bit more narrower and thus easier to trace.

**Comment by chadlwilson** [comment]
Well I can certainly replicate, but no idea what is causing this. Based on random googling, it does seem there are a lot of Chrome things broken for various folks on Sonoma.

There is anything fancy about this dropdown - it's a basic HTML `<select>` with `<option>`s. Only slightly different weirder thing is that it's on an overlay. I suspect we just need to wait for a MacOS or Chrome fix here.

**Comment by chris-gillatt** [comment]
Great - thanks for looking.  I think you're probably right - something for Apple to fix.  What's puzzling about this is that I've not been able to find another dropdown in GoCD that suffers from the same (mis)behaviour.

**Comment by chadlwilson** [comment]
The problem is related to the `-` default option which is specific to this pipeline material selector. Other dropdowns don't seem to have that "force the user to actually select something valid" behaviour.

When there is no existing selection from the dropdown (as for a new material, not not an existing one), something is going awry with the default selection when you open it causing the native selector to close.

After some digging, I think this is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1497774 - I am guessing when there is no existing selection the selection gets updated when you open the menu, or something, triggering this bug. Fixed for 121 based on https://github.com/chromium/chromium/commit/9aa331b609148d588ce602cec147ec2f61fc09c3 and also verified it's fixed for in Chrome Dev (`121`) locally.

Anyway, the workaround is pretty low risk, so will implement that all the same.
