### ISSUE TITLE
Feature: extend Artifact API for easier access of artifacts from upstream dependencies

### ISSUE THREAD

**Issue by mpoeter** [gocd/gocd#1244]
One can fetch an artifact of a pipeline using the Artifact API -> `http://[server]/go/files/[pipeline]/[pipeline-counter]/[stage]/[stage-counter]/[job]/[pathname]/[filename]`

However, there is no simple way to fetch the correct version of an artifact from an upstream dependency of this pipeline. i.e. fetch the same artifact as a fetch-artifact-task in the pipeline would.
I would like to have something like this: `http://[server]/go/upstream/files/[pipeline]/[pipeline-counter]/[upstream-dependency]/[stage]/[job]/[pathname]/[filename]`

Background: I would like every job to contain only a single task that runs a script that comes from VCS. At the moment the fetch-artifact-tasks are part of the go config, while the build/test script is part of some other VCS repository. Whenever I change the script (e.g. add a new dependency) I also have to update the go config. But since these two places cannot be updated together in one step there is almost always at least one broken build.
Also it is easy to forget to update the go config or to make a mistake (e.g. mistype a filename). There is no way to test a job that contains fetch-artifact-tasks other than running the pipeline. This is effectively a try-and-error approach.
With such an API it would be possible to define the artifacts that have to be fetched from other pipelines as part of the build script (e.g. a special Rake task), but leave the heavy lifting (i.e. determine the correct version) to Go.
That way the script could also be run locally (one just has to define the pipeline and pipeline-counter).

**Comment by mpoeter** [comment]
After thinking about this for a while I think it would be even better to have an API for bulk request of artifacts. The requested artifacts together with their target path could be defined in a json file like this:
```
[
  "." : "upstream-dependency1/stage/job/path1/folder",
  "subfolder" : [
    "upstream-dependency1/stage/job/path2/file",
    "upstream-dependency2/stage/job/path/*"
  ]
]
```
This would allow to define all the required artifacts together with the target structure in a single place. Go could process this in on step and generate a zip archive with all artifacts (from potentially different pipelines) already in the request structure of folders.
This would reduce the number of network connections and the amount of data to be transferred as all artifacts are fetched in a single step in a compressed archive.

What do you think?

**Comment by virtuald** [comment]
I was just contemplating the need for something like this, and I'd definitely like something similar to your last comment.

What I would really like is just a pipeline step that is "fetch all", and it unpacks all immediately upstream artifacts in directories sorted by their upstream pipeline name. I don't think it's strictly necessary to zip it all up for our use case since our artifacts tend to be small. 

Example: two upstream pipelines, `a` and `b`. both publish some file called `VERSION`. Pipeline `c` uses `a` and `b` as upstream pipelines, and contains a build step for 'fetch all', with a destination parameter of 'upstream'.

When the 'fetch all' build step runs, then it automatically creates the following directory structure in the working space of pipeline `c`:

    upstream/
    upstream/a/VERSION
    upstream/b/VERSION

This would be particularly useful from inside a template.
