### ISSUE TITLE
Environment variables fields get cleared on validation errors 

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1272]
To reproduce this.

* Edit a pipeline
* Click on the environment variables tab
* Set an invalid value for e.g. sample = #{undefinedParameter}
* Click on save

The name and value fields get cleared.

Expected behavior.
name and value must **not** be cleared.

**Comment by juhijariwala** [comment]
As things stand currently, the environment variables page [link](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/environment_variables.html.erb#L7)  loads up the environment variables directly from the pipeline config object.

Ideally, we'd want to load these environment variables from a pipeline config that is controlled by the controller (so that we can pass in the set of bad environment vars to be rendered)

**Comment by chopraapooja** [comment]
Fields clearing will only occure when validation fail due to #{undefinedParameter}, if we look at any other type of validation fail it doesn't clear feilds. For e.g. repeating env var name, value without env var name, etc.

**Comment by arvindsv** [comment]
Closing this, since this should be irrelevant, given the move to the new config page. @zabil, can you please reopen this if you don't agree?
