### ISSUE TITLE
rpmlib(RichDependencies) <= 4.12.0-1 is needed by GoCD 24.2.0

### ISSUE THREAD

**Issue by xRomZak** [gocd/gocd#12893]
##### Issue Type

- Bug Report

##### Summary

Trying to upgrade installed GoCD distro
```
rpmlib(RichDependencies) <= 4.12.0-1 is needed by go-server-24.2.0-19076.noarch
rpmlib(RichDependencies) <= 4.12.0-1 is needed by go-agent-24.2.0-19076.noarch
```

###### Basic environment details

* Go Version: 23.5.0 (18179-7702b283accd1f90f014f0087aa2e9bd8baf4a97)
* JAVA Version: 17.0.9
* OS: Linux 3.10.0-1160.114.2.el7.x86_64

**Comment by chadlwilson** [comment]
Which distro and version are you trying to install on?

**Comment by chadlwilson** [comment]
Based on some quick googling, this looks like something that might happen after doing an in-place CentOS 7 to CentOS 8 type of migration (or perhaps a migration away from CentOS) so you may need to cleanup/upgrade of `dnf` and/or `rpm` versions, but we'd need to know the history of what you did to suggest a workaround.

**Comment by chadlwilson** [comment]
`Linux 3.10.0-1160.114.2.el7.x86_64` implies you are/were on some kind of RHEL7 variant. RHEL 7/CentOS 7 and similar are no longer supported since they are EOL in a week, however that's not normally the error you would get if trying to install on it. (normally you'd get a missing dependency for `java-21-openjdk-headless` or `java-17-openjdk-headless`)

If you are happy to "bring-your-own" Java runtime (Java 17 or Java 21) from `24.2.0` you possibly can work around this by **not** installing the JRE dependencies, i.e `dnf upgrade go-server --setopt=install_weak_deps=False` but you would then need to alter GoCD wrapper config to point it to a Java 17|21 runtime, if there is not one on the path by default.

See #12415, #12712 and #12792

**Comment by chadlwilson** [comment]
Will re-open if you still think this is a bug.

**Comment by polaroi8d** [comment]
I have the same issue when trying to update `24.3.0` `go-agent` service on `RHEL 7.9`.

**Comment by chadlwilson** [comment]
Yeah, as i said above, RHEL 7 is EOL from Redhat outside of extended lifecycle support so GoCD does not support it 'out of the box'.

You need to BYO Java Runtime with my workaround above if you want to continue to install later GoCDs from RPM on RHEL 7.

**Comment by polaroi8d** [comment]
I saw that, but we are using `7.9` which is still supported as I understand correctly.

**Comment by chadlwilson** [comment]
Not for almost all users: https://endoflife.date/rhel 

Only "Extended Life Cycle Support" is available since June 2024 - which requires purchasing an annual subscription add-on from RedHat, on top of your existing Standard/Premium subscription. https://access.redhat.com/support/policy/updates/errata#Extended_Life_Cycle_Support

> Extended Life-cycle Support (ELS) is an optional Add-On subscription for certain Red Hat Enterprise Linux subscriptions. The ELS Add-on is available during the Extended Life Phase for Red Hat Enterprise Linux 7.
>
> Red Hat Enterprise Linux 7 ELS delivers certain Red Hat defined Critical and Important security fixes and selected (at Red Hat discretion) urgent priority bug fixes and troubleshooting for the [last minor release](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).

GoCD is a community-driven open-source project; so we do not provide more than best-efforts support for EOL software which otherwise requires an enterprise/corporate commercial support contract. RHEL 7 falls into this category, and since there are no open source/FOSS 7.x RHEL clones that provide security support (CentOS, Rocky, Alma etc), we also no longer support it.

**Comment by polaroi8d** [comment]
Thanks @chadlwilson for the detailed answer.
