### ISSUE TITLE
Cannot delete a build (pipeline run)

### ISSUE THREAD

**Issue by andreoid** [gocd/gocd#13]
As an admin, using the web interface I should be able to delete old builds.

As an example, in the screenshot below, I should be able to delete the #52 pipeline.

![image](https://f.cloud.github.com/assets/452963/2332185/bfab08aa-a453-11e3-8c12-40fd0cebe640.png)

**Comment by srinivasupadhya** [comment]
@birgitta410 that is a problem of graph rendering framework more than problem of of data?

---

Deleting builds specially in between pipeline runs leaves holes in history & this could cause issues while rendering pipeline/stage/job history & VSM. Currently you can view VSM of all pipelines (even if the upstream pipelines don't exist anymore in config) because the run information is still present. If the run info. is deleted it will not be possible to reproduce the whole upstream.

**Comment by birgitta410** [comment]
@srinivasupadhya Good point :-)

**Comment by andrewmyhre-justgiving** [comment]
In my case I accidentally manually pushed a package to a repository with a major version much higher than our CI build actually produces. Now there is a pipeline ~50 major versions ahead of our build so now Go is ignoring new builds from that material. If there's any way to delete that build I want to do it, even if it's really really hard because it'll only happen one time.

**Comment by andrewmyhre-justgiving** [comment]
I figured out I can resolve this by creating a new material and specifying version less than X

**Comment by tdegueur** [comment]
Sorry for reviving this old issue, but it seems to me that being able to delete old builds is a good thing in some circumstances. In our case, a build was launched and has been running for about 15 hours due to a problem in test scenarios. During those 15 hours, a tremendous amount of logs has been generated (our Go server can't even load the console for the stage in question), the result being that our Go server ran out of disk space and now refuses to schedule new builds.

Maybe we shouldn't put our Go server on a machine with limited disk space, and maybe we should have put a fail-safe in place to avoid such behavior, but the fact of the matter is that it can happen due to human error and the simplest solution to fix the situation would be to delete the build and/or its logs.

**Comment by zabil** [comment]
Alternatively.
@tdegueur the logs are managed as artifacts and by default saved in the 'artifacts' folder.
You can locate the pipeline/stage/job there delete the console logs when you run into a problem like this.

**Comment by tdegueur** [comment]
@zabil
Thanks for quick response, I managed to delete the artifacts of the build but the file that contained the problematic logs was located in "{go-server-home}/data/console".

**Comment by zabil** [comment]
Ah ok, So those are temporary files.
While the build is running all the console logs are buffered on the server and *moved* to artifacts folder once a build is complete. (passed, failed or canceled). 
However, killing an agent etc leave these temp files around.

**Comment by tdegueur** [comment]
Good to know, I did kill a few processes instead of cancelling the stage through the server GUI, my bad.
If I understand correctly, this big temporary file would have been moved as is to the artifacts folder you were pointing me to and stayed there permanently?

**Comment by zabil** [comment]
> If I understand correctly, this big temporary file would have been moved as is to the artifacts folder you were pointing me to and stayed there permanently?

Yes

**Comment by TehPsychedelic** [comment]
From what I see this still not possible?
Another reason: You output a file contents that you modify on the fly or anything that can have sensitive information on it (secrets) for debug purposes (deployment failing etc), and then you'd like to remove the history for that particular run, or at least the console output.

Saying that it cannot be deleted for audit purposes would be like forbidding an unix admin to delete bash history.

**Comment by arvindsv** [comment]
@TehPsychedelic It's easy to delete console output. Just find the console.log file in `artifacts/pipelines/pipelineName/pipelineCounter/stageName/stageCounter/jobName/cruise-output/console.log`. In fact, it'll even delete automatically if there's a lack of space.

This is more about the fact that the pipeline run even happened. It's more about what is in the DB.

**Comment by arvindsv** [comment]
Closing as stale.
