### ISSUE TITLE
Startup Scripts should use Exec, not Eval

### ISSUE THREAD

**Issue by grahamc** [gocd/gocd#1334]
The startup scripts on the agent and server both call `eval` instead of `exec`. This has the side effect of signals being sent to the parent process (the bash script when not using nohup) do not get sent to the child java process. Using exec`s process replacement, java correctly receives the signal.

 - https://github.com/gocd/gocd/blob/master/installers/server/release/server.sh
 - https://github.com/gocd/gocd/blob/master/installers/agent/release/agent.sh

**Comment by ketan** [comment]
Thank you for reporting this issue, we're at the tail end of 15.2, so we'll be considering this issue for 15.3 instead.

**Comment by chopraapooja** [comment]
Using exec instead of eval to start java process in foreground looks fine here :-
- https://github.com/gocd/gocd/blob/master/installers/server/release/server.sh#L139 
- https://github.com/gocd/gocd/blob/master/installers/agent/release/agent.sh#L124 

I think, there is no need  of ```exec``` during starting java process in background (DAEMON), ```nohup``` will take cares of that.

**Comment by rajiesh** [comment]
this has been QA tested on 15.3.0-2597 build on MAC OSX, linux(centOS and Ubuntu) and solaris
