### ISSUE TITLE
ldap group OUs

### ISSUE THREAD

**Issue by jeremymv2** [gocd/gocd#134]
Support for using an organization's existing ldap/AD groups would be really valuable.

**Comment by maxamg** [comment]
It's been a year - is there really no demand for this feature? I'm working at a Bank - it could be make or break.

**Comment by arvindsv** [comment]
@maxamg: There's no lack of demand for this and many other things. However, no one from the community has stepped up to work on the feature, and within the core group of contributors, the focus has recently been more on enabling Go to be extended, rather than working on specific features.

Specially with LDAP, there seems to be a never-ending set of extensions that Go would need to support, if we go down that path. For instance, I have heard the need for support for LDAP referrals, Microsoft AD support, support for groups (this one) and support for multiple different LDAP servers. That's off the top of my head. Though all of this would be great, I don't think we can afford to work on all of this, given that there are other aspects which need work too.

Getting to solutions: I talked about the core contributors work on extensibility. A relevant example of this is the [authentication endpoint](http://www.go.cd/documentation/developer/writing_go_plugins/authentication/json_message_based_authentication_extension.html) (it is in progress, and documentation is not complete too) which is in its early days. It was started because of the need for TOTP and SSO authentication support (login). I can think of ways that it might be extended to support groups, etc. That work isn't done yet. It'll need to become a little mature. But, if Go gets support for LDAP groups, I think it'll be through a plugin or through a contribution by a contributor outside of the core group.

**Comment by maxamg** [comment]
Understood - thanks for the detailed update @arvindsv

**Comment by lenucksi** [comment]
:+1:

**Comment by arvindsv** [comment]
Closing this. The [LDAP authentication plugin](https://github.com/gocd/gocd-ldap-authentication-plugin) is the right place for this now - and it is more feature-ful, I think. Maybe this is done?

**Comment by PredatorVI** [comment]
I think this is is still an issue as it relates to the integration between roles and the authentication system(s).  From my experience, user permissions are managed through LDAP groups.  Users are added to groups and groups are given permissions in the application to do certain things or have certain visibility.

I'm using GoCD 17.11.0 with LDAP authentication plugin 1.0.1-49 and can authenticate users just fine, but if I try to use an LDAP group as a role, such as:

**Comment by PredatorVI** [comment]
"approval": {
				"type": "manual",
				"users": [],
				"roles": ["deploy_production"]
			},
where 'deploy_production' is an ldap group containing the users who have permission to perform production deployments, I get the error:

![image](https://user-images.githubusercontent.com/1933277/32908054-9cd8f148-cabf-11e7-8aad-9773c245c290.png)
 
So roles dont' seem to extend beyond what is defined in GoCD explicitly. It would be nice if the role system would allow LDAP groups to be specified and enable defined access based on user membership.

**Comment by ketan** [comment]
> So roles dont' seem to extend beyond what is defined in GoCD explicitly. It would be nice if the role system would allow LDAP groups to be specified and enable users access based on group membership.

This role mapping is available as a commercial add-on from ThoughtWorks.
