### ISSUE TITLE
UI bug with chrome

### ISSUE THREAD

**Issue by Ehekatl** [gocd/gocd#1352]
15.2 is become support release, but the UI bug remain on Chrome, it works fine with other web browser: 
![](http://7xicnm.com1.z0.glb.clouddn.com/tmpbug.PNG)

**Comment by arvindsv** [comment]
Hmm. This doesn't happen to me, and I haven't heard about this happening to anyone else.

Which version of Chrome do you use? I use 43.0.2357.134 and it's fine on it. Do you have any extensions which change stylesheets or something? Can you check with an incognito window, whether this happens?

You can also try to start up Chrome with a new profile, so that existing plugins don't get used. Something like:

```
mkdir /tmp/newchrome
/path/to/chrome --user-data-dir="/tmp/newchrome" --no-default-browser-check --incognito --homepage=about:blank --no-first-run --window-position=0,0'
```

Finally, can you try and see whether it happens on build.go.cd as well? Username: "view" and password is "password".

**Comment by Ehekatl** [comment]
@arvindsv 
I'm on windows with 43.0.2357.134 m, disable all plugins and try with an incognito window
![](http://7xicnm.com1.z0.glb.clouddn.com/tmp_screencapture-build-go-cd-go-pipelines-1437097851393.png)

**Comment by Ehekatl** [comment]
this problem happens when I upgrade to 15.2

**Comment by arvindsv** [comment]
Closing this. Please reopen if happening on a recent build.
