### ISSUE TITLE
How to autoregister Agents on Mac OS X?

### ISSUE THREAD

**Issue by JamesMGreene** [gocd/gocd#1365]
As far as I can tell, I've read _all_ of the instructions related to installing GoCD Agents on various platforms several times over.  On the Linux/UNIX-style platforms, it appears to be pretty easy to auto-register a new Agent by just putting a "autoregister.properties" file in the appropriate location.

Can this be done with Agents on Mac OS X (when installing via either the "Go Agent.app" or the source ZIP file, either would be fine if they can support this)?

If so, what is the correct location for that "autoregister.properties" file?  I'm unsure, at least when using the "Go Agent.app" installation, because the file structure is completely different than using the Linux/UNIX-style packages/installations.

**Comment by JamesMGreene** [comment]
Is the correct assumption that it should be a file called "config/autoregister.properties" that is located relatively to the "agent-bootstrapper.jar" file?

e.g.

```
- agent-bootstrapper.jar
+ config/
     - autoregister.properties
```

**Comment by ketan** [comment]
> Perhaps a correct cross-platform generalization is that it should be a file called "config/autoregister.properties" that is located relative to the "agent-bootstrapper.jar" file?

Technically, the `config` directory is relative to the directory where the agent runs from (`$PWD`). What you have is a good approximation for all practical purposes, since the bootstrapper is invoked using `java -jar agent-bootstrapper.jar`

Would you mind updating the [auto register documentation](https://github.com/gocd/documentation/edit/master/user/advanced_usage/agent_auto_register.md) with a simple table that lists the location on various OSes (or atleast that you have figured out)

**Comment by JamesMGreene** [comment]
> Would you mind updating the auto register documentation with a simple table that lists the location on various OSes (or atleast that you have figured out)

Will do.

**Comment by arvindsv** [comment]
Closing since it needs a doc update.
