### ISSUE TITLE
Go Server check for new git connections fails because GIT_SSH is not honored

### ISSUE THREAD

**Issue by JamesMGreene** [gocd/gocd#1382]
We use a elegant little bash script to automatically manage Go's use of per-repo application/deployment keys for our private repos, whose path is exported in the `go` user account's `.bashrc` file to the environment variable `GIT_SSH` (a part of `git` core).

If I SSH into the Go Server and impersonate the `go` user account (`sudo su - go`), all of my SSH-based Git commands work just fine when I attempt to access those private repos.

This leads me to believe 1 of 2 (or maybe 2 of 2) trouble spots exist in your implementation's use of the `git` command line:
 1. Your `CommandLine` object is not executing as the `go` user account.
 2. Your `CommandLine` object is executing as the `go` user account **but** its command is executed in such a way that the `.bashrc` file for the `go` user account is not sourced (i.e. no bash session/TTY created when executing the command) and thus the `GIT_SSH` environment variable is not being exported.

Offhand, I'm guessing the latter is the real culprit.

**Comment by JamesMGreene** [comment]
FYI, putting the `GIT_SSH` environment variable export into the `/etc/default/go-server` configuration file instead of the `/var/go/.bashrc` file seemed to do the trick.

Are the `/etc/default/go-server` config file (and/or its `/etc/default/go-agent` counterpart) the best places to add such environment variables?  If not, where else should things such as this be accounted for?

**Comment by arvindsv** [comment]
Yes, the files in `/etc/default` are the right places to initialize those environment variables. The files are sourced [during startup](https://github.com/gocd/gocd/blob/master/installers/server/release/server.sh#L24). Depending on [bash initialization](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_01.html) is always going to be a little tricky, because it runs some scripts only in certain modes (interactive/non-interactive, login vs. non-login, etc). So, I'll close this issue for now. Let me know if you think I should reopen it.

**Comment by JamesMGreene** [comment]
:+1:
