### ISSUE TITLE
check paths in zip archive before unzipping during artifact upload

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1393]
#1371

**Comment by rajiesh** [comment]
When the artifact to be uploaded to Server contains directory traversal characters, the artifact upload fails but appropriate message not logged in the log file

The reason is because on identifying traversal characters the method throws "IllegalStateException" but the caller only handles "IOException" due to which the appropriate exception is not handled

**Comment by rajiesh** [comment]
verified this fix on 15.3.0-2651. Exception handled as expected. However there is a retry during artifact upload failure which can be avoided in case of IllegalPathException. Have created new issue #1621 to fix the retry logic. This bug can be closed.
