### ISSUE TITLE
Redesign the pipeline configuration page

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1404]
Linked and part solution to #838 

The current admin screen posts every operation (save stage, jobs etc) to the server. This is turning out to be a painful experience for the user when the size of the config file is large as we validate, merge, save and reload the config.

To solve the problem we propose 
- Converting the page to have a save operation that will post the whole pipeline configuration when stages/jobs/tasks etc are modified.
- Exposing an API that will validate and save the pipeline configuration intelligently without having to validate the whole of config xml.
-  Maintaining the state of Added/Modified/Deleted of stages, jobs or tasks in the browser till the save/cancel button is clicked.

@ketan @arvindsv @srinivasupadhya please feel free to add more details.
#### Checklist of Items to be done
- #1722 General Options
- #1723 Project Management
- #1724 Materials
- #1725 Stages
- #1726 Stage
- #1605 Auto-complete for resources
- #1727 Tasks
- #1729 Navigation  
- #1728 Save
- #1733 Job Configuration
### Technical
- Trim down the list of routes in `js-routes`
- Handle situations when a plugin is removed, but configuration exists 
  ![screen shot 2015-09-03 at 3 00 47 pm](https://cloud.githubusercontent.com/assets/10598/9655109/8fd14286-524c-11e5-81fe-fa7257578d07.png)

**Comment by zabil** [comment]
Showdown for UI framework to be adopted happening at
https://github.com/gocd/spikes

**Comment by zabil** [comment]
Post initial spike we are convinced on using Mithril.
We'll use it to model a better config edit page and see how it goes. 

Some notes on Mithril
* Better handling of binding and intelligent redraws using the virtual dom.
* Support for traditional MVC, routing and template in a uncompressed 12kb library
* Cleaner template system even without the use of JSX/MSX   
* Support for using plain javascript idioms without being tied to a framework.
* Excellent documentation (partly due to the simplicity of the framework)

Mithril code: [app.js](https://github.com/gocd/spikes/blob/4277dc1c0ec43c6fd4d13001653d8f6f2918d9a7/ui/frameworks/mithril/app.js)
React code: [jobs-view.jsx] (https://github.com/gocd/spikes/blob/4277dc1c0ec43c6fd4d13001653d8f6f2918d9a7/ui/frameworks/react/jobs-view.jsx)

* Fewer lines of code without using magic or conventions

**Comment by srinivasupadhya** [comment]
Possible Config Validation Improvements:

*major*:

- [ ] `TaskWorkingFolderValidator` can be moved into the `FetchTask` & `BuildTask`
- [ ] `JobNameValidator` can be moved into the `JobConfig`
- [ ] `UniqueOnCancelValidator` can be made XSD validation

*minor*:

- [ ] `MaterialConfigs` -> `validateScmMaterials()` -> `validateDestinationFolder()` loop can be improved from n^2 to n*(n+1)/2

**Comment by vinasoni** [comment]
Here are few concepts which depict the proposed flow for the user. The idea behind these flows is to allow multiple users to edit/ change configuration at the same time. It also has suggestions for minor improvements to the UI which can help improve the user experience.
[Config flows.key.zip | uploaded via ZenHub](https://files.zenhub.io/55daed5b6008098761421d6b)

**Comment by vinasoni** [comment]
Here are few concepts which depict the proposed flow for the user. The idea behind these flows is to allow multiple users to edit/ change configuration at the same time. It also has suggestions for minor improvements to the UI which can help improve the user experience.
[Config flows.pdf | uploaded via ZenHub](https://files.zenhub.io/55daed746008098761421d6f)

**Comment by ketan** [comment]
I've hosted an example single page app here - http://gocd-spa.ketanpkr.in/go/admin/pipelines/up42/edit for everyone to play around with and give feedback.

Please note that the "app" currently does not support saves because it is hosted on a static server (github pages) and may take a few seconds to render because we've not got around to compress the JS and CSS.

**Comment by vinasoni** [comment]
Uploading the updated wireframe (minus look & feel) of the screen we intend to build.
![config](https://cloud.githubusercontent.com/assets/12891016/9781643/43346e0e-57b4-11e5-8fe1-5ae945ee9bec.jpg)

**Comment by FredrikWendt** [comment]
Will this rewrite also allow scheduling from the same view/page/screen? With the UI in 15.2 you have to either go to the Home screen and lookup your pipeline (or possibly go to the Run history screen for the pipeline (via Home) if it's triggered manually) to force a scheduling of the newly edited pipeline.

**Comment by zabil** [comment]
@FredrikWendt Only edits for now. Triggering pipelines, like mentioned, must be done via Home or History.

Are you suggesting a message and button ("This pipeline was modified do you want to trigger it with the new configuration?") after the save?

**Comment by FredrikWendt** [comment]
That would be great. Even better would perhaps be two buttons "Save" and "Save and trigger". Or a checkbox "After saving, automatically trigger the pipeline with the new configuration." But yes, 9 times out of 10, I'll want to trigger it directly so please include this if you can!

**Comment by zabil** [comment]
@FredrikWendt I like the idea. Will check on the UX and effort for this. 
No promises though :-)

**Comment by chrislovsund** [comment]
+1 for @FredrikWendt suggestion to add "Save" and "Save and trigger".

**Comment by kerrmarin** [comment]
Is it possible also, as part of this, to add a "Shallow clone material" checkbox when creating a pipeline? We have a large repository (2GB+) that takes quite a long time to clone.

**Comment by FredrikWendt** [comment]
Ideally only get the FROM and TO changesets/commits and the stuff in
between if any.
/ Fredrik
Den 19 nov. 2015 5:50 em skrev "Kerr Marin Miller" <notifications@github.com

**Comment by arvindsv** [comment]
Feedback from some user interviews. This is quite unstructured and is from about 20 days ago. So, it's based on the old UI. Also, not everything needs to be worked on. We need to talk about some of them. But, here it is:

##### User 1:

1. "Ignore pattern" is confusing (not 100% sure what it means).

2. [Nice to have, says @arvindsv] Working directory should auto-complete if possible, since Go knows about materials.

3. Need a "Save & execute pipeline" button.

4. Handle stage rename properly: Should renamed downstream fetch artifact values.

5. Undo functionality missing.

6. Talked about switching between config and run view of a pipeline being painful. Too many clicks.

##### User 2:

1. The "Destination" in the materials section is cryptic. What happens if I enter `/tmp`?

2. "Ignore pattern": I think it is related to blacklist. It took us a while, and is not well documented.

3. "Auto update": Not sure how it works across pipeline. Is it related to material?

4. Wanted to pause the pipeline. Since there was no "Save" button in the old version, thought that every change would affect the pipeline and run it. Said: "There's no feedback about whether it is saving".

5. On stage, the cursor changes to a "Move" cursor. Was afraid to click it.

6. **Missing: Expected command repository functionality in "Exec task" section. We use it a lot.**

7.  Checked "Clean working directory" and said maybe Go doesn't clean up after itself.

8. Was confused about "Never cleanup artifacts": Asked "Is this about removing from the server or agent?"

9. What happens when there are too many stages?

10. Templating seems to be missing.

11. Said: "Stage arrows can be changed to show "Manual" or "Automatic".

12. Talked about switching between config and run view of a pipeline being painful. Same as User 1 above.

##### User 3:

1. Confusion about "Auto update". What is it? Why is it unchecked? No tooltips.

2. Material branch should default to "master", for git.

3. "Ignore pattern" (blacklist) has no feedback. Did my blacklist apply? [@arvindsv says: Opportunity to improve this, by making a call to the server]

4. Said: "Based on my GoCD knowledge, I know jobs have tasks. What about others?"

5. Re-ordering tasks is a little funky. I'd expect it to slide up at ... this point. [Was talking about moving a task down. Try it. You need to move it a little too far down, before the one below slides up]

6. Task accordion summary is confusing. Has "working directory". Show command summary instead. [@arvindsv says: I know this is not relevant right now, since task is not collapsible. But, still leaving this out here, if it does become collapsible]

7. Too much information by default. New users should have less, and advanced users should be able to get to more, quickly. "Getting used to" view vs. "Power user" view.

8. Hard to perceive flow since it is inconsistent.

### Not relevant any more?

There was other feedback, but I feel that the new UI in #1684 takes care of some of this already:

##### User 1:

1. "How do I enter a secure environment variable?" - This person had clicked the lock there and it wasn't working.

2. Unable to delete task.

3. Not sure whether the trash icon on job deletes the job or task.

4. Need a "Save" button.

5. Ability to enter a job name is missing.

6. "Environment variables" section did not "pop out".

##### User 2:

1. Adding a "Git" material did not immediately expand the material. I had to click the bar.

2. Cannot delete material.

3. **Bug? Perforce's "View" is a multi-line value.**

4. Ignore syntax for Perforce. Is it documented? Is it multi-line?

5. Env vars: Thought tabs would be easier to identify as a section, rather than an accordion.

6. Where are the pipeline environment variables? [In the old UI, it was hidden in some bar at the top]

7. No way to delete a task.

8. Expected "On Success" to be checked, upon adding a stage (this is now the case, in the new UI).

9. Bug in movement of stages: "Add Stage" can be moved too.

##### User 3:

1. "Is it saved?" - There was no "Save" button.

2. "Resources" has no tool tip.

**Comment by arvindsv** [comment]
I have to say there's a big part missing in the feedback as *no one* found the pipeline-level parameters section.

**Comment by arvindsv** [comment]
Also, if an exec task has this kind of config:

```
<exec command="ls" workingdir="something">
  <arg>arg1</arg>
  <arg>arg2</arg>
</exec>
```

then, the arguments don't even show up in the new UI. I think it should show, with an option to use it the old way. The new way (without one arg per line) should be the default.

**Comment by jyotisingh** [comment]
> Bug? Perforce's "View" is a multi-line value.

No, not a bug. You can map multiple views for a given project and perforce will sync all of them on the agent, so you could switch to different folders and run whatever task you want, eg:

``` xml
<p4 port="perforce:1666" username="user" password="password" autoUpdate="true" materialName="p4_changelist">
          <view>//project/main/build/... //cruiseclient/main/build/...
            //project/main/acceptance-tests2/... //cruiseclient/main/acceptance-tests2/...
            //project/main/client/... //cruiseclient/main/client/...
            //project/main/libraries/... //cruiseclient/main/libraries/...
          </view>
</p4>
```

**Comment by arvindsv** [comment]
@jyotisingh: I think what I meant was that the view field in the new UI is a text box, not a text area. It does not allow multiline values. So, your XML snippet would not show correctly, I think.

**Comment by jyotisingh** [comment]
@arvindsv - ah, I get it now.

**Comment by arvindsv** [comment]
@zabil: Did you mean to close this?

**Comment by zabil** [comment]
woah, no
@maheshp did it with the "fixes" word on https://github.com/gocd/gocd/commit/350f116b6ff691f849e0f32f32803f8ff8d45e7b 

is there a way to turn off that auto close feature?

**Comment by arvindsv** [comment]
:) No. Not that I know of.

**Comment by maheshp** [comment]
New design for the PipelineConfig Page
[config-draft.pdf](https://github.com/gocd/gocd/files/137428/config-draft.pdf)

**Comment by schmod** [comment]
> New design for the PipelineConfig Page config-draft.pdf

@maheshp This is really good.

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
