### ISSUE TITLE
Git materials & BlackList

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1425]
Hello
I am trying to blacklist some directories that I don't want to retrieve when I set a material (Git)
But when I run the pipeline, it is always retrieving all the repository
I am not able to found the correct syntax to exclude directories

can somebody help?
Thanks
E. Leite

**Comment by ketan** [comment]
There is no way for git to exclude certain directories when performing a clone or a checkout, a lot of other SCMs (mercurial, svn) behave in a similar manner.

Within go, blacklists for materials are not used for the material checkout, because of the design of the scm in question. The purpose (and design) of blacklists is to not trigger the pipeline if any of the files/dirs that belong to the blacklist change.

I'm marking this issue as closed, unless you think this a bug that needs to be addressed.

**Comment by eleite77** [comment]
Thank you very much Ketan

sorry for my missunderstanding.


Regards


<http://fr.linkedin.com/in/ernestoleite>



________________________________
De : Ketan Padegaonkar <notifications@github.com>
Envoyé : lundi 10 août 2015 09:28
À : gocd/gocd
Cc : Ernesto Leite
Objet : Re: [gocd] Git materials & BlackList (#1425)


There is no way for git to exclude certain directories when performing a clone or a checkout, a lot of other SCMs (mercurial, svn) behave in a similar manner.

Within go, blacklists for materials are not used for the material checkout, because of the design of the scm in question. The purpose (and design) of blacklists is to not trigger the pipeline if any of the files/dirs that belong to the blacklist change.

I'm marking this issue as closed, unless you think this a bug that needs to be addressed.

-
