### ISSUE TITLE
Bug Filename too long

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1426]
I have a strange message when executing a pipepline
03:19:37.122 STDERR: error: unable to create file xxx (Filename too long)
Is there any way to bypass that without having to rename not only the file but also the path that is very deep?

thanks

**Comment by ketan** [comment]
This is not a problem with go itself.

I suspect that you're running on an operating system that does not allow long filenames (windows?). Windows has a hard limit on the [length of a filename](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx#maxpath).

If you are running the go agent out of `C:\Program Files (x86)\Go Agent\pipelines`, then I suggest that you re-install the go agent in `c:\go-agent` but this will only take you so far by trimming a few more characters from the filename.

See [this conversation](https://groups.google.com/forum/#!topic/go-cd/NPJaniW5j2M) for some more details.

I'm going to mark this issue as closed, because this does not appear to be a go issue.

**Comment by arvindsv** [comment]
[This conversation](https://groups.google.com/d/msg/go-cd/BK2W6CoBarg/aToDnyBpme8J) might be useful too.
