### ISSUE TITLE
Pipelines limits

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1427]
Hi
we are asking if there is a limit in how many pipelines a Go.Server is able to manage?
We are wondering having more than 250 pepelines and 100  agents...

if not do we have to create or cluster the Go main Server?

Thanks

**Comment by ketan** [comment]
@eleite77 - if you're looking for information on specific questions on gocd, we suggest using [the forums](https://groups.google.com/forum/#!forum/go-cd).

Since you asked the question - there are no limits on the number of pipelines and agents, as long as there the server has sufficient memory and CPU cores, and IO capability.

If you're looking for high-availability or improved performance (by using a postgres server) we recommend [buying gocd support](http://www.thoughtworks.com/products/go-continuous-delivery) from ThoughtWorks.

I'm going to close this ticket out.
