### ISSUE TITLE
Ability to set role permissions per environment

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1441]
Currently in order to give our developers the ability to add their newly created pipelines to an environment I have to give them full Administrator rights, which is less than ideal as it gives them far too much rights.

Separate permissions per environment - controlling at least coupled pipelines and environment variables - would solve this issue. Preferably role based instead of separate users as current templates allow you to do.

**Comment by greenmoss** [comment]
+1 I have had this same issue for a year; my GoCD admins are proliferating :(

**Comment by meagonqz** [comment]
+1 I don't want everyone to be a GoCD sysadmin, so I have to add their pipelines to our environments myself; bottleneck for others and annoying for me.

**Comment by cnatan** [comment]
+1 Please implement this. When everyone has to be admin, it becomes a messy.

**Comment by joel74** [comment]
+1. I want my developers to be able to try out their new pipelines in the lab environment without my having to add every new one. Thanks.

**Comment by ShaunInIdaho** [comment]
+1 I would like my developers to be able to add their pipelines to an environment without having to involve the Go admins.

**Comment by cholmes1111** [comment]
+1!! See my original request from Nov 2015. (https://github.com/gocd/gocd/issues/1104)

**Comment by theangrydev** [comment]
+1 Feels like GoCD needs a revamp of the role based access. For example, more granular control over which actions each group can perform.

**Comment by Preen** [comment]
+1

**Comment by zee-ahmed** [comment]
+1 the big bottleneck is not allowing users to add pipelines to the environment page.

**Comment by shannonxfiles** [comment]
+1 the inability to do so puts burden on both developers/architects and the admins who have to fulfill their request due to the lack of role granularity

**Comment by vivuu1989** [comment]
We ave a number of GOCD pipelines which were created across different environments by different teams.

But now we have only one role as admin and we have to give admin previlege to all the developers inorder to make them trigger pipeline which is not a safety way and we came into a lot of issues as all are having admin access.

So we have to have some more Roles in GOCD(Eg: Pipeline_admin, Template_admin). So for trigering pipelines , we can assign the the first role and for template editing the second role , etc....


But how to create a new role in GOCD ?
How to make the roles the specified access\permission only . 
eg: only pipeline triggering previlege for Pipeline_Admin Role.
Only template ediing previlege for template_admin Role.

**Comment by shannonxfiles** [comment]
@vivuu1989 there is only one admin role, but you can control a bit more granular permissions through creating non admin roles and environments (which has been our work around until this issue is resolved in a way). You can create new roles by navigating to the user summary page. When you checkbox a user or several users drop down the roles option and you should see something that says "Create New Role". You can type a new role in there and apply it to those users. That role can then be used in the fashion described below.

You could try creating pipeline groups, isolating a group of pipelines related to a specific project or function, and associate those with different types of roles. Or create pipeline groups that mirror your environments. 

If you navigate to the admin page and edit one of the pipeline groups you'll see a view similar to [this](https://docs.gocd.org/current/configuration/delegating_group_administration.html). There you can apply a role or user and only give them view, trigger, or admin access to just that specific group.

Not as familiar with templates. Hope this helps at least a bit

**Comment by zerolaser** [comment]
@shannonxfiles Is there a better way to manage the roles via LDAP groups ? 
whoever belongs to particular set of ldap group they should be System administrators. something like this ?

**Comment by ketan** [comment]
Role based access control is available via a commercial plugin. See docs at https://extensions-docs.gocd.org/ldap/current/

**Comment by gibsonm** [comment]
+1  Looks like #4735 is talking about the correct solution, but has seemingly had little interest so far.

**Comment by arvindsv** [comment]
Closing in favor of https://github.com/gocd/gocd/issues/7222
