### ISSUE TITLE
Custom Place For Go Agent Pipelines

### ISSUE THREAD

**Issue by SteveyPugs** [gocd/gocd#1469]
Is there a way to make your pipeline custom to a different folder then the already designated "C:\Program Files (x86)\Go Agent\pipelines" on Windows?

**Comment by arvindsv** [comment]
Hello! The correct place for questions is the [mailing list](https://groups.google.com/forum/#!forum/go-cd). Not GitHub issues. I'm closing this issue (it just gets hard to maintain a lot of issues). But, since you asked, take a look at [this](https://groups.google.com/d/topic/go-cd/suD8jPYRlRU/discussion).
