### ISSUE TITLE
Cloning a pipeline using a name of a pipeline that has been deleted make it appear again on the dashboard.

### ISSUE THREAD

**Issue by ciscox83** [gocd/gocd#1473]
Here how to reproduce it:

1. Create two pipeline A, B. Where A != B
2. Delete B
3. Clone A and name it B

Bug: the dashboard displays the old version of B.

**Comment by arvindsv** [comment]
Closing this as a known issue. Has been discussed in #879 and on the [mailing list](https://groups.google.com/forum/#!topic/go-cd/LVnapi82dmg/discussion). Due to the way the data is, this is not easy to do. In the DB, the pipeline name is stored as a part of dependencies too. Needs thought about how to fix the data, and effort from external contributors too.
