### ISSUE TITLE
Agent status mismatch from API/UI 

### ISSUE THREAD

**Issue by cmourouvin** [gocd/gocd#1487]
Hi,

When i cancel a job and disable the underlying agent in a row i have a status : "Building (Cancelled)"

Now still on the Agent list in the UI, i disable this same agent and it goes to this status : "disabled (building)"

My point is that from the API, the status is still : "Building (Cancelled)" since in the UI it is at "disabled (building)"

Is that a bad comprehension from my part or a real issue ? Is it linked to issue #1438 ?

Regards,

**Comment by ketan** [comment]
Yes, this is a dup of #1438. This got resolved as part of #1455 and will be out with the 15.3 release.

Please leave any comments on #1438 if you'd like to test the new status information with the experimental builds. Please note that you'll have to use `v2` in the version header instead of `v1` to test the new API.

**Comment by cmourouvin** [comment]
Cool, great job and thank you for you job. We're switching from Jenkins and are happy with go until now :)
