### ISSUE TITLE
Allow perforce to use parallel syncs

### ISSUE THREAD

**Issue by fire** [gocd/gocd#1538]
According to http://www.perforce.com/blog/140820/lightning-fast-syncs

`-v net.tcpsize=524288 --parallel "threads=4,min=1,minsize=1"`

Added to the command line of the perforce client would sync faster. It would be useful if gocd allowed you to enter this.

![parallelsync](https://cloud.githubusercontent.com/assets/32321/10271712/ead72e9e-6ac9-11e5-939b-59122637901a.png)

Currently you are only able to change the host and the port.

**Comment by ketan** [comment]
As a workaround, it should be possible to create a wrapper script `p4.bat` or `p4.cmd` that does this.

**Comment by BrewRunner** [comment]
This would be a huge improvement.  The use of 8 parallel threads on my network literally cuts the time required to sync a 200MB, 300 file project in half.

Having the option to turn parallel threads on or off per pipeline as well as having the ability to specify the number of threads would be greatly useful to anyone using Perforce as a source.

I attempted the wrapper option, but I wasn't able to get Go to kick off the wrapper instead of p4.exe.

For my sync test, I called:
     p4 sync --parallel threads=8,min=1,minsize=1 //mydepot/...
instead of calling:
     p4 sync //mydepot/...
Sync time was cut from 8.5 minutes to 4 minutes.

**Comment by fire** [comment]
@arvindsv There's some interest.

**Comment by arvindsv** [comment]
@fire: :) I assume you mean the milestone it is in. The "interest" part is about someone working on the code, as mentioned [here](https://github.com/gocd/gocd/milestones). But, yes, I see there is some interest.

**Comment by arvindsv** [comment]
@BrewRunner: You should be able to do it. On *nix, I would try with a script such as this:

```shell
#!/bin/bash

ORIGINAL_P4="/usr/bin/p4"

if [ "$1" == "sync" ]; then
    shift
    exec "$ORIGINAL_P4" "sync" "--parallel" "threads=8,min=1,minsize=1" "$@"
else
    exec "$ORIGINAL_P4" "$@"
fi
```

1. Would need to put this script in some place (say, "/usr/local/gocd/p4").
2. Would need to prepend that to the PATH of the server, so that /usr/local/gocd comes ahead of /usr/bin (and so that "p4" in there gets selected).


On Windows, it should be similar. You should be able to change the PATH and restart the server. The p4.cmd wrapper will have to be written, obviously.

**Comment by arvindsv** [comment]
Just in case someone is looking to contribute a change, this is [the area](https://github.com/gocd/gocd/blob/76d6c4508145ac332b5593f70e2a1ed065ccc370/common/src/com/thoughtworks/go/domain/materials/perforce/P4Client.java#L105-L111) that will need to be changed. Tests are around [here](https://github.com/gocd/gocd/blob/76d6c4508145ac332b5593f70e2a1ed065ccc370/common/test/unit/com/thoughtworks/go/domain/materials/perforce/P4CommandTestBase.java#L105-L112).
