### ISSUE TITLE
Improve VSM error message when material URL has changed

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1554]
Every page that I visit fails to show the VSM on build.go.cd:
1: Go to https://build.go.cd/go/pipelines/value_stream_map/qa-packages/460
2: Now click the left most git repo, and the top changeset/commit - should lead to: https://build.go.cd/go/materials/value_stream_map/03c8d2a131154436b6ef2d621c6f773837481aaea8c5c1bb9c0cb9b5bc64a2f1/956f8baab3b01eaea52fa345a802e0568933ce0b

**Comment by ketan** [comment]
As per [conversation here](https://gitter.im/gocd/gocd?at=561be56ba15f996e24c4a486):

> @jyotisingh 
>> @ketan, @FredrikWendt - that happened because gocd_mirror repo does not exist in the config anymore. The repo url was changed from download.../git/gocd_mirror to be download.../gocd/gocd . VSM does not work for deleted materials. The error says Material with fingerprint '03c8d2a131154436b6ef2d621c6f773837481aaea8c5c1bb9c0cb9b5bc64a2f1' not found. Fingerprint 03c8d2a131154436b6ef2d621c6f773837481aaea8c5c1bb9c0cb9b5bc64a2f1 maps to download.../git/gocd_mirror in db.
ketan 11:16

**Comment by FredrikWendt** [comment]
Doesn't the go server keep a full clone of the repo?

**Comment by jyotisingh** [comment]
It does, but users could technically go ahead and delete the "flyweight" folder or the local cloned copy from Go server since the material is not supposed to be used by Go. Moreover, in order to draw VSM for a material, Go needs to know what pipelines are dependent on the given material. It gets this information based on the current version of the config. Since the config does not include this material anymore, Go wouldn't know how to draw the VSM. Theoretically, we could get the older version of the config from config.git repo, but then again, at this point there is no way to know what git-SHA of config.git repo corresponds to a given material revision.
