### ISSUE TITLE
Multiple Agents on the same machine

### ISSUE THREAD

**Issue by szop85** [gocd/gocd#1555]
Hey guys,

I'm quite new to go cd and I'm having some trouble to start multiple agents like described in http://www.go.cd/documentation/user/current/advanced_usage/admin_install_multiple_agents.html on my Ubuntu 14.04LTS machine with go 14.4.0:

To create a second agent on the same host, run this as root:

```
ln -s /etc/init.d/go-agent /etc/init.d/go-agent-1
ln -s /usr/share/go-agent /usr/share/go-agent-1
cp /etc/default/go-agent /etc/default/go-agent-1
mkdir /var/{lib,log}/go-agent-1
chown go:go /var/{lib,log}/go-agent-1
```
/etc/default/go-agent-6
```
root@solrcloud1:/# cat /etc/default/go-agent-6
GO_SERVER=78.x.x.x
export GO_SERVER
GO_SERVER_PORT=8080
export GO_SERVER_PORT
AGENT_WORK_DIR=/var/lib/go-agent
export AGENT_WORK_DIR
DAEMON=N
VNC=N
JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
export JAVA_HOME
```

After I've started the first agent, it's not possible for me to start a second one because my prompt is saying: Go Agent already running.

I guess it's because of the PID. Would be nice if someone could point me into the right direction.

Cheers,
Szop

**Comment by ketan** [comment]
Was the agent running when you performed these steps?

Could you remove those files/dirs you created, stop the go agent and repeat again?

**Comment by szop85** [comment]
No, it wasn't running. Sure, will do. Thanks for the fast reply.

Cheers,
Szop

**Comment by ketan** [comment]
Thanks for confirming that.

In any one of the file `/etc/default/go-agent-*`, could you add a line `set -x` before anything else, and then start the agent, if it generates any output on the command line, could you please provide the complete output here.

Be sure to scrub out any sensitive information you may have in the output.

**Comment by ketan** [comment]
Also, the version of go-agent you're running.

**Comment by szop85** [comment]
I'm running with go 14.4.0. I've repeated the steps, but have the same result: Go Agent already running. After removing all folders/files:

```
root@solrcloud1:/# ps aux |grep go
root     11797  0.0  0.0   8812   748 pts/1    S+   12:42   0:00 grep go

ln -s /etc/init.d/go-agent /etc/init.d/go-agent-1 && ln -s /usr/share/go-agent /usr/share/go-agent-1 && cp /etc/default/go-agent /etc/default/go-agent-1 && mkdir /var/{lib,log}/go-agent-1 && chown -R go:go /var/{lib,log}/go-agent*

ln -s /etc/init.d/go-agent /etc/init.d/go-agent-2 && ln -s /usr/share/go-agent /usr/share/go-agent-2 && cp /etc/default/go-agent /etc/default/go-agent-2 && mkdir /var/{lib,log}/go-agent-2 && chown -R go:go /var/{lib,log}/go-agent*

root@solrcloud1:/tmp# /etc/init.d/go-agent-1 start
++ GO_SERVER=78.x.x.x
++ export GO_SERVER
++ GO_SERVER_PORT=8080
++ export GO_SERVER_PORT
++ AGENT_WORK_DIR=/var/lib/go-agent
++ export AGENT_WORK_DIR
++ DAEMON=N
++ VNC=N
++ JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
++ export JAVA_HOME
+ case "$1" in
+ start_go_agent
+ '[' root '!=' root ']'
+ check_proc
+ pgrep -u go -f /usr/share/go-agent/agent-bootstrapper.jar
+ '[' 1 -eq 0 ']'
+ '[' -d /var/run/go-agent ']'
+ '[' /usr/lib/jvm/java-8-oracle/jre '!=' '' ']'
+ '[' root == root ']'
+ start_daemon /bin/su - go -c /usr/share/go-agent/agent.sh
+ eval '/bin/su - go -c /usr/share/go-agent/agent.sh'
++ /bin/su - go -c /usr/share/go-agent/agent.sh
[Tue Oct 13 12:44:23 CEST 2015] using default settings from /etc/default/go-agent
++ GO_SERVER=78.x.x.x
++ export GO_SERVER
++ GO_SERVER_PORT=8080
++ export GO_SERVER_PORT
++ AGENT_WORK_DIR=/var/lib/go-agent
++ export AGENT_WORK_DIR
++ DAEMON=N
++ VNC=N
++ JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
++ export JAVA_HOME
++ dirname /usr/share/go-agent/agent.sh
+ CWD=/usr/share/go-agent
++ cd /usr/share/go-agent
++ pwd
+ AGENT_DIR=/usr/share/go-agent
+ AGENT_MEM=128m
+ AGENT_MAX_MEM=256m
+ GO_SERVER=78.x.x.x
+ GO_SERVER_PORT=8080
+ JVM_DEBUG_PORT=5006
+ VNC=N
+ '[' Y == Y ']'
+ AGENT_WORK_DIR=/var/lib/go-agent
+ '[' Y == Y ']'
+ '[' -d /var/log/go-agent ']'
+ LOG_DIR=/var/log/go-agent
+ LOG_FILE=/var/log/go-agent/go-agent-bootstrapper.log
+ '[' '' ']'
+ '[' Y == Y ']'
+ '[' -d /var/run/go-agent ']'
+ PID_FILE=/var/run/go-agent/go-agent.pid
+ '[' N == Y ']'
+ '[' '' '!=' '' ']'
+ JVM_DEBUG=
+ '[' '' '!=' '' ']'
+ GC_LOG=
+ AGENT_STARTUP_ARGS='-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m   '
+ '[' '' '!=' '' ']'
+ export AGENT_STARTUP_ARGS
+ export LOG_DIR
+ export LOG_FILE
+ CMD='/usr/lib/jvm/java-8-oracle/jre/bin/java -jar "/usr/share/go-agent/agent-bootstrapper.jar" 78.x.x.x 8080'
++ date
+ echo '[Tue Oct 13 12:44:23 CEST 2015] Starting Go Agent Bootstrapper with command: /usr/lib/jvm/java-8-oracle/jre/bin/java -jar "/usr/share/go-agent/agent-bootstrapper.jar" 78.x.x.x 8080'
++ date
+ echo '[Tue Oct 13 12:44:23 CEST 2015] Starting Go Agent Bootstrapper in directory: /var/lib/go-agent'
++ date
+ echo '[Tue Oct 13 12:44:23 CEST 2015] AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m   '
+ cd /var/lib/go-agent
+ '[' /usr/lib/jvm/java-8-oracle/jre == '' ']'
+ '[' N == Y ']'
+ eval '/usr/lib/jvm/java-8-oracle/jre/bin/java -jar "/usr/share/go-agent/agent-bootstrapper.jar" 78.x.x.x 8080'
++ /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /usr/share/go-agent/agent-bootstrapper.jar 78.x.x.x 8080
logFile Environment Variable= /var/log/go-agent/go-agent-bootstrapper.log
Logging to /var/log/go-agent/go-agent-bootstrapper.log
0 [TouchLoopThread-2] INFO com.thoughtworks.go.agent.launcher.Lockfile  - Using lock file: /var/lib/go-agent/.agent-bootstrapper.running
289 [main] INFO com.thoughtworks.go.agent.common.util.JarUtil  - Attempting to load Go-Agent-Bootstrap-Class from agent.jar File:
290 [main] INFO com.thoughtworks.go.agent.common.util.JarUtil  - manifestClassKey: Go-Agent-Bootstrap-Class: com.thoughtworks.go.agent.AgentProcessParentImpl
292 [main] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Agent is version: 14.4.0
496 [main] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Launching Agent with command: /usr/lib/jvm/java-8-oracle/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dagent.launcher.version=14.4.0 -Dagent.plugins.md5=Y118FHclMskSMw0daJR2dQ== -Dagent.binary.md5=JctJ0k5lXCgmzI5PdfxrmQ== -Dagent.launcher.md5=2wQuVBPD0BL6ZVfxuX82Ng== -jar agent.jar https://78.x.x.x:8154/go/

root@solrcloud1:/# /etc/init.d/go-agent-2 start
++ GO_SERVER=78.x.x.x
++ export GO_SERVER
++ GO_SERVER_PORT=8080
++ export GO_SERVER_PORT
++ AGENT_WORK_DIR=/var/lib/go-agent
++ export AGENT_WORK_DIR
++ DAEMON=N
++ VNC=N
++ JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
++ export JAVA_HOME
+ case "$1" in
+ start_go_agent
+ '[' root '!=' root ']'
+ check_proc
+ pgrep -u go -f /usr/share/go-agent/agent-bootstrapper.jar
+ '[' 0 -eq 0 ']'
+ log_success_msg 'Go Agent already running.'
+ echo 'Go Agent already running.'
Go Agent already running.
+ exit 0
```

**Comment by ketan** [comment]
> I'm running with go 14.4.0. I've repeated the steps, but have the same result: Go Agent already running. After removing all folders/files:

Thanks for confirming. This [feature](https://github.com/gocd/gocd/issues/931) is only available with version 15.1 of the agent.

I'd suggest upgrading to a newer version.

**Comment by szop85** [comment]
Ahh that's the problem. Thanks for the info :)!

Cheers,
Szop

**Comment by simranj** [comment]
Hi,

I have go agent version go-agent-15.2.0-2248 and i am trying to run multiple go agent on ubuntu 12.4
I have followed the following steps to create another agent on the same machines
(steps are as per go documentation)
ln -s /etc/init.d/go-agent /etc/init.d/go-agent-1
ln -s /usr/share/go-agent /usr/share/go-agent-1
cp /etc/default/go-agent /etc/default/go-agent-1
mkdir /var/{lib,log}/go-agent-1
chown go:go /var/{lib,log}/go-agent-1

I get following errors in /var/log/go-agent-1

Starting Go Agent Bootstrapper with command: /usr/lib/jvm/java-7-oracle/jre/bin/java -jar "/usr/share/go-agent-1/agent-bootstrapper.jar" 10.5.9.194 8153
[Sun Nov 22 08:01:13 IST 2015] Starting Go Agent Bootstrapper in directory: /var/lib/go-agent-1
[Sun Nov 22 08:01:13 IST 2015] AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m
logFile Environment Variable= /var/log/go-agent-1/go-agent-1-bootstrapper.log
Logging to /var/log/go-agent-1/go-agent-1-bootstrapper.log
2015-11-22 08:01:13,595 [main     ] ERROR go.agent.bootstrapper.AgentBootstrapper:39 - Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /var/lib/go-agent-1/agent-launcher.jar (Permission denied)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.RuntimeException: Agent Bootstrapper initialization failed. Could not validate file: agent-launcher.jar
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.validate(AgentBootstrapper.java:149)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:63)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
        ... 6 more
[Sun Nov 22 08:01:43 IST 2015] Starting Go Agent Bootstrapper with command: /usr/lib/jvm/java-7-oracle/jre/bin/java -jar "/usr/share/go-agent-1/agent-bootstrapper.jar" 10.5.9.194 8153
[Sun Nov 22 08:01:43 IST 2015] Starting Go Agent Bootstrapper in directory: /var/lib/go-agent-1
[Sun Nov 22 08:01:43 IST 2015] AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m
logFile Environment Variable= /var/log/go-agent-1/go-agent-1-bootstrapper.log
Logging to /var/log/go-agent-1/go-agent-1-bootstrapper.log
2015-11-22 08:01:43,414 [main     ] ERROR go.agent.bootstrapper.AgentBootstrapper:39 - Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /var/lib/go-agent-1/agent-launcher.jar (Permission denied)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.RuntimeException: Agent Bootstrapper initialization failed. Could not validate file: agent-launcher.jar
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.validate(AgentBootstrapper.java:149)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:63)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
"go-agent-1-bootstrapper.log" [readonly] 4054L, 383978C

**Comment by arvindsv** [comment]
Does root own `/var/lib/go-agent-1/agent-launcher.jar`? Try with `ls -l /var/lib/go-agent-1/agent-launcher.jar ` and take a look. If so, you might need to do a:

```
chown -R go:go /var/{lib,log}/go-agent-1
```

and then we can change the documentation as well.

**Comment by simranj** [comment]
Yes root own agent-laucher.jar

Does go-agent and go-agent-1 use the same workspace(i.e use the same directory to clone).
if so, why is /var/lib/go-agent-1 is empty?


Thanks

**Comment by arvindsv** [comment]
I suppose you haven't run `chown -R` yet? Is that true? Basically, the `go` user needs full access to `/var/lib/go-agent-1/` directory, since it needs to create other directories there. Manually copying the jar only doesn't help.
