### ISSUE TITLE
Pipelines using a template are automatically triggered on changes sometimes

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#1580]
This morning (6.53a CST, 10/26/15), a pipeline was manually scheduled. This somehow triggered the scheduling of all members of a group of pipelines using a totally separate template. This group of pipelines should only be triggered automatically by an internal chron job, and should not automatically run based on any other criteria. How do I go about determining why they were scheduled?

Thanks,
Joel

**Comment by joel74** [comment]
It happened again. This time, I could see that a SVN checkin to a directory used as a material caused all the pipelines to get scheduled. However, this should not happen. The materials aren't polling for changes and so shouldn't execute automatically.

**Comment by arvindsv** [comment]
Hello @joel74: I don't think this is an issue. Can you see if [this issue]( https://github.com/gocd/gocd/issues/1080#issuecomment-113394772) is similar to what's happening with you?

Auto update doesn't decide whether a pipeline triggers or not. If you want a pipeline to be triggered only by a timer or manually, then you should mark that pipeline itself as manual.

I'll close this issue for now, but will happily reopen it if it turns out to be a real problem.

**Comment by joel74** [comment]
Hi, @arvindsv  Thanks for clarifying. So is it accurate that 'Automatic pipeline scheduling' will always trigger a pipeline if one of its materials is updated?

Thanks,
Joel

**Comment by arvindsv** [comment]
@joel74: Yes, that is an accurate statement. If two pipelines have the same non-auto-updated material, then if one of the pipelines is triggered and the material is updated, the other one will trigger too. The way to prevent this is to mark the second pipeline (or both) manual, so that they don't trigger on update of the material.

**Comment by joel74** [comment]
Thanks, @arvindsv. One last query, and then I'll leave this thread in peace. :)
We have several pipelines where we want them to trigger based on the completion of a stage in another pipeline, but we don't want them to trigger when an SVN material they shared with other pipelines gets updated. Is there anyway to accomplish this? Has the option to tie auto-scheduling to specific materials in a pipeline ever been discussed?

Thanks,
Joel

**Comment by arvindsv** [comment]
Hi @joel74: In the link I posted earlier, there's a mention of a blacklist. That's the way to approach this. You can blacklist some or all paths of a material (SVN, Git, etc) and then the pipeline won't trigger if there are changes only in those blacklisted paths.

**Comment by joel74** [comment]
Excellent. I wasn't familiar with the blacklisting features. 
Thanks.

**Comment by joel74** [comment]
Thanks, Aravind.

I did try that and it's working for me.
Cheers for that.

-Joel

On Mon, Oct 26, 2015 at 5:38 PM, Aravind SV <notifications@github.com>
wrote:

> Hi @joel74 <https://github.com/joel74>: In the link I posted earlier,
> there's a mention of a blacklist. That's the way to approach this. You can
> blacklist some or all paths of a material (SVN, Git, etc) and then the
> pipeline won't trigger if there are changes only in those blacklisted paths.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocd/gocd/issues/1580#issuecomment-151304964>.
>



-- 
Joel Newton
Sr. DevOps System Engineer
SpringCM

jnewton@springcm.com
+1.312.881.2213

www.springcm.com
LinkedIn | Facebook | Twitter

Copyright © 2015 SpringCM. All rights reserved. This email, including any
attachments, is confidential and may not be redirected without permission.

--

**Comment by arvindsv** [comment]
Yay! :+1: Good.
