### ISSUE TITLE
go-cd is using an insecure block encryption algorithm.

### ISSUE THREAD

**Issue by crashsystems** [gocd/gocd#1587]
Per `config/config-api/src/com/thoughtworks/go/security/GoCipher.java`, it appears that go-cd is using DES for encryption:

```
import org.bouncycastle.crypto.engines.DESEngine;
import org.bouncycastle.crypto.modes.CBCBlockCipher;
```

DES has been [breakable](https://en.wikipedia.org/wiki/Data_Encryption_Standard#Security_and_cryptanalysis) for some time now. In addition, the CBC block cipher mode does not provide resistance against attacker tampering.

I recommend switching to AES, which is provided by `org.bouncycastle.crypto.engines.AESEngine`. In addition, I suggest switching to a block cipher mode that provides authenticated encryption, which prevents chosen ciphertext attacks. `org.bouncycastle.crypto.modes.AEADBlockCipher` provides this, and this library supports both CCM and EAX, two authenticated encryption modes.

If for some reason you cannot use the modes provided by `AEADBlockCipher`, you can perform an SHA256 HMAC on your CBC mode encrypted ciphertext, which I believe can be found in `org.bouncycastle.crypto.macs.HMac.

Finally, I noticed that the ciphertext of secrets are viewable in the response for the corresponding edit page. Even with properly implemented encryption, it is best to never send this data to the browser if it isn't needed.

If you have any questions about my recommendations, please let me know.

**Comment by arvindsv** [comment]
Yes, I agree. [Linking to a post](https://groups.google.com/d/msg/go-cd/RlP24jKWQCo/y7vOClOC68oJ) on the mailing list which mentions DES to AES. /cc @jyotisingh.

The edit page issue is going to be [fixed in 15.3](https://github.com/gocd/gocd/issues/1404), because the edit page itself is changing to be a single page application.

**Comment by crashsystems** [comment]
Awesome, good to know. I'm not much of a Java person myself, but if there is any way I can help, such as giving advice on crypto stuff, let me know.

**Comment by arvindsv** [comment]
Crypto advice will be very welcome, and is usually in short supply, anyway. :) So, thank you for this.

**Comment by jyotisingh** [comment]
There are few things to be taken care of for this:
* Changing of the algorithm itself in code. 
* All existing configs with encrypted values should get migrated to use the new cipher
* The encrypted values are put up on the UI as masked fields. 

The first one was a decently simple task to do. The second one required some effort and is where I left it when I was looking at it last. 
Coming to the third item, the [pipeline-config-api](https://github.com/gocd/gocd/issues/1417) which would be consumed by the [new UI](https://github.com/gocd/gocd/issues/1404)  return the encrypted values at this point. The UI for secure variables still needs to be decided/worked upon, but at the very least, I see the variable names being displayed. 
@crashsystems - If we change the encryption algorithm to be AES, what kind of issues do you foresee if the API continues to return the encrypted value which is not rendered on the UI?

**Comment by crashsystems** [comment]
Not rendering it in the UI is a good start, but unless you have a
compelling use case to do so, the encrypted value should never leave the
host, even in an API response. Switching to AES would greatly mitigate the
risk of putting it in the response, but if you don't need it there, why
give a potential attacker access to the ciphertext at all?


-- 
Douglass Clem
crashsystems.net
Public Key: EDCB 9854 D516 991D 080B 0E47 141F 2355 B001 2AA7

**Comment by zabil** [comment]
It will be masked in the UI.
 However the API response (e.g. for pipeline config) is a representation of the  configuration as is. IMO for this case we shouldn't be hiding information.

**Comment by crashsystems** [comment]
If the encryption is handled properly, then I think a compromise of it
being exposed via the API would be reasonable. It'll be important to make
sure that a new IV is generated each time a secret is encrypted, so that
two identical plaintexts won't result in identical ciphertexts.

On Tuesday, November 3, 2015, Zabil C.M <notifications@github.com> wrote:

> It will be masked in the UI.
> However the API response (e.g. for pipeline config) is a representation of
> the configuration as is. IMO for this case we shouldn't be hiding
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocd/gocd/issues/1587#issuecomment-153572217>.
>


-- 

-- 
Douglass Clem
crashsystems.net
Public Key: EDCB 9854 D516 991D 080B 0E47 141F 2355 B001 2AA7

**Comment by grahamc** [comment]
I agree with @crashsystems about not exposing it by the API by default. I think it is well within the realm of reasonableness to have the API exclude the decrypted value. It is worth noting, too, that many CI systems other than Go never even let you see the original value again.


- Graham

**Comment by ketan** [comment]
I think one of the core issues with our implementation is that encrypted values in go don't have an identifier so that we can use an [identity map](http://martinfowler.com/eaaCatalog/identityMap.html).

**Comment by arvindsv** [comment]
@grahamc: Not showing the value again makes sense, but that implies a couple of things:

1. Storing that value outside of the config (makes it harder to clone a Go Server). Also, we need to decide a proper place for it.
2. Having an identifier to use in place of the value, and replace the value whenever needed (extension of point 1 above, and I think it's what @ketan is saying too).

So, it's a choice we need to make. Ideally, I don't like even the encrypted value going back and forth. But, I understand that if we don't send the encrypted value back and forth, then it becomes hard to map the value back, once the response from the client is received.

What I mean is: Config has this:

```
<key>ABC</key>
<encrypted value>DEF</encrypted value> (plain text was 123)
```

Now, it goes to the client:

```
{
   "key": "ABC",
   "value": nil,
   "encrypted": true"
}
```

Now, the user can do one of three things:

1. Change the value.
2. Keep it the same.
3. Remove the whole key-value pair.

We'll need to handle all three. The first and third cases are fine. For the second one, we'll need to have stored the value before sending it, and put it back into the config.

@ketan, @zabil: Does it make sense to keep that value in a map, only at runtime and send UUIDs back and forth? The code for the API's controller will need to parse the input and handle the case 1 and 3, anyway. Handling case 2 using UUIDs should work, IMHO.

To bring up @grahamc's point, this does not remove the "real" encrypted value from the config (and so, doesn't make the config hard to clone).

**Comment by dudadornelles** [comment]
Bumping this,

Now with the pipeline-as-code plugin and the encrypt endpoint, the stakes on this issue are higher it seems, since people out there might want to be storing their encrypted values as code for encrypted environment variables.

**Comment by ketan** [comment]
> Now with the pipeline-as-code plugin and the encrypt endpoint

That actually makes it a bit of a challenge. GoCD can re-encrypt stuff that it owns (in `cruise-config.xml`) using a more secure cipher. However re-encrypting stuff that's sitting in external git repos polled by the pipeline-as-code plugins may not be possible without some thought.

@tomzo WDYT?

**Comment by tomzo** [comment]
> GoCD can re-encrypt stuff that it owns (in cruise-config.xml) using a more secure cipher. However re-encrypting stuff that's sitting in external git repos polled by the pipeline-as-code plugins may not be possible without some thought.

Yes, the upgrade to new cipher will be a problem. Eventually the user will need to upgrade from current encrypted value to a new one by commiting new code in each config repo.
I think the best what we can do is provide a time window to migrate each config repository with some delay. That implies new version of GoCD which **allows to use DES and new cipher simultaneously**.
Otherwise starting new server with current config repos would make them all invalid and force immediate action in all of them, that's quite undesirable.

I'd also like to propose **switching to asymmetric encryption**. The primary benefit would be that public key can be distributed to any client, so that client may encrypt value without talking to server. This removes necessity for encrypt endpoint (which is still useful, but not mandatory). Some of update/create API operations could be simpler then.

> Handling case 2 using UUIDs should work

@arvindsv  I also agree that there should be an UUID for each secret. I don't understand why you need 2 though.

**Comment by arvindsv** [comment]
@tomzo I think I was talking about "Case 2" in [this comment](https://github.com/gocd/gocd/issues/1587#issuecomment-153775369). A single key-value pair. Single UUID.

What would help is a top-level tag at the `<cruise>` or `<security>` level, which holds these and can be used anywhere in the config:

```xml
<cruise>
  <security>
    <vault>
      <item plugin-id="vault.gpg">
        <key>some-uuid-here-1234</key>
        <value>someencryptedvaluehere</value>
      </item>
      <item plugin-id="vault.gocd">
        <key>some-uuid-here-1234</key>
        <value>someotherencryptedvaluehere</value>
      </item>
    </vault>
  </security>

  <pipelines>
    <pipeline>
      <git src="https://#{CRED[some-uuid-here-1234]}:some/url/here" />
    </pipeline>
  </pipelines>
</cruise>
```

and only the UUID is sent back and forth during edits and is made available to be used by the config repo too.

However, first steps first:

1. We need to move away from the current cipher.

2. We can handle config-repo usage of the (old) cipher because it is separate [like this](https://github.com/gocd/gocd/blob/be1ff52e07d80323fcc615864a64f3afe83b7016/server/src/com/thoughtworks/go/config/ConfigConverter.java#L121). I agree with you that we need to provide a time window for migration, with suitably scary warnings.

We will also need to change the API call to provide new UUIDs or tokens or whatever we decide. Do we then need to prefix a token with something so we can figure out it is a token of a specific type or something, I wonder. Maybe not.

**Comment by arvindsv** [comment]
Sigh, yes. That does complicate it. Maybe going asymmetric and having different parts use different keys helps? Otherwise, it seems to get too complicated.

**Comment by tomzo** [comment]
> just knowing the name of the item in the vault will give access to just about everything

So maybe rather then referencing a key in vault by its full name, the references should use name with salt? Each reference can have a new salt. That would never reveal actual key name.

**Comment by arvindsv** [comment]
I'll wait for @ketan to respond, but I thought his point was that the credential's "key" now becomes a secret. If you have the key, you can put in `#{CRED[key]}` anywhere and see what it is, if you are a pipeline group admin, for instance. Even if we salt it, the salted key name will be the same.

At least, that's what I was thinking when I asked about asymmetric. Something like this:

```
<cruise>
  <security>
    <vault>
      <item name="abc" plugin-id="vault.gpg">
        <key>your-private-key</key> <!-- Sigh, who obfuscates this key? Using the GoCD cipher maybe. -->
      </item>
    </vault>
  </security>

  <pipelines>
    <pipeline>
      <git src="#{CRED[abc][ciphertext-from-pubkey-of-abc-private-key]}" />
    </pipeline>
  </pipelines>
</cruise>
```

That way, you can know the name but it won't help as you are providing the ciphertext. Of course, this loses the ability to share a secret between pipelines, which is what the earlier proposal would have had.

Otherwise, we'd need to add auth for the vault items, which feels over-complicated and hard to maintain. Even the AWS IAM model hinges on the knowing the access key and secret key.


Anyway, whatever the decision we take on this can be delayed, I feel, while we migrate the existing cipher out to something much better.

**Comment by ketan** [comment]
> I'll wait for @ketan to respond, but I thought his point was that the credential's "key" now becomes a secret. If you have the key, you can put in #{CRED[key]} anywhere and see what it is, if you are a pipeline group admin, for instance. Even if we salt it, the salted key name will be the same.

That's precisely what I meant. Plus with pipeline-as-code plugins, anyone with commit access to the repo can possibly declare any pipeline to be part of any pipeline group, which makes it difficult to see how one may apply the right authorizations for pipelines to be able to access specific items in the vault.

**Comment by ketan** [comment]
Fixed by #4803

**Comment by ketan** [comment]
I've added a note here https://github.com/gocd/gocd/pull/4803#issuecomment-398058181 describing the implementation. We are now going to be using `AES/CBC/PKCS5Padding` with some code in place to be able to move to encryption using a more secure method in the future, if needed.

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7117-1709149e6946f9cec95e4a8e914a47c7806f0672)
