### ISSUE TITLE
Make the error notification more visible

### ISSUE THREAD

**Issue by iliasbartolini** [gocd/gocd#1595]
From various colleagues I collected feedback that the important error notifications are not visible enough.
![screenshot from 2015-11-04 16 26 31](https://cloud.githubusercontent.com/assets/186468/10942630/354209a4-8311-11e5-9592-98b69897b510.png)

1) One first and very simple change would be to make this more visible.

2) The second proposal is that actually many of this error could be contextual to a specific pipeline/stage/job and would make more sense to see that one failing or having the error visible in that context. 
This speciffic example could make the first stage in the ABC pipeline to fail:
```Error while scheduling pipeline: Deploy-Dashing as no compatible revisions was identified. [Nov-04 15:31:14]
Failed resolution of pipeline ABC : Cause : No valid revisions found for the upstream dependency: DependencyMaterialConfig{pipelineName='DEF', stageName='SomeStage'}```

**Comment by xli** [comment]
Looking into this issue. Thinking about group errors/warnings by pipeline and the show little icon to indicate the errors/warnings:

![pipelines_-_go](https://cloud.githubusercontent.com/assets/17474/12527465/a2355fe0-c130-11e5-9683-963b86c33254.jpg)

After clicked the icon, it should show a popup like current right bottom errors did, but only show errors/warnings related to the pipeline.

Current right bottom errors will still be there for global errors and list all errors

**Comment by arvindsv** [comment]
I'm proposing a full rewrite of the dashboard with much better performance. Interested? It should include this and more (single click to reach the console of a failing job and more obvious access to the VSM, etc).

Ignoring what I said above for a moment and focusing on what you brought up: Yes, that makes sense. Of course, because a material can be shared by multiple pipelines, the same error can show up on different pipelines. Might be irritating for someone who is trying to fix all errors.

Second: I don't think the information sent back from the server is rich enough to figure out the pipelines affected by it. It needs us to move to the dashboard JSON API. That's what I want to replace with a more performant one as I mentioned above.

**Comment by xli** [comment]
As long as you're ok with the user behaviors described above, I'll check out how to implement it. It's a chance to learn more about this part code.

**Comment by arvindsv** [comment]
@xli: I'd mentioned the dashboard rewrite idea in an earlier comment. Just finished writing it up (gocd/gocd#1841). You should continue working on what you are. I agree that it is a chance to learn that part. You might need to put more information in the ServerHealthState object, so that it can be tied to a pipeline or material, I guess. In my view, changing that whole erb and stuff to do this is too messy.

**Comment by arvindsv** [comment]
Also, whatever you do around the server health, to tie to a pipeline or material, will be useful in any new dashboard. That kind of thing will be needed.

**Comment by arvindsv** [comment]
Closing as @xli's change is merged in.
