### ISSUE TITLE
PWD environment variable is not updated to be the same as the pipeline workspace

### ISSUE THREAD

**Issue by scottmuc** [gocd/gocd#1596]
I'm not even sure if this is a bug, but I was urged to post this here so others can take part in the dialogue.

I have a Makefile that looks like the following:

```
make-pwd:
    @echo $(PWD)

shell-pwd:
    @echo $(shell pwd)

make-curdir:
    @echo $(CURDIR)

env:
    @env

.PHONY: make-pwd make-curdir shell-pwd env
```

When I have a pipeline that has a task as follows:

```
          <exec command="make">
            <arg>make-pwd</arg>
            <arg>shell-pwd</arg>
            <arg>make-curdir</arg>
            <arg>env</arg>
            <runif status="passed" />
          </exec>
```

The results look like:

```
14:12:31.951 /data/go-agent/workspace
14:12:31.953 /data/go-agent/workspace/pipelines/make-pwd-test
14:12:31.953 /data/go-agent/workspace/pipelines/make-pwd-test
14:12:31.954 GO_SERVER_URL=https://<redacted>:8154/go/
14:12:31.954 SHELL=/bin/sh
14:12:31.954 _=/usr/lib/jvm/jdk1.8.0_25/bin/java
14:12:31.954 XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt
14:12:31.954 GO_FROM_REVISION_GIT=195438d2ee17be1bc730ea15101740870459782b
14:12:31.954 GO_STAGE_NAME=test
14:12:31.954 PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
14:12:31.954 LOG_FILE=/data/go-agent/workspace/go-agent-bootstrapper.log
14:12:31.954 AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m   
14:12:31.954 GO_TO_REVISION_GIT=195438d2ee17be1bc730ea15101740870459782b
14:12:31.954 PWD=/data/go-agent/workspace
14:12:31.955 GO_SERVER_PORT=8153
14:12:31.955 HOME=/srv/go-agent
14:12:31.955 LOGNAME=ci
14:12:31.955 GO_PIPELINE_COUNTER=1
14:12:31.955 SHLVL=1
14:12:31.955 AGENT_WORK_DIR=/data/go-agent/workspace
14:12:31.955 USER=ci
14:12:31.955 GO_PIPELINE_LABEL=1-195438d
14:12:31.955 OLDPWD=/srv/go-agent
14:12:31.955 MAKEFLAGS=
14:12:31.955 MFLAGS=
14:12:31.955 MAIL=/var/mail/ci
14:12:31.955 GO_PIPELINE_NAME=make-pwd-test
14:12:31.955 GO_SERVER=ci.dev.s-cloud.net
14:12:31.955 GO_TRIGGER_USER=changes
14:12:31.956 GO_REVISION_GIT=195438d2ee17be1bc730ea15101740870459782b
14:12:31.956 NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat
14:12:31.956 GO_JOB_NAME=make
14:12:31.956 GO_STAGE_COUNTER=1
14:12:31.956 LOG_DIR=/data/go-agent/workspace
14:12:31.956 MAKELEVEL=1
```

With a task that looks like:

```
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>make make-pwd shell-pwd make-curdir env</arg>
            <runif status="passed" />
          </exec>
```

The output is:

```
14:34:56.127 /data/go-agent/workspace/pipelines/make-pwd-test
14:34:56.128 /data/go-agent/workspace/pipelines/make-pwd-test
14:34:56.128 /data/go-agent/workspace/pipelines/make-pwd-test
14:34:56.129 GO_SERVER_URL=https://<redacted>:8154/go/
14:34:56.129 SHELL=/bin/sh
14:34:56.129 _=/usr/bin/make
14:34:56.129 XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt
14:34:56.129 GO_FROM_REVISION_GIT=89cdddb6306393c6e8f0374ec0193c42a973499d
14:34:56.129 GO_STAGE_NAME=test
14:34:56.129 PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
14:34:56.129 LOG_FILE=/data/go-agent/workspace/go-agent-bootstrapper.log
14:34:56.129 AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m   
14:34:56.129 GO_TO_REVISION_GIT=89cdddb6306393c6e8f0374ec0193c42a973499d
14:34:56.129 PWD=/data/go-agent/workspace/pipelines/make-pwd-test
14:34:56.129 GO_SERVER_PORT=8153
14:34:56.130 HOME=/srv/go-agent
14:34:56.130 LOGNAME=ci
14:34:56.130 GO_PIPELINE_COUNTER=3
14:34:56.130 SHLVL=2
14:34:56.130 AGENT_WORK_DIR=/data/go-agent/workspace
14:34:56.130 USER=ci
14:34:56.130 GO_PIPELINE_LABEL=3-89cdddb
14:34:56.130 MAKEFLAGS=
14:34:56.130 MFLAGS=
14:34:56.130 MAIL=/var/mail/ci
14:34:56.130 GO_PIPELINE_NAME=make-pwd-test
14:34:56.130 GO_SERVER=ci.dev.s-cloud.net
14:34:56.130 GO_TRIGGER_USER=changes
14:34:56.130 GO_REVISION_GIT=89cdddb6306393c6e8f0374ec0193c42a973499d
14:34:56.130 NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat
14:34:56.130 GO_JOB_NAME=make
14:34:56.131 GO_STAGE_COUNTER=1
14:34:56.131 LOG_DIR=/data/go-agent/workspace
14:34:56.131 MAKELEVEL=1
```

The key difference is in the value of the `PWD` environment variable and the echoing of it when invoking `make`.

There was some [gitter](https://gitter.im/gocd/gocd?at=563a12bfc74a90c744793551) conversation about this. From what I can understand, the "fork exec" implementation of the task runner leaves the `PWD` env variable unchanged from the agents working directory.

My ["research"](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=PWD+vs+CURDIR+Make) on `make` standards shows that `PWD` might not be a reliable variable since it depends on the shell setting the variable correctly. That being said, that seems to be a pretty common expectation. Would that be a breaking and/or a difficult change for the `go-agent` to manage?

**Comment by tomzo** [comment]
I ran into the same problem. Recently I added a pipeline that runs `docker-compose` where yml contains a volume mount:
```
$PWD/cookbook-aptly_repo:/path/in/docker
```

I am running agent in docker with
```
exec su - go -c "/usr/share/go-agent/agent.sh"
```
I've read the conversation on gitter.

@scottmuc has brought up the `make` example. `make` is very flexible and you can find a workround to not relying on PWD. 

But I'd like to ask a question:

> What if the tools used in the job require to have full paths to files?

I think currently there is no way for these tools to interpolate a full path (e.g. `/var/lib/go-agent/pipelines/aptly/cookbook-aptly_repo/`)
I mean regadless of the fact if using PWD is nice or not. There is no single environment variable that would allow to construct a full path from a relative path.
If that is true then I would consider this as a bug.
IMO agent should set `PWD`, or something like `GO_WORKSPACE_DIRECTORY`
I don't think there is any harm in setting `PWD` considering that now it is not set to what one might expect and completely useless when executed on go-agent.
There is also a slight chance that this is related only to docker, since I am using almost the same command as @scottmuc to start the agent.

I don't think this would be hard to implement. @arvindsv Do you think this could it be set in the same place that other `GO_*` variables are set?

**Comment by tomzo** [comment]
[Here is some more conversation](https://gitter.im/gocd/gocd?at=56a454e0aaae7a3a7592c185) about how to fix this.

I think the final approach would be to have agents run all tasks with `bash -c` so that they execute in bash shell, therefore have `PWD` and other bash variables set properly.

This will require to port this ruby code to java to handle escaping quotes properly
 * https://github.com/ruby/ruby/blob/trunk/test/test_shellwords.rb
 * https://github.com/ruby/ruby/blob/trunk/lib/shellwords.rb

**Comment by grahamc** [comment]
I think it is a fine idea to make it easier for new users to run their scripts through bash, especially given all the confusion on the ML about why variables don't interpolate.

 That said, it shouldn't be done lightly:
 - bash isn't without security issues and bugs
 - and if the command which is actually run is munged from your input to what is executed (ie: with shellwords) it may create some confusion into what is happening and why.

I would be more inclined to bundle https://github.com/gocd-contrib/script-executor-task with core, and make it the default job configuration screen with a way to go back to the current method. I understand this is, however, a political decision being discussed a bit on the ML now.

**Comment by scottmuc** [comment]
@grahamc My vote goes for updating `$PWD`. The rationale for me is that it mimics what I would expect on my local machine (though it could be my expectations are what need updating). I definitely learned a bit about shells from this thread.

**Comment by arvindsv** [comment]
@grahamc: Yes, I agree the meaning shouldn't change. It should be transparent to the user. This will be the biggest constraint here and one we cannot break.

Also, `bash -c` will exec the rest of the command, meaning it will replace its own process and so it won't be sticking around. So, it won't be a change in the number of processes (and really the security).

@ketan's argument against PWD is that it is a shell construct and we shouldn't be handling it specially (because it is not special from a *nix/posix perspective). It's a bash construct. I think if we can transparently bring in `bash -c` probably with a feature toggle for a couple of releases, then I think it will handle everyone's concerns and have the right PWD value, among other things.

Why I like that approach is that it will be consistent. Right now we know about PWD. Something else might come up (for instance, I think the `$PPID` will be set to the wrong value currently, as well).

If, for some reason, we can't easily make `bash -c` work, then my vote is to correct `$PWD` as well. But, I feel we should try to make it work first.

**Comment by ketan** [comment]
> Also, bash -c will exec the rest of the command, meaning it will replace its own process and so it won't be sticking around. So, it won't be a change in the number of processes (and really the security).

Not quite. The process count won't change only if we do a `bash -c "exec ..."`

There's no way to know if the "command" that the user has entered is valid to perform an exec.

**Comment by arvindsv** [comment]
As far as I know, everything gets `exec`ed. In fact, there's no other way to start a process on a POSIX system. You don't need to do a `base -c "exec ..."`. Think about it. It has to either do a fork-exec and stick around (in which case, the bash process which got the `-c` option sticks around and waits for exit of the "command") or it just does an exec, rather than a fork-exec.

```
$ echo $$
59111
$ echo $SHELL
/bin/bash
$ bash -c "sleep 20" &
[1] 59355
$ ps -ef | grep [5]9355
  501 59355 59111   0  7:47AM ttys006    0:00.02 sleep 20
```

As you can see, the parent is the original shell, and not the `bash -c` one. Can you give an example of a command for which `bash -c` is the parent?

**Comment by arvindsv** [comment]
I'm thinking of this as well. Maybe something with process substitution or something.

**Comment by arvindsv** [comment]
```
$ echo $$
59571
$ bash -c "ls | less" &
[1] 59617
$ ps -ef | grep [5]9617
  501 59617 59571   0  8:03AM ttys007    0:00.03 -bash -c ls | less
  501 59619 59617   0  8:03AM ttys007    0:00.00 less
```

Two processes, as you'd expect. One for "ls" which exited and one for "less" which is still running. So, the first process has to stick around since it needs to wait for less to finish. Still doesn't increase the number of processes. Maybe if I have two processes which stick around.

But, this might be a false example, since this could never have been provided in our:

```
<exec>
   <arg>...</arg>
</exec>
```

way, without using `bash -c` anyway.

**Comment by arvindsv** [comment]
Found one:

```
$ bash -c "sleep 100 | less" &
[2] 59668
$ ps -ef | grep [5]9668
  501 59668 59571   0  8:09AM ttys007    0:00.01 -bash -c sleep 100 | less
  501 59669 59668   0  8:09AM ttys007    0:00.00 sleep 100
  501 59670 59668   0  8:09AM ttys007    0:00.00 less
```

Again, I think it's a false example, because this cannot translate to the `<exec>` thing in the config. So, the number of processes remains the same.

Is what I'm saying making sense?

This has been fun. Need to go.

**Comment by arvindsv** [comment]
Overall, I feel: If we had `<exec><arg>...</arg></exec>`, and Go could have `exec`ed it before, then bash will also exec it. It won't stick around and have an extra process.

**Comment by arvindsv** [comment]
What I mean is:

```
<exec command="bash">
  <arg>-c</arg>
  <arg>sleep 100 | less</arg>
</exec>
```

would still have three processes.

**Comment by grahamc** [comment]
Interesting, I didn't know about this exactly. It appears Bash _sometimes_ uses process-replacement when executing a command. Without the explicit `exec` though, it is difficult to guarantee that is what will happen. There will have to be very careful effort and testing to ensure this doesn't break behavior:

```xml
<exec command="docker-run-only-artifact">
  <arg>-e</arg>
  <arg>FURY_URL</arg>
  <arg>--</arg>
  <arg>bash</arg>
  <arg>-c</arg>
  <arg>                                                     
    python3 setup.py sdist;                                 
    package_file=$(ls dist | head -n1);                     
    STATUS_CODE="$(curl                                    \
                      --silent                             \
                      --output /dev/stderr                 \
                      --write-out "%{http_code}"           \
                      -F "package=@dist/$package_file"     \
                      $FURY_URL                             
                   )"                                       
    test "x$STATUS_CODE" = "x200"                           
  </arg>
</exec>
```

**Comment by grahamc** [comment]
Even then, Bash won't see the `exec` and drop everything and be done, it continues to parse and add functionality:

```
[grahamc@NdNdNx:~]$ help exec
exec: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
    Replace the shell with the given command.
    
    Execute COMMAND, replacing this shell with the specified program.
    ARGUMENTS become the arguments to COMMAND.  If COMMAND is not specified,
    any redirections take effect in the current shell.
    
    Options:
      -a name	pass NAME as the zeroth argument to COMMAND
      -c		execute COMMAND with an empty environment
      -l		place a dash in the zeroth argument to COMMAND
    
    If the command cannot be executed, a non-interactive shell exits, unless
    the shell option `execfail' is set.
    
    Exit Status:
    Returns success unless COMMAND is not found or a redirection error occurs.
```

**Comment by tomzo** [comment]
@arvindsv Wouldn't it be both simpler and less of a *breaking change* to just blacklist current invalid PWD and bundle the `script-executor-task` with core?

May I also ask what was the original rationale behind having `exec` task the way it is now? With executable and arguments split like they are now?

Now introducing `bash -c` in exec we suddenly make arguments like `sleep 100 | less` valid. This issue was about `PWD` being invalid and now this is becoming a total rewrite of driver behind `exec`, breaking current users expectations towards it.

My vote is to do what @grahamc  suggested 3 days ago

> I would be more inclined to bundle https://github.com/gocd-contrib/script-executor-task with core, and make it the default job configuration screen with a way to go back to the current method

* add `script-executor-task` as recommended way to run custom tasks
* bundle it in the core to make it easier to use
* keep exec task as it was so far - for running a single process with some arguments.
* remove the invalid PWD in `exec` task, because it is a bug.

**Comment by arvindsv** [comment]
@tomzo: Whatever we choose won't be a breaking change. If it looks like it will be, then we should not go ahead with this approach. I don't think any of the discussion we have had (about `sleep 100 | less` or anything) changes what we talked about. Using that with or without `bash -c` makes no real difference. I'll explain why below.

Before that, I wanted to say what I don't like about `script-executor-task` plugin. I think it's a very bad idea for people to write whole shell scripts in their GoCD config. I think scripts should be checked in and properly versioned, and the config should be used to call those scripts. That's the reason I like the work you're doing too, on the config. I love the idea that the pipelines themselves are versioned and changeable, without having to come to the CD server. I feel that putting in the plugin in core reinforces very bad behavior. If someone really wants to, they can install the plugin, but it should be their choice. I'm not saying we should make it hard for people to configure tasks in GoCD, though.

I wasn't around when the exec task was decided. But, I can see why it is the way it is. Having it that way gives you ultimate flexibility. All exec implementations (which finally come down to the [execve system call](https://github.com/torvalds/linux/blob/075356c1cf59e37368f60cd68bdc99a6e2e46d83/include/linux/syscalls.h#L843) on Linux at least), need to be able to pass in a command followed by separate arguments. As you probably know, anything you call with `bash -c` or anything else has to finally be separated into arguments and passed down to the kernel.

Here's what we have currently:

```
<exec command="ls">
  <arg>-l</arg>
  <arg>/tmp/abc</arg>
</exec>
```

This is a simple command, which gets translated to:

```
command = "ls"
args = ["-l", "/tmp/abc"]
```

Not much of a translation, as you can see, and that's what makes it safe. However, it also supports this:

```
<exec command="ls" args="-l /tmp/abc"></exec>
```

Which is a little bit more troublesome, because it still needs to get converted to the same set of command and args as I showed above. Some code in GoCD does that, and splits the `"-l /tmp/abc"` into `["-l", "/tmp/abc"]`.

What @ketan is suggesting is that, instead of exec-in these directly, we use `bash -c`:

With the examples above, it's easy to show what it should be like:

```
bash -c "ls -l /tmp/abc"
```

This won't change behavior.

You said `sleep 100 | less` might become valid *now* because of that. I don't think so. Let's take that example:

```
<exec command="bash">
  <arg>-c</arg>
  <arg>sleep 100 | less</arg>
</exec>
```

This is valid and continues to be valid. Earlier, Java exec would have been called with bash as the command and the rest as the args (two args). Now, in the proposal, it will be translated to a shell equivalent of:

```
bash -c 'bash -c "sleep 100 | less"'
```

which continues to be valid. Behavior doesn't change still. The number of processes remains the same at 1, which will be the internal `bash -c`, because the outside `bash -c` will exec the internal one and you won't notice any difference.

All of this comes down to whether we can reliably convert any command with the `<exec><arg>...</arg></exec>` list into a single line command like I showed. It is theoretically possible, and @ketan claims that ShellWords in ruby has no gotchas. :) I am not yet convinced, because bash can be (ab)used quite well.

It will also be behind a toggle and we will need to see whether we have enough confidence in it to turn it on for all.

Having said all that, I think we should at least correct the PWD variable now, because I agree it is a bug, even though it's not a bug of GoCD's making. It's a bug because of how environment variables propagate between processes. I would have expected it to not have been an exported variable in the original shell which started the agent. That's the real problem, but it's something we should handle in the agent, that we don't send it along to a task.

@grahamc task should get converted to something like the one below. It's not a perfect translation, because in Java code, it won't have that single-quote there. The question is whether ShellWords can quote the double-quotes properly, which was my original question when I mentioned gotchas. We will have to see.

```
bash -c 'docker-run-only-artifact -e UPSTREAM_URL -- bash -c "    python3 setup.py sdist;                                 
    package_file=$(ls dist | head -n1);                     
    STATUS_CODE=\"$(curl                                    \
                      --silent                              \
                      --output /dev/stderr                  \
                      --write-out \"%{http_code}\"          \
                      -F \"package=@dist/$package_file\"    \
                      $UPSTREAM_URL                             
                   )\"                                       
    test \"x$STATUS_CODE\" = \"x200\"'
```

**Comment by arvindsv** [comment]
@ketan: Let's fix the PWD first, even though it is not pure or the "correct" solution. :) We can continue with this after.

**Comment by arvindsv** [comment]
To @grahamc's point earlier, the "exec" builtin you mentioned will not be used. The exec used will be in Java, and the command and arg-list will be wrapped with just `bash -c`.

**Comment by arvindsv** [comment]
I'd also like your thoughts about making `<exec command="ls" args="-l /tmp/abc">` the default in the UI. I prefer that, because it makes it easy for users to use it.

The `<exec><arg>...</arg></exec>` will be around, since it gives flexibility (you can specify exactly what you want) and for backwards compatibility.

This is what is being done with the new config UI.

**Comment by arvindsv** [comment]
Ideally, it should just be: `<exec>ls -l /tmp/abc</exec>`, I feel. It's the easiest and most intuitive for anyone to use.

**Comment by grahamc** [comment]
I'm satisfied. If a user currently puts `sleep 10 | less` into their exec command, shellwords will escape it enough so the executable to actually get run will be called `sleep 10 | less`. (Yeah, it is possible.)

I am a bit concerned about making the command outputted in a way the user will recognize it, but this is A-OK with me. I really appreciate all the conversation we've had around this here.

Also, there was some chatter on Gitter about it starting here: https://gitter.im/gocd/gocd?at=56a92b5380ad69394a7ad69c

**Comment by arvindsv** [comment]
Haven't yet played around with Shellwords, but thinking about this, as long as its approach is to use double-quotes instead of single-quotes, it should be possible to do this, without breaking anything. If we convert:

```
<exec command="command1">
  <arg>arg1</arg>
  <arg>arg2</arg>
</exec>
```

to something like:

```
bash
-c
quote(escape(command)) quote(escape(arg1)) quote(escape(arg2))
```

I think it can be gotcha-less. :)

Ok, I really need to stop thinking about this. I need to go make up for all the time I spent on this now. :) Long evening then.

**Comment by remy-tiitre** [comment]
Instead of changing exec behaviour why not just add bash command?
```
  <exec command="/bin/bash">
    <arg>-c</arg>
    <arg>make make-pwd shell-pwd make-curdir env</arg>
  </exec>
```
vs
```
  <bash command="make">
    <arg>make-pwd shell-pwd make-curdir env</arg>
  </exec>
```
