### ISSUE TITLE
why GO_REVISION, GO_TO_REVISION, GO_FROM_REVISION always the same value

### ISSUE THREAD

**Issue by kinwahlai** [gocd/gocd#1611]
I have 2 pipelines, 1 is unit testing which run whenever there is a commit and other 1 is nightly build which run every night. Both pipelines has different materials but it is the same git branch.

I notice that GO_REVISION, GO_TO_REVISION, GO_FROM_REVISION always the same value for the nightly build pipeline. I had a hard time to understand, plus because of this, i cannot create commit log using GO_FROM_REVISION.

Anyone can explain why it happen and any work around?

**Comment by arvindsv** [comment]
This question should be asked in the mailing list. Here is a similar question on the [mailing list](https://groups.google.com/d/topic/go-cd/aHmTCrtz1vw/discussion) which might be related.

So, I'll close this issue. If, after discussions on the mailing list, this turns out to be an issue, then it can be reopened.
