### ISSUE TITLE
User Delete API being a DB delete not adding much value to users

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1634]
The current implimentation of the user DELETE API (single user delete) deletes the user details from the database, however the user can still login as the user will be present in the password file or in LDAP.

Steps to check it:

Add a user from LDAP or password file
Using Update User API disable the user
Use Delete API to delete the user
From UI try login with the deleted user and the login will be successful, since the user is deleted only from go DB and not from the LDAP or password file.

Since a deleted user is allowed access to system, the API as such does not make much impact. However disabling a user makes sense as the user will not be allowed the login.

In this case, there is no use of delete API, Update API itself suffice the need of disabling the user and restricting access.

So Delete API for users can be removed or moved to as NON PRODUCTION code for test purposes

**Comment by arvindsv** [comment]
I started off writing "I think it's important, for the sake of completeness". But, after a bit of thought, I started to agree with you. Not because of the LDAP or password file issue you bring up (that can be taken care of by a user, by removing them from there). But for the fact that history might get messed up.

Having said that, I went and looked at the [schema](http://www.go.cd/documentation/developer/4/4.2.html#4-2-2-1-schema) and it looks like users are not referenced by the stages table, and so history shouldn't get messed up.

So, I don't have a strong opinion about this. I'd like us to move away from non-production code, if possible, though. One good point you bring up is that with the defaults of allowing anyone who is in LDAP or password file to log in, deleting an existing and disabled user actually *enables* the user to log in again.

**Comment by rajiesh** [comment]
>defaults of allowing anyone who is in LDAP or password file to log in, deleting an existing and disabled user actually enables the user to log in again

@arvindsv  As you mentioned here delete will actually allow user to self-enable by just login again, which is the concern. Just disable would not let self-enablement, but only an admin can do it
