### ISSUE TITLE
Feature Request: Permissions for API usage

### ISSUE THREAD

**Issue by cholmes1111** [gocd/gocd#1666]
Currently, only users that have system administrator privileges can execute against the API. It would be nice to have a role/permission that allowed for the specified user to call the API without granting that user system administrator rights.

**Comment by arvindsv** [comment]
Hi @cholmes1111! Not every API call is for a system administrator. Usually, anything that a user can do/access can be done by that user through the API. For example, a normal "operate" user can trigger pipelines using the API. Pipeline group administrator users can administer their pipelines using the API.

From a security perspective, allowing a user to call an API, without them really having permissions to do so, just because it's an API doesn't really make sense to me. Would API tokens work better? That way, the token can be used to execute API actions without sharing credentials. Still, the token is tied to the administrator, not the normal user who wants to do some action.

**Comment by arvindsv** [comment]
#1246 might be relevant.

**Comment by cholmes1111** [comment]
Fair point. Let me think about it and get back with you.

**Comment by arvindsv** [comment]
Closing in favor of: https://github.com/gocd/gocd/issues/7222
