### ISSUE TITLE
Move new rails URLs out of urlrewrite.xml

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1678]
I see why urlrewrite exists and why having it as a means of migration from the old spring/velocity pages over to rails made sense.

I'm beginning to wonder why it plays a role with NEW routes that get introduced in rails.

So my question to @arvindsv and @jyotisingh —

Would (should?) it be possible to directly add a servlet mapping and remove the urls from urlrewrite.xml altogether?

```
    <servlet-mapping>
        <servlet-name>rails</servlet-name>
        <url-pattern>/api/users</url-pattern>
    </servlet-mapping>

    <servlet-mapping>
        <servlet-name>rails</servlet-name>
        <url-pattern>/api/users/*</url-pattern>
    </servlet-mapping>
```

**Comment by arvindsv** [comment]
The only reason I can think of why this might not work is because of [rack_hack](https://github.com/gocd/gocd/blob/e55f66f6bf0e41339304ac74cc8990b8278ecb03/rack_hack/src/com/thoughtworks/go/rackhack/DelegatingServlet.java#L47) which seems to expect all Rails routes to have `/rails/` in it. However, since it does a `replaceAll()`, it should be ok. Worth a try.

**Comment by arvindsv** [comment]
Of course, if we do this for everything, there will be too many rules.
