### ISSUE TITLE
Update manager for 3rd party plugins

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1711]
I'm quite amazed by how sublime text automatically updates any sublime plugins that I have.

The way it works is by having [some metadata](https://packagecontrol.io/docs/submitting_a_package#Step_6) about the plugin (name, url, author — something we already have).

The expectation is that plugins have a public github repository which is published via the metadata. The packagecontrol.io servers will then periodically poll each repository for any new "git tags" and update it's own meta-data so that instances of sublime text can either notify users or upgrade the packages themselves.

I quite like this idea because it's a completely hands off approach. That needs no human intervention when new plugins are released.

Of course, our plugins are not just a splattering of files in the plugins directory, but a jar file — so I expect that "git tags" may not work, but I'm sure we could work something else out.

Thoughts?

**Comment by jyotisingh** [comment]
I think it would be awesome to have this. 

Some thoughts:
I am not so sure about turning on automatic upgrades by default as there could possibly be some breaking changes in the latest version of the plugin while users are still on an older version of Go. A notification about a new version with an option to upgrade from the dashboard (without a restart) would be nice. An *option* to turn on automatic upgrades of plugins for the bravehearts would be great. BTW, for this to work, we need to allow auto-load of plugins to happen by default in production - this is turned off by default at present. 

While its not mandated by us, but all published go plugins use github releases for hosting the released jars, so that could be the default location we could look for the jars (use github apis). We could also add an additional field in plugin xml to specify the a publicly accessible download location incase someone chooses to not host the released jar on github. Could we rely on GoPluginDescriptor#pluginJarFileLocation to get the right file name?- this won't handle the case when a plugin is released with a new name. 

Few things to note (not that it cannot be changed):
* plugin.xml is not a mandatory for a plugin
* pretty much all fields in the xml are optional

**Comment by ketan** [comment]
> I am not so sure about turning on automatic upgrades by default

I'm not suggesting that we start with that, but that this is a possibility that we could explore once plugins are maintained.

> While its not mandated by us, but all published go plugins use github releases for hosting the released jars, so that could be the default location we could look for the jars (use github apis). We could also add an additional field in plugin xml to specify the a publicly accessible download location incase someone chooses to not host the released jar on github. Could we rely on GoPluginDescriptor#pluginJarFileLocation to get the right file name?- this won't handle the case when a plugin is released with a new name.

I'm not convinced if plugin.xml is the right place for this metadata. Having it hosted on github releases is a good (opinionated) first start, we may later look at other hosting providers (or make it generic enough)

> Few things to note (not that it cannot be changed):
> 
> plugin.xml is not a mandatory for a plugin
> pretty much all fields in the xml are optional

That is news to me, but I'm not surprised at this. I don't think plugin.xml should be the source of truth for the update server. The link I posed in the first post will gives an excellent idea, and I don't mind stealing it :)

**Comment by arvindsv** [comment]
I agree it would be great.

The plugin repository idea for managing plugins considered this (can't find a writeup for this). For that to happen, we'll need to invert how Go Server finds out about plugins. To do that, we need to maintain the "latest known" version of every plugin. Doing that through a PR into a file as we do today is not sustainable. So, it'll need to be inverted and plugin authors should be given control over it. Just as @ketan suggests above.

One thing I'd think we should consider along with this is to move away from pure Java plugins. That'll make these plugins not necessarily have to be running in the same process as the JVM of the Go Server and will make updates less dangerous. Today, the need for Java is just because of how the server uses OSGi to register a plugin and find out its capabilities. Most communication happens through messages anyway. We can easily write a little wrapper which simulates a container in a spawned off Java process. Ideally, that process runs in a more secure manner.

**Comment by lenucksi** [comment]
I would think that this is quite a nice proposal. 
I'm with most of the others that automatic reload&upgrade might not be exactly as desirable due to the named reasons which could lead to malfunctions in production.

@arvindsv suggested to also use non-JVM plugins and basically only rely on message exchange for the plugin communication which I think also is a nice idea. However some possible challenges come to mind here:
 - What about latency if the plugins take rather longish to answer or are located on remote hosts?
 - What about plugins failing to answer or having the communications path interrupted?
 - Could this idea basically be realized by exposing the plugin endpoints as REST/JSON/... endpoints? Or maybe some pubsub service or one or more websockets endpoints?  Thus basically extending the entire discussion into the API direction.

**Comment by arvindsv** [comment]
Hey @lenucksi, sorry about this delay.

Yes, as with any distributed communication, we'll need to consider latency and failures. It can happen, and we should wait a reasonable time and mark it failed, I guess. I can't think of anything different. My idea was to have a websocket connection between the server and the plugins. So, if it goes down, you'd know immediately.

Yes, the idea (in my head, not in code :)) is to have registration itself as an exposed endpoint for plugins. Communication with such plugins will then go over that channel. The messaging is already JSON as I said. So, it's only the channel we need to decide on.

It'll need some work on websockets happening currently. @xli is [working / spiking](https://github.com/xli/gocd/tree/websocketspike) on it. Once that happens, we can try out some of this. This work is not planned any time soon. There's just too much other stuff to do. If there are other (potential) contributors hanging around ... now might be a time to speak. :)
