### ISSUE TITLE
pipeline config API: cannot create pipeline with dependency on an upstream with a template

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#1799]
Pipeline "upstream" uses some template that has a stage called "run". 

Using the pipeline config API, try to create a pipeline "downstream" with a material that points to the upstream pipeline. 

```
"materials": [ some_git_repo, {"attributes": {"auto_update": true, "name": "upstream", "pipeline": "upstream", "stage": "run"}, "type": "dependency"}], 
```

I get the following error:

```
Validations failed for pipeline 'downstream'.... errors: pipeline: "Stage with name 'run' does not exist on pipeline 'upstream'"
```

**Comment by magnus-lycka** [comment]
I get this error doing PUT. I GET the pipeline config, change something else, PUT it again, and it complains about these dependencies on templated pipelines I got on the GET call. They work as expected. I also get another, related error message. One of the upstream pipelines, has a parameterized upstream dependency, and there is also an error message about that: "Pipeline \"#{UPSTREAM_PIPELINE}\" does not exist. It is used from pipeline \"pipeline_x\"." Of course, parameter UPSTREAM_PIPELINE is defined in pipeline_x. That was also already there in the config.

**Comment by arvindsv** [comment]
/cc @jyotisingh, @maheshp - Any thoughts?

@magnus-lycka and @virtuald: I assume that just getting the config and putting it back, without changing anything does the same? If you have any more information or can make this reproducible with a small config, it might help, unless @jyotisingh or @maheshp can already guess from the info you've provided.

**Comment by virtuald** [comment]
@arvindsv I'm not sure. I was only trying to use it to create new pipelines, not modify existing ones.

**Comment by ketan** [comment]
@juhijariwala — can you look into this when you've got time?

**Comment by magnus-lycka** [comment]
Yes, I get the same result if I do GET, then PUT exactly what I got from GET for a pipeline which is fetching artifacts from a templated upstream pipeline. I'm testing on 16.1. Do you want me to provide a test case? It's pretty trivial... 

Use any pipeline P1, and extract to template if it's not already templated.

Make a downstream pipeline P2 with a dependency on P1 which fetches the artifact from P1. (Maybe you don't even need the fetch. It complains in the material section too.) P2 does not need to use a template.

GET http://localhost:8153/go/api/admin/pipelines/P2 > temp.txt as per https://api.go.cd/current/#get-pipeline-config. 

Extract the ETag and use PUT with the content of temp.txt as described in https://api.go.cd/current/#edit-pipeline-config (plus the missing ContentType header...)

You get something like

    "materials": [
      {
        "errors": {
          "pipeline": [
            "Stage with name 'defaultStage' does not exist on pipeline 'cv'"
          ]
        },
        "type": "dependency",
        "attributes": {
          "pipeline": "cv",
          "stage": "defaultStage",
          "name": "cv",
          "auto_update": true
        }
      }
    ],

and 

              {
                "type": "fetch",
                "errors": {
                  "stage": [
                    "\"downstream :: defaultStage :: defaultJob\" tries to fetch artifact from stage \"cv :: defaultStage\" which does not exist."
                  ]
                },
                "attributes": {
                  "run_if": [
                    "passed"
                  ],
                  "on_cancel": null,
                  "pipeline": "cv",
                  "stage": "defaultStage",
                  "job": "defaultJob",
                  "is_source_a_file": false,
                  "source": "target",
                  "destination": ""
                }
              }

Since it does the right thing and looks in the template if you use the web UI or edit the XML file, it seems you aren't quite following the DRY principle...

**Comment by arvindsv** [comment]
> you aren't quite following the DRY principle ...

Completely new implementation, for reasons of performance. Can't be very dry. :) I guess @juhijariwala will take a look sometime.

**Comment by magnus-lycka** [comment]
Ok.

I hope that new implementation will be used also for saving via the XML
file and the web forms soon.

It's much better to have a consistent interface (even with some bugs now
and then) than slightly
different implementations, so that we risk that input which works when
saved one way fails if we
save it in another way... :-(


Magnus Lyckå - https://www.linkedin.com/in/lycka
Thinkware AB, Gavelåsvägen 20, SE-433 31 Partille, SWEDEN -
http://thinkware.se

2016-01-28 13:22 GMT+01:00 Aravind SV <notifications@github.com>:

**Comment by arvindsv** [comment]
@magnus-lycka: The web forms are being moved over to use this API. The API was created to be used by it. You can see some of the progress [here](https://www.go.cd/contribute/roadmap). So, the UI editing and APIs will be in sync (correct or wrong). The XML won't, since it's a manual edit by a user. But, the XML will continue to be the source of truth. The API and the UI will be ways to edit that XML, in a nicer way.

**Comment by magnus-lycka** [comment]
Ok, thanks. So far, the validation when saving a new XML config has been excellent at pointing out all my little mistakes...

**Comment by juhijariwala** [comment]
@virtuald @magnus-lycka: Thanks for reporting this bug and providing the config. I am able to reproduce this bug. You can see the progress [here] (https://github.com/gocd/gocd/pull/1869).

**Comment by henriquegemignani** [comment]
Shouldn't this be closed?

**Comment by arvindsv** [comment]
Closing, based on [this comment](https://github.com/gocd/gocd/pull/1869#issuecomment-194664589).
