### ISSUE TITLE
Preferences menu

### ISSUE THREAD

**Issue by todadot** [gocd/gocd#1862]
Hi,

I've been searching the documentation and the web for this for a while. I would like to set email notifications. 

After upgrading my go and checking the current documentation I found the notifications page.
https://www.go.cd/documentation/user/current/faq/notifications_page.html

The only problem is that I can not find that anywhere. I am on Go Version: 16.1.0.

Where can I reach this setting from?

**Comment by arvindsv** [comment]
As it says [in the documentation](https://www.go.cd/documentation/user/current/configuration/dev_notifications.html), "Notifications will only work if Security is enabled and mailhost information is correct.". Have you setup auth?

**Comment by todadot** [comment]
Thanks, I read this. Although was not sure about what does Security is
enabled mean.... I tried to add users but that button was disabled. With
setting the password file I can set this up.
Although I have still problems with email sending. I tried to set up gmail
as an email sender, although the TLS with the port 587 and host
smtp.gmail.com does not work. I tried to find the way to extend the
properties mentioned in the documentation, although did not find how. I
first added to the server.sh
file SERVER_STARTUP_ARGS+=("-Dmail.smtp.starttls.enable=true "), that did
not solve it, neither of extending the command at the end of the
server.cmd. How can I set that it should use TLS?


2016-02-01 18:30 GMT+01:00 Aravind SV <notifications@github.com>:

> As it says in the documentation
> <https://www.go.cd/documentation/user/current/configuration/dev_notifications.html>,
> "Notifications will only work if Security is enabled and mailhost
> information is correct.". Have you setup auth?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocd/gocd/issues/1862#issuecomment-178084977>.
>



-- 
Czako Gabor

**Comment by arvindsv** [comment]
So, I guess you've seen [this](https://www.go.cd/documentation/user/current/configuration/admin_mailhost_info.html#smtps-and-tls), since you mentioned that property. Also, since you mentioned server.cmd, I guess you're trying this on Windows. On Windows, the way to override a startup argument is documented [here](https://www.go.cd/documentation/user/current/installation/install/server/windows.html#overriding-default-startup-arguments-and-environment). Can you please try that?

You want something along the lines of:

```
wrapper.java.additional.16=-Dmail.smtp.starttls.enable=true
```

in a new file called `config/wrapper-properties.conf` in your installation directory. Right next to the config file, and a similarly named wrapper-server.conf file.

**Comment by todadot** [comment]
Hi, thank you very much. It works. this configuration part I did not remember for. That is why I was searching for the property name in the code and docs (I started from an earlier version, maybe that is why I missed).

**Comment by arvindsv** [comment]
:+1: :) Cool. Closing this issue.
