### ISSUE TITLE
Request: Better Password Hashing Strategy

### ISSUE THREAD

**Issue by danielsomerfield** [gocd/gocd#1863]
I noticed that auth is done with sha1 and no salt. That's obviously bad news if someone steals the password file. 

I recommend the following change:
- support one (or more) of PBKDF2, bcrypt, scrypt. 
- add per-credential random salt

**Comment by MFAnderson** [comment]
Someone from the Go team may come along and refute this but my understanding has always been that the local credential strategy is not really "production-ready", as indicated by the fairly anaemic support for the option (no ability to create new users/passwords, no ability to change passwords for existing users).  If credentials were to move to be actually managed by Go rather than editing a plain-text file on the server I would absolutely agree that it should be considerably more robust than it currently is, but in my experience all of the 'production' Go instances I've worked with have deferred authentication to an LDAP server.

**Comment by danielsomerfield** [comment]
That's a bit naive on our part, I would say. There are going to be cases where there isn't an LDAP server to connect to, or less centralized efforts. I don't think we should present such a weak security posture for the only option other than LDAP. And if we must, it should be dripping with warnings: don't ever use this. Because I'm sure people do.

**Comment by lenucksi** [comment]
I guess both of you are right. A warning would probably be appropriate.

**Comment by arvindsv** [comment]
@lenucksi is right (in that both of you are right). The password file has not been considered production-worthy. But, it should come with warnings, at least.

And, there should be a better replacement. I think this need a new authentication plugin, which provides this. I'll try and work on it sometime, but no promises as of now. I've been meaning to write an auth plugin for a while. So, if I write one, it will be this. If anyone else is interested, please pick it up. Usually, I don't get a lot of time to do stuff on the side.

**Comment by danielsomerfield** [comment]
How have you been thinking about putting this together? Still file backed
but with better practices? Or something different: database-driven, or even
source agnostic? I might be able to contribute...

**Comment by arvindsv** [comment]
Yes, I'm thinking file backed with better practices. Not database driven. The plugin doesn't really have direct access to the database. If you want, I can put together a skeleton soon, and we can collaborate on it. You'll know more about the right ciphers to use, etc.

I want to see if we can do a bit of user management from the plugin settings or somewhere, so that a user can be created and password changed, controlled by the plugin, rather than a user having to go to a file for it.

**Comment by danielsomerfield** [comment]
That would be great. I'm in.

**Comment by arvindsv** [comment]
Just for the record: @danielsomerfield is working on the new plugin [here](https://github.com/danielsomerfield/go-strong-auth-plugin).

**Comment by arvindsv** [comment]
If you haven't seen the announcement of this plugin by @danielsomerfield, [here it is](https://groups.google.com/d/topic/go-cd/-GR3_zG3Prs/discussion).

**Comment by dudadornelles** [comment]
If this https://github.com/danielsomerfield/go-strong-auth-plugin/issues/3 gets resolved I guess this  issue could be closed.

**Comment by danielsomerfield** [comment]
Agreed, assuming that bcrypt is the default.

**Comment by arvindsv** [comment]
Closing. The [bundled file based plugin](https://github.com/gocd/gocd-filebased-authentication-plugin) now uses bcrypt.
