### ISSUE TITLE
[RFC] Deprecating solaris support

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1946]
In light of downward trend in solaris installers, we are now considering a timeline to stop providing solaris installers starting from 1st June 2016. This does not mean that we've taken a firm decision, it just means that we're considering taking one.
##### What does this mean for users installing GoCD on Solaris

Users can continue to use the generic zip files to run GoCD on Solaris. However the support for solaris will be on a best-effort basis.

If you're someone who's using GoCD with Solaris, please provide your comments on this issue to make sure your voice is heard.

**Comment by fire** [comment]
I'm using gocd on SmartOS. However, it's not the installer.

**Comment by sriramnrn** [comment]
Hi:

We have commercial support in place (and this has been extended recently for a few years more). We use GoCD on Solaris 10 and on Solaris 11. Since I also use GoCD on other opensolaris distress, I know that just the zip file is enough to get started.

However, the startup scripts, the packaging recipe, etc are useful for those of us who want to install via packages.

Would it be possible to move these Solaris scripts into a contrib folder? That way, you don't necessarily need to supply signed installers, but those who want to build the installers can still do so.

I will reply via the commercial support channel to discuss what an EoL duration would mean when one has commercial support.

-- Ram

**Comment by arvindsv** [comment]
This has been done.
