### ISSUE TITLE
Allow setting of shallowClone for Git materials from UI and API

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1979]
https://github.com/gocd/gocd/pull/1887 takes care of setting/resetting the flag from config xml. Currently there is no way to set the same through the API and UI.

**Comment by wpc** [comment]
@jyotisingh,

On the #313 issue, @arvindsv suggest waiting for the new configure UI change finished, because in the new design "the whole material stuff is going away".

But I wouldn't mind just adding yet another checkbox in current config UI for now, extra work but make testing easier and less dependency between stories.

@arvindsv, what do you think?

--wpc

**Comment by jyotisingh** [comment]
Agree that the fix to the UI might be an interim solution given that the work on pipeline config UI is going on in full swing. I just added this one here so we don't forget about adding it to the new pipeline config UI. The other thing is about handling this flag in the pipeline config API which can be done now. I am fine splitting this into two issues one that deals with the new UI and the one that deals with the API. I will let @arvindsv  comment if we need to handle the older UI too, I am no issues if we decide not to handle it in old UI.

**Comment by arvindsv** [comment]
If you two really want to do this in the old UI as well, sure. I still think it's more work which won't be needed soon and would rather have that effort put towards finishing the new UI :)

But, if you want to keep it consistent, then sure, it's not like it's wrong or anything.

**Comment by jyotisingh** [comment]
I am fine leaving the old UI as is since we hope to get rid of it soon.

**Comment by wpc** [comment]
ok, I will pick this up
