### ISSUE TITLE
Automatic build in loop after rebase of a GIT branch

### ISSUE THREAD

**Issue by jguilloux71** [gocd/gocd#2110]
##### Issue Type
- Bug Report

##### Summary
This issue is appeared after an update from 15.2 to 16.3.0.

On a pipeline, with a GIT material, for a dedicated branch, if a rebase has been executed (git rebase -i other-branch) on this branch, then the Go server build one time on the new commit and then one time on the old commit (before rebase). And the server does that in loop!

It detects modifications for material but there is no modification!

##### Environment
Go Server is installed on a Debian Jessie, in version 16.3.0.
With the version 15.2, no issue.
Builds are triggered manually.

###### Basic environment details
* Go Version: 16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)
* JVM version: 1.8.0_77
* OS Information: Linux 3.2.0-4-amd64*
Browser vendor and version (if relevant): all browser (IE, Chrome, Firefox, Safari)

**Comment by jguilloux71** [comment]
Up. Go CD is unavailable with this issue :-(

**Comment by zabil** [comment]
A git bisect tracked the problem to this commit (3981000187df0d7693226e7efbfdafc3663e726f)

**Comment by zabil** [comment]
This line
https://github.com/gocd/gocd/commit/3981000187df0d7693226e7efbfdafc3663e726f#diff-97dd991971202dc0de417dbb4271aa82R101

Forms a wrong git log command 
For e.g 
Let's say you make a commit with the sha 1
Our database registers that as the latest commit executes the build and everything's good.
The git log to check for modification ends up as follows
```
git log origin/master 1..
```

Which return nothing.
However when you rebase you get a new sha 2 which executes the build. 
Now when it checks for modifications it executes

```
git log origin/master 2..
```
which returns 1 and then the loop starts

Next time it does

```
git log origin/master 1..
```
which returns 2

The fix is to use the right log command i.e

```
git log 2..origin/master
```
