### ISSUE TITLE
Incorrect error message with invalid template name

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#2197]
##### Issue Type

- Bug Report
##### Summary

error message for invalid template name does not state hyphens are allowed characters but templates do allow hyphens in names
###### Basic environment details

- Go Version: `16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)`
- JAVA Version: `1.7.0_80-b15`
- OS: `Linux, amd64, 2.6.32-504.8.1.el6.x86_64, 10, 2.53`
- Browser vendor and version (if relevant): `N/A`
##### Steps to Reproduce

1. Create a new template
2. Use a + in the name
3. System correctly reports that + is invalid
4. Create a new template 
5. Use a - in the name
6. System allows - even though previous error states "Invalid template name 'test+template'. This must be alphanumeric and can contain underscores and periods (however, it cannot start with a period). The maximum allowed length is 255 characters."
##### Expected Results

Corrected error message:
`"Invalid template name 'test+template'. This must be alphanumeric and can contain underscores, hyphens, and periods (however, it cannot start with a period). The maximum allowed length is 255 characters."`
##### Actual Results

`"Invalid template name 'test+template'. This must be alphanumeric and can contain underscores, and periods (however, it cannot start with a period). The maximum allowed length is 255 characters."`
##### Possible Fix

Just a missing string in the error message

**Comment by GaneshSPatil** [comment]
This issue can be fixed by tweaking the [this ERROR_MESSAGE](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/config/validation/NameTypeValidator.java#L27-L28).

Note: As the [NameTypeValidator](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/config/validation/NameTypeValidator.java) is a common validator shared across many GoCD entities, multiple unit+functional tests will be affected because of this change.

**Comment by GaneshSPatil** [comment]
https://github.com/gocd/gocd/pull/7951 PR has been opened to fix this issue.

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.3.0 (11450-b09b089652fae2543cda69a9a788038547a19054)
