### ISSUE TITLE
Database Migration: dbdeploy bug

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2223]
##### Issue Type

- Bug Report
##### Summary

dbdeploy inserts a database migration into the changelog table before the migration has run. Suppose that the migration ran and failed and the go-server is restarted, the migration that failed in the first place won't be run again. 
##### Basic environment details

- Go Version: `16.5`
- JAVA Version: `1.7`

**Comment by thejasbabu** [comment]
This seem like a critical bug. We ran into this problem when the migration takes longer time and since the gocd server is deployed in kubernetes, it might get killed (liveliness checks) before the migration is complete, leaving the system in an inconsistent state. The only way to recover from this is to fallback to previous state. 

Any work done on this? @varshavaradarajan  
Should we reopen this?

**Comment by varshavaradarajan** [comment]
@thejasbabu - there is work being done to move away from dbdeploy to Liquibase - https://github.com/gocd/gocd/pull/7646#issuecomment-597446641. So, I think this should remain closed.
