### ISSUE TITLE
Sending artifact results to email alert

### ISSUE THREAD

**Issue by hassanfarid** [gocd/gocd#2332]
I have raised the issue on forums, but don't seem to have a response on it yet.

I have created artifacts, as a result of build and execution of UnitTest. How can I notify on email, on success / failure of build with artifact as message body?

https://groups.google.com/forum/#!topic/go-cd/sYCu4OzKtXo

**Comment by zabil** [comment]
Closing this as it's not an issue.
We suggest waiting it out in the forums for someone to reply.

**Comment by hassanfarid** [comment]
@zabil thank man.

I can wait for sometime, then I might probably shift over to TeamCity. I am in the exploring phase, it would have been really helpful to find tutorials or documentation that can help.

**Comment by arvindsv** [comment]
> I can wait for sometime, then I might probably shift over to TeamCity. I am in the exploring phase, it would have been really helpful to find tutorials or documentation that can help.

Sure. You need to find and use whatever is right for you. If no one has replied on the forum, that unfortunately means that no one feels that they have anything valuable to say.

Might want to check out [notifications](https://docs.go.cd/current/faq/notifications_page.html) or the [email notifier plugin](https://github.com/gocd-contrib/email-notifier), though it won't do exactly what you want (sending artifacts).

As @zabil said, this is not the forum for asking questions. The mailing list is.

**Comment by hassanfarid** [comment]
Thanks @arvindsv .

Looking at one of the links you have shared, I can't find this screen on my page.
https://docs.go.cd/current/faq/notifications_page.html

I searched a little bit and found how to do LDAP authentication settings,
https://docs.go.cd/16.1.0/configuration/dev_authentication.html

I added path to /etc/passwd and 'Saved'

I am now prompted Login screen, and I am locked out of system. I can't even login using 'go' user, which I can use using terminal 'su go'.
hassan@satxeonphisrv:~$ su go
Password:
go@satxeonphisrv:/home/hassan$

**Comment by arvindsv** [comment]
@hassanfarid: Sorry. I did not mean to give the impression that I will answer all your questions. I will not. It does not make sense for me to do that. It is an open-source project, and we all try to help whenever we can. However, the community mailing list is really the best option for all of this for a reason. For instance, if you go to https://groups.google.com/forum/#!forum/go-cd and click on the "Search for topics" text box at the top and enter "locked out", you will find that a few other people have asked the same question and have found reasonable answers such as one with the subject "File Based Authentication". That has some information about what you can do. That's the reason we keep mentioning the mailing list. Because it is easily searchable and can be used to get help, even if no one is answering your questions.

I know it's a bit of a shame that a new user like you is finding it hard. It does reflect that the getting started experience is not where it should be. I care about that and care about fixing that. So, it is helpful that you bring up problems that are happening. However, this cannot change overnight. It involves better documentation too.

Finally, I'd like to reinforce that it's not that I don't want to help you. But, one or a few people cannot keep helping everyone new who tries GoCD. Some of it you'll need to find out by trial and error. Some of it you'll need to find out by searching archives in a mailing list. Some of it you can find by going through [some documentation](https://www.go.cd/getting-started/part-1/). A large part of it will involve us changing the getting started experience for the better too. I am not "blaming you" for this. That's the stark reality of such projects. No one is obligated to use it and no one is obligated to answer questions. :(

You also mentioned TeamCity earlier. I have a lot of respect for that, too. If that suits you better, then all power to you. I happen to feel that GoCD does some things differently and better, and for me that's a better choice.

**Comment by hassanfarid** [comment]
Thanks @arvindsv for taking out time and responding to queries on this issue, and all previous issues you have responded to - even if they were supposed to be addressed at google group. I appreciate your patience and support.

I am exploring CI tools for the first time, Getting started guide for goCD is a good piece. It helped me a lot. Honestly, I like goCD for it's simplicity in UI and good design of pipeline, stages, and tasks.

I hope I will find something for setting up authentication, and then email alerts. I don't know, if I can spare time to understand goCD API and write some plugin for email alerts. I wish I can contribute on this.
