### ISSUE TITLE
One resource being loaded over HTTP

### ISSUE THREAD

**Issue by aj-jaswanth** [gocd/gocd#2350]
##### Issue Type

- Bug Report
##### Summary

 The endpoint is being accessed over HTTP 'http://server-address/go/api/version_infos/stale' even when the site is being accessed over HTTPS. 

Chrome gives a warning 'Mixed Content: The page at 'https://server-address/go/agents' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://server-address/go/api/version_infos/stale'. This request has been blocked; the content must be served over HTTPS.send @ application-788070d….js:174'
###### Basic environment details

- Go Version: `16.6.0`
- JAVA Version: `1.7.0_79`
- OS: `Centos 6.7`
- Browser vendor and version (if relevant): `Chrome 51`
##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by ketan** [comment]
If you're fronting your server with a reverse proxy, have you set the `x-forwarded-proto` header?

**Comment by ketan** [comment]
@aj-jaswanth any updates? I'm going to mark this issue as closed unless you can provide more information. Exporting requests from chrome using HAR would be great in terms of resolving this.

**Comment by aj-jaswanth** [comment]
@ketan Didn't get time to look into it. We can close this issue as it is not directly related to it. Moreover, we can use Upgrade-Insecure HTTP header to solve it.

**Comment by ketan** [comment]
The point I'm trying to make is that this should work fine. If it is not,
then we need to investigate and put in a proper fix, and not duct-tape :)

**Comment by stackfull** [comment]
I'm seeing this on 16.12. It seems to be only for that 1 request - all the others are working and the UI seems to be fully functional.

**Comment by arvindsv** [comment]
/cc @maheshp - Can you take a look at this?

Taking a quick look at the code around [here](https://github.com/gocd/gocd/blob/500e24c0db41bb9ca7538412134dffe7a16b023e/server/webapp/WEB-INF/rails.new/app/views/navigation_elements/_footer.html.erb#L29), I think this could be because `apiv1_stale_version_info_url` is used and not `apiv1_stale_version_info_path`.

Also, I don't see this javascript at all on some of the new pages, on build.go.cd (for instance, [the login page](view-source:https://build.go.cd/go/auth/login)). So, is [this check](https://github.com/gocd/gocd/blob/500e24c0db41bb9ca7538412134dffe7a16b023e/server/src/com/thoughtworks/go/server/service/ServerVersionInfoManager.java#L96) correct?

**Comment by maheshp** [comment]
@arvindsv will look into it. Will be done for 17.1.
