### ISSUE TITLE
Consider using semantic versioning

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#2509]
In Go release 16.7 there are a few breaking changes documented in the release notes.
The version number of this release is 16.7, which follows the convention introduced a couple of years ago where the first number is the year. I don't understand how this delivers any value - especially when the industry standard tends to be [semantic versioning](http://semver.org/), where 

> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

As such, this version of Go should really have its major version incremented to show there are breaking changes.

**Comment by zabil** [comment]
@paulclarkin 
We don't follow semantic versioning as it doesn't fit our style of trunk based development. 

As of now, a version is decided **before** we plan or start our development and we cut a release when we feel the experimental build is stable with features that's completed development, incomplete features are toggled off and shipped with the release.

Using semantic versioning for this workflow means changing the versions **after** you've realised there's a breaking change.  

Meanwhile, we try our best to maintain backward compatibility using toggles, branch by abstractions and versioning our API's (in the same release) and talking in advance about deprecations. So normally, you'll find very easy to fix these "breaking changes" across releases.

I am closing this because we won't be moving to semantic versioning. However, feel free to discuss more about it here.
