### ISSUE TITLE
Pipeline config api: Stage operate permission user not validated

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2629]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `16.9.0 (3995-2584deab37edc05ffd02532370dc635bd1dc5a05)`

##### Steps to Reproduce

1. Create a pipeline with stage level permissions defined as here,
```
"authorization": {
          "roles": [
          ],
          "users": [
            "non.existing.user"
          ]
        }
```

##### Expected Results

Pipeline create should fail since the user `non.existing.user` do not exist

##### Actual Results

Pipeline created successfully

**Comment by GaneshSPatil** [comment]
Same Issue on `Pipeline Group` Permissions, where the users are not validated.


![image](https://cloud.githubusercontent.com/assets/15275847/18166956/b52d10a8-706b-11e6-8ae8-dcdc9f37d7fe.png)

**Comment by varshavaradarajan** [comment]
This is the expected behaviour, as a user need not exist in the config to be used in stage operate permissions and pipeline group permissions. A user exists in the database after he/she has logged in. A user need not be present in any role, and more importantly in the ```<admins>``` section to be a pipeline group admin (or have any other permission), or to operate a stage.
