### ISSUE TITLE
JS error on Agents SPA

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2654]
##### Issue Type
- Bug Report
##### Summary

I see the following error in the chrome dev tools —

```
agents:109 Uncaught ReferenceError: VersionUpdater is not defined(anonymous function) @ agents:109
```

Apparently the culprit is this line in code —

``` javascript
  <script type="text/javascript">
    var updater = new VersionUpdater('https://build.go.cd/go/api/version_infos/stale', 'https://build.go.cd/go/api/version_infos/go_server');
    updater.update();
  </script>

```

**Comment by maheshp** [comment]
This happens because the both the old and new SPA pages use the same header and footer partial. I think the script to update the version is added in the footer and this JS is missing in the new javascript. @naveenbhaskar is working on creating a new header and footer for the SPA's only there we can remove the script for the version update.
