### ISSUE TITLE
[Agent improvement] Use a different authorization mechanism to authorize agents

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2731]
##### Issue Type
- Feature enhancement (See #2729, too)
##### Summary

Currently the server uses an agent client certificate to authenticate and authorize agents, this is cumbersome when users may sometimes want to terminate SSL at a reverse proxy like apache or NGINX or HAProxy.

My current thought is to use a simple basic auth header for all agent authentication, and allow SSL termination on a reverse proxy.

This is not to say that agents will use plain text, we'll make sure to only force SSL for all agent connections

**Comment by vladistan** [comment]
Just keep in mind that doing this will expose you to potential MITM attack.   

Client certs make you immune from those provided that both client and server certs are signed by trusted CA,  and that CA is not compromised.

**Comment by ketan** [comment]
@vladistan — I've said in the comment "we'll make sure to only force SSL for all agent connections".

Depending on how the certs are setup, this may still involve users to specify an SSL root cert when setting up the agent as described at https://docs.go.cd/current/installation/ssl_tls/end_to_end_transport_security.html. Am I missing something?

**Comment by vladistan** [comment]
Ahh,  sorry misunderstood your comment.   This will work,  however it should be emphasized that NGINX and HAProxy should  verify agent's client certs.   And in these case the proxy can supply necessary authorization headers to the Go.CD server.  This way it will be harder for users to create insecure installations with agent supplying basic auth and proxy not checking client certs of the agent.

**Comment by alan-czajkowski** [comment]
why not use the JetBrains TeamCity model for agent-server communication, out of all of the build servers I've used (and I've used them all) TeamCity seems to have the best agent-server communication and authentication model

some notes:
a) if an agent is local to the server (on the same machine) then auth is not required
b) any agent that connects to the server must be authorized by the server, an admin viewing the agent screen on the UI can see all of the connected agents, but those agents cannot perform any work until they are explicitly approved, when they are approved they are assigned an auth token that they store in their config so that on subsequent re-connects to the server they automatically get auth'd and can immediately start performing work

i strongly urge you to install TeamCity and view their agent management screen on the server UI and view the agent properties file to see how it is configured -- very simple, very elegant model, and works wonderfully behind reverse proxies

more on TeamCity Agents: https://confluence.jetbrains.com/display/TCD10/Build+Agent

**Comment by arvindsv** [comment]
The issue, as I see it, is that the GoCD server insists on terminating the TLS connection and authorizing an agent using the client certificate of that TLS connection. Upon registration, it creates and provides a certificate to the agent, which it is expected to use when connecting the next time.

When @ketan said above:

> My current thought is to use a simple basic auth header for all agent authentication, and allow SSL termination on a reverse proxy.

The basic auth header will be sending the equivalent of the "auth token" you mentioned earlier.

About the rest of the points:

> a) if an agent is local to the server (on the same machine) then auth is not required

That's what happens with GoCD too.

> b) any agent that connects to the server must be authorized by the server, an admin viewing the agent screen on the UI can see all of the connected agents, but those agents cannot perform any work until they are explicitly approved, when they are approved they are assigned an auth token that they store in their config so that on subsequent re-connects to the server they automatically get auth'd and can immediately start performing work

That's what happens in GoCD too. But, instead of the auth token stored in their config, the TLS certificate is stored in their config (in the keystore). The certificate acts as both the auth token and the TLS end-point auth key. This is what @ketan is proposing to separate as a part of this issue. Keeping the TLS certificate as just that and a new token for auth. In GoCD, currently, subsequent re-connects will automatically get auth'd if they connect using the certificate they were provided. This is what causes the problem/requirement of TLS termination of the GoCD server and not at a proxy.

> c) ... about separation of concerns ...

I agree. This issue is all about doing this to allow proxies to terminate TLS.

**Comment by arvindsv** [comment]
In case I wasn't clear, doing what is proposed here should get us all where we want, and should do what you mention.

**Comment by rajiesh** [comment]
Moving to 19.8 as some enhancements pending

**Comment by arvindsv** [comment]
In 20.2, this is done anyway.
