### ISSUE TITLE
Jobs run on elastic agents show misleading agent information on job run page

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2812]
##### Issue Type
- Bug Report
##### Summary

The job run page shows a misleading Agent information `Not yet assigned (ip:Unknown)` if the job runs on an elastic agent.

The expected agent information is agent_name:(ip_address) which is linked to the agents page. The info displayed for a normal agent might not make sense for elastic agents since these might be deleted post job run, but the current info is misleading as well.

**Comment by kierarad** [comment]
@maheshp Is this still an issue? I was unable to recreate it. The build summary information showed the agent for me. See screenshots - one is a build in progress, the other a completed build. 
![screen shot 2017-03-22 at 1 19 58 pm](https://cloud.githubusercontent.com/assets/3814794/24219004/8c4ce718-0f02-11e7-94d8-7773adb52786.png)
![screen shot 2017-03-22 at 1 18 58 pm](https://cloud.githubusercontent.com/assets/3814794/24219008/90a826c4-0f02-11e7-83af-a88fe181605b.png)

**Comment by arvindsv** [comment]
@kierarad I still see it on build.gocd.io (see [this](https://build.gocd.io/go/tab/build/detail/build-linux/1558/build-non-server/1/agent)). As the title said, it's for elastic agents, only.

**Comment by kierarad** [comment]
@arvindsv ok I'll dig deeper. The screenshots are with an elastic agent (using the docker-elastic-agents plugin)

**Comment by jyotisingh** [comment]
@kierarad - so the issue is not isolated to elastic agents. 
Basically, the agent information for a completed job shows correctly, as long as the agent is still part of Go's config. As soon as you delete it from the config, the agent information from job details page goes away too. 
For regular agents, such a case would happen only if someone manually removes the agent from the config, so this behavior was sort of not a big deal as people wouldn't delete agents from config very often. However, with elastic agents, esp things like docker the agents are torn off and removed from config a min or so after job completes (during the server ping call). So, there is a very high chance that you would see a message like "Not yet assigned" for a completed job if you use elastic agents. Since, most of Go's builds happen on elastic agents, we pretty much always see that message, and its mis-leading. 
If you still have your setup running where you took the screenshot, you would see the same behavior. You probably took a screenshot before the server-ping call to the plugin happened which is why the agent was still alive.

**Comment by kierarad** [comment]
@jyotisingh - can you confirm the expected behavior?
We grab the agent information (hostname, ip address) from the current go config. As you mentioned, if the agent isn't in the current config then the information won't be there. I can't find anywhere else that we store this agent information? It looks like the job only stores the uuid of the agent and the agent only stores the uuid and cookie (is this information in the cookie?) according to this...
https://developer.gocd.io/17.3.0/4/images/database_schema.png

If we aren't already storing this information elsewhere, do we want to save this information so that we can display it in this situation? Or do we just want to display something that is less misleading, like "Agent Not Found"

**Comment by arvindsv** [comment]
My opinion: We should start with a message such as "Agent not found" or "Agent not available". But, for the longer run, we should be storing some information about the agent, explicitly to show it here. It's part of the history.

**Comment by arvindsv** [comment]
This is fixed. It shows the old agent's IP, even if it doesn't exist any more.
