### ISSUE TITLE
How to access the GO.CD build number in gradle

### ISSUE THREAD

**Issue by saithala** [gocd/gocd#2904]
##### Issue Type

- Question

##### Summary

I'm new to Go.CD and I'm trying to explore the tool. I have a question though. I want to be able to access the Go.Cd environment variable in my build.gradle. Could you please share an example of how I can achieve this?

**Comment by arvindsv** [comment]
Hello @saithala. This is a forum for issues in GoCD. Since this is a question, it's probably more appropriate in the [mailing list](https://groups.google.com/forum/#!forum/go-cd) (please search the archive before posting).

This [page in the documentation](https://docs.go.cd/current/faq/environment_variables.html) mentions environment variables. For the Gradle part of this question, you'll probably have to ask at the Gradle forum or look at their documentation. It's probably something like `System.getenv("GO_PIPELINE_NAME")`. Not sure.

Anyway, since this is not a GoCD issue being reported, I'm closing this.

**Comment by arvindsv** [comment]
Oh, I forgot to mention: If you're looking for help getting started, take a look at: https://www.go.cd/help

There's a part called "Setup your first pipeline" which leads you through most of the concepts.
