### ISSUE TITLE
Support for building from multiple branches in GIT

### ISSUE THREAD

**Issue by JensRantil** [gocd/gocd#298]
See https://groups.google.com/d/msg/go-cd/sX7NLgT6v3s/vvARG3yLU4EJ. This would enable one to execute tests on multiple branches _before_ commits are merged into main development branch. It would also enable users to mark pull requests red/green on Github.

**Comment by underyx** [comment]
I've seen you guys are holding a hack night today. Sadly not only do I live on the other half of the world, but I have no Java experience, either, so there's no way I could just go ahead and implement this myself. I would still like to give my enormous +1 to this feature request, in case you guys are going to be struggling to find stuff to work on… ah, who am I kidding :disappointed:

**Comment by salizzar** [comment]
Hello all,

Any news related to this issue? Is possible to create a workaround?

Thank you.

**Comment by sgran** [comment]
I'd be happy enough with the ability to run just the CI portions on feature branches, so that you can see if they are passing the tests.

In our setup, we have all the CI checks in one pipeline, and that pipeline fans out to deploy pipelines for the various production environments.  The normal CI pipeline tracks master.

I am imagining a feature-branch pipeline that tracks any branch except for master, and runs all the CI checks, but doesn't notify the downstream deploy pipelines.  As the notification is a property of the deploy pipeline, I think this should work fine with templates.  The main issue I see in implementing this right now is that the git material has a string value for branch name, instead of a regex/filter/etc.  Making this change would be enough for our use case, I suspect.

**Comment by srinivasupadhya** [comment]
Go 15.1 will have support for SCM end-point & Notification end-point. @ashwantkumar & I have written a [plugin to support feature-branch/pull-request builds](https://github.com/ashwanthkumar/gocd-build-github-pull-requests) & a [plugin that updates build status](https://github.com/srinivasupadhya/gocd-build-status-notifier). ([discussion thread](https://groups.google.com/d/topic/go-cd-dev/Rt_Y5G2VkOc/discussion)) Give them a spin & let us know if you have some feedback.

When PRs https://github.com/gocd/gocd/pull/939, https://github.com/gocd/gocd/pull/913 & https://github.com/gocd/gocd/pull/968 are in & deployed on http://build.go.cd (user: view & password: password) I will add a `build-linux-for-PR` pipeline using these plugins for dog fooding.

**Comment by bmess** [comment]
Thanks for the work on the plug-ins @srinivasupadhya .  While this is extremely helpful for Github users, I'd like to know how to apply your plugins to a standard git repository, regardless if it's in Github or not.  With your current examples I can see how to easily link to a Github repository, but I can't determine between the documentation and the examples given how to build off of another branch without a complete pipeline clone.

**Comment by srinivasupadhya** [comment]
download `git-fb-poller-1.2.jar` from https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases.

pipeline clone is just a convenience. you can create a new pipeline from scratch and add git branch poller material.

**Comment by arvindsv** [comment]
Closing: Plugins mentioned by @srinivasupadhya.
