### ISSUE TITLE
Redirect behind AWS ALB loses the port

### ISSUE THREAD

**Issue by kief** [gocd/gocd#3049]
##### Issue Type

- Bug Report

##### Summary

Running a stock build of GoCD behind an AWS ALB, when accessing /go/home the redirect to /go/pipelines loses the port.

`curl -v http://gocd.sandbox.cloudspin.net:8153/go/home`
The response includes: `Location: http://gocd.sandbox.cloudspin.net/go/pipelines`

The same thing happens with https:
`curl -v https://gocd.sandbox.cloudspin.net:8154/go/home`
Redirects with: `Location: https://gocd.sandbox.cloudspin.net/go/pipelines`

If I log into the instance hosting the go server and curl localhost, the redirect has the relevant port:

`curl -v http://localhost:8153/go/home` redirects to `Location: http://localhost:8153/go/pipelines`

###### Basic environment details

* Go Version: `16.12.0 (4352-018c65856d46007240cc75577e9cc8535b44148d)`
* JAVA Version: `1.7.0_121`
* OS: `Linux 3.13.0-103-generic` - Ubuntu 14.04

Go server is installed on a stock Ubuntu 14.04 AMI with this script:

```
echo "deb https://download.go.cd /" | sudo tee /etc/apt/sources.list.d/gocd.list
curl -s https://download.go.cd/GOCD-GPG-KEY.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install go-server -y
```

(Note that I have added the various go.cd hostnames/IP addresses to /etc/hosts, given the current DNS issues)

###### Additional Environment Details

Using AWS Application Load Balancer, with an SSL certificate.

##### Steps to Reproduce

If I go to a URL that doesn't result in a redirect, I can browse the go server fine. It's just redirects that seem broken.

This might be related to #741?

##### Output

The full output of the curl statement is:

```
$ curl -v http://gocd.sandbox.cloudspin.net:8153/go/home
* Hostname was NOT found in DNS cache
*   Trying 54.171.29.233...
* Connected to gocd.sandbox.cloudspin.net (54.171.29.233) port 8153 (#0)
> GET /go/home HTTP/1.1
> User-Agent: curl/7.35.0
> Host: gocd.sandbox.cloudspin.net:8153
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Wed, 28 Dec 2016 13:43:09 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: JSESSIONID=1ak745eixpq551a5ot4xt0atjd;Path=/go;Expires=Wed, 11-Jan-2017 13:43:08 GMT;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-UA-Compatible: chrome=1
< Location: http://gocd.sandbox.cloudspin.net/go/pipelines
< Cache-Control: no-cache
< X-Request-Id: b3a15bbc-2511-416f-83b0-dfa6a86eaba3
< X-Runtime: 0.006000
<
* Connection #0 to host gocd.sandbox.cloudspin.net left intact
<html><body>You are being <a href="http://gocd.sandbox.cloudspin.net/go/pipelines">redirected</a>.</body></html>
```

**Comment by phoenix-zhu** [comment]
No one is looking at this? Or we have to use an nginx before it?

**Comment by chadlwilson** [comment]
This is stale issue from nearly 7 years ago :-) There have been many changes to GoCD in the last 7 years and since some sort of ALB or reverse proxy is required for TLS termination now (which it was not in 2016) it should be a common use case. I have not heard of any specific issues with AWS ALBs in the last few years, so I'd be surprised if there is a problem.

As general advice I'd make sure you have set both of the Site URLs correctly in **Admin > Server Configuration** (this affects redirects for logins, but not _all_ redirects) and double check the traffic reaching GoCD is retaining standard proxy headers such as `X-Forwarded-Port` and `X-Forwarded-Proto` to tell GoCD what the originating port/protocol was/is. This relatively recent thread implies it works fine with an AWS ALB: https://groups.google.com/g/go-cd/c/BLZphIn5DvM/m/3DFLU_ecAQAJ

If that's not the problem please open a new issue, discussion or [forum thread](https://groups.google.com/g/go-cd) to describe your setup and configuration.
