### ISSUE TITLE
Change mac installers to work with Oracle java 7

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#308]
Steps to Reproduce : 

1) Install Go on mac with osx version 10.9
2) It gives following error:

![mac-install-error](https://cloud.githubusercontent.com/assets/6175869/3466054/f30586bc-0277-11e4-8b80-331e7358e4bd.png)

Read following links to better understand cause of this issue:
http://stackoverflow.com/questions/14806709/application-is-using-java-6-from-apple-instead-of-java-7-from-oracle-on-mac-os-x
https://github.com/tofi86/universalJavaApplicationStub

**Comment by zabil** [comment]
This happens on a new mac. Mac puts a templae java command which when invoked downloads java 6 (by showing this dialog)

In our case we need java 7 so we need to display a different message.

**Comment by arvindsv** [comment]
Tell me what you think about [this patch](https://github.com/arvindsv/gocd/commit/4f6880e9d5586123e14368dfd48b12712e50811b). It checks only two places now. One is GO_JAVA_HOME environment variable (so that we can override it, if needed). Second is: ```/usr/libexec/java_home -v 1.7+```. This should work only if it is 1.7 or newer.

I've verified this:

1. Tried on a completely new Yosemite instance, and found that this works properly (meaning, shows a message), since /usr/libexec/java_home exists and no Java 1.7 is installed.

2. On that same instance, I installed Apple Java 1.6 from [here](https://support.apple.com/kb/DL1572?locale=en_US). It still showed the same message (which is good).

The message shown looks like this:

![screen shot 2015-04-10 at 3 56 36 pm](https://cloud.githubusercontent.com/assets/172235/7095889/299f9d64-df9c-11e4-82c7-d4fb40d7520c.png)

I mention a documentation link there, which we can write to help.

The advantage of this solution is that it doesn't try and be clever and find some random Java, which might be 1.6 or 1.5 or something, and fail. If there is some problem with finding the right Java using ```/usr/libexec/java_home -v 1.7+```, we can always ask a user to set GO_JAVA_HOME, which will effectively override everything else and use the specified Java instance.

**Comment by zabil** [comment]
Yup, this looks fine.

**Comment by ketan** [comment]
@arvindsv - is there a task to write up some troubleshooting doc mentioned in the error message?

http://www.go.cd/documentation/user/current/installation/troubleshoot_installer.html#mac_java

**Comment by arvindsv** [comment]
Yes, there is. [This one](https://github.com/gocd/documentation/issues/108). Haven't got to it, yet. Sorry. Will do soon.

**Comment by ketan** [comment]
Verified on `15.1.0(1839-0f15ee122cda40)` running on `Mac OS X 10.10.3` on both JDK 7 and JDK 8.
