### ISSUE TITLE
Default value for plugin setting is not shown

### ISSUE THREAD

**Issue by alisonps** [gocd/gocd#3087]
##### Issue Type

- Bug Report

##### Summary

For plugins, the default value of a setting is lost when the settings map is populated. This issue can be traced back to the following snippet: https://github.com/gocd/gocd/blob/388b2c238943613f50900aeca4b0a056a64be8e4/server/src/com/thoughtworks/go/server/domain/PluginSettings.java#L73

##### Environment

We encountered this while developing a custom plugin, but it's true for the current version of the server, which we were locally from the last commit (388b2c238943613f50900aeca4b0a056a64be8e4).

###### Basic environment details

* JAVA Version: 1.8.0_25
* OS: Mac OS X 10.11.6

##### Steps to Reproduce

1. Add a default value to a required settings field in a plugin
2. Load the plugin onto the server
3. In a JS console, access the plugin settings via `jQuery("#plugin_settings_data_plugin_settings").text()`

##### Expected Results
The default value for the setting field should be returned

##### Actual Results
No value for the setting field is returned

**Comment by bdpiparva** [comment]
@alisonps --- This behavior is intentional, If we populate the default value(`foo`) in form then on click of save that value get stored in db and that we don't want. Now `foo` is no longer default value.

**Comment by arvindsv** [comment]
@bdpiparva: Without this, the default value is useless, isn't it?

**Comment by bdpiparva** [comment]
@arvindsv -- No, default value is used when user have not configured it.

Scenario - 1: (current behavior)
1) Lets say plugin-0.0.1 is having `foo` as a default value.
2) User have not configured this field but changed other fields so plugin will use `foo` for processing
3) Now lets say plugin-0.0.2 is released with default value `foo-1`
4) We will have that value available for use because user haven't configured it.

Scenario - 2: (After populating default value in form)
1) Lets say plugin-0.0.1 is having `foo` as a default value.
2) User have not configured this field but we populated default value in form, then on saving of other values, this value also gets stored in db.
3) Now lets say plugin-0.0.2 is released with default value `foo-1` but since we have `foo` stored in db, plugin will use `foo` instead of `foo-1`

**Comment by arvindsv** [comment]
Ok. If it's the case that the value should not be populated, then we should at least have it as a placeholder (I mean, an HTML5 input placeholder). Right?

**Comment by ketan** [comment]
The placeholder comes from the template. There's no control that we have over the template.

**Comment by arvindsv** [comment]
Ah, I forgot that this one is not generated. Cool. Then, it's up to the plugin author to put in the placeholder.
