### ISSUE TITLE
Shallow clone of Git materials

### ISSUE THREAD

**Issue by hackinjack** [gocd/gocd#313]
We have some git repos which contain pretty large history - it can take about 20 minutes just to check this out so obviously we don't need ALL this cloned into our deployments. Is there a way of getting the 'depth' parameter added to the clone commands performed internally by Go? That way we could check out this repo in seconds.

**Comment by paulclarkin** [comment]
See also #711

**Comment by paulclarkin** [comment]
Any update on this?

**Comment by mitchtbaum** [comment]
Users on slow and/or metered networks could benefit from this.  So, +1!! :-)

**Comment by scottmuc** [comment]
+1

**Comment by eelkram** [comment]
+1.  I would think the default should be a depth of 1 and a setting if you needed to have the history.

**Comment by cholmes1111** [comment]
+1. Would be nice to pull just the current one by default but have the ability to overwrite if you want the full history.

**Comment by dsmorse** [comment]
+1 - last year at the atlassian conference, they mentioned that performing shallow clones on their build servers was one of the most important changes they made on their infrastructure to support enterprise scale devops.  I wish Go allow use to set the depth.

**Comment by agbodike** [comment]
+1 - This would speed up builds for many people

**Comment by ketan** [comment]
So as not to need a feature toggle, can we —

* add a `shallow` boolean attribute (default it to `--depth 40`) to `<git />` material. This is an opinionated and non-configurable choice.

OR 

* add a `depth` (Integer) attribute to `<git />` material?

**Comment by agbodike** [comment]
I prefer the second option. I assume that for all existing configs that do not have the depth attribute set, it would do a full repo clone, but for those that want control over the depth, they can get it as fine grained as they want.

**Comment by agbodike** [comment]
I'm not sure if this is feasible, or desirable, but a third option would be to add an `args` (String) attribute to <git /> material, which would allow for arbitrary parameters to be passed to the git clone command.

**Comment by holmesc1111** [comment]
If the goal is to not add a feature toggle, I'd prefer that the default depth integer be set to 1. If for any reason someone wants more depth than that, they would override the default of 1.

I'm still not seeing a viable use case where full depth is needed every time a material check is performed for every pipeline.

**Comment by eelkram** [comment]
I prefer the 2nd option (depth integer attribute) as well.  I think you want to support granularity in the depth so if someone want / needs any specific depth that option is available.  A default of 0 should clone the entire repo causing no functional change.

**Comment by kkennedy1** [comment]
+1 for option 2.  Having the ability to provide arguments like in the comment from @agbodike would be nice also, similar to MSBuild arguments, but at a minimum being able to provide a depth as an integer would be great.

**Comment by arghac** [comment]
+1 for allowing a custom depth integer attribute, with a default of cloning all revisions.

**Comment by wpc** [comment]
I am considering picking up this issue. Need feedback from you guys.

Implementation proposal:

* **Add a clone options section git material configure UI**

![shallow clone](https://cloud.githubusercontent.com/assets/10283/12526685/001f036a-c125-11e5-9ebd-b00a00134348.png)

![shallow-clone-checked](https://cloud.githubusercontent.com/assets/10283/12526701/2ac655e6-c125-11e5-98c3-1b99de0648bd.png)


* **By default shallow clone is off**

Ideally should be default on, because almost all build can get benefits.  But there are cases people do not expect it and will get hell lot of confusions. Take a look at [this travisci issue](https://github.com/travis-ci/dpl/issues/127), [this circleci post](https://discuss.circleci.com/t/problems-with-git-commit-count/339) and [another circleci post](https://discuss.circleci.com/t/git-errors-failing-the-build-when-deploying-to-heroku/776)

* **Default depth is 50 instead of 1**

Shallow clone with small depth may be problematic. Suppose server update the material and find the latest revision is ```r1```,  a new agent pickup the job do a ```git clone --depth 1```. If in between these two actions new commits were pushed into the repo, agent will not be able to find revision ```r1``` anymore. Depth 50 normally does not have much performance difference comparing to depth 1, but can reduce the chance of above case. And in the tiny chance it happens, we can:

* **Fallback to full clone when can not find revision to build in a shallow cloned repo**

This is useful for handling the above edge case. And it will also handle the case when user trigger a build with specific revisions. The fallback should only happened if the repo is shadowly cloned. We can tell if file ```.git/shallow``` exists.

Thoughts?

-- wpc

**Comment by arvindsv** [comment]
Two quick thoughts:

- UI is changing. That whole material stuff is going away. So, I wouldn't change it there. In the new UI, we should find a suitable place ("advanced options").

- Instead of setting an arbitrary limit of 50, it's also possible to slowly un-shallow a shallow clone, by doing a: `git fetch --depth=20` and then a `git fetch --depth=40`, etc, if you want. Just gives some flexibility rather than just 50 and full.

**Comment by arvindsv** [comment]
From around git 2.5, we might even be able to [fetch a specific commit](https://github.com/git/git/commit/68ee628932c2196742b77d2961c5e16360734a62) from a remote, if the git server allows it.

**Comment by agbodike** [comment]
@wpc sounds like a good proposal to me

@arvindsv My understanding of the proposal is that the default of 50 can be changed by changing the integer value in the `<git />` material config, or in the UI.

**Comment by arvindsv** [comment]
@agbodike: Right, but it's still arbitrary. How do you know you'll find a commit in 50? What if you rerun an old build, on a new agent? Ideally, you want to fetch that commit only (a very new git feature), or you walk back from the first commit looking for the one you want. Maybe a few times before giving up and doing a deep clone. Just an option to consider.

**Comment by agbodike** [comment]
@arvindsv 

I think the idea of being able to rerun an old build, or fetch a specific commit are good points and important, but a different set of functionality.

I don't particularly love the idea of doing repeated fetches if a commit is not found.

I'd propose that re-running old builds should fetch the specific commit that was run for that build. Perhaps this would be configurable, so those using older versions of git could have the option of the looping fetch, but I personally think the default should be for newer versions of git.

**Comment by arvindsv** [comment]
@agbodike:

Every build, whether it is the newest or a rerun works the same. The server will tell the agent to fetch a specific commit SHA. It might be the SHA of the HEAD or the SHA of an older commit. We won't be able to differentiate (till we fetch history).

> I'd propose that re-running old builds should fetch the specific commit that was run for that build. Perhaps this would be configurable, so those using older versions of git could have the option of the looping fetch, but I personally think the default should be for newer versions of git.

The problem is that this is not a git-client-side option, but a server side git option (the git server has to advertise this behavior and then a reasonably new client can use it).

> I don't particularly love the idea of doing repeated fetches if a commit is not found.

I can understand that, and can sort of agree with it. One thing to note is that repeated fetches are just bringing diffs, not full content. @wpc's proposal of a fall back to full clone will bring more content over (full history), but it will not be repeated fetches. So, there are advantages to both approaches.

At the end of the day, from a usage perspective, the option should be to allow a user to decide between a potential shallow clone or a deep clone. The implementation approach, we can choose. Anything we choose is likely to be better than the current approach of a full clone every time the repo is not found locally. :)

**Comment by wpc** [comment]
@agbodike @arvindsv thank you for your feedback.

I really like the incremental un-shallow idea. This way we can reduce configuration burden from the user. But looping with `git fetch --depth` is very slow. And it can put considerable pressures on the git server. To show that I setup an experiment with linux kernel repository.

```
# full clone
% time git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
243.86s user 197.34s system 101% cpu 7:15.71 total

% git log --pretty=oneline | wc -l
  573407

# shallow with depth 1 
% time git clone -n --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
5.50s user 2.68s system 18% cpu 44.241 total
```

A script for incremental un-shallow with 2<sup>(n+4)</sup> as depth 
```bash
for i in $(seq 0 17); do
    depth=`echo "2^($i+4)" | bc`;
    git fetch --depth $depth
done
```

Running it:
```
% time ../unshallow.sh
> git fetch --depth 16
> git fetch --depth 32
...
> git fetch --depth 4096
remote: Total 0 (delta 0), reused 0 (delta 0)
> git fetch --depth 8192
remote: Total 0 (delta 0), reused 0 (delta 0)
^C
../unshallow.sh  346.07s user 175.64s system 33% cpu 26:04.40 total
```
For almost half hour it only finished 9 iteration. Each time it getting slower and slower. There is a incremental pause at beginning of each iteration, I guess it is server side processing time for calculating revisions need to be fetched. And for the last couple of iterations I get no data. I probably get banned. :-P

Given that I suggest we do a two step un-shallow process on agents when revision is missing: first try fetch a hard code depth such as 100, then do a full un-shallow if it does hit the mark. In the first fetch we try to cover most of cases with a controllable cost. And pay the full bill in whole if not avoidable.

```
# git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git depth 1 shallow clone
 
% time git fetch --depth 100
44.95s user 17.71s system 45% cpu 2:17.20 total

% time git fetch --unshallow
164.01s user 93.87s system 67% cpu 6:22.96 total
```

**Comment by agbodike** [comment]
Sounds like a good approach to me!

It covers the desired functionality, but has a fixed cost (relative to the individual repository) failover in the case that the desired SHA is not found in the shallow clone.

**Comment by wpc** [comment]
updated the original proposal

**Comment by arvindsv** [comment]
I agree. Sounds good to me too. We need to make sure what is being done is logged to the console so the user knows. Also, we need to find out when `unshallow` was introduced. When announcing this feature, we will need to tell people which version of git this will work from. I checked the RelNotes (https://github.com/git/git/tree/master/Documentation/RelNotes) and found no mention of it.

Of course, I had checked out the tree using `--depth 1`. :) So, no history. Not going to unshallow it. Feels too meta to do that.

**Comment by arvindsv** [comment]
Fine, unshallowed it. [Looks like](https://github.com/git/git/commit/4820a33) around 1.9.

**Comment by wpc** [comment]
@arvindsv:  Documentation is start from v1.8.2.1:  https://git-scm.com/docs/git-fetch/1.8.2.1

**Comment by arvindsv** [comment]
You're right. This [commit](https://github.com/git/git/commit/4dcb167fc3536db0e78c50f239cd3a19afd383fa) seems to have started it off. It seems to have an interesting history, starting off as an alias for `--depth=2147483647`. :) I don't know if it is still the same. Probably not.

**Comment by wpc** [comment]
> starting off as an alias for --depth=2147483647

LMAO

**Comment by FredrikWendt** [comment]
I'm terribly late to the party, but on the agent side, what I'd expect to find in the repo is `GO_FROM_REVISION` and `GO_TO_REVISION` and any and all commits in between. That would allow automatic bisect, inspecting any change from previous run etc. For any other operation I'd execute towards the git repo itself, I'd be OK with manually unshallowing it.

It's of course a trade off made in the name of speed, but we [need](https://github.com/gocd/gocd/issues/1290) all of [these](https://github.com/gocd/gocd/issues/1125) improvements asap.
Moving from Jenkins, we've added minutes of extra wait time to our pipelines (execution time of all steps in a value stream map) because of the inefficient/slow/delayed job scheduling and pull based server-agent communication.

**Comment by arvindsv** [comment]
> I'm terribly late to the party, but on the agent side, what I'd expect to find in the repo is GO_FROM_REVISION and GO_TO_REVISION and any and all commits in between. That would allow automatic bisect, inspecting any change from previous run etc. For any other operation I'd execute towards the git repo itself, I'd be OK with manually unshallowing it.

/cc @wpc: This is an interesting (and new) viewpoint, we probably didn't think about. About the from revision.

**Comment by ketan** [comment]
>I'm terribly late to the party, but on the agent side, what I'd expect to find in the repo is GO_FROM_REVISION and GO_TO_REVISION and any and all commits in between. That would allow automatic bisect, inspecting any change from previous run etc. For any other operation I'd execute towards the git repo itself, I'd be OK with manually unshallowing it.

That is a good catch, I'd probably expect that the shallow clone contain `GO_FROM_REVISION` without setting any expectation that it be the first revision in the shallow clone.

**Comment by wpc** [comment]
@FredrikWendt, @ketan and @arvindsv 

Yeah, this is a good catch. I haven't thought about from revision as well. 

From implementation perspective this could be straightforward to add to the PR. We can change the unshallow check to against the oldest revision instead of latest. Then we will need bump up the initial clone depth. It need to be some relative large number because we do not want to trigger the slow unshallowing process frequently. Probably 50 will be fine to cover checkin behaviors for most of teams. (currently is 2)

This way we can  make sure "GO_FROM_REVISION" always be in the shallow cloned repo.  But we will pay cost for it. Bumping up clone depth make quite a difference on cloning cost if it is "feature branch" type of repo. Because it is not just extra 48 revisions to fetch, it is extra 48 "levels" of objects in the tree.

```
git clone --depth 2 -n file:///tmp/linux.git s2  44.75s user 4.60s system 130% cpu 37.914 total
git clone --depth 50 -n file:///tmp/linux.git s50  62.67s user 12.25s system 160% cpu 46.701 total
```
I feel twisted now between matching expectation of "GO_FROM_REVISION" and paying extra cost for 99% cases where GO_FROM_REVISION never used.

Any thoughts?

-- wpc

**Comment by arvindsv** [comment]
@wpc: Isn't this case only applicable when GO_FROM_REVISION is *different* from GO_TO_REVISION and we're cloning for a new repo? That seems like it can be handled specially, without changing the default (and presumably most-used case), where they are the same. No?

Or, are you talking about the depth being hard-coded (maybe configurable) but defaulting to 50, instead of 2?

**Comment by wpc** [comment]
@arvindsv 
>  Or, are you talking about the depth being hard-coded (maybe configurable) but defaulting to 50, instead of 2?

Yes, this is what I planned to do for code simplicity reason. But now after thinking a little bit more, it may not be that complicated for dynamically calculating clone depth base on how many revisions in between FROM and TO revision. Something like

``` java
cloneDepth = materialRevision.numberOfModifications() + 1; 
```
Of course we need take the complicity passing the information into material by expanding updateTo interface, but feel like bearable. 
What do you think?

**Comment by arvindsv** [comment]
> Of course we need take the complicity passing information needed into material by expanding updateTo interface, but feel like bearable. 
> What do you think?

Yes, I think that should work. /cc @jyotisingh should know this and take a call as well, in case she has missed this.

**Comment by wpc** [comment]
@jyotisingh  and @arvindsv: 

I have pushed a change to make sure "GO_FROM_REVISION"  is included in the shallow clone. In the change I expanded Material#update_to interface for passing down extra information:

```java
- void updateTo(ProcessOutputStreamConsumer outputStreamConsumer, Revision revision, File baseDir, final SubprocessExecutionContext execCtx);
+ void updateTo(ProcessOutputStreamConsumer outputStreamConsumer, Revision revision, File baseDir, Revision oldestRevision, int numberOfModifications, final SubprocessExecutionContext execCtx);
```
An alternative is passing down MaterialRevision instead of revision

```java
- void updateTo(ProcessOutputStreamConsumer outputStreamConsumer, Revision revision, File baseDir, final SubprocessExecutionContext execCtx);
+ void updateTo(ProcessOutputStreamConsumer outputStreamConsumer, MaterialRevision revision, File baseDir, final SubprocessExecutionContext execCtx);
```

Passing MaterialRevision will make the interface a little bit cleaner, but it will introduce more dependencies and making Materials a little bit harder to test. 

Which one do you prefer?

**Comment by arvindsv** [comment]
It could be a RevisionContext or something. Otherwise, my preference is to have lesser number of params. But, it's your and @jyotisingh's call.

**Comment by jyotisingh** [comment]
We need not send MaterialRevision, worst case we would have to send the `modifications`. But I like RevisionContext, and passing along just the required information ie. latest-rev, oldest-rev and modification-count in it.

**Comment by wpc** [comment]
Do you guys prefer an extra RevisionContext passed in along with the revision parameter or just use RevisionContext to replace revision because it has latest revision anyway?

**Comment by jyotisingh** [comment]
Just RevisionContext would be nice

**Comment by rajiesh** [comment]
verified on 16.3.0(3184-737bce06c5f29bd77562bbc3704040af72d0fe00). Shallow clone default on server and option provided on materials page for shallow clone on agents

**Comment by paulclarkin** [comment]
Has this been added to the Go documentation?

**Comment by wpc** [comment]
@paulclarkin It is in Reference section: https://docs.go.cd/current/configuration/configuration_reference.html#git
