### ISSUE TITLE
API should issue an authorization challenge 

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#3153]
##### Issue Type

- Bug Report

##### Summary

If an unauthenticated request comes in the API issues a redirect to the GoCD login page.  That's not going to work for an API.  Instead the API should simply issue the HTTP auth challenge.

It's easiest to see this when using wget and curl to hit the API.  Newer versions of wget do not send HTTP authentication unless challenged (which is per spec).  Curl and old versions of wget send credentials without being prompted.

See https://www.gnu.org/software/wget/manual/wget.html#index-authentication-2

##### Environment
GoCD 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69)
Linux 4.4.43
JVM 8

##### Steps to Reproduce

FAILS: wget --http-user='admin' --http-password='password' -O ./localfile https://gocd-server/go/files/pipeline/latest/stage/latest/job/artifact 
WORKS: wget --auth-no-challenge --http-user='admin' --http-password='password' -O ./localfile https://gocd-server/go/files/pipeline/latest/stage/latest/job/artifact

**Comment by maheshp** [comment]
@tpbrown the artifacts API is one of our older API's, redirecting to login page for an unauthenticated requests is incorrect. This endpoint is also used on the job details page to link to artifcats, so a redirect to login page in browser makes sense but not for a curl or wget. 

To fix this, we can think of having two different endpoints one for the browser which redirects to login page for unauthenticated requests and the other for requests through wget which would return a auth challenge. Also, since it is one of our older API's we might also have a complete relook at it.

However, the newer API's send back an authentication challenge for an unauthenticated request,  

e.g ```curl 'https://ci.example.com/go/api/agents' -H 'Accept: application/vnd.go.cd.v4+json'```

returns
```
HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Basic realm="GoCD"
```
