### ISSUE TITLE
[Question] is it possible to set a server/web context for Go?

### ISSUE THREAD

**Issue by williamsbdev** [gocd/gocd#3160]
##### Issue Type

Feature enhancement/Question

##### Summary

I am having difficulty figuring out where and even if it is possible to set a server/web context for Go. For example, with many other Java applications I've deployed, I can set something along the lines of `sonar.web.context=/sonarqube` for the SonarQube product (https://github.com/SonarSource/sonarqube). Is this possible to do with Go as I am having trouble finding this configuration option. If not, could someone point me in the right direction in order to be able to add this?

**Comment by arvindsv** [comment]
@williamsbdev: Unfortunately not, it's embedded pretty deeply in places such as [this](https://github.com/gocd/gocd/blob/5e0a5079f8cc06b1292c006ca40950ca8aea2177/base/src/com/thoughtworks/go/util/GoConstants.java#L73), [this](https://github.com/gocd/gocd/blob/5e0a5079f8cc06b1292c006ca40950ca8aea2177/rack_hack/src/com/thoughtworks/go/rackhack/DelegatingServlet.java#L46), [this](https://github.com/gocd/gocd/blob/5e0a5079f8cc06b1292c006ca40950ca8aea2177/jetty9/src/com/thoughtworks/go/server/Jetty9Server.java#L151) and mainly [here](https://github.com/gocd/gocd/blob/5e0a5079f8cc06b1292c006ca40950ca8aea2177/base/src/com/thoughtworks/go/util/SystemEnvironment.java#L615). The final one is the one that seems to decide the real context and changing it is possible through a system property, but the others, unfortunately, have it hard-coded.

I'm going to close this issue, since it's a question. If you're planning to look into working on it and trying to consolidate the usages or something, I'll happily reopen it. Thank you!
