### ISSUE TITLE
404 error when clicking More Information on compare pipeline page

### ISSUE THREAD

**Issue by wlsf82** [gocd/gocd#3208]
Bug Report

Ubuntu server 14.04
Go Version: 16.12.0
Java version: 8
Browser: Safari 10.0.3

Summary:
When inside the compare pipelines page, in the Card Activity's tab, after clicking in the More Information link, it redirects to a new tab with the following 404 error:

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: current/integration/mingle_card_activity_gadget.html
RequestId: C80249F5921D68B7
HostId: 252ZvUJjwWEvpP47E4jNOIT1cWmOP2UUdcHvZTzP95UQErM9YtPgWeX1/S1kuc7bs2ypNT8jMNI=
```

Steps to Reproduce:
1. From the home page of the gocd dashboard, with at least one pipeline with two executions, click in the compare link
2. Then click in the Card Activity tab
3. Then click in the More information link.

Expected Results:
A page with more information about the card activity should be shown.

Actual Results
The already mentioned 404 error is shown in a new tab.

**Comment by varshavaradarajan** [comment]
@wlsf82, as of GoCD release 17.1.0, we removed support for OpenSocial gadget. You will no longer be able to view the 'Card Activity' tab. In the GoCD server, we usually provide links to the latest version of the documentation, which is `current`. And since we removed gadgets, we removed the corresponding documentation as well. 

Thank you for reporting the broken link though. :) For more details, checkout the `Breaking changes` section of the release notes for GoCD `17.1.0`. Closing the issue.
