### ISSUE TITLE
Is it possible to specify the order in which jobs should start?

### ISSUE THREAD

**Issue by Malabarba** [gocd/gocd#3232]
This might sound a little weird, given that jobs are run in parallel. Still, there's a stage in one of my pipelines  where one of the jobs takes much longer than the others, so I'd like this job to always be the first one to start (which optimizes the runtime of the pipeline). 

Is there any way to specify a given job should be first one to start?

**Comment by varshavaradarajan** [comment]
@Malabarba , no. Since the jobs run in parallel, they should be independent of each other in every way. Although I understand what you've said, perhaps there is a better pipeline model you could use to optimize the run time. 
Consider having the long running job to be a part of another stage so that you do not have to wait for it to finish if you do not have downstream pipelines depending on this job. But, this is very dependent on your use case and not recommended for all cases. 

You might want to try asking on the [google group](https://groups.google.com/forum/#!forum/go-cd) for more insights.

**Comment by Malabarba** [comment]
Thanks for the help. I don't think I can change the pipeline model, unfortunately. Everything downstream does depend on this job, I just wanted it to start first because that's more time efficient. I think I'll just invest some effort in optimizing this job so it's not so slow.

Still, thanks a lot for your time.
