### ISSUE TITLE
Plugin extension for credentials

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3369]
##### Issue Type
- Feature proposal

##### Summary

Plugin extension which allows user to provide credentials through plugin for `ssh`,`git` or other material etc.

#### How does this help ?
1) If password is changed for git user then we  have to update most of the place we are using it. 
2) No need to save password on agents.
3) User can provide their credentials for AWS S3 bucket or docker hub.

**Comment by jyotisingh** [comment]
Does this also cover adding support for things like password vaults etc? If so, any task should also be able to make use of it right?
Also, how do we use this in conjunction with existing plugins? For instance: A docker-swarm-elastic-agent requires a CA cert, client cert, and client key. Would having such an extension allow me to pick the certs and key from this plugin(say a password vault) instead of specifying it as plain text/secure properties?

**Comment by bdpiparva** [comment]
> Does this also cover adding support for things like password vaults etc? If so, any task should also be able to make use of it right?

Yes, This includes support for password vaults and can be used with tasks

> Also, how do we use this in conjunction with existing plugins?

We can think of something like this:
Docker Credentials provider plugin and `docker-swarm-elastic-agent` is depends on that cred provider

**Comment by arvindsv** [comment]
GoCD now supports secrets management plugins.
