### ISSUE TITLE
Fix: Order of loading of bundled plugins and external plugins

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3616]
##### Issue Type

- Feature enhancement

##### Summary

Since there will be more bundled plugins in GoCD soon, it becomes important for a user to be able to override the bundled plugin with a custom plugin or a newer version of a bundled plugin in `plugins/external`. This needs to be verified, but it might not be possible currently.

###### Basic environment details

* Go Version: 17.6.0

##### More info

See [this](https://github.com/gocd/gocd/blob/356c4c716c3a06d8c7a49cc9fb4301a3a68ed6b9/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/monitor/DefaultPluginJarLocationMonitor.java#L187) and [this](https://github.com/gocd/gocd/blob/356c4c716c3a06d8c7a49cc9fb4301a3a68ed6b9/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/listeners/DefaultPluginJarChangeListener.java#L96). Also this [conversation](https://gitter.im/gocd/gocd?at=59526cda97cedeb04825807a).

**Comment by jyotisingh** [comment]
@arvindsv 'plugins/external' folder is for installing external plugins and not for overriding the bundled ones. In order to override a bundled plugin, one needs to replace the older plugin jar with the new one in 'plugins/bundled', restart go-server and that should be it. There was a bug that did not let us do this, but that was fixed in 17.5.

**Comment by arvindsv** [comment]
I see what you mean. That we would overwrite it from the zipped bundle and now we don't. Hmm. Ok. Still feels a little weird that it will get wiped upon the next upgrade, but I can live with that.

**Comment by arvindsv** [comment]
I'll close this then.
