### ISSUE TITLE
Navigate to/from failed jobs - VSM

### ISSUE THREAD

**Issue by tinozza** [gocd/gocd#3827]
Scope: Allow users to go to a broken job easily from the VSM. If a stage is failing, go directly to the first failed job.

Proposed Solution:
1) On hovering over the failed stage in a pipeline the failed jobs are listed in the tooltip. On clicking on failed job users are taken to the console. Or on clicking on the stage the user is taken directly to the first failed job. 
![vsm hover](https://user-images.githubusercontent.com/16536421/30105634-d981d0aa-9316-11e7-8749-2335371459f5.png)

Proposing two options for navigating to other failed jobs in the job details page.
option 1: dropdown in the navigation header 
![failed job console _dropdown header_breadcrumbs copy](https://user-images.githubusercontent.com/16536421/30105766-361f8e60-9317-11e7-8115-dd2efc8bf1fd.png)

option 2: Side bar with all the jobs listed
![job1](https://user-images.githubusercontent.com/16536421/30105826-5a49d250-9317-11e7-9052-254ae44558c4.png)

invision link prototype 1 with dropdown in navigation header: https://invis.io/68DCU1M4N
invision link prototype 2 with side bar: https://invis.io/MEDCUBDFZ

Please do share your feedback/concerns regarding the mockup proposed above.

**Comment by arvindsv** [comment]
Option 1: I'm concerned about discoverability.

Option 2: I'm concerned about the space it takes up, after we finally made the console log take up the full page width.

Between the two, I would prefer option 1, but the discoverability seems to be low in that.

**Comment by tinozza** [comment]
Reworked on this story. Attaching couple of options below
**Option1a:**
Dropdown in navigation header:
![image](https://user-images.githubusercontent.com/16536421/30691100-3a7458a0-9ee4-11e7-857e-388e6a5d9e9f.png)
**Option1b:**
Dropdown for Job Name above job details content:
![image](https://user-images.githubusercontent.com/16536421/30691517-9badb48a-9ee5-11e7-8eb7-c53c3cbb4326.png)


**Option2:** prototype link: https://thoughtworks.invisionapp.com/share/G8DLC77HV

For this option: On clicking on the failed job in the VSM (a list of failed job appears when the user hovers over the failed stage) - users are taken directly to the console of the failed job. A dropdown menu with the other jobs in the stage (for easy navigation between jobs) is also provided in this view. Once this view is closed,  they are taken to the job details page.

step1 - list of failed jobs on hovering over the failed stage in the pipeline:
![image](https://user-images.githubusercontent.com/16536421/30687552-396c04ae-9ed9-11e7-86c8-8269faddfa16.png)
step2 - On clicking on the failed job users are taken directly to the console of the failed job. For easy navigation between the jobs users can use the dropdown menu.
![image](https://user-images.githubusercontent.com/16536421/30687616-7d8fc116-9ed9-11e7-8c4d-f50157984b5f.png)
step3- On closing this view users are taken to the job details page. 
![image](https://user-images.githubusercontent.com/16536421/30687776-f0af2e2a-9ed9-11e7-9662-5d0dab391237.png)

Pros:
1.Users are taken directly to the full screen view of the console panel of the failed job. 
2. Having the jobs listed in the panel on the left side in job details page allows for easy navigation between jobs.  Plus, this is easily discoverable.
3.  users can switch to full screen view - based on their preference. 

Cons:
1. The job details page has the jobs listed on left panel - which takes up space. 
------------------------------------------
**Option3:** Prototype link: https://thoughtworks.invisionapp.com/share/G8DLC77HV
Proposes similar flow as option 1, but in this view the stage details page and job details page are combined to form a single page. 
1. The stage details are collapsed by default here. 
![image](https://user-images.githubusercontent.com/16536421/30688857-e8836db2-9edc-11e7-9318-4a8c999443ca.png)

2. The expanded view would look like this:
![image](https://user-images.githubusercontent.com/16536421/30689550-e1d16ea4-9ede-11e7-9c2f-c51dc23fe225.png)

Pros: 
1. Having the stage details and job details in a single page helps users to easily navigate between jobs and stages in the pipeline. The heirarchy also becomes clear for the user.
2. Users can easily move to other failed stages in the same pipeline. We have tested this feature earlier in our UX refresh research.

Cons:
1. Not sure about the Implementation for this.  

Please do share your feedback/concerns for the options proposed above.

**Comment by eeluke** [comment]
Hi Tina -

Thanks for sharing. A few immediate reactions, but I'd like to go through
this on a call with you (and maybe Duck too) to talk through it. I think
it's too complex to discuss entirely in this issue. Also, the InVision
links both took me to the same place:(

-Option 1a doesn't seem great to me. I think people will miss the dropdown
if it's part of the breadcrumbs. Plus I think the header should serve a
single purpose.
-I like the positioning of the dropdown on 1b. It's very clear what is
happening.
-I do really like the idea of combining jobs and details, but I think that
right now, we are just squishing them together. Can we think more about
user behaviors on these pages and how we can enable them with a new design?
-Just noticing right now how awkward the "jobs history" part of the screen
looks. I think we can make that a normal dropdown rather than styled like a
header.

I'll put a time on your calendar and we can chat more.

Thanks!

Emily Luke
Head of User Experience,
ThoughtWorks Studios <http://www.thoughtworks.com/products>
Email eluke@thoughtworks.com
Telephone +1 908 209 6204 <+1+908+209+6204>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=emily-luke-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by tinozza** [comment]
Hi emily-
Sure we can discuss this over a call..
And i have replaced the link to the prototype above with the correct one .. sorry about that.. but here is the link to the prototypes
Prototype 1: https://thoughtworks.invisionapp.com/share/BKDLF9U57
Prototype 2: https://thoughtworks.invisionapp.com/share/G8DLC77HV
