### ISSUE TITLE
Enforce email notification on failed build/test for all users

### ISSUE THREAD

**Issue by fanicia** [gocd/gocd#3830]
##### Issue Type
- Feature enhancement

##### Summary
One way or another it would be nice to be able to set the email notifications to "on" as default for all users so people get an email if they trigger a change that causes a pipeline build/test stage to fail.

I've been looking in the config.xml file to see if the email notification setting is saved for all users in there, which it doesn't seem to be.

But the setting IS saved somewhere on the server, so is it possible for me to have a script run through all the users and setup the email notification setting in case it hasn't been set before? (Part of my question is also where i can look up this email notification setting for the users?)

Whether it happens through a daily script or a feature build into GoCD this would be a nice feature-enhancement :)

**Comment by arvindsv** [comment]
Hello @fanicia. There's no such option. There is a community-written email notifier plugin (https://github.com/gocd-contrib/email-notifier) which you might want to take a look at - and maybe customize.

I'm going to close this for now, since it is probably not going to change, from a GoCD side. Thank you!
