### ISSUE TITLE
Inconsistent behaviour for Material Name for pipeline material type

### ISSUE THREAD

**Issue by mikhailadvani** [gocd/gocd#3846]
##### Issue Type

- Bug Report

##### Summary

For a pipeline material:

- Material Name field is not present in the pipeline creation wizard
- Material Name is optional for a pipeline material in the old pipeline edit view
- Material Name is mandatory in the Edit Pipeline Config API and hence the quick edit view
- The Material Name defaults to the pipeline name in the Get Pipeline Config API and hence on Save in the quick edit view, implicitly gets updated in the pipeline
- Additionally, the Material Name is not flagged with as asterisk to show that it is a mandatory field

##### Environment

Running from source

##### Steps to Reproduce

1. For a pipeline A, add a material in the old edit view without giving the material a name.
2. Switch to the quick edit view, remove the name of the material and Save.

##### Expected Results
Behavior should be consistent across the 2 flows

##### Actual Results
 Scenario 1 is successful but scenario 2 fails

##### Possible Fix

1. Make the pipeline name mandatory in the old edit view and pipeline creation wizard(field does not exist today)
2. Migrate the config xml(not sure if and how this is possible)

**Comment by varshavaradarajan** [comment]
@mikhailadvani , about the possible fix -  currently through the xml and ui, for the other basic materials, material name  is optional. I'll have to check for the API and the quick edit (pretty sure it is optional for the other materials). I think that in order to make this consistent, making the material name for pipeline dependency optional rather than mandatory is better because that's the behaviour that had been decided on and people are used to it. Also, you wouldn't have to worry about config migration. If we do go about making material names mandatory, it should be for all materials and not just for pipeline dependency.  

Thanks for pointing out about the absence of material name field in the pipeline creation wizard.

**Comment by mikhailadvani** [comment]
@varshavaradarajan if everyone else is also on board with the solution you are proposing, I would like to pick this up to fix. Summarizing the tasks below:

1. Make the material name optional in the API and client side(if there is a check on the client side).
2. In the GET call, remove the fallback material name has on pipeline name.
3. Add a field for material name for pipeline material in the pipeline creation wizard.

**Comment by varshavaradarajan** [comment]
@mikhailadvani ,

1. Yes. 
2. You'd have to introduce a new API version
3. Add the field for all materials in the pipeline creation wizard. 

@ketan , @maheshp  - cool?

**Comment by maheshp** [comment]
I tried adding a Pipeline material without specifying the name and got a 500 response. I don't think we need a new version of API, but fix this by using the default name when one not passed.

**Comment by ketan** [comment]
I agree that a new API version should not be needed, since we're not changing the structure of the JSON.

**Comment by varshavaradarajan** [comment]
Closing. Irrelevant now. The new pipeline wizard doesn't present an option for material name for any material. The pipeline config API shows the name to be the pipeline name in such cases. The materials tab in the old UI provides an optional material name field for all types of materials.
