### ISSUE TITLE
P4 tests would failed which  is caused by the data version for p4d repo

### ISSUE THREAD

**Issue by qiaoliang** [gocd/gocd#3898]
##### Summary

If your test box installed P4 version by 
When you run gradle task ```server:test```  2017.1/1559660
Then  tests about P4 will fail.

##### Environment

```plain
Perforce server error:
	Database is at old upgrade level 26.  Use 'p4d -r /private/tmp/test -xu' to upgrade to level 27.
```
##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by ketan** [comment]
We expect to run this with p4d `2016.2` and not `2017.1`, since this is the minimum version of p4d that is supported. Even upgrading to 2017.1 will cause this to fail with other versions of p4d.

I'm going to mark this as closed, since I don't really see a good way to keep this data in a form that's unversioned and easily upgradeable/downgradeable between versions.
