### ISSUE TITLE
[API] Different rights between the API and the web interface (Get all environments endpoint)

### ISSUE THREAD

**Issue by timoa** [gocd/gocd#3991]
##### Issue Type

- Bug Report / maybe security issue if not the attended behaviour

##### Summary

From the web interface, I can access to the Environments list but from the API endpoint "Get all environments", I'm not authorized to access the endpoint (401 error).

Is it from the https://build.gocd.org server. Maybe custom permissions but just in case, I prefer to report it.

###### Basic environment details

* URL: https://build.gocd.org
* Go Version: 17.12.0 (5551-3eebade2e7b833542c92ea0a027870aeb5399c14)
* JAVA Version: 1.8.0_144
* OS: Linux 3.10.0-693.2.2.el7.x86_64

###### Additional Environment Details

No access to the API support (not enough rights)

##### Steps to Reproduce

1. Connect to https://build.gocd.org with view / password credentials
2. Go to the Environments page https://build.gocd.org/go/environments
3. Now type this code into a terminal to use the API
```
curl 'https://build.gocd.org/go/api/admin/environments' \
      -u 'view:password' \
      -H 'Accept: application/vnd.go.cd.v2+json'
```
4. It return a 403 Forbidden error

##### Expected Results
To get the list of all the environments like the web interface

##### Actual Results
The access to this endpoint is forbidden

**Comment by arvindsv** [comment]
It looks like what you're trying to access is the environments _config_ API. That's why it's returning a 403. Surprisingly (to me at least), there doesn't seem to be an environments GET API which returns the runtime representation. That page is using an internal call, which returns some ugly HTML and is not usable.

I think that the dashboard API or pipelines API itself should provide details about which environment a pipeline is in, if any. The environments page itself is largely superfluous.

**Comment by varshavaradarajan** [comment]
@arvindsv - The runtime representation of environments should the same as https://api.gocd.org/17.12.0/#get-all-environments API, right? I recall a conversation we had around making https://build.gocd.org/go/environments/gocd/show view for all environments. We would be using https://api.gocd.org/17.12.0/#get-all-environments API for it right?

**Comment by maheshp** [comment]
While the dashboard page groups pipelines by `pipeline_group`, the environments page groups pipelines by `environment`. The environment_config APIs deals with the configuration part of the environment and as @arvindsv mentioned we do not have any API which would list all the active pipeline instances with environment information.

I agree with @arvindsv, the environment information should be part of the dashboard API or pipelines API. With this information as part of new dashboard page, users can be given an option to group pipelines either by `environment` or `pipeline_groups`.

Regarding configuring the pipeline, that would need a new page I guess similar to templates.

**Comment by timoa** [comment]
Hi Guys,

It makes sense for me to have it on the dashboard and reduce the number of calls if you just need to gets only the name of the environment like we get the pipeline group name.

I will release the next CI Remote version with the environment config list endpoint only accessible by the admin users and wait this new endpoint to provide access to all users:

<img width="375" alt="ciremote-environmentlist-1511771905122" src="https://user-images.githubusercontent.com/1432989/33262091-fda8fc2a-d35c-11e7-9119-c2e366351a56.png">

<img width="375" alt="ciremote-environmentdetails-1511771905122" src="https://user-images.githubusercontent.com/1432989/33262114-0dd131a8-d35d-11e7-97a7-743fb3dad964.png">

**Comment by maheshp** [comment]
@timoa we are working on the version 2 of the [dashboard API](https://github.com/gocd/gocd/pull/3920), currently it does not have the environment details but we plan to add it eventually which might take a little while.

Since environments page is different from the environment config API the behaviour in terms of authorization is different, I will be closing this issue for now.
