### ISSUE TITLE
Show downstream pipelines as gray, when upstream is running.

### ISSUE THREAD

**Issue by GusSkog** [gocd/gocd#4093]
##### Issue Type
Feature proposal

##### Summary
In pipelines pane, it would be nice to have the feature to have the color gray instead of red or green, when the upstream pipeline is running.
This would be a variant of what you can see in the VSM.
Right now users gets confused, and mistake that the last pipeline has completed (or failed), before the whole stream of pipelines have completed.

##### Environment
GoCD UX pipelines tab.

###### Basic environment details
Go Version: 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1). 

###### Additional Environment Details
N/A

##### Steps to Reproduce
1. Create a pipeline "Pipeline-1". 
2. Create a pipeline "Pipeline-2", which has "Pipeline-1" as material.
3. Run the pipelines.
4. Run a 2:nd run on "Pipeline-1".
5. While "Pipeline-1" is running (yellow), the downstream pipeline "Pipeline-2", is still green (showing last run status). This confuses the users.

##### Expected Results
Have a selection in the pipeline configuration to enable ability to show that upstream is in progress. 

##### Actual Results
By mistake users think that the stream of pipelines have completed prematurely. 

##### Possible Fix
N/A

##### Log snippets
N/A
##### Code snippets/Screenshots
N/A
##### Any other info
N/A

**Comment by GaneshSPatil** [comment]
@GusSkog -- The Dashboard page represents the **latest status of the pipeline**. The status of the pipeline could either be "_never ran_", "_passed_", "_failed_" and is independent of other pipelines.

Graying out the pipeline based on the VSM workflow status will defeat "showing the latest pipeline status on the dashboard" feature.

Also, here are following scenarios where the above feature will be misleading/ won't work:
1. If a pipeline has many upstream dependencies and belongs to many VSM workflows, when builds are happening very frequently, the pipeline will always be grayed out.

2. For the following workflow:
  A -> B -> C
If first runs of all pipelines pass and later second run of the pipeline A fails. In such scenarios, pipeline B and pipeline C will be grayed out forever.

3. For the simple workflow A-> B. If pipeline A pass and pipeline B is running. Another run of the pipeline A pass, in such scenarios, two workflows are represented by a set of pipelines. Should pipeline B be grayed out due to pipeline A's 2nd run has completed or should the pipeline B's 1st run being shown because it's in progress?

Pipeline dashboard does not represent the VSM workflow details hence it will be misleading to gray out pipelines without knowing the workflow context.
