### ISSUE TITLE
Job Feeds API does not show the environment variables that were overridden with trigger with options

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4097]
##### Issue Type

- Bug Report

##### Summary

Job Feed API provides the xml representation of the job. Once the job has completed, the environment variables that were overridden while triggering the pipeline with trigger with options are not shown. 

###### Basic environment details

* Go Version: `17.12`

##### Steps to Reproduce

1. Set up a pipeline with a pipeline level environment variable `foo` and value `bar`
2. Trigger the pipeline with options, override the pipeline level environment variable `foo` with `baz`
3. Wait for the job to complete. Make a request to `/go/api/jobs/:job_id.xml`

##### Expected Results

The environment variables section should list that the value of `foo` is `baz`

##### Actual Results

The environment variables section shows the value of `foo` to be `bar` 

##### Possible Fix

https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/domain/xml/JobXmlViewModel.java#L86 should also add trigger variables present in the job plan.

**Comment by jyotisingh** [comment]
@varshavaradarajan - we have been talking about deleting [some of that information](https://github.com/gocd/gocd/pull/2875#issuecomment-350198830) from the feeds api, which is why I am not sure if we will ever get to his bug. 

That entire API was built for `Shine` and `Shine` doesn't make use of the environment variables. That could be the reason why the trigger variables were not added. However, @ketan would have a better idea as to why was the information not available in this API.

**Comment by ketan** [comment]
I do not have an idea why it was not present. However this info will be
removed. I'm going to close this as WONTFIX.
