### ISSUE TITLE
MDU doesn't happen in case a pipeline is configured with the attached config

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4103]
##### Issue Type
- Bug Report
##### Summary

If a pipeline is created by using a template ( template created without extracting it from a pipeline),  and with material auto-update=false but the first stage configured with "fetch-material" the MDU for the material never happens. The pipeline is never run and has the following entry in logs

"Skipping scheduling of timer-triggered pipeline 'usingTemplate' as it has previously run with the latest material(s)"

###### Basic environment details

* Go Version: 17.7.0
* JAVA Version: JDK8
* OS: Mac

##### Steps to Reproduce

1. Use the attached cruise-config.xml file to make the configuration
2. Once configured leave the pipeline to be triggered by timer
3. The pipeline MDU will not happen ( will happen only on Manual triggers)
4. The pipeline will thereafter run with the same revision.

##### Expected Results
The MDU should happen or the user must be informed about this combination.
##### Actual Results

This currently acts as a manual trigger even though user specifies "fetch-material" in the first stage"

##### Log snippets

[go-server.log](https://github.com/gocd/gocd/files/1568189/go-server.log)
[cruise-config.txt](https://github.com/gocd/gocd/files/1568222/cruise-config.txt)

**Comment by varshavaradarajan** [comment]
@adityasood - This is the expected behaviour. MDU doesn't happen for materials with autoUpdate turned off unless you manually trigger the pipeline. Manual trigger forces an MDU to happen. The fetch materials configuration has nothing to do with MDU on the Go server. MDU just means that the Go server is polling the repositories to check whether there are new changes. If you disable that, no new changes are identified. The fetch material configuration is for the agent side. The console log  will show `Skipping material update since stage is configured not to fetch materials` if fetch materials is set to false and it shows `[GIT] Fetching changes` if fetchMaterials is true. 

Regarding the message on the go server log `Skipping scheduling of timer-triggered pipeline 'usingTemplate' as it has previously run with the latest material(s)`. This message is always accompanied with a change in the cron timer spec (the previous line). It doesn't mean that the scheduling of the pipeline `usingTemplate` will not be done ever. It just means that at the time of the change in spec, it is not necessary to schedule the pipeline.
