### ISSUE TITLE
Improvements to Dashboard API V2

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4121]
- [ ] Include html url links along with api links for:
    - [ ] Pipeline History
           - `history_url` links to Pipeline history API. 
           - Add `history_html_url` which links to Pipeline History Page.
    - [ ] Pipeline Settings
           - Currently `settings_path` links to Pipeline settings HTML page. 
           - Change `settings_path` to point to Pipeline Config API.
           - Add `settings_html_path` to point to Pipeline settings HTML page.
    -  [ ] Stage Details
           - Currently, stage instance`self` links to stages get instance API. 
           - Add stage instance `details_html_url` to point to Stage Details HTML page.

~~- [ ] Dashboard API does not return the previous stage instance related information.
       - Previous Stage instance information is necessary to show the previous stage status when the current run is in progress.~~ @arvindsv and @jyotisingh voted this feature out while building the API.

**Comment by arvindsv** [comment]
@GaneshSPatil or @yankurk: I think there's a potential issue around the usage of the cache for this. Specifically [GoDashboardService.java#L101](https://github.com/gocd/gocd/blob/6752c191c77fc00e52d30326bbcd97e137734548/server/src/main/java/com/thoughtworks/go/server/dashboard/GoDashboardCache.java#L101) and [GoDashboardService.java#L111](https://github.com/gocd/gocd/blob/6752c191c77fc00e52d30326bbcd97e137734548/server/src/main/java/com/thoughtworks/go/server/dashboard/GoDashboardCache.java#L111). `cache.get` is not a safe operation here. In fact, the `get` method should be marked internal and used only in tests, or completely removed to be replaced with usages of `allEntriesInOrder`.

`allEntriesInOrder` is the only safe method which can be called to get entries from the cache. That's because the cache [can be changed](https://github.com/gocd/gocd/blob/6752c191c77fc00e52d30326bbcd97e137734548/server/src/main/java/com/thoughtworks/go/server/dashboard/GoDashboardCache.java#L49-L58) by other threads while it is being used. Whenever a cache update finishes, the `cacheHasChanged` method is called and the `dashboardPipelines` object is updated. A double buffer, essentially.

So, a `cache.get` can return null. That's why the usages in GoDashboardService should be rewritten to use `allEntriesInOrder`.

/cc @jyotisingh

**Comment by maheshp** [comment]
@arvindsv spoke to @GaneshSPatil about the caching issue you mentioned. He will have a look at it, it's on his todo list.

**Comment by arvindsv** [comment]
@GaneshSPatil Can this be closed? Given all the other work around dashboard, etc?

**Comment by GaneshSPatil** [comment]
@arvindsv -- I am not sure. The new dashboard uses all the links from either `js-routes` or we've hardcoded the values. We need to fix the Dashboard API to not include the links which are not used by the view.

**Comment by arvindsv** [comment]
Ok.

**Comment by GaneshSPatil** [comment]
Remove following attributes from the Dashboard API dashboard:

Dashboard API v2 Fixes:
  - [ ] Dashboard Pipeline Links
    - [ ] self
      - Does sending history url make sense here?
    - [ ] delete `unlock` link
    - [ ] delete `schedule` link
    - [ ] delete `pause` link
    - [ ] delete `unpause` link
  - [ ] Pipeline Instance Links
    - [ ] delete `compare_url` link
    - [ ] delete `history_url` link
    - [ ] delete `vsm_url` link

**Comment by GaneshSPatil** [comment]
[Dashboard API v2](https://api.gocd.org/18.12.0/#dashboard) has been documented as part of V2, with the above-mentioned fixes.
