### ISSUE TITLE
JSESSION id not removed from cookie when user authenticates via HTTPS url

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4130]
##### Issue Type

- Bug Report
##### Summary

The JSESSION ID is persisted in the cookie when user logins in (using HTTPS based URL). This causes the user to be unable to login via HTTP based URL. User gets redirected to login page.

###### Basic environment details

* Go Version: 17.12.0
* JAVA Version: Java8
* OS:  Mac OS
* Browser vendor and version (if relevant): Chrome v62

##### Steps to Reproduce

1. Login via https://<go-server-URL>
2. Logout
3. Try logging in via http://<go-server-URL>

##### Expected Results
User should be able to login

##### Actual Results
User gets re-directed to login page

##### Possible Fix
Remove the JSESSIONN ID from cookie

**Comment by ketan** [comment]
What version are  you reproducing this on?

**Comment by ketan** [comment]
Fat fingered the send button. If you try a newer build with commit https://github.com/gocd/gocd/commit/858d65466fa01a2c2632e5ed5f5cc2c99e7900fb on it, then you'll see there's a bunch of other toggles that you can use. Your problem is because you're using both HTTP and HTTPS, ideally you'd want to use only HTTPS and set the secure cookie flag to true.

**Comment by ketan** [comment]
@adityasood — is this still reproducible?

**Comment by adityasood** [comment]
@ketan yes it is
