### ISSUE TITLE
Windows path with spaces for custom command fails

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#4173]
##### Issue Type

- Bug Report

##### Summary

For running msbuild bundled in the microsoft build tools I've been using the following command

```
C:\PROGRA~2\MICROS~1\2017\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
```

with the following arguments

```
/m
/nr:false
targets.msbuild
/t:BuildAndRunUnitTestsAndRelease
/p:BuildVersion="%GO_PIPELINE_LABEL%"
```

This works fine on the windows server 2012 r2 I've installed the go.cd agent on.

However when switching to a microsoft windows docker container it turns out 8.3 naming is disabled, so the short names no longer work.

I've tried various ways of writing the msbuild path with the spaces escaped or quoted, but none successful.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe
```

```
""C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe""
```

```
C:\""Program Files (x86)""\""Microsoft Visual Studio""\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe
```

```
C:\Program^ Files^ (x86)\Microsoft^ Visual^ Studio\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe
```

##### Environment

Go.cd agent 17.12.0 running in `microsoft/dotnet-framework-build:4.7.1-2017.12-windowsservercore-1709` container with openjdk JRE 8.0.152.

It also fails on windows 2012 R2, but there we still have the possibility of using 8.3 notation for the path.

###### Basic environment details

* Go Version: `17.12.0 (5626-cb7df2ffe421e43f2a682a7a323cb3a3e30734cc)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.4.86+`

##### Steps to Reproduce

1. Run go.cd agent on Windows 12 R2 or Windows 2016 Server or in microsoft/dotnet-framework-build:4.7.1-2017.12-windowsservercore-1709 windows docker container
2. Install chocolatey package `cinst microsoft-build-tools` version `15.0.26320.2`
3. Run custom command `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe` in any of the escaped forms

##### Expected Results

Command to run equally well as with the 8.3 notation

##### Actual Results

Fails with either

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

```
The input line is too long.
```

or

```
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by fabriciocduarte** [comment]
I'm also running into this issue.
GoCD 17.11 windows.

This may also relate to #2153

**Comment by ZigMeowNyan** [comment]
I pulled the latest stable build today (19.1.0-8469) and got the same issue on Windows 10. Doesn't matter how I do quotes - commands with spaces in them fail. Which means this issue has been open for over a year without any fix. That's stellar. This honestly makes the custom command task and command repositories useless on windows. Unless this gets some attention, I'll be throwing this away and going back to Jenkins. A build system that can't run an arbitrary task for over a year isn't a reliable one.

My command is pretty simple: 

`%ProgramFiles(x86)%\NuGet\nuget.exe`

And the error is as follows:
![image](https://user-images.githubusercontent.com/3219710/52536046-925cf800-2d0a-11e9-8ed3-715f2a46797c.png)

The command gets expanded properly, but then fails. Pre-expanding the path makes no difference.

Near as I can tell, the issue with this lies somewhere in the interaction between the `ExecTask`, `ExecTaskRepresenter` and `CommandUtils` classes. It's clearly being mangled by some code that's intended to quote paths that contain spaces, since adding or removing spaces from the task command makes absolutely no difference - the output is always outside of quotes. Whether that's because the quotes are being removed, or because the quote count is off I can't tell as there's no visibility into what's being run - only on the output error message.

Is there some sort of configuration for logging the command that's executed? If there is, I'd be glad to provide more information. If not, that should be considered for CommandTask usage as it will save a lot of time in testing and debugging. There should also be explicit tests to verify that the output is generated as expected for the given operating system.

Using short file names is not an acceptable workaround. Best practices for the NTFS file system recommend disabling short file names (8.3 format) for best performance. So enabling short file names as a fix for this one issue affects IO performance for the rest of the system. It's also a bad workaround, as it complicates the system unnecessarily.

Filenames with spaces in them should be fully supported. Especially as vendor tools will often be installed in the Program Files folder on Windows by default.

**Comment by eliaslevy** [comment]
Until this is fixed, you can get around this issue by running your command using cmd.exe.  E.g.
```
cmd 
/s 
/c 
"<your command>"
```

**Comment by mgiammarco** [comment]
I have the same problem and I have seen other bug filed for this problem and marked as stale.
The workaround suggested froma eliaslevy does not work for me.

**Comment by sriramnrn** [comment]
Does it help if you run a batch file at a short path name without spaces,
where the batch file itself calls the actual Command with various fill path
names with spaces?

— Sriram

**Comment by chadlwilson** [comment]
I imagine that would work.

I suspect the root of the problem here is most likely as described at https://eli.thegreenplace.net/2011/01/28/on-spaces-in-the-paths-of-programs-and-files-on-windows and https://superuser.com/questions/238810/problem-with-quotes-around-file-names-in-windows-command-shell

When GoCD launches Windows commands, behind the scenes it actually does `cmd /c <command> <arg1> <arg2>...`, where each chunk above is a discrete argument to a `ProcessBuilder`.

Needs more digging, but there seems to be complete bizarre ways Windows deals with quotes and/or spaces when processing args to `cmd`, and I suspect GoCD is also affected. Not sure if something changed or broke at some point though.

**Comment by chadlwilson** [comment]
I'm working on a fix for this to behave more intuitively.

In the meantime the workaround for this is to:

1. Add a single `"` before your command expression
2. Add an extra `"` at the end of the final argument in your list (OR an extra arg which is a lone double-quotation `"`)

e.g in the above example

Command
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\amd64\MSBuild.exe

^ NOT a typo
```

Args

```
/m
/nr:false
targets.msbuild
/t:BuildAndRunUnitTestsAndRelease
/p:BuildVersion="%GO_PIPELINE_LABEL%"
"
```

There's a long story as to why this likely works for almost all cases in the above links. 

Note that using this workaround will likely cause failures once the underlying problem is addressed in a future release (assuming it can be done without side effects) since GoCD will end up doing extra quoting on top of the user's manual quoting to ensure things are interpreted correctly.
