### ISSUE TITLE
Dashboard API - Build cause material revision is empty

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4440]
##### Issue Type

- Bug Report

##### Summary

Dashboard API response do not have the material revisions in the build cause section which causes Build cause modal to show empty on UI

###### Basic environment details

* Go Version: `18.2.0 (6175-1058e75b18e8a645dd71702851994a010789f450)`

##### Steps to Reproduce

1. Create pipeline and get few runs
2. Do a call on dashboard API - Directly hit the API or access dashboard page on UI
3. Build cause section of any pipeline instance is as here,

```
"build_cause" : {
            "approver" : "",
            "is_forced" : false,
            "trigger_message" : "No modifications",
            "material_revisions" : [ ]
          }
```

##### Expected Results

Dashboard response to contain correct revisions which the pipeline instance is run with

**Comment by ketan** [comment]
Marking as WONTFIX. We have a build cause api precisely for this reason. The dashboard will not contain any build cause information, because it:

- bloats up the size of the response
- can possibly contain several thousand items for several pipeline (single material triggered after several months) and cause the dashboard to slow down
