### ISSUE TITLE
Cannot remove empty pipeline group from personalize dropdown

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4454]
##### Issue Type
- Bug Report

##### Summary
1. Create an empty pipeline group(foo). This won't show up on the dashboard.

- In new dashboard 
  -  In a personalization dropdown, you will see the `foo`. Click on select none and then click on apply. After refreshing the page you will see `foo` selected.
  - You can not uncheck the pipeline group when there is no pipeline.

![new-dashbord](https://user-images.githubusercontent.com/7871209/36788091-a6db4732-1cb2-11e8-843a-1b889078435b.gif)

- In old dashboard
  -  In a personalization dropdown, you will see the `foo`. Click on select none and then click on apply. After refreshing the page you will see `foo` selected.
  - You can also try unchecking` foo` manually and then apply it. you will see the same behavior.

![old-dashboard](https://user-images.githubusercontent.com/7871209/36787959-20a64f72-1cb2-11e8-9426-9af0d140f729.gif)

**Comment by AksMKR** [comment]
I went through the issue. There are 2 problems present here
1. In personalize dropdown, if we select None and Apply then all the pipeline groups will get unselected. But the empty pipeline groups will still stay selected. This issue can be fixed with few tweaks.
2. We are showing empty pipeline groups in personalize menu but not on dashboard. This might bring confusion to users. Either we can show the empty pipeline groups on both personalize menu and dashboard, or hide them on both.

@naveenbhaskar @arvindsv What's your call on this? How should we go about it?

**Comment by varshavaradarajan** [comment]
@yankurk and I had spoken about this issue before he went on leave. I think he was working on it or has a WIP branch.

**Comment by varshavaradarajan** [comment]
https://github.com/yankurk/gocd/tree/personalize-dropdown is the WIP branch for this

**Comment by rajiesh** [comment]
verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
