### ISSUE TITLE
Value stream map does not refresh automatically like other views

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#449]
When one opens the value stream map it is not refreshed from time to time and one has to reload the page to see the pipeline progress.

**Comment by granddesigntech** [comment]
This is a big roadblock for us moving from Jenkins to GoCD.
Our delivery pipeline is currently implemented as jenkins jobs in which the test phases are run concurrently and the jenkins pipeline view plugin provides our default view (no-one even looks at the main view showing a bunch of jobs. we;re only interested in seeing them in pipeline form).
The VSM is the equivalent view since that kind of concurrent execution is achieved in GoCD via seperate pipelines (rather than stages or jobs which would be the GoCD equiv to a jenkins job).
But without the status updating in real-time (or a decently small poll period) the VSM is useless to us and the "non-pipelined" (to us) default view is worse.

I am surprised that there is so little interest since 2014 for improvement in this area of the VSM.
Am I missing something?

**Comment by dpsenner** [comment]
We've moved from GoCD to gitlab / gitlab-runner..
