### ISSUE TITLE
Trigger with option: material changes doesn't show up  when full git SHA is provided.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4562]
##### Issue Type
- Bug Report

##### Summary
When full git SHA is provided in a `trigger with option`. It is not auto-suggesting commits to pick up from. After removing the last character auto-suggestion is working fine.

![trigger-with-option](https://user-images.githubusercontent.com/7871209/37946105-5122c956-31a1-11e8-8b61-002716c1c638.gif)

###### Basic environment details

* Go Version: `18.3.0 (6355-d9f72ef78133277e33b7c6089dc284753ad7c9d9)`

**Comment by GaneshSPatil** [comment]
@bdpiparva -- this is an expected behavior. 
If the user has provided the exact SHA which matches one of the results, the suggestion is not shown as it is an exact match.

The suggestions are shown only when the user hasn't selected any material revision to trigger with.
More information: https://github.com/gocd/gocd/issues/4449

**Comment by akshaydewan** [comment]
When pasting a full SHA, does the pipeline trigger with the correct revision? I think the logic uses the material search results for validations and subsequently triggering the build. It may pick up the last run revision instead of the specified SHA.

@AksMKR Can you test this whenever you're working on the pending Trigger With Options issues?

**Comment by AksMKR** [comment]
yeah sure. will test this one as well.

**Comment by yankurk** [comment]
@GaneshSPatil -- I think we should show suggestion even when we paste the exact SHA. It is confusing if no suggestions are provided. Talked to @tinozza about this and she thinks the same too. Can we reopen this issue?

**Comment by GaneshSPatil** [comment]
Sure. will reopen it!

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
