### ISSUE TITLE
Saved Pipeline artifacts do not maintain mod flags when fetched

### ISSUE THREAD

**Issue by peterabbott** [gocd/gocd#464]
If you have a pipeline that saves an artifact for use in other pipelines, the flags on the files are not maintained, in particular the executable flag. 

We have several jobs that generate common artifacts, for example the output from bundle install, that are then used in other piplines. We do this as the bundle install can take a long time and is not necessary to run on every build. 

The issue is the when the output from a bundle install is passed to another pipeline, none of the executables can run because the executable flag is reset. We tried running `bundle install --binstubs bin` on the downstream pipeline to ensure the binaries where available but there is still issues with other modules that need the correct permissions.

The current solution is to have the upstream Pipeline tar the relevant directory and the downstream one untar. Seems a bit silly when that is exactly what the save artifact functionality does anyway.

**Comment by marcelboettcher** [comment]
+1, should really be adressed in the next release.
Work-around is described here: http://stackoverflow.com/questions/22168557/thoughtworks-go-changing-artefact-file-permissions

**Comment by j-ledoux** [comment]
Any updates about this issue ? I've been struggling with this for whole day (I blamed git at first and added checkout tasks) until I realized it was when I fetch my artefacts that permissions where gone...
Suggested workaround does not fit my case, I ended up adding a task that chmod required scripts... quite an ugly fix

**Comment by nikskiz** [comment]
+1 Any updates? I don't like having dodgy work arounds

**Comment by arvindsv** [comment]
@helmesjo You're right, it should. However, no one is currently looking at it, as far as I know. :( I'll put some more thought into how this can be made compatible with the existing zip implementation - since this will have to be controlled from the server side while the agents are the one that are doing the actual zipping.

This is not likely to be picked up soon, though. For the short term, your best best will be to tar the directory before upload and upload the tar file as the artifact and untar when fetching:

```xml
<tasks>
  <exec command="tar" args="cvf artifact.tar artifact-dir/" >
    <runif status="passed" />
  </exec>
</tasks>
<artifacts>
  <artifact type="build" src="artifact.tar" dest="my-artifacts" />
</artifacts>
```

Considerations (for me to think):

1. The performance profile of agents tar-gzipping vs. zipping [big and small artifact dirs]
2. Ideally, this is a flag turned on at the server side, which propagates to the agents - so that this change can be made with lesser risk.

**Comment by arvindsv** [comment]
FYI: In case anyone is looking to contribute a change, the changes will have to be around:

- Upload from agent: [here](https://github.com/gocd/gocd/blob/e8cc060883e4d4b5236efa9a41f5f3a608e7d549/common/src/main/java/com/thoughtworks/go/publishers/GoArtifactsManipulator.java#L84)
- Storing on server: [here](https://github.com/gocd/gocd/blob/e8cc060883e4d4b5236efa9a41f5f3a608e7d549/common/src/main/java/com/thoughtworks/go/publishers/GoArtifactsManipulator.java#L84)
- Fetch from server: [here](https://github.com/gocd/gocd/blob/e8cc060883e4d4b5236efa9a41f5f3a608e7d549/common/src/main/java/com/thoughtworks/go/publishers/GoArtifactsManipulator.java#L84)

This does not include the sligtly sticky challenge of affecting the agents (telling them to tar, instead of zip), from the server. It can be managed through parameters in FetchArtifactBuilder, etc. or through a full change in how the agent launcher params works.

**Comment by helmesjo** [comment]
Wouldn't it be enough to let the type of the bundle be decided once during creation (eg. on upload), and have the others (eg. fetching) fall back to basic type-checking?
So:

1. Files are bundled (tar/zip/whatever)
2. Files are unbundled:
    1. Detect type of bundle (tar/zip/whatever)
    2. Unbundle using correct util

Sounds like the _Chain-of-responsibility_ pattern could come handy here. Get the file, hand it to our chain of possible "bundle/unbundle"-utils and whoever first determines that it can handle the file does the unbundling (or if none we can print a very detailed error-message using the file & each utils prerequisite).

Anyways, just some brainstorming. :)

**Comment by brettcurtis** [comment]
I'm struggling with this one too. This fails trying to create an artifact out of the local terraform modules to be used in different stages. For example plan vs. apply. 
```yaml
- apply:
          approval: manual
          jobs:
            run:
              elastic_profile_id: "k8s-gcloud-pre-prod"
              tasks:
                - fetch:
                   pipeline: vault-exp
                   stage: plan
                   job: run
                   source: artifacts/.terraform
                   destination: terraform/
```
Error:
```none
provider.google: fork/exec /godata/pipelines/vault-exp/terraform/.terraform/plugins/linux_amd64/terraform-provider-google_v1.18.0_x4: permission denied
```

For now it's probably best just to re-run terraform init in each stage vs. muck around with tar. Maybe there is a better way but I haven't thought of one yet.

**Comment by brettcurtis** [comment]
So, I'm pretty smoked right now after banging my head off this today but I'm really not seeing a easy way to use Terraform with remote state in GoCD. 

If tar up the initial .terraform directory like described [here](https://www.terraform.io/guides/running-terraform-in-automation.html#plan-and-apply-on-different-machines) and the workaround above I hit yet another issue. If the apply fails and I want to re-run the job I can't because I mess up the lineage again since I extract the old state as part of the stage. This would happen too if the tar vs. zip problem was solved.. bummer - I'll see if i can figure anything out tomorrow.

**Comment by nicolas-geniteau** [comment]
+1, for this feature !
