### ISSUE TITLE
[New Dashboard] Trigger buttons do not get disabled if the pipeline was force triggered and material update is in progress

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#4647]
##### Issue Type

- Bug Report

##### Summary

Manual trigger of a pipeline forces an update of all associated materials. Once the material update completes, the latest revision of each of the materials is used in the build cause.
On new dashboard, the trigger-button immediately gets enabled after a force build. It gets disabled only after the pipeline gets triggered successfully. 
Older dashboard restricts further scheduling of a given pipeline if it has been scheduled already. 

Current state when pipeline is trigger and server is waiting for the MDU of associated materials to finish :

New Dashboard

<img width="322" alt="screen shot 2018-04-10 at 4 29 46 pm" src="https://user-images.githubusercontent.com/1046342/38553341-9d94ba9c-3cdc-11e8-8218-e43a7a6bdee6.png">

Old Dashboard
<img width="344" alt="screen shot 2018-04-10 at 4 29 54 pm" src="https://user-images.githubusercontent.com/1046342/38553337-987676b8-3cdc-11e8-9a28-748e3cd9a57f.png">

Seen in 18.3.0 (1b6ddff7fb7cf9de764f5658ca1bf0362bd497eb)

**Comment by jyotisingh** [comment]
Had a look at this one.
A pipeline can be triggered or not is decided upon based on a few conditions:
1. authorization
2. first stage is active across any of the instances - pipeline already triggered or someone reran first stage of old run, or the previous run hasn't finished etc
3. pipeline was already force triggered by someone and its in one of the two stages
  a) running an MDU of all the materials associated with this pipeline (this is done as part of force trigger `WaitForPipelineMaterialUpdate`). `TriggerMonitor.markPipelineAsAlreadyTriggered``TriggerMonitor.markPipelineAsCanBeTriggered` signal the start completion of this activity. 
  b) Pipeline material update has completed. Pipeline has been sent to the `PipelineScheduleQueue` and is waiting to be picked up for scheduling  or `PipelineScheduleQueue` is in the process of scheduling the pipeline (creating db entries etc). `PipelineScheduleQueue.schedule` and `PipelineScheduleQueue.finishSchedule` signal the start and completion of this activity

For the new dashboard, conditions (1) and (2) are being considered to decide if the trigger buttons should be enabled or not. The old one considers all the 3 conditions. 

If this check is not added for the new-dashboard, even though clicking on the button is allowed, it doesn't let a re-trigger of the pipeline happen since the schedule API does check for those conditions again. Also a flash message is shown to the user about the result:

<img width="301" alt="screen shot 2018-04-12 at 12 43 35 pm" src="https://user-images.githubusercontent.com/1046342/38661655-469b8c2e-3e4f-11e8-9fac-9792944de31b.png">

The same happens for trigger-with-options. Meaning, once the user selects all the required revisions etc from the popup and clicks on the trigger button, same message shows up for them.

In most cases this people wouldn't notice it since it could be really a small period of time when condition (3) is valid. In some systems where say MDU does take time or if the db queries/inserts are slow, it will be noticeable. 

For the fix:
I thought its going to be simply passing along the value of `PipelineModel.canForce` which is populated at the time of dashboard cache creation to the API and use the same in the UI. However, thats not it. Thing is `GoDashboardService` does receive any of the signals that come into picture for (3), hence it doesn't always have the up to date info on the trigger scene of a pipeline. 
Is it worth adding it?

**Comment by arvindsv** [comment]
@jyotisingh: From what I understand, the `AboutToBeTriggeredChecker` already takes care of figuring out whether the `TriggerMonitor` knows that an MDU is happening and when scheduling is in progress. We already use that from `GoDashboardCurrentStateLoader`. What is missing is events sent to `GoDashboardActivityListener` when these two events happen. Right? Essentially a `TriggerMonitorChangeListener` and a `PipelineScheduleQueueChangeListener`.

One concern (about not doing this) is the user experience, which can be bad - if it looks like they can trigger it, but they really cannot. The least we can do is to provide a better message. The trigger with options case is more troubling, because it's possible that a user will have time setting the right options just to be told that they can't trigger it.

So, I think it makes sense to consider this. It's not like every MDU causes this to happen. It's only when manually triggered.

**Comment by arvindsv** [comment]
One more case to think about:

1. Pipeline 1 uses material1.
2. Pipeline 2 uses material1.

3. I force trigger Pipeline 1.
4. material1 gets stuck updating.

What is the trigger status of Pipeline 2, in old dashboard? Assuming it allows triggering, what happens when I trigger it?

I guess it'll wait for the previous MDU to finish?

**Comment by arvindsv** [comment]
PS: I don't think we need to do this for 18.3. I'm moving it.

**Comment by childsc** [comment]
Could this somehow be caused by a large number of errors? 
I have seen that there was a team ( which does not own Pipeline 1 or Pipeline 2) with over 100 errors. The errors related to an incorrect credential (because the password was changed in AD but not update). The team is now correcting this. 

We are starting to see this occur with lots of other pipelines too. We will try to restart GoCD and see if that allows pipelines to work after. 

After a restart the pipelines which we had this error "Failed to trigger pipeline" "{pipeline already triggered}" automatically started to build.

**Comment by maheshp** [comment]
>We have two pipelines that are NOT either upstream or down stream from each other. However they both share the same git material, although with different branches defined. The problem seems to have occurred after the first run of Pipeline 2.

> Material 1 Branch A, Material 2, Branch A --> Pipeline 1
> Material 1 Branch B, Material 2, Branch B --> Pipeline 2

@childsc even though both the pipeline refer to the same git repo GoCD will consider `Material 1 Branch A` and `Material 1 Branch B` as two different materials since they refer to different branches. And since both the pipelines have different materials, the pipeline scheduling should not affect each other.

The possible reason for `Failed to trigger pipeline` message could be because on the first trigger of the pipeline a material update is scheduled but is stuck for some reason. On the GoCD server instance can you run `ps -ef | grep -i git` to check if the material update is stuck.

**Comment by iSanchezDev** [comment]
Still happening 

I had a release branch and it failed, I moved to master branch and got stuck.
