### ISSUE TITLE
Deleting pipeline blocks gocd

### ISSUE THREAD

**Issue by grobie** [gocd/gocd#4705]
##### Issue Type

Bug Report

##### Summary

Deleting a pipeline on a large gocd server stalls the server for everyone. While the deletion is processed, no one is able to load any page. This can take tens of seconds in our environment with more than 800 pipelines.

##### Environment

```plain
Number of pipelines | 814
Number of agents | 30
Number of environments | 0
Number of unique materials | 683
Number of schedulable materials | 683
```

###### Basic environment details

* Go Version: 18.3.0
* JAVA Version: 1.8.0_162
* OS: Linux
* Browser vendor and version (if relevant): Firefox

##### Steps to Reproduce

1. Configure hundreds of pipelines
2. Delete a pipeline via `/go/admin/pipelines`
3. Click "Proceed"
4. Wait for tens of seconds to process the result
5. Watch "is gocd down?" questions in Slack ;-)

##### Expected Results

A deletion should not block the UI for everyone.

##### Actual Results

It does.

**Comment by ketan** [comment]
@grobie what OS are you on?

**Comment by grobie** [comment]
@ketan GoCD is running on Debian. Locally I use Arch. Do you think that's related? It appears the large the config gets, the longer it takes to delete a pipeline from it.

**Comment by dziemba** [comment]
Taking over for @grobie, we work together.

Here's the output, let me know if you need more:
[go-server.out.log.gz](https://github.com/gocd/gocd/files/1973870/go-server.out.log.gz)

**Comment by ketan** [comment]
Thanks — we have been looking at a similar issue from another user, and this finding seems to confirm our understanding that there is contention in the database. In the 57th dump taken at `2018-05-04 09:28:49` (see [this link](http://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMTgvMDUvNC8tLWdvLXNlcnZlci5vdXQubG9nLmd6LS05LTM0LTU2) for a visualization) we see the following:

There are 58 threads blocked:
- 32 of these are because the dashboard cache is being built after a config save. This acquires a lock on the database, causing a bunch of other `MaterialUpdateListener` threads to wait on the database
- in the meanwhile, the DB connection pool (size 32) is exhausted, and about 25 web requests are waiting on that

We're looking at this issue on priority since it affects some other users. To help us diagnose this problem, would you mind clicking on the backup button under the **Admin>Backup** and send a copy of the timestamped backup folder to `support[at]thoughtworks.com`. Please add a link to this issue so we know they are related. **Please do not attach the backup to this issue.**

Thanks.

**Comment by dziemba** [comment]
Thanks for the quick reply. I talked to our security/legal team and unfortunately we cannot send you the backup because it contains too much sensitive data. Is there anything else we can do?

**Comment by ketan** [comment]
> Is there anything else we can do?

We have figured out the root cause and will have a fix (and release available) sometime early next week.

We can provide you an experimental build sometime on Monday — do you have a test server to throw this on and provide some feedback?

**Comment by dziemba** [comment]
That sounds great! Yes, we can then try out the build with a clone of our production server.

**Comment by jyotisingh** [comment]
@grobie , @dziemba - Could you try out the latest *Experimental* build from https://www.gocd.org/download/ on a test server to verify if the issue is resolved. Thanks

**Comment by dziemba** [comment]
We just tried `18.4.0-6639` on an exact clone of our production instance, looks like this issue doesn't appear anymore  🎉 

It also works for arbitrary changes to the config XML, not only for deleting pipelines.
Thanks for fixing this so quickly!
