### ISSUE TITLE
Build that pass after the Cancelled stated is considered Fixed

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#4728]
##### Issue Type

- Feature enhancement
##### Summary

In this link there is a little table that explains the state of the pipelines.
https://docs.gocd.org/current/configuration/dev_notifications.html
![image](https://user-images.githubusercontent.com/23528701/39868209-f4e39d36-542e-11e8-9d23-36e79d2c9587.png)

We are using this states to comunicate the team when the build is broken/failed and when it is fixed (passed after broken/failed).
Thing is that when the build is Cancelled, and passes after, it is considered fixed. We work with a lot of devs, so sometimes, when two or more devs commit things at a close time, we can cancel the build and re-run it, to get all the changes and spare some time. And for many other reasons that are not a problem, like restarting the machine, or starting to build a pipeline by mistake, etc.

I don't see the reason why the Cancelled state should throw a Fixed event. And this is kinda anoying, since we get our bot notification all of us when there is no need for it (and we do need the fixed notification, when the build is really broken).

Maybe we could remove that fixed event after a cancelled build?

**Comment by arvindsv** [comment]
@hbsis-williamdasilva I think it's reasonable (in the general case) to say that a cancellation is a failure. In the sense that it didn't finish successfully. I do understand how you're using it and why that's not ideal for you. However, it is unlikely to change.

I wonder if it would be better to use/write a  custom notification plugin (API docs [here](https://github.com/gocd-contrib/email-notifier)) or modify an existing one such as [this](https://github.com/gocd-contrib/email-notifier). Especially since it gives you so much more control.
