### ISSUE TITLE
QuickEdit button is missing in 18.6.0

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#4849]
##### Issue Type

- Bug Report

##### Summary

After upgrading to version 18.6.0 I no longer see the QuickEdit that's been visible at the top of the pipeline edit page for a long time.

##### Environment

```json
{
   "Timestamp":"2018-06-14T15:30:26Z",
   "Go Server Information":{
      "Version":"18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338)"
   },
   "Config Statistics":{
      "Valid Config":{
         "Number of pipelines":519,
         "Number of agents":73,
         "Number of environments":0,
         "Number of unique materials":159,
         "Number of schedulable materials":144
      },
      "Security":{
         "Plugins":[
            {
               "Google oauth authorization plugin":true
            },
            {
               "Password File Authentication Plugin for GoCD":true
            },
            {
               "LDAP Authentication Plugin for GoCD":false
            }
         ],
         "Enabled":true
      }
   },
   "OS Information":{
      "OS Name":"Linux",
      "OS Version":"4.14.22+",
      "System Architecture":"amd64",
      "Available Processors":8,
      "Average System Load":0.24609375
   }
}
```

* Go Version: `18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.14.22+`
* Browser vendor and version (if relevant): `Google Chrome for Mac Version 67.0.3396.62 (Official Build) (64-bit)`

**Comment by varshavaradarajan** [comment]
@JorritSalverda - we removed the quick edit button in 18.6.0. The pipeline quick edit page had been in beta for a while and remains incomplete. Since, a few of the config options were unsupported, we decided to remove the button but retain the feature behind a toggle. If you want to use the quick edit page, turn on the feature toggle `pipeline_config_single_page_app_key` by make a feature toggle API request

```
curl https://your-go-server/go/api/admin/feature_toggles/pipeline_config_single_page_app_key \
  -d toggle_value=on \
  -H 'Confirm:true' \
  -u username:password
```

The pipeline quick edit page can be accessible with the url `https://<go-server>/go/admin/pipelines/<pipeline_name>/edit`

If you want the quick edit page shown by default when you click on the settings icon, enable the feature toggle `quick_edit_page_toggle_key`. 

One of the things to note is that if the pipeline config has configuration options that is not supported by the quick edit (example: work on external artifacts - #4049 ) and later you use the quick edit page to update the pipeline configuration, the config related to the external artifacts is lost at the moment.
