### ISSUE TITLE
Fan-in seems not to be working (pipeline dependency fan-in)

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#4894]
Hi,

I'm currently creating a pipeline that depends on two other pipelines.

As this seems simple, the fact is that the fan-in seems not to be working.

Current setup:
Pipeline A (that depends on some SVN materials and other pipelines)
Pipeline B (that depends on some SVN materials and other pipelines)
Pipeline C (that depends ONLY on Pipeline A and Pipeline B).

However, I keep getting this error:

```
Error while scheduling pipeline: C as no compatible revisions were identified.29 Jun, 2018 at 14:22:12 Local Time

Failed resolution of pipeline C: Cause : Could not find compatible revision for material: DependencyMaterialConfig{pipelineName='A', stageName='StageName'}
```

This message sometimes appears complaning about dependency A, other times B.

If I remove one of the dependencies (A or B) the automatic schedule starts working. When I have both it does not.

Am I missing something here?

GoCD version 18.5.0.

Cheers,
Diogo

**Comment by arvindsv** [comment]
@Diogomrol Can you attach a screenshot of the VSM for Pipeline C? It looks like pipelines A and B have some common upstream pipeline or material. 

PS: This is not really the right place for this question, since we don't know that this is an "issue" yet. Maybe you're using [blacklists, which can cause issues with fan-in](https://docs.gocd.org/current/advanced_usage/fan_in.html#limitations) or some upstream pipeline could be paused, etc. However, I'm happy to wait for more details and then decide, before closing this issue.
