### ISSUE TITLE
Pipelines created via the PipelineConfig v6 API shouldn't be created paused by default

### ISSUE THREAD

**Issue by moritzheiber** [gocd/gocd#5041]
##### Issue Type

- Bug Report

##### Summary

I believe I've found a bug in the `PipelineConfig` API (v6) which leads to pipelines provisioned through the API being created in a `paused` state. There is no API parameter to change this default behavior, [it's hardcoded](https://github.com/gocd/gocd/blob/4b9e583edddda720ca4d010c608804367ed0c675/api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/PipelineConfigControllerV6Delegate.java#L164-L166).

I believe this attribute should not default to `true`, or else needs to be configurable through the `PipelineConfig` API.

##### Environment

Linux

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: 1.8.0_171
* OS: Linux 4.14.62-65.117.amzn1.x86_64

##### Steps to Reproduce

Provision any pipeline through the `PipelineConfig` v6 API and observe its status set to "Paused".

##### Expected Results

Any pipeline provisioned through the `PipelineConfig` v6 API is unpaused when provisioned.

##### Possible Fix

Either remove the code related to pausing the pipeline provisioned through the `PipelineConfig` API or introduce a parameter which lets you adjust the attribute, with a sane default.

cc @arvindsv @ketan

**Comment by GaneshSPatil** [comment]
@moritzheiber @gocd/committers 
Pipelines created via UI and API both remain in the paused state after creation.

Pipelines created via UI remains in the paused state as the UI pipeline creation wizard does not allow users to add multiple materials, stages, jobs, tasks, etc. Hence, after creating basic pipeline, users can add extra materials, stages, jobs, tasks.

Using a Pipeline config API, users can create entire pipeline in one request and it doesnt require the pipeline to be paused due to "under construction" reason.

A new version of API is *not* required as the change not affecting the structure of the pipeline config API response.

Changes needs to be done for: `pipeline config API v5` and `pipeline config API v6`

Adding this for upcoming release `v18.8.0`.

**Comment by arvindsv** [comment]
Linking to: https://github.com/gocd/gocd/pull/5058

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7361-907023c3a6c8fe5d2dd13ca1e9dbcee6e36431ac)
