### ISSUE TITLE
Extra tab space on agents page with the message on Agents page

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5201]
##### Issue Type
- Bug Report

##### Summary

When any action is performed on the agents, there is an extra tab space on the agents' page along with the message

###### Basic environment details

* Go Version: 18.10.0-7527
* JAVA Version: Java10
* OS: MacOs
* Browser vendor and version (if relevant):Chrome and Firefox

##### Steps to Reproduce

1. Navigate to agents page
2. Either enable/disable an agent or allocate a resource/environment to the agent
3. You will notice an extra tab space with the message

##### Expected Results
The extra tab space should not be seen

##### Actual Results
The tab space is seen

**Comment by GaneshSPatil** [comment]
@adityasood -- This issue has been fixed in the latest versions of GoCD.

![Screen Shot 2019-05-07 at 3 01 37 PM](https://user-images.githubusercontent.com/15275847/57289532-2dcaf280-70d9-11e9-85a0-ef9cb101740d.png)
![Screen Shot 2019-05-07 at 3 01 19 PM](https://user-images.githubusercontent.com/15275847/57289533-2e638900-70d9-11e9-8a87-95bcb3dc045e.png)
