### ISSUE TITLE
tput setting up color output

### ISSUE THREAD

**Issue by avatarworf** [gocd/gocd#5204]
##### Issue Type
- Bug Report

##### Summary

The GoCD console when executing a bash shell which previously produced colorised output now fails at the point it sets `tput bold`

##### Environment

Each pipeline executes against a 'Amazon Linux AMI 2018.03' JVM agent, on the same machine. After the upgrade from v18.7.0 to v18.9.0 last night, I traced down the problem to the tput command.

###### Basic environment details

* Go Version: 18.9.0 (7478-f202ea9416939d7ce356cf3939239ef953ec423b).
* JAVA Version: 1.8.0_181
* OS: Linux 4.14.62-65.117.amzn1.x86_64
* Browser vendor and version (if relevant): Chrome Version 68.0.3440.106

##### Steps to Reproduce

1. create a shell script containing a simple tput command

```bash
#!/usr/bin/env bash
echo "Colors please"
bold=$(tput smso)
reset=$(tput sgr0)
green=$(tput setaf 2)
echo "${bold}Bold{$reset}"
echo "${green}Green{$reset}"
```
2. call the shell script in any pipeline

```bash
bash -e script.sh
```
##### Expected Results
The console in v18.7.0 returned colorised text, while in v18.9.0 failed.

##### Actual Results
The console returns a '[go] Task status: failed, took: 0.8s, exited: 1' failure message. the tput command seems to fail with an cli error code.  Running from the goCD box itself no error code.

##### Possible Fix
Work around currently, i've remove the use of tput and the colorised output.  But this removed the readability of the output for others.  Open to other ways to have colorised terminal output, if it works.

**Comment by ketan** [comment]
Before someone digs this further, could you confirm a few things:

- that nothing else on the server has changed (just a simple `yum upgrade` or whatever of the gocd server)
- that nothing else on the agent has changed. The agent is the one that actually executes the command, captures the output and sends to the server.

Could you click on the "raw" logs between builds (save as, no copy-paste in the browser please) where this colorized output has broken and attach them here, if you're unable to attach the logs because there's sensitive content, could you snip out the sensitive contents using an editor that supports utf-8 (aka not windows notepad ;) and attach that?

Thanks

**Comment by ketan** [comment]
I'm looking at the following lines in your console log, and it seems like the `tput` binary is likely not available on path, or fails to execute. Depending on your linux distribution, `tput` is provided by the ncurses package, can you check by adding `which tput` before executing `tput`?

```plain
!!|11:52:12.874 [go] Task: bash -e pipeline-scripts/accounts-test.sh master
&2|11:52:12.876 + composer_commit=master
&1|11:52:12.876 Setting up Environment
&2|11:52:12.876 + echo 'Setting up Environment'
&1|11:52:12.876 HI
&2|11:52:12.876 + echo HI
&2|11:52:12.876 + tput bold
?1|11:52:12.877 [go] Task status: failed (3 ms) (exit code: 1)
```

**Comment by ketan** [comment]
I'm going to mark this as closed based on my previous comment. The issue is clearly with the script being unable to run, and not with the console log as described in the issue.

If you feel this still needs investigation from the GoCD team, let me know and I can reopen this issue.
