### ISSUE TITLE
Issue with enabling debug mode for logging in GOCD

### ISSUE THREAD

**Issue by vamsikrishna1789** [gocd/gocd#5249]
Our GOCD application id going down more frequently and we could not find any errors in the log. So we are trying to enable debugging logs for GOCD server. So we have added logback-include.xml in /etc/go/ which is also not working. Kindly help me change the logging mode.

**Comment by ankitsri11** [comment]
Can you share `logback-include.xml` you are currently using? Our documentation [here](https://docs.gocd.org/current/advanced_usage/logging.html) has some examples for configuring additional logging for GoCD server and agent.

In order to troubleshoot, can you share below information:

1. GoCD version
2. logback-include.xml 
3. Try enabling GC logging as mentioned [here](https://docs.gocd.org/current/installation/performance_tuning.html#enable-gc-logging)
4. Was there any recent changes after which you ran into this issue?
5. Send us the latest go-server.log

**Comment by GaneshSPatil** [comment]
@vamsikrishna1789 -- As of now, I will be closing this issue. 
Please reopen the issue and attach all the information mentioned by @ankitsri11, if you are still facing the problems with enabling debug mode for logging in GoCD.
The information mentioned [here](https://github.com/gocd/gocd/issues/5249#issuecomment-428286149) will help us debug this issue further.
