### ISSUE TITLE
Fetchartifact is (or just feels like being?) slow

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#526]
Our artifacts are not huge, but can be 50mb in size. Passing them over to another pipeline and thus fetching those on a agent is utterly slow. A performance improvement there would be awesome.

My assumption for the cause is that we have quite a lot of artifacts with sizes from 6mb to 80mb. If the API does fetch artifact by artifact adds an obvious communication overhead which could be improved by requesting a bunch of artifacts at once?

And maybe there are still ways to improve the protocol to handle big files better (i.e. samba file transfers are faster than http file transfers because of the protocol)?

**Comment by NachbarsLumpi** [comment]
We recently upgraded go to the latest version (14.4) and the issue still persists. The logfiles on the server show lines like:

2015-01-22 13:29:16,177  INFO [19476327@qtp-8515211-10] ArtifactsController:290 - [Artifact Download] Successfully resolved 'XXX.exe' for 'XXX/481/compile/1/compile'. It took: 16437ms

Resolving an artifact takes 16 seconds? *huh* Something's going wrong here. And then a few lines later there is:

2015-01-22 13:31:25,727  INFO [19476327@qtp-8515211-10] FileView:116 - [Artifact Download] Finished downloading: C:\Program Files (x86)\Go Server\artifacts\pipelines\XXX\481\compile\1\compile\XXX.exe. ShouldZip? = false. The time taken is: 129550ms

So it took 129 seconds to fetch a 35mb executable over a gigabit network. This would mean that it transferred this file at 277kb/s! :-(

What I can observe is that downloading a file seem to become slower the longer the server is up. Eearlier lines show a steady increase in how fast files are resolved/transferred. Thus it looks like there is something going on there that makes the server slower over time.

Last but not least I'm not sure if this matters, but the logs are filled up with more than 90% of messages like:

2015-01-19 00:07:17,081  WARN [materialUpdateThread] MaterialUpdateService:146 - [Material Update] Skipping update of material SvnMaterial{url=XXX, userName='go', checkExternals=false} which has been in-progress since Mon Jan 19 00:06:10 CET 2015

and:

2015-01-19 00:07:17,081  WARN [materialUpdateThread] MaterialUpdateService:146 - [Material Update] Skipping update of material DependencyMaterial{pipelineName='XXX', stageName='YYY'} which has been in-progress since Mon Jan 19 00:06:10 CET 2015

**Comment by mynkow** [comment]
We have the same issue. We have to restart the server to get full performance.

**Comment by fire** [comment]
Our artifacts are 8 gigabytes ~ so anything that speeds up transfers is welcome!

**Comment by NachbarsLumpi** [comment]
*bump*

We still have one stage that fetches 81 artifacts and that takes about 366 seconds to complete. This means that fetching each artifact takes an average of 4.5 seconds to complete. In total it is roughly 1.1GB and hence the average transfer rate is 3mb/s. We are in a gigabit network and therefore it could be about 97mb/s faster than this! If it would use the full 100mb/s of the gigabit network the fetching of the artifacts could in theory be as fast as 11 seconds!

**Comment by ketan** [comment]
@NachbarsLumpi — when you run a stage the first time, all artifacts are compressed on the server before being sent over. So the first download will take a reasonable amount of hit. Does a stage re-run which downloads identical artifacts as the previous run take just as long?

**Comment by NachbarsLumpi** [comment]
2016-11-04 11:55:01,543  INFO [qtp30979190-7346863] FileView:114 - [Artifact Download] Finished downloading: OBFUSCATED. ShouldZip? = false. The time taken is: 3954ms

The above log message indicates that files are not compressed before they are transferred. Let me note that it makes not much sense to compress small or large data when having a gigabit network. It simply takes way longer to compress/decompress data than simply transfering the data as is!

Log messages further indicate that a significant amount of time is spent in between one fetch artifact and the next. The following log messages show that one entire second passed by in between the artifact download and the fetch of its md5 checksum:

> 2016-11-04 11:54:57,589  INFO [qtp30979190-7346863] ArtifactsController:291 - [Artifact Download] Successfully resolved 'OBFUSCATED.exe' for 'OBFUSCATED.exe'. It took: 250ms
> 2016-11-04 11:54:57,589  INFO [qtp30979190-7346863] FileView:108 - [Artifact Download] About to download: OBFUSCATED.exe. ShouldZip? = false
> 2016-11-04 11:55:01,543  INFO [qtp30979190-7346863] FileView:114 - [Artifact Download] Finished downloading: OBFUSCATED.exe. ShouldZip? = false. The time taken is: 3954ms
> 2016-11-04 11:55:02,433  INFO [qtp30979190-35] ArtifactsController:273 - [Artifact Download] Trying to resolve 'cruise-output/md5.checksum' for OBFUSCATED'
> 2016-11-04 11:55:02,433  INFO [qtp30979190-35] ArtifactsController:291 - [Artifact Download] Successfully resolved 'cruise-output/md5.checksum' for 'OBFUSCATED'. It took: 0ms
> 2016-11-04 11:55:02,433  INFO [qtp30979190-35] FileView:108 - [Artifact Download] About to download: OBFUSCATED\md5.checksum. ShouldZip? = false
> 2016-11-04 11:55:02,433  INFO [qtp30979190-35] FileView:114 - [Artifact Download] Finished downloading: OBFUSCATED\md5.checksum. ShouldZip? = false. The time taken is: 0ms
