### ISSUE TITLE
UI Issues for 18.12

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#5464]
This issue to track all the UI issues that need be fixed for the 18.12 release, so that we can prioritize things easily, and so that it's easier for @naveenbhaskar to keep track.

- [x] Config Repo forms layout needs to be fixed
- [x] Size of modals needs to be tweaked (there is too much white space either at the bottom or right side)
- [x] Add Data Sharing to the new Menu
- [x] Make Config Repo delete confirmation modal Small
- [x] Fix for long text in key-value-pair component
- [x] Feedback for the new Menu - the Security section seems odd.
- [x] For Internet Explorer 11 users, we need to show a message saying that the browser is not supported
- [x] UI for notifying users that Drain Mode is active
- [x] Revisit "danger button" color.
- [x] Move plugin ID from top into the details section on plugins SPA page.
- [x] Fix broken headers in history and Job details page
- [x] Inconsistent highlighting for menu items under admin (https://github.com/gocd/gocd/issues/5464#issuecomment-445298019)
- [x] 'Admin' menu is not clickable or hoverable  on IE edge browser.
- [x] 'GoCD YAML files pattern:' field is not displaying on expanding config repo even though it has a values.
- [x] On config repo spa , after couple of seconds, a same config repo displaying multiple times.

**Comment by rahulpargaonkar** [comment]
Adding some UI issues on plugins page & config repo spa page
1. on plugins page, irregular spacing between plugin names & ids
<img width="1425" alt="screen shot 2018-11-28 at 10 29 08 pm" src="https://user-images.githubusercontent.com/33080845/49171172-f2770b80-f363-11e8-816f-eaf9c1d61048.png">

2. on config_repo SPA page, error symbol is miss-aligned on plugins page, it looks incorrect as compared to green tick symbol.
<img width="1430" alt="screen shot 2018-11-28 at 11 19 04 pm" src="https://user-images.githubusercontent.com/33080845/49171222-14708e00-f364-11e8-86ce-416ae30d34fc.png">

3. on config repo add/edit pop-up window, a text box sized window is highlighted when a checkbox is selected or not- selected.

4. when config repo expanded the the username is diplayed as null if not provided. Instead of null, can we specify either 'not specified'? or hide it? Or may be we can make username and password field interdependent?

**Comment by ibnc** [comment]
I've noticed an issue with the dashboard tabs on build.gocd.org. When I click the Go icon on the top left, it takes me back to the furthest left tab, but the content of the page is incorrect.

Screenshot 1:
<img width="1438" alt="screen shot 2018-11-28 at 3 28 56 pm" src="https://user-images.githubusercontent.com/5726224/49189341-c4bda280-f322-11e8-9348-d9b97e011e5f.png">

Screenshot 2:
<img width="778" alt="screen shot 2018-11-28 at 3 29 02 pm" src="https://user-images.githubusercontent.com/5726224/49189347-d2732800-f322-11e8-8c6b-50e9e25dfb36.png">

**Comment by rahulpargaonkar** [comment]
@ibnc I am not able to reproduce the issue on build.gocd and on locally.  could you please provide the gif of issue?

**Comment by rahulpargaonkar** [comment]
Issue 6: correct (green tick) icon is displayed even though the parsing error is there is config repo.
<img width="1436" alt="screen shot 2018-11-29 at 5 00 02 pm" src="https://user-images.githubusercontent.com/33080845/49219088-43384400-f3f8-11e8-9186-29e8b7920010.png">

**Comment by vishaldevgire** [comment]
UI Issue 7: When using <KeyValuePair>, long key names and values overlap
<img width="712" alt="screen shot 2018-11-29 at 6 45 17 pm" src="https://user-images.githubusercontent.com/24635164/49224379-53a3eb00-f407-11e8-93d6-6948715779ca.png">

**Comment by ibnc** [comment]
@rahulpargaonkar Here's a gif of the issue I see:

Chrome version: 70.0.3538.102

![dashboard_tabs_content_issue](https://user-images.githubusercontent.com/5726224/49244655-2898a780-f3c5-11e8-8834-a25d16389165.gif)

**Comment by rajiesh** [comment]
UI Issue 8:

`ADMIN` link visible for view users. On the GoCD server build : 18.12.0 (8092-8b8ef0cf42f2186aa73a0a7074e669fa2c70655d) Login as view user and observe that `ADMIN` link is visible on the header, however the admin menu is disabled. Prefer to disable it for the view users

<img width="1244" alt="screen shot 2018-12-03 at 2 56 47 pm" src="https://user-images.githubusercontent.com/6533924/49366361-2c9f2f00-f70f-11e8-9756-08be43c7ddf3.png">

**Comment by rajiesh** [comment]
UI Issue 9:

On server setup with analytics plugin, `ANALYTICS` option is visible on rails pages like Stage/Job details page for non admin users.

**Comment by maheshp** [comment]
@rajiesh I am looking into Issue #8 & #9.

**Comment by vishaldevgire** [comment]
UI issue 10:

One Elastic Profile component SPA, while creating or editing profile the `Id` text field is not aligned properly to other form elements.

<img width="1156" alt="screen shot 2018-12-04 at 12 55 10 pm" src="https://user-images.githubusercontent.com/24635164/49498422-06a19800-f891-11e8-9afc-eb23eccbbce1.png">

**Comment by rajiesh** [comment]
While discussing on the UI issues on Plugins SPA page with componentization - there came up a suggestion to remove `Id` field from top level and move it to the details section of each plugin so that we get more space for plugin name and `Version` can be aligned similarly for all plugins in the list. Adding it as an item to the issue

cc: @akshaydewan @maheshp

**Comment by rajiesh** [comment]
Headers are broken on History page and Job details page. Its observed on version 18.12.0 (8139-005f4fd80bafd2efd1d413537368156303f6ef6e)

<img width="1016" alt="screen shot 2018-12-06 at 7 46 07 pm" src="https://user-images.githubusercontent.com/6533924/49589533-a3e2f600-f98f-11e8-9798-669bbd6b306d.png">

**Comment by akshaydewan** [comment]
@rajiesh I'm looking into the broken header

**Comment by varshavaradarajan** [comment]
Some links in the dropdown menu are in gray until you access them. Eg - role configuration, data sharing. Pipelines, package repositories were also gray until I clicked on them and then came back to the dashboard. Is this intentional, @akshaydewan ? 

<img width="653" alt="screen shot 2018-12-07 at 9 00 21 am" src="https://user-images.githubusercontent.com/4715748/49661707-af213a80-f9fe-11e8-85c3-de7ed20b1ca6.png">

**Comment by naveenbhaskar** [comment]
@varshavaradarajan .. not intentional , will fix that

**Comment by GaneshSPatil** [comment]
Extra whitespaces on all the modals.

<img width="776" alt="screen shot 2018-12-12 at 7 15 24 pm" src="https://user-images.githubusercontent.com/15275847/49873647-6b856100-fe42-11e8-80f3-f9b81c1473fa.png">


this is broken due to https://github.com/gocd/gocd/commit/c27c94a49a0331d3d680caca0831ae2cf763f730

IMO, setting min height on the modal-body will cause these issues at many places, if a specific modal-body element requires min-height, we should wrap it inside a wrapper container and add min-height to the wrapper container.

\cc: @akshaydewan @naveenbhaskar

**Comment by varshavaradarajan** [comment]
Elastic agent profile view for K8s elastic agent is screwed up. Not sure if this belongs here though.
<img width="776" alt="screen shot 2018-12-13 at 1 57 10 pm" src="https://user-images.githubusercontent.com/4715748/49970115-31b66800-fedf-11e8-8fab-08ea6bfa19d6.png">

**Comment by arvindsv** [comment]
﻿
On 18.12.0 (8203-bbeebad6c03497cf3f5bf0bcddbe13bbc08a11c8, I see this:
<img width="1439" alt="2018_12_14_17-16-08" src="https://user-images.githubusercontent.com/172235/50032833-048fb580-ffc4-11e8-8337-615a337342de.png">

The font size of the red warning div is too much.

<hr/>

Also on 18.12.0 (8203-bbeebad6c03497cf3f5bf0bcddbe13bbc08a11c8:
<img width="1439" alt="2018_12_14_17-14-40" src="https://user-images.githubusercontent.com/172235/50032838-08bbd300-ffc4-11e8-8953-9c61dd2abbef.png">

The filter history text box is not aligned.

**Comment by adityasood** [comment]
verified by @rahulpargaonkar on 18.12.0-8222
