### ISSUE TITLE
Migrate user summary page to SPA

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5539]
##### Summary

Placeholder issue to track progress on converting the user summary page to an SPA.

**Comment by naveenbhaskar** [comment]
Design for user summary page

![image](https://user-images.githubusercontent.com/1627961/49849316-fb092080-fdfe-11e8-938f-09637e3c6f31.png)

**Comment by akshaydewan** [comment]
Updated designs:
![image 2](https://user-images.githubusercontent.com/6024038/50636495-446f0a80-0f7c-11e9-84d0-f3a4ffe3dfdd.png)
![image 3](https://user-images.githubusercontent.com/6024038/50636496-4507a100-0f7c-11e9-9131-00e258d4936e.png)

**Comment by akshaydewan** [comment]
Some discussion points:
- Do we need a “Revoke Admin” similar to “Make Admin”? Previously, the admin setting was in the Roles dropdown, so it could be enabled/disabled
- Since we’re indicating GoCD Roles and Plugin Roles, should the Roles SPA also be thought out?
- We have a setting in Server Configuration which probably would be better suited to the Users page or the Authorization Config page: https://docs.gocd.org/current/configuration/dev_authentication.html#controlling-user-access
- Should we rethink how permissions are managed?

**Comment by adityasood** [comment]
The user summary page and related changes were listed and are tracked in https://github.com/gocd/gocd/issues/5564.

Closing this issue.
