### ISSUE TITLE
Support for template configuration in config-repo

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#5675]
EPIC: https://github.com/gocd/gocd/issues/5175

Currently, GoCD template feature allows to extract template from a pipeline and reuse it for other pipelines. It limits user to further expand the pipeline configuration (cannot add/edit stage/job/task).

**Proposal:** Allow user to define their own template and store it in the config-repo.
Once it is defined, user can then reuse it further with capability to add additional pipeline configuration.

**User experience:**
- Allow user to create template not in a pipeline template structure 
- Doesn’t need to have entire pipeline/stage/job configuration. It could be a simple task block.
- Allow user to define material and its properties.
- User should be able to pass in parameterized values.

For instance:

Define template configuration (mytemplate.yaml) as part of config-repo 

```
mytemplate:
  $PIPELINE:
    group: mygroup
    Materials: 
      mygit:
        git: http://example.com/mygit.git
        branch: $BRANCH
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: make
Mysecondtemplate:  #template for a task 
  - exec:
      command: make
```
Pipeline configuration:
```
pipelines:
 $ref: ./mytemplate.yaml
    name: mytemplate
    params: 
      - PIPELINE: docs-18-10
      - BRANCH: v18.10
```
Note: These changes need to be done in the plugin code. 

/cc:  @arvindsv @tomzo

**Comment by arvindsv** [comment]
@ankitsri11 and I talked. Some ideas are based on https://github.com/tomzo/gocd-yaml-config-plugin/issues/2. With templating, we can go wild and do everything. But, this is a start, at least a stake in the ground we can all talk about.

**Comment by paulbrimicombe** [comment]
My team use the Config Repos and template features of GoCD heavily. Many of our GoCD builds (~50 and counting) are basically identical so almost every pipeline uses a template. Having the pipelines in version control near the actual code is great.

The fact that the templates can't be in version control is not ideal, however (no history can't easily roll back to an earlier version, more difficult to share between instances of GoCD). There are ways around this by using the Config API but this would be a bit of a hack. Anything that can be done to allow templates to be served from a config repo would be greatly appreciated and obviously the sooner the better.

As has been said in the [config repo plugin discussion](https://github.com/tomzo/gocd-yaml-config-plugin/issues/2) and above, we could really go to town on the templating. As far as we are concerned, even something with the same functionality as the existing templates but served from a remote repository would be a vast improvement. Would this be possible as a first step towards more flexible templates?

**Comment by arvindsv** [comment]
@paulbrimicombe Thanks for sharing your thoughts!

You might be interested in: https://github.com/tomzo/gocd-yaml-config-plugin/pull/104 which is adding Jinja templating support at the plugin level.

About adding the functionality of the existing templates: @tomzo has argued against that at different times before. One of the reasons is that it's not flexible enough (only at a template level). I think putting in a little thought and implementing it in a more flexible manner is better.

**Comment by paulbrimicombe** [comment]
@arvindsv Thanks for the quick response! I've had a look at [tomzo/gocd-yaml-config-plugin#104](https://github.com/tomzo/gocd-yaml-config-plugin/pull/104) this doesn't really fulfil our requirements:

* Pipeline instance definitions should live near the actual code in various different repositories. This keeps all of the configuration associated with a project / service / deployable in one place.
* These pipeline instances come in various different "flavours" -- one flavour might build and deploy an NPM library, another might build and deploy a Maven package, another might build and deploy a Docker image to kubenetes, etc.
* Each of these pipeline "flavours" has a template that defines the required stages. Each pipeline instance then simply has a few input parameters. This is very clean as configuration and implementation are separated.
* These pipeline templates should live near our build tooling in source control since they are coupled (the stages call various deployment scripts so there is a coupling there).

The only piece we are missing from the current template feature is the ability to have them in source control rather than in the main GoCD config XML.

Adding jinja templating to the existing config plugin is probably solving a slightly different problem -- where there is partial overlap between different templates rather than where builds are completely consistent.

At present it is good that templates and instances are separate entities at it separates the concerns nicely. This PR (unless I'm misreading it) merges the template and instances into one entity.

**Comment by arvindsv** [comment]
@paulbrimicombe I see that your case is different. You want templates managed centrally, in a separate repo. The "Templates" part of this comment by @tomzo might also be interesting to you: https://github.com/gocd/gocd/issues/5175#issuecomment-422883413. It talks about a use-case similar to yours.

I wonder if a `git submodule` is applicable. Along with generic templating support. The `git submodule` will allow binding to a specific version of the templates, while the generic templating will allow flexibility. A new commit to change a template will not make existing pipelines fail.

A downside is that you'll need to go to each pipeline repo and update the submodule. Without that, you'd anyway have the avalanche that @tomzo mentions in that comment.

**Comment by tomzo** [comment]
Hi @paulbrimicombe 
Thanks for feedback. 

As you have noticed https://github.com/tomzo/gocd-yaml-config-plugin/pull/104 is basically a syntax boost to current yaml. It allows to express more pipeline elements with less code, because you can use jinja. But it does not allow to share templates, which is the major missing feature at the moment.

I think we have similar use cases that you do. I mean - we also have quite some duplication in pipelines and "flavors", common patterns, which vary between project types. But I think my perception of how to manage config-repos is a bit different than yours..

> The only piece we are missing from the current template feature is the ability to have them in source control rather than in the main GoCD config XML.

Can you tell what benefits do you see in this? You would be only swapping the current centrally managed XML templates into another centrally managed templates with a different syntax/format.

In your current solution with having multiple "flavors" implemented as GoCD XML templates, what are the the biggest problems?

You mentioned 

> no history can't easily roll back to an earlier version, more difficult to share between instances of GoCD

But just having templates in a config-repo does not solve above problems.
If you share a single repository between many servers, then what happens when one commit is breaking  config in other servers? 
The rollbacks you mention could also be tricky when template is shared between multiple config-repos.

Basically I am asking what is your vision on managing changes around templates and references to them? I think there is much more to think about that workflow, than actual templating engines and available parameters.

> * Each of these pipeline "flavours" has a template that defines the required stages. Each pipeline instance then simply has a few input parameters. This is very clean as configuration and implementation are separated.

I agree that having just a few parameters in config-repo near the code that is being built is correct. But I would think a few times if you really want to expand them at runtime in server after they were pushed, rather than expand them earlier and commit the result to the repository.
For example, you could have a git repository, shared within the company, with jinja templates common to all projects. Then a custom, relatively simple tool could be used to expand these templates to create `.gocd.yaml` files specific for each project.
The benefits of that would be
 - locking the resulting pipelines config, so that changes in template repo do not immediately affect each repository.
 - you can see and review configuration before sending it to the server.

**Comment by ibnc** [comment]
What would the JSON syntax look like?

/cc @tomzo @ankitsri11 @arvindsv

**Comment by paulbrimicombe** [comment]
First of all, thanks so much for all of these responses. It's great to be having this discussion. We think having templates in a Config repository would give us the following benefits:

* When making template changes we can branch, develop, peer review etc, and then test by pointing GoCD to the development branch. If we are unhappy with the results we can roll back by pointing back to the stable branch.
* Better visibility of what changes have been made and when -- you can just use a Git diff to see the changes. If someone goes into the UI and changes something that breaks the pipelines and then goes on holiday, it's hard to work out what's actually changed.
* We can share templates between GoCD instances.
* We can add (brief) documentation to the templates using `README.md` files or similar so that clients who create pipelines know any assumptions / conventions used.
* We have an additional backup of our GoCD templates -- we do back up our GoCD configuration in multiple places but if a bad actor manages to erase it we still have the bulk of the configuration elsewhere. Our GoCD configuration pretty much contains templates and config repositories and not much else.
* We can put build tooling and the client code (i.e. the templates) close to each other in source control.
* Probably some other stuff that I can't think of right now because I've not drunk enough coffee this morning.

We can't really do any of this with the templates in the main XML file.

I absolutely agree that it's hard to manage the dependencies between templates and pipelines which is why I would suggest keeping the interaction as simple as possible -- the current implementation is quite good in this respect in that you can have parameters and nothing else.  There is nothing to stop you adding version numbers to template names so that you can manage breaking changes correctly.

e.g. I have Pipeline `pipeline-foo` that uses Template `template-bar-v1` which requires parameters `param-1` and `param-2`. I decide that a new version of the template requires an additional parameter `param-3`. I copy `template-bar-v1` and create `template-bar-v2`. The pipelines that are using `template-bar-1` still work and will continue to work as long as you don't delete `template-bar-v1`. You can then gradually upgrade your pipelines to use `template-bar-v2`.

All of this versioning is possible with the templates in the config XML but it's more tricky to track the changes between the versions and duplicate the templates.

**Comment by arvindsv** [comment]
@ankitsri11 and I were talking about this. We're wondering whether the Jinjava template support with submodules will work (and we can close this issue). Here's what we were thinking:

Repo 1: Has template YAMLs (just JinJava-compatible templates).
Repo 2: Has pipeline YAMLs.

```
$ cd /tmp/repo1

$ ls -1
mytemplate1.tmpl

$ cd /tmp/repo2

$ ls -1
mypipeline1.gocd.yaml

$ grep template mypipeline1.gocd.yaml
{% include 'templates/mytemplate1.tmpl' %}

$ git submodule add /tmp/repo1 templates/
...

$ ls -1
mypipeline1.gocd.yaml
templates/

$ git add templates

$ git commit -m "Added templates"
```

Ignore the fact that this doesn't work currently, because GoCD doesn't seem to do a `git submodule update --init` when it creates the directory for the plugin to parse. That can be changed.

However, with this, don't we get the best of all worlds?

1. The templates repo can be maintained / controlled externally.

2. A commit to change a template will not automatically break any pipelines, since submodules are pegged to a specific revision. You can update it when you want.

3. You can continue to use GoCD's templates (in the config XML), of course.

What are we missing?

**Comment by arvindsv** [comment]
Oh, also, the `{% include ... %}` bit is not yet working, but it looks like the PR will be changed soon to make it work.

**Comment by paulbrimicombe** [comment]
Sorry for the delay. Thanks for the input @arvindsv . We generally steer well clear of git submodules because they can be confusing for people and tend to cause too many WTF moments.

Also as a solution to @tomzo's versioning concerns, the versioning is somewhat limited if you are using monorepos. You would either have to have a single submodule and all of the pipelines in the monorepo would have to be updated at once or you would need a separate submodule potentially pointing to different versions in different parts of the monorepo. This could get pretty confusing pretty quickly.

**Comment by moritz** [comment]
I know I'm a bit late to the party, but I'd like to propose an alternative.

GoCD's templates are a bit limited, for example they have no conditionals, which I could have used in a few cases already (have a template for applications that include a deployment stage, but for a library, I would like to leave out the deployment stage), templates are not evaluated everywhere (not in resources) and so on.

So, instead of relying on GoCD's fairly limited template mechanism, we could use an existing template mechanism for data structures to generate full pipelines. Examples of such data template systems include

* [jsonnet](https://jsonnet.org/)
* [cue](https://cue.googlesource.com/cue)
* [json-e](https://github.com/taskcluster/json-e)

... and I'm sure many more that I'm not aware of.

Allowing to write the user to use such a template language in a config repo would enable them to create templates that can parameterize any aspect of the configuration (for example materials, conditional stages, environments).

I plan to experiment with that by creating a pipeline that uses jsonnet files as input, and produces a config repo as the output. If I get to that soon, I'll report here on my experience.

**Comment by moritz** [comment]
I have conducted the experiment mentioned in my comment from April 21st, and I don't want to go back.

Our starting positions was a GoCD instance with around 130 to 140 pipelines, about 6k lines in the GoCD  config, and about a dozen templates.

I have started with the JSON dump of an existing pipeline, and gradually extracted [jsonnet](https://jsonnet.org/) templates. As I migrated more pipelines from the traditional XML config to the config repository,  I gradually enhanced those templates.

The result was a reduction in lines of code/config of about 53%, and the number of  templates was reduced to 3.

The main features that allowed me consolidate so many templates were:

* being able to template everything, including resources (and not just as string, as arrays)
* conditionals that allowed me to exclude tasks or even stages where not necessary, thus avoiding either dummy tasks or duplication
* the ability to use (computed) defaults meant less repetition when instantiating the templates
* with list comprehensions I was able to pass in a list of Debian distributions to build packages on, and have the template generate one job per distribution, and later in the pipeline one job per distribution that d uploads each package to the corresponding repository.

If there is more interest in this approach, I can disclose the scripts I used to translate source files into `*.gopipeline.json` files, and maybe some of the jsonnet templates.

The experiment has strengthened my believe that a generic templating system, not tied to the specific of GoCD, is very beneficially to have in the pipeline (pun intended).

**Comment by tomzo** [comment]
Hi @moritz ,
It's nice to hear back from you and that you actually went through the experiment.

Earlier you said
> I plan to experiment with that by creating a pipeline that uses jsonnet files as input, and produces a config repo as the output. 

Is this what you did to implement the 140 pipelines? 

> The experiment has strengthened my believe that a generic templating system, not tied to the specific of GoCD, is very beneficially to have in the pipeline (pun intended).

So did you put the generation step in another pipeline (one or more)? I have recently mentioned this idea a [blog post](https://kudulab.io/posts/gocd-preflight-validation), but I am not sure if you are doing this or if you added jsonnet to the plugin. Have you added pre-validation with the preflight API?

> If there is more interest in this approach, I can disclose the scripts I used to translate source files into *.gopipeline.json files, and maybe some of the jsonnet templates.

Maybe you could write about your experiments in the public wiki of the json plugin? - https://github.com/tomzo/gocd-json-config-plugin/wiki

I think that would be the right place to document your experience. People could pick it up and enhance further. I for one am very curious on what you got there.
An overview of how you did this and some examples would be great:
 - where are the templates stored?
 - when is the `json` generation happening
 - how many config repos are there and how are they related to the templates

**Comment by moritz** [comment]
You are right, I should explain the setup in more detail.

I have a repo `go-pipelines-source` that contains the templates implemented in jsonnet, as well as the source files for each template. The source file might look like this:

```
local stdpipeline = import 'standardpipeline.libsonnet';

stdpipeline.debian_packaging({
    name:       'snmp-collect-pl',
    deploy:     false,
    group:      'Perl-Packaging',
    distribution: 'stretch',
})
```
the template provides defaults that construct material URLs (like `git@gitlab.example.com:ourteam/` + name + `.git`).

In the same repo is a small script that translates the templates and source files to actual json files. As you can imagine, that runs as a go pipeline, and pushes the result to a second repository, `go-pipelines-generated`.

This second repository, `go-pipelines-generated`, is then used as a config repository in GoCD.

As for the numbers, 120 of the original 140 pipelines where replaced by files in `go-pipelines-source`, the remaining 20 remained in GoCD, because they weren't well-suited to be templated.

**Comment by moritz** [comment]
@tomzo I've tried to write up a more coherent version of the experiment [in the wiki](https://github.com/tomzo/gocd-json-config-plugin/wiki/Template-Experiment), as you suggested.

**Comment by tomzo** [comment]
@moritz that's great. Thank you!

**Comment by arvindsv** [comment]
> The experiment has strengthened my believe that a generic templating system, not tied to the specific of GoCD, is very beneficially to have in the pipeline (pun intended).

That's fair, but do you (and others) think there's benefit in having templating support within the plugin as well?

**Comment by moritz** [comment]
> That's fair, but do you (and others) think there's benefit in having templating support within the plugin as well?

That's a good question @arvindsv :-)

On the upside, it would get rid of an extra repository (for the generated files), an extra pipeline that processes the files, and the script that does the processing, and would generally be a smoother experience. I have also noticed that explaining the setup of my experiment took a few times to get right, which means there is some barrier to understanding it that a built-in template system would avoid.

On the downside, it decides the template system for everybody who uses it, thus reducing flexibility. There would also need to be extra steps to let you inspect the expanded/full pipeline.

It's the question whether batteries should be included (python approach) or if the system should be minimal and highly extensible (lisp approach).

I think I'm in favor of including it, but I totally understand why a product owner might decide against it.

**Comment by arvindsv** [comment]
> On the downside, it decides the template system for everybody who uses it, thus reducing flexibility. There would also need to be extra steps to let you inspect the expanded/full pipeline.

I see it as an addition. Having template support doesn't need to mean an external templating mechanism like the one you detailed cannot be used.

Why I'm thinking about templating is that I think it can be used to implement proper branch support, without having GoCD core be aware of it. GoCD core being aware of it causes other problems, which will cause it to take a lot of time.

I've written about it [here](https://github.com/gocd/gocd/issues/6123#issuecomment-496999147). One of the pre-requisites is a templating mechanism. I wouldn't be surprised if you all say that doing what I'm proposing there is madness. :) Or, outside of the plugin's role.

**Comment by moritz** [comment]
> I wouldn't be surprised if you all say that doing what I'm proposing there is madness. :)

Not at all, a proof of concept could be built pretty easily that uses script to fetch all the branches of a material, feed it into a template, and generate a pipeline for each branch. The only tricky part is that the material is part of the pipeline being generated from the template, so in order to extract the material, you first have to render the template. A PoC could work around that by always building a pipeline for branch "master" first, a fully-fledged solution might want to put more thought into it.

**Comment by arvindsv** [comment]
Yes, I struggled with that a bit. If we said it's a normal material, then we would have to allow something like this:

```
pipeline1:
  ...
  materials:
    mygit1:
      git: https://some.git.1
      track_branches: true
    mygit2:
      git: https://some.git.2
      track_branches: true
  ...
```

which could be a bit of a nightmare being a cross-product of the two sets of branches. So, I was considering pulling the material with track branches outside, as mentioned in that other comment: https://github.com/gocd/gocd/issues/6123#issuecomment-496999147
