### ISSUE TITLE
ETag of plugin settings changes as config-repos are parsed

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#5842]
##### Issue Type

- Bug Report

##### Summary

ETag on `go/api/admin/plugin_settings/<plugin-id>` is changing way too often. In fact it changes each time when any of the config-repos parses a commit.

How I found this and reproduction:
1. GoCD server is starting with a bunch of config-repos, so there is expected a few minutes when config-repos are parsing materials.
2. I query `curl -i -u **** -H 'Accept:application/vnd.go.cd.v1+json' 'http://go.ai-traders.com/go/api/admin/plugin_settings/cd.go.contrib.elastic-agent.openstack' ` to get current configuration of the plugin.
3. Observed that on each response the `ETag` header is different, while plugin configuration is unchanged.

##### Environment

Example response:
```
curl -i -u **** -H 'Accept:application/vnd.go.cd.v1+json' 'myserver/go/api/admin/plugin_settings/cd.go.contrib.elastic-agent.openstack' 
HTTP/1.1 200 OK
Server: nginx/1.15.6
Date: Tue, 12 Feb 2019 17:18:35 GMT
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=node0ak438u3bb3mfe186qi9z1fkn662.node0;Path=/go;Expires=Tue, 26-Feb-2019 17:18:35 GMT;Max-Age=1209600;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID=node019crqdj1745z01m7ia1kgaj66o663.node0;Path=/go;Expires=Tue, 26-Feb-2019 17:18:35 GMT;Max-Age=1209600;HttpOnly
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
ETag: W/"19d9dec6ce1452a5744b89b8053bd25c"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: a9a40727e2e04d87b7ca86134eed0ffb
X-Runtime: 0.105705
Vary: Accept-Encoding, User-Agent

{ ... plugin settings ... }
```

###### Basic environment details

* Go Version: `18.12.0` + some unrelated patches.

##### Expected Results

I would expect `Etag` of plugin settings to be a hash of plugin configuration values. 
In worst case it would be a hash of configuration values AND config-xml md5 sum. But that does not make much sense neither since settings are in db.

##### Actual Results

`Etag` in plugin settings response changes on each config-repo material update.

**Comment by prateekbaheti** [comment]
On analysis of the issue this is what I have found:

Plugin settings json string can be different for each request because secure variables value changes each time. The encrypted value differs due to usage of a new salt each time and hence generates different md5s.

Ideally we should still receive the same Etag from cache given a PluginSettings object but the cache gets invalidated on config change in 
[EntityHashingService.onConfigChange()](https://github.com/gocd/gocd/blob/e1937046b7e1d9471b20ed24f6225cb24ef98ec0/server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java#L85). 

**Possible solutions:**
* Entities stored in DB (Plugin Settings) should not get invalidated on configXML change. We can cache them under a different key prefix. That will need explicit invalidation on PluginSettings change.

* MD5 generation should consider PluginSettings json string with decrypted values so the md5 does not change each time.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8627-ceb298c65f9355943c56c588d8a0fc24d58ec285)
