### ISSUE TITLE
/etc/init.d/go-agent stop on Linux does not use PID and kills all agents run by go user with the same service name

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5858]
##### Issue Type

- Bug Report

##### Summary

If you have the following setup

1. Start an agent on a linux box using the /etc/init.d/go-agent start command. This will run as go user
2. Start a gocd docker agent as a go user.
3. Run ps -aux | grep go-agent. This should list both the agents and check they are run by the same user
4. Kill the agent using the /etc/init.d/go-agent stop command. This will kill both the agents since the killproc function does not honor PID as per [this](https://github.com/gocd/gocd/blob/71a87e5b6a923a45e9b1c0606ee9d93b59ee9205/installers/go-agent/release/go-agent.init#L39)

**Comment by aqneves** [comment]
Hi,

The fix that it's being planned won't fully fix the issue.

The problem is that /etc/init.d/go-agent considers that the pid file is on one specific location:
PID_FILE="/var/run/go-agent/${SERVICE_NAME}.pid"

But, the start_agent.sh can place it in one of two locations:
if [ "$1" == "service_mode" ] && [ -d "/var/run/go-agent" ]; then
PID_FILE="/var/run/go-agent/${SERVICE_NAME}.pid"
else
PID_FILE="$AGENT_WORK_DIR/go-agent.pid"
fi

In our scenario, the file is placed on /var/lib/go-agent/go-agent.pid which means that the stop of the agent will not work.

Regards

**Comment by ibnc** [comment]
> 1. Start an agent on a linux box using the /etc/init.d/go-agent start command. This will run as go user
> 2. Start a gocd docker agent as a go user.
> 3. Run ps -aux | grep go-agent. This should list both the agents and check they are run by the same user
> 4. Kill the agent using the /etc/init.d/go-agent stop command. This will kill both the agents since the killproc function does not honor PID as per [this](https://github.com/gocd/gocd/blob/71a87e5b6a923a45e9b1c0606ee9d93b59ee9205/installers/go-agent/release/go-agent.init#L39)

A PR to fix this issue has been merged. It should be noted for testing purposes that the steps above will not reproduce the issue if you're using one of the agent docker images we publish. If you want to reproduce this issue specifically to test the PR, then you'll need to start a docker container, and then manually install a go-agent. This will cause both process to look similar enough that the custom `killproc` function will kill both. The custom `killproc` function searched through processes to figure out what to kill: `pkill -u go -f /usr/share/${SERVICE_NAME}/agent-bootstrapper.jar`

This wasn't an issue for our docker images because the bootstrapper location in the container would look like: `/go-agent/agent-bootstrapper.jar`
whereas the locally installed agent bootstrapper would look like: `/usr/share/go-agent/agent-bootstrapper.jar`

Creating the custom docker image will have the agent in the container's bootstrapper location look the same as the locally installed agent's: `/usr/share/go-agent/agent-bootstrapper.jar`

**Comment by arvindsv** [comment]
The fix also needs to verified when using multiple agents on one machine installed as [in the docs](https://docs.gocd.org/current/advanced_usage/admin_install_multiple_agents.html) (not in Docker).

**Comment by ibnc** [comment]
> he fix also needs to verified when using multiple agents on one machine installed as [in the docs](https://docs.gocd.org/current/advanced_usage/admin_install_multiple_agents.html) (not in Docker).

@arvindsv I can confirm that this works with multiple agents running on the same machine as described in the docs

**Comment by ketan** [comment]
Tested on Ubuntu/Debian too?

**Comment by adityasood** [comment]
@ibnc @ketan I tested this fix on the ubuntu machine and found the following

1. When we start an agent by /etc/init.d/go-agent start it creates a PID file on /var/run/go-agent/${SERVICE_NAME}.pid as per [this](https://github.com/gocd/gocd/blob/master/installers/go-agent/release/agent.sh#L115). However, when we try to stop it we are using the wrong param replacement [here](https://github.com/gocd/gocd/blob/master/installers/go-agent/release/stop-agent.sh#L31). This should ideally be checking for the second param as per the call [here](https://github.com/gocd/gocd/blob/master/installers/go-agent/release/go-agent.init#L93). Currently since the if clause is not satisfied it looks for the PID file in the wrong location and errors out. 

2. In a scenario where a user starts an agent on a machine through the init service the bootstraper is at the location /usr/share/go-agent/agent-bootstrapper.jar where go-agent is the service name. If we were to start another agent in a container by installing a go-agent in it it would have the same bootstrapper location. This causes the stop-agent to be in an infinite loop because of the check_proc function [here](https://github.com/gocd/gocd/blob/master/installers/go-agent/release/go-agent.init#L51). This is also true for the start_agent where it will not allow the agent to start.

**Comment by arvindsv** [comment]
@ibnc @marques-work - Based on the issue @adityasood found and based on his suggestions, I've opened https://github.com/gocd/gocd/pull/5939 which fixes part 1 in the comment above.

It doesn't solve case 2:

1. Start an Ubuntu docker container on Linux.
2. Install a GoCD agent (from RPM, say).
3. Start it (make sure it starts as `go` user).
4. Start an agent on the host machine, outside of the docker container.
5. Make sure it runs as `go` user too.

With your changes and the one in this PR, the agent inside the docker container won't be killed if you do an `/etc/init.d/go-agent stop` on the host. However, the `check_proc` method uses `pgrep` and will see the agent inside the docker container and potentially never exit from that script.

I'm leaving towards marking it as a known issue - because this is a special case of running multiple agents on one machine, without changing the filename as mentioned in https://docs.gocd.org/current/advanced_usage/admin_install_multiple_agents.html

**Comment by ibnc** [comment]
Working on a fix for issue number 2 that @adityasood mentioned

**Comment by ibnc** [comment]
@arvindsv @adityasood I opened a PR fixing case 2 that @adityasood mentioned in their comment

https://github.com/gocd/gocd/pull/5942

**Comment by adityasood** [comment]
@ibnc this does fix the issue, however, we would have to do something similar for stop-agent and status operations. I will be raising a new issue for this and closing the original one.

**Comment by adityasood** [comment]
Verified the agent with build(19.2.0-8461)on following

1. ubuntu
2. centos6

Known cases

The functionality of the script is not compromised. However if a user

1. Tries to stop a newly installed agent which has never been started and a PID file does not exist then they will see an error

2. Tries to know the status of a newly installed agent which has never been started and a PID file does not exist then they will see an error

The above can be tracked [here](https://github.com/gocd/gocd/issues/5945)
