### ISSUE TITLE
Functional Issues with Spark based Environments API v2

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5956]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `GoCD Version: 19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68).`
* JAVA Version: `1.8`

###### Bugs:
  - [x] Secure environment variables configured for the environment are returned as `******` instead of returning `encrypted_value`. (Fixed as part of #5957)
 - [x] API should accept both `value` and `encrypted_value` in the environment variables. Details [here](https://github.com/gocd/gocd/issues/5956#issuecomment-470489060) (Fixed with https://github.com/gocd/gocd/pull/5967)

**Comment by rajiesh** [comment]
API does not accept `encrypted_value` as a key in Environments variables JSON, it always looks for `value`. So create/update request like this 
```
{
    "name": "from-api",
    "pipelines": [
        {
            "name": "pipeline-in-environment543d8f06"
        }
    ],
    "environment_variables": [
        {
            "name": "secured",
            "encrypted_value": "AES:Nla+0y+uOInW4ZVsHzLZBg==:qP+V9XpV53UvzgcieGWpKyEiP5uHudFuArTsnETozo8=",
            "secure": true
        }
    ]
}
```
will fail [here](https://github.com/gocd/gocd/blob/master/api/api-environments-v2/src/main/java/com/thoughtworks/go/apiv2/environments/representers/EnvironmentRepresenter.java#L64) with NullPointerException since there is no `value` in the request
