### ISSUE TITLE
View permission cannot be unchecked

### ISSUE THREAD

**Issue by eproxus** [gocd/gocd#6052]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

It should be possible to uncheck the View permission checkbox when configuring pipeline User and Role permissions.

###### Basic environment details

* Go Version: `19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68)`
* JAVA Version: `1.8.0_191`
* OS: `Linux 4.15.0-46-generic`
* Browser vendor and version (if relevant): `Safari 12.0.3`

##### Expected Results

The box is unchecked so that certain users and roles cannot view the pipeline.

##### Actual Results

The box is re-checked when Save is pressed.

##### Possible Fix

Make the unchecked view permission stick. It's obviously possible, since checking Operate and unchecking View hides the pipeline in the UI.

**Comment by varshavaradarajan** [comment]
@gocd/committers -

> It's obviously possible, since checking Operate and unchecking View hides the pipeline in the UI.

Why is this allowed? Is there a valid use-case for someone to schedule pipelines (via API alone) but not view the job console, pipeline configuration?  I suppose we can't change it now.

How about checking the view checkbox and disabling it if operate or admin checkbox is not checked? Conveys that the user is explicitly given view permissions. If unnecessary, the user can be removed. @naveenbhaskar - WDYT?

**Comment by eproxus** [comment]
I can also add some details about our actual use case. We use the guest login plug-in and want to hide certain jobs from the `guest` user (which is currently not possible, only by making the guest user an "operator" but not a "viewer").

**Comment by arvindsv** [comment]
@eproxus I'm not sure I understand whether this is a problem. I put together a small video to show what I see: https://www.dropbox.com/s/mf5p3rpi38ky8ar/2019_03_GH_Issue_6052_view_user_permissions.mov?dl=1

Can you:

1. Make sure that you have a GoCD system admin in the system? Make any (non-view) user an admin. Otherwise, all users are system administrators. Like this:

![2019_04_03_11-43-17](https://user-images.githubusercontent.com/172235/55492769-c9160700-5605-11e9-9087-bfb24c7d57f7.png)

2. Make sure that you have a group administrator for that group. Without that, the default permission is (or seems to be) view and operate permissions for everyone, as you can see in the video.

3. Then, don't bother about the view user. Just remove it, rather than having it and hiding it by providing the "operate" permission.

Can you check that and see if that solves the problem? I'm, somewhat preemptively, going to close this issue for now. However, I'm happy to reopen it if I haven't understood it right. Just let me know. 

Thank you!

**Comment by arvindsv** [comment]
@varshavaradarajan 

> Why is this allowed? Is there a valid use-case for someone to schedule pipelines (via API alone) but not view the job console, pipeline configuration? I suppose we can't change it now.

Could be useful for some API-only usage such as scripts, I suppose. I knew it was possible, but the reasons why that is allowed are lost in time.

> How about checking the view checkbox and disabling it if operate or admin checkbox is not checked? Conveys that the user is explicitly given view permissions. If unnecessary, the user can be removed.

As I showed in the video, you can remove the user and it works fine, as long as you have a pipeline group administrator. You can't have a user in the "Name" field and then have them have no permissions checked. That's the reason it keeps bringing the lowest-level permission back.

If we do check the view box and disable the operate or admin checkbox that would probably make sense. We'd need to enable it when the other boxes are checked. However, it doesn't significantly reduce the burden of understanding for the user. It needs a bigger change. Maybe even a message which says: "There's no group admin, so everyone can view and operate this group". It's a similar conversation to the one around user management page and "GoCD system administrator" role.

**Comment by eproxus** [comment]
@arvindsv Your "trick" works. I just noticed that by default the _User Permissions_ list is actually empty, so the correct solution is to add the `admin` user and give it admin permissions. This will "lock out" the `guest` user. Not very intuitive, but it works.

**Comment by arvindsv** [comment]
Ok! Thank you for following up and confirming this.
