### ISSUE TITLE
Title tag issue on job detail page

### ISSUE THREAD

**Issue by BenWolstencroft** [gocd/gocd#6064]
#### Issue Type
- Bug Report

#### Summary
Minor UI issue - on the job detail page, the page title tag is not rendered correctly in the DOM, instead of being in a &lt;title> tag in the &lt;head>, it's in a &lt;pre> tag at the bottom of the page

##### Basic environment details

* Go Version: 19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68)
* JAVA Version: 1.8.0_171
* OS: Linux 3.16.0-7-amd64
* Browser vendor and version (if relevant): Chrome

#### Steps to Reproduce

1. Visit any job detail page e.g. /go/tab/build/detail/&lt;pipeline>/&lt;instance>/&lt;stage>/&lt;counter>/&lt;job>

#### Expected Results
Title tag correctly rendered by browser

#### Actual Results
Title tag rendered in a tag below the footer of the page.

#### Code snippets/Screenshots

![gocd-bug](https://user-images.githubusercontent.com/12066104/55471570-f2349880-5601-11e9-8f81-2f7912c76f6d.PNG)

**Comment by adityasood** [comment]
@BenWolstencroft can you try this out in incognito mode ensuring no extensions are enabled? We currently suspect this could be caused by some chrome extensions. For e.g Screenshot1 is without a JSON viewer extension in chrome and I do not see the title tag rendered. Whereas Screenshot2 is with the JSON viewer extension, and I can see the title tag below the footer of the page

### Screenshot1
<img width="1438" alt="screenshot1" src="https://user-images.githubusercontent.com/17826464/55774198-ce65cc80-5ab1-11e9-8e8c-9f21d5b9ef56.png">


### Screenshot2
<img width="1440" alt="screenshot2" src="https://user-images.githubusercontent.com/17826464/55774161-ad04e080-5ab1-11e9-9559-af2716dd74f2.png">

**Comment by BenWolstencroft** [comment]
Can confirm your results!, guess the issue lies with the extension then, not GoCD!

**Comment by BenWolstencroft** [comment]
@adityasood 
Just had a quick cursory search through the source code in this repo and spotted this in
https://github.com/gocd/gocd/blob/3b679bc498e0af3d84204bca0c81a156930b5431/server/webapp/WEB-INF/vm/shared/_header.vm
Line 44-46
```
    #foreach( $css in ${webpackAssetsService.getCSSAssetPathsFor("single_page_apps/header_footer_shim")})
      <link rel="stylesheet" type="text/css" href="${css}"
    #end
```
is this where the missing /> are?

```
    #foreach( $css in ${webpackAssetsService.getCSSAssetPathsFor("single_page_apps/header_footer_shim")})
      <link rel="stylesheet" type="text/css" href="${css}" />
    #end
```

**Comment by adityasood** [comment]
verified on 19.3.0 (8897)
