### ISSUE TITLE
GoCD Server Full Observer role

### ISSUE THREAD

**Issue by agerro** [gocd/gocd#6089]
##### Issue Type

- Feature proposal
- Feature enhancement

##### Summary

It would be nice to have a role definition in GoCD to make it possible to have a GoCD Server (Admin) Observer role for entire server. (Similar to the scope that an GoCD admin has, but only READ permissions.)

**Comment by arvindsv** [comment]
@agerro This seems to be a subset of [Granular Auth](https://github.com/gocd/gocd/issues/4735#issuecomment-466217517), which is being talked about and will probably be worked on soon, after the current secrets management work.

So, I'll close this issue for now, till we pick this up. I've labeled it, so that we don't lose this point of view. Thank you!

PS: Closing it doesn't mean I disagree! :)

**Comment by agerro** [comment]
Sounds great 😊
