### ISSUE TITLE
Show config repo id in the hover message when settings is disabled

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#6125]
##### Issue Type

- Feature enhancement

##### Summary

When a pipeline configuration cannot be seen because the pipeline is defined in a config-repo, the settings icon on dashboard, vsm etc is disabled with the message `Cannot edit pipeline defined in config repository`. It will be useful to show which config-repo has the definition to go to the repo and view/edit the pipeline configuration.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- related issue: https://github.com/gocd/gocd/issues/4403

**Comment by kritika-singh3** [comment]
We are planning to provide a `read-only` view for the pipelines defined in config-repos. We have already linked the pipelines created from the config repo SPA (#6360 ). This issue will be revisited as a part of Pipeline Config UX Refresh.

**Comment by arvindsv** [comment]
If the information is available, I'd love to see it too (and maybe the URL). Currently, it leaves me very confused about where a pipeline is defined. Even if we provide a read-only view, users without permission in GoCD to see it might appreciate knowing where it is in a config repo?

**Comment by maheshp** [comment]
> If the information is available, I'd love to see it too (and maybe the URL). Currently, it leaves me very confused about where a pipeline is defined.

We discussed bout it, I thought just showing the the config_repo id would be a temporary fix as we are planning to add a read-only view for the config. The view can have the details of the config_repo and a link to the config repo page. I understand today it is hard to figure out the source of the pipeline, having the repo id(probably the url) would help. Guess, we an add this information for now till we have the read-only view.

> Even if we provide a read-only view, users without permission in GoCD to see it might appreciate knowing where it is in a config repo?

Are you suggesting we show this info for PipelineGroup Admins or users who have read-only permissions for a pipeline.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan  @arvindsv @maheshp @kritika-singh3 @viraj2712 -- 

I feel the pipeline setting gear icon on-hover message might not be the best place to show the config repo related information, as:
1. To check whether a pipeline is defined in a config repository or not, a user needs to hover on the pipeline settings gear icon and read the message (as the settings icon might be disabled due to permission issue).
2. When a user is a non-admin user and a pipeline is defined in config repo, either the `user does not permissions` or `pipeline defined in config repo` message will show up. Not Both. (I know we can fix the message to show both but might cause a lot of text in small hover window)
3. I feel the pipeline settings icon should only show configuration related information. Whereas, Config Repo Id is the pipeline config definition (source) information.

_Alternative_:
A visual indication on the pipeline box denoting the pipeline configuration is defined in config repo. How about an icon for config repos? 
This would cause pipeline(s) defined in config repo easily identifiable without requiring the user to do clicks/hover.
Any additional information (config-repo-id), links (link to config repo SPA) can be given on this new visual indication(config-repo-icon)
Also, Provides separation between pipeline-configurations (pipeline-settings) and pipeline-definition (definition of pipeline in config repository)

**Comment by varshavaradarajan** [comment]
@GaneshSPatil - 
As Duck said, I want to be able to get to the config repo to edit the pipeline config without much hassle. Like having to go to the config repo spa, searching for that pipeline, then finding config repo id and url etc. 

Will this new icon tell me which config repo to go to to edit the pipeline config? If so, how? I don't think it should link to the config repo SPA for that and make people go there to find the id and url. It's an additional interaction that we could do without, imo But, yes, if the config repo url can't be shown nicely, then, this new icon linking to the specific config repo on the SPA might be good. Ideally, would want the url as well from the dashboard, to go to the repository. 

I don't know if that authorization on entities is still on the cards. If yes, this might get complicated. But, I don't think we should be so strict about it to not show non admins the url. If someone is that concerned about it, they can have a private repo to restrict access. Anyway, not especially related to this issue. Just FYI. 

The second concern is that the pipeline box might look very crowded. But, um, better someone else's opinion than mine. I agree that on hover of settings icon may not be the best place. 

On a side note, I also think it might be good to provide an easy way to filter pipelines defined in config repos or not defined in config repos in the personalized views. WDYT? We can create a separate issue for that if we want to do this.

**Comment by rajiesh** [comment]
IMO tool tip is not the right place to show the info. Looking at this PR - https://github.com/gocd/gocd/pull/6602 - which I believe is the first cut of this feature implementation have some concerns. SCM server domain name may be lengthy(not necessarily as short as `github.com`), Just the URL may not be sufficient to locate, branch/view/project path will also be needed to locate the pipeline definition file in the repo. Squeezing that info into the tool tip makes it more crowded(defeats the purpose of tool "tip" itself :) )

So as mentioned by @maheshp if this is a temporary solution before we have a read-only view, not sure what is the purpose of take this on priority over the read-only view. If its because read-only view is going to take time, I think we have had this problem from beginning of config repo feature

cc @maheshp @arvindsv

**Comment by GaneshSPatil** [comment]
@varshavaradarajan 

> Will this new icon tell me which config repo to go to to edit the pipeline config? If so, how? I don't think it should link to the config repo SPA for that and make people go there to find the id and url. 

True. Currently, GoCD pages does not have the ability to link to a particular entity on the SPA. It would be nice if the URLs could link to the entities. (Dashboard Pipeline link)

Also, Not sure if the config repo URL specified by the user can be shown. As @rajiesh  mentioned, the URL has multiple parts, the URL itself, branch, and the credentials. A user needs to know all 3 to navigate to the config-repo material.

> The second concern is that the pipeline box might look very crowded. 

+1. We thought of this problem while designing the Dashboard SPA. We were wondering if we could place all the icons together in an additional row. @naveenbhaskar  would know the best!

> On a side note, I also think it might be good to provide an easy way to filter pipelines defined in config repos or not defined in config repos in the personalized views. WDYT? We can create a separate issue for that if we want to do this.

Hmm, I think this has already been discussed on PR: https://github.com/gocd/gocd/pull/6360

https://github.com/gocd/gocd/pull/6360#issuecomment-505285935
https://github.com/gocd/gocd/pull/6360#issuecomment-505679657
https://github.com/gocd/gocd/pull/6360#issuecomment-505821949

**Comment by marques-work** [comment]
@varshavaradarajan @arvindsv @maheshp @kritika-singh3 @viraj2712

I like the idea of having a different icon to differentiate pipelines defined in config repos, be it a different icon or some other visual treatment. @varshavaradarajan's filter option would also be a welcome change IMO.

> The second concern is that the pipeline box might look very crowded.

It shouldn't be any more crowded then they currently are right? I would think the config repo icon would replace the cog icon on local pipelines, rather than be in addition to. Am I missing something?

I don't think showing the URL on hover in a tooltip is the right answer either. I imagine there are usability concerns, and the URL may not be human-friendly or meaningful (e.g., could be just an IP address, or a long, ugly URL that's hard to read). Tooltip info could show something helpful (config repo id or [description (in the works)](https://github.com/gocd/gocd/issues/6578), but shouldn't be the only means to communicate essential info.

> It would be nice if the URLs could link to the entities

I think that is the best option (of course, the capability is yet to be implemented). Aside from private URLs with credentials and all, we **can't even guarantee that the URLs are servable over HTTP**. For instance, the repo could be a `file://` protocol (or relative FS path) or some other non-HTTP proto, so linking directly to the SCM repository won't work in every case. Linking to a particular config repo entity will, however.

**Comment by arvindsv** [comment]
I'm seeing it as: "Is it better than what we have now?" and for something like #6602, my answer is "Yes. It's better". If we get a read-only view, we can always remove it. I understand that a tool-tip is not ideal, but without deeper thought, it improves on the current experience by a _lot_.

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10357-44d61cc733a94287979f1fb99583d69139f386e4)
