### ISSUE TITLE
Elastic agents profile API v1 expects cluster_profile_id when user upgrade to 19.3

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6127]
##### Issue Type

- Bug Report

##### Summary

**Setup**:

GoCD server 19.2.0 with any Elastic agent plugin setup and elastic agent profile created and used.

CRUD operations on Elastic agent profile works fine with v1 of the elastic agent profile API

**Scenario**:

Upgrade GoCD server to 19.3.0

If user try to create elastic agent profile with v1 of the API, it fails. API expects `cluster_profile_id` to be provided. Error message `No Cluster Profile exists with the specified cluster_profile_id 'null'`

**Expected**:

v1 of API should still continue to work without cluster_profile_id. To overcome this issue user will have to add `cluster_profile_id` with the value of no-op cluster profile created by the server

Also its breaking an API without any warning

**Comment by rajiesh** [comment]
@GaneshSPatil @arvindsv It was discussed previously. However did not think that breaking this v1 of API is right, so raised this issue. Feel free to close it with comments

**Comment by arvindsv** [comment]
> To overcome this issue user will have to add cluster_profile_id with the value of no-op cluster profile created by the server

If they need to do that, they might as well use v2, right?

If it is going to be truly backwards compatible, it should continue with no change in the body (and implementation changes to automatically include an appropriate cluster ID).

However, after a discussion, it seems like the decision was to break it intentionally, because there is no good default cluster ID to use.

Assuming my understanding is right, I'm going to close this issue.

**Comment by maheshp** [comment]
V1 of profiles would be unusable or give partial information from 19.3. Why not just remove it, since we v2 now.

**Comment by arvindsv** [comment]
@maheshp Yes, that's what was decided. It's a little abrupt and is different from what we usually do. But, we need to.

**Comment by maheshp** [comment]
\\cc @GaneshSPatil
