### ISSUE TITLE
ability to specify pause behaviour for a pipeline created through the pipeline config API

### ISSUE THREAD

**Issue by aqneves** [gocd/gocd#6287]
##### Issue Type

- Feature enhancement

##### Summary

I would be nice to be able to specify in the pipeline config api if a newly created pipeline should be paused by default or not. Currently, when we create a pipeline through the User Interface, due to the fact we can't specify for example multiple materials in the wizard, it's created paused by default, but when using the API (same goes for pipeline as code through config repository) it's created unpaused by default and it runs as soon as it's created.

There might be scenarios where a customer on-boarding is being prepared and although we are preparing the pipelines for this customer, we want to control from when it can actually be executed.

##### Environment

https://api.gocd.org/19.2.0/#create-a-pipeline

###### Basic environment details

GoCD 19.2

##### Steps to Reproduce

1. prepare a new pipeline creation file for a pipeline with a name that was never used before 
2. call the GoCD API to create that pipeline
3. verify that it runs automatically upon creation

**Comment by arvindsv** [comment]
This was brought up in https://github.com/tomzo/gocd-yaml-config-plugin/issues/64 too.

**Comment by msaurabh1978** [comment]
###  Design Considerations

The preference `Pause or do-not-pause` at the time of pipeline creation through API is not a pipeline configuration detail - it is more of metadata about the pipeline, hence this preference is not going to be added to the create pipeline config request payload (body). 

Other ways we have considered to support this preference is using

- Path Parameter
- Query Parameter or
- Request Header

***Path Parameters*** primarily contributes to uniquely identifying a resource (or a sub-resource) on the server. Something like,

/issues/**{issueId}**/comments/**{commentId}**

Since the preference `Pause or do-not-pause` does not constitute unique resource information, we are not considering the path parameter to support this preference. 

***Query Parameters*** are used mainly for filtering (narrowing down) the resource related details. Things like *searching based on filter criteria*, *pagination*, etc. Since the preference `Pause or do-not-pause` doesn't fit into this description, we are not considering *Query Parameters* for this.

***Standard Request Headers*** are used for exchanging crossing cutting concerns that are applicable across resources, things like *Authorisation*, *Content-negotiation*, and ***custom request headers*** are used for specifying *meta-data* about the resource (e.g state information). 

Considering all of the above, using *custom request headers* looks the most suitable option for `Pause or do-not-pause` preference,  hence we are adding a custom (and optional) `X-pause-pipeline-after-create` request header to specify the preference in the create pipeline config API. Any value other than ***true*** is considered as `do-not-pause` preference.

**Comment by msaurabh1978** [comment]
### Conclusive summary

Based on the discussions so far, below is the consolidated conclusive details regarding how we want to support pause/no-pause configuration as part of pipeline config API on creating the pipeline.

- This support is going to be added in version v8 of pipeline config API

- A header `X-pause-pipeline-after-create` would be added to specify whether the pipeline should be paused on create or not. Only valid value to pause pipeline on create is `true`, any other value (or no value) is considered as `false`.

- A header `X-pause-cause` would be added to specify the reason for pausing the pipeline on creation. This value would be honored only when the above header value is true.

- API doc would be modified to include these details

**Comment by msaurabh1978** [comment]
The changes mentioned in the above consolidated summary are complete and ready for review and merge,

#### Details of PR is

API doc changes are incorporated as part of https://github.com/gocd/api.go.cd/pull/325

Pipeline config v8 API changes are incorporated as part of  https://github.com/gocd/gocd/pull/6395

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9478-5f827efbc8001e16417fe13503f5e240d7ed060d)
