### ISSUE TITLE
[UI issue] Pipeline Analytics

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#6316]
##### Issue Type

- Bug Report

##### Summary
Does not show the last metric properly while displaying all the metrics.

<img width="778" alt="Screen Shot 2019-05-21 at 9 34 05 AM" src="https://user-images.githubusercontent.com/4715748/58113976-9b801f80-7bab-11e9-94da-3e6c3ae84f1e.png">

###### Basic environment details

* Go Version: `19.4.0 (9113-1e344e8848ceda4ce67cc202813cdb4f95698e45)`
* Browser vendor and version (if relevant): `Chrome: 74.0.3729.157, Firefox: 67.0`

##### Steps to Reproduce

1. Login to build.go.cd as admin
2. Go to the Analytics page
3. Select Pipeline Level Analytics

##### Expected Results

Show all the metrics in the header before the graph.

##### Actual Results

Does not show the last metric properly.

**Comment by GaneshSPatil** [comment]
\cc - @naveenbhaskar @marques-work 

I think this is because we're showing the chart in half width of the page. i.e (1366/2 = **683**) px

Whereas, when the same chart is rendered in the modal (on dashboard pipeline), it is rendered in width **846** px

Ideally, all the charts (rendered by the plugin) should be responsive enough to be rendered in any width. 

---

An easy enough fix would be to render the pipeline chart in full width, instead of half of the page. As the other half of the page is unused.

**Comment by naveenbhaskar** [comment]
There is no enough width to accommodate those values. There is a white-space:nowrap property which makes the values "no-wrap" which blocks from taking the available space. but if it wraps, the height of the container increases and will block the content below , as its in position:absolute.
either , we need to increase the width or position it based on the height of the grey-box matrix container.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd-private/gocd-analytics-plugin/pull/211 (Note: This PR links to a private repository and might not be visible to everyone!)
