### ISSUE TITLE
[EPIC] PipelineConfig SPA

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#6362]
##### Issue Type

- Feature enhancement

##### Summary

Introduce a PipelineConfig SPA to replace the existing rails pages to configure a Pipeline.

The SPA should solve the issues listed in the earlier attempt to [re-write](https://github.com/gocd/gocd/issues/1404) and also with a better UX.

**Comment by akshaydewan** [comment]
Adding some things that were previously discussed:

(This was previously shared in a google doc)
Rethinking quick edit … again:

### Considerations:
- Show only the bare minimum and most important parts. Most options are hidden by default.
- Exec tasks are most important and should be default.
- Should show the first stage, first job by default (maybe only if it’s a single-stage, single-job pipeline?)
- Errors should show somewhere (at the top and inline).
- Needs to support too many stages (scrolls to the right and left using those arrows)
- Needs to support too many jobs (need to figure it out - box grows?).
- Needs to support too many tasks (page grows).
- Needs to support too many materials (box grows).
- No accordions, if possible.

- Haven’t figured out interaction when those edit icons / add buttons are clicked. - Modal or a separate SPA “page” from which they can press Back. I see those pages as normal scrolling settings pages, as in Chrome or Firefox. Nothing fancy with tabs and all.
- If edit (task, material, etc) is possible inline, it should. If not, similar interaction to above.
Didn’t want to use too many icons, if possible.

Try to: Use this for template edit as well, by removing the “Materials” section and making some other very small changes.
Try to: Use this for config-repo-pipeline view as well. View-only mode is needed anyway, since we also have a template view.

Link to latest image: [pipeline_config_edit.png](https://gist.githubusercontent.com/arvindsv/ce86b93c580da28bd15fe05229ba5ec3/raw/f6995230095d3f6d2e5fb5488a430e3a425fe0da/pipeline_config_edit.png)


Thoughts from Ganesh: (2019-01-22)

- We are showing minimum required information on the screen. How easy it is for a user to locate the hidden information? Is it just one click away or multiple clicks?
- Does our design change for the inline-template view? As we need to explicitly say that the stage configurations come from the template.
- Template views are read-only. How to show the other hidden information? Still on settings icons? or some other icon?
- Config repo - everything is readonly.
- How about another tab to programmatically editing pipeline? May be JSON we pick by default (as our typescript models will be mapped to json). So i can edit the json can hit save. Will show read only json/yaml for config repo plugins.
- Inline creation of reference entities. Inline creation of package-repos, elastic-profiles, etc. may be we show a dropdown with available options and last option in that dropdown list is `define new`?

**Comment by akshaydewan** [comment]
Another option - We have the trial experience pipeline creation flow that exposes a minimal set of configuration options. Perhaps that can be expanded on and made into a full featured Pipeline Config UI.

**Comment by maheshp** [comment]
> Another option - We have the trial experience pipeline creation flow that exposes a minimal set of configuration options. Perhaps that can be expanded on and made into a full featured Pipeline Config UI.

I was talking to @arvindsv on similar lines. My point was, we should not have two completely different looking UI/UX for pipeline creation and edit. While we make it easier for creating pipeline when getting started we need to maintain some consistency between create and edit flow. \\cc  @marques-work

**Comment by akshaydewan** [comment]
Here are screenshots of the two layouts we're considering. There may be few changes to the layout as we proceed and there will definitely be a lot of changes to finer details as we iterate further. Feedback is most welcome.

![Screenshot_2019-08-07 temp Changed](https://user-images.githubusercontent.com/6024038/62601055-1e448b00-b90e-11e9-8c81-83c225e49865.png)

☝️ The user has to click on a stage to reveal its jobs and tasks below. Jobs are listed on the left side. Settings at the pipeline/stage/job level will open in modals (wherever there's a "gear" icon)

-------------------


![Screenshot_2019-08-07 Stages With Many Jobs](https://user-images.githubusercontent.com/6024038/62600624-f6a0f300-b90c-11e9-9a7b-d98b856a2826.png)

☝️ Each "box" is a stage which contains jobs. The user needs to drill down to open tasks and other settings, all of which will open in a modal.

**Comment by ketan** [comment]
I prefer the second option above. It provides a high level view of the entire pipeline in one go, and users can get anywhere in a click or two.

The first option, OTOH, provides no such view, and users would be expected to fumble, click around to get context of the pipeline and what they need to edit in order to do what they are expected to do.

**Comment by kritika-singh3** [comment]
I agree with @ketan. But a small query, where will the user access the stage level settings in the second option though? Those panels look like collapsible ones with no space for a settings icon.

**Comment by arvindsv** [comment]
I think here?

![image](https://user-images.githubusercontent.com/172235/62604126-fd336880-b914-11e9-90e1-fec37890f2ff.png)

Don't think it's collapsible.

**Comment by akshaydewan** [comment]
Yes, that's right. Clicking on it opens a dropdown menu. We might replace it with a gear icon that directly goes to the modal.

**Comment by viraj2712** [comment]
There will be some more changes in both mockups to fine-tune and make it more consistent (such as using the same action icons for each entity) and might be alignment changes as well.

**Comment by akshaydewan** [comment]
As per the design, the settings for Pipelines, Stages, Jobs, Tasks will open in modals. 

By default, modals close when:
- a user clicks outside the modal
- the Esc key is pressed
- the 'X' button is clicked
- The Cancel button (if present) is clicked

A user may accidentally close a modal after making several changes. To prevent this, should we configure these specific modals to close only when:
- the 'X' button is clicked
- The Cancel button (if present) is clicked
?

**Comment by arvindsv** [comment]
Another way I've seen it handled is to confirm, if they've made a change and they click Cancel (or press Esc), without a save.

**Comment by akshaydewan** [comment]
> Another way I've seen it handled is to confirm, if they've made a change and they click Cancel (or press Esc), without a save.

It would mean a modal opening from a modal. I'm still open to trying it.

**Comment by arvindsv** [comment]
Umm. Yeah. Maybe a question for @streisguth ?

**Comment by mehmetcavus** [comment]
> I prefer the second option above. It provides a high level view of the entire pipeline in one go, and users can get anywhere in a click or two.
> 
> The first option, OTOH, provides no such view, and users would be expected to fumble, click around to get context of the pipeline and what they need to edit in order to do what they are expected to do.

Agree with a comment:
In the second option, how about adding line wrap for list of stages and let user toggle by a preference: _horizontal scroll_ vs _line wrap for vertical scroll_? In the screenshot, it provides a high level view of the entire pipeline in one go if number of stages exist is <= 5 for example or maybe browser window is wide enough to show all stages like 10 to 20.

Toggle icon can be placed to top-right of stages header section.

**Comment by adityasood** [comment]
@mehmetcavus We are still going through different options and we will consider everything. It might help to talk to you once we churn out some of these options over the next couple of weeks, if you have a little time — and get some of your thoughts about this first-hand. Would you be interested?

**Comment by mehmetcavus** [comment]
> @mehmetcavus We are still going through different options and we will consider everything. It might help to talk to you once we churn out some of these options over the next couple of weeks, if you have a little time — and get some of your thoughts about this first-hand. Would you be interested?

@adityasood sure thing.
