### ISSUE TITLE
Pipeline definitions are also read from config repos' git submodules

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#6390]
##### Issue Type

- Bug Report

##### Summary

When configuring a git config repo, pipeline definitions are also read from any submodules configured in that git repo.

###### Basic environment details

* Go Version: `19.4.0`
* JAVA Version: `8`
* OS: `Linux / Debian 9`

##### Steps to Reproduce

1. Set `GoCD YAML files global pattern` to `*.gocd.yml,*/*.gocd.yml`
1. Create repo `mylib` containing a pipeline definition: `pipeline.gocd.yml`
1. Create repo `myapp`, add `mylib` as a git submodule
1. Add both `myapp` and `mylib` repos as config repos in GoCD

##### Expected Results

GoCD reads the pipeline definition from the `mylib` config repo. It does not try to read the pipeline definitions from `mylib` via the submodule in`myapp`.

##### Actual Results

GoCD finds `mylib`'s pipeline definition both via the `mylib` config repo and via the submodule in `myapp`, resulting in a config merge error.

##### Possible Fix

Exclude pipeline definitions in git submodules.

##### Any other info

It is unintuitive and potentially dangerous that pipeline definitions in git submodules are imported, since usually those submodules are already being built directly (resulting in the error above) or are 3rd party dependencies that should/must not be built on our CI systems.

It is possible to circumvent this by setting individual `GoCD YAML files pattern`s for each config repo. We often have pipeline definitions that are in directories and not directly in the root folder of each repo, so we have to include subdirectories for most repositories. Since we deal with hundreds of pipelines and config repos, it would be a manual and error-prone process to configure individual patterns for each repo.

**Comment by arvindsv** [comment]
This should probably be opened in the plugin's repo (https://github.com/tomzo/gocd-yaml-config-plugin) rather than here.

My personal preference is that this behavior is not changed. A submodule should not be treated specially, since it is not special from a git perspective. It's just that a part of the repo is defined elsewhere. There are [potentially valid scenarios](https://github.com/gocd/gocd/issues/5675#issuecomment-461620811) where submodules can be useful.

However, this is a question/decision for @tomzo and the plugin. GoCD core wouldn't really care - as long as the pipelines found are valid.

**Comment by tomzo** [comment]
> There are potentially valid scenarios where submodules can be useful.

There are users like @dziemba who wish to not have git modules scanned and other users who want the opposite because of templates or alike use cases. So maybe there is some way make into a user option. I  have only one idea right now how that could be implemented - On GoCD core side, config-repo definition could have `checkoutSubmodules` option:
```xml
<config-repo pluginId="json.config.plugin" id="repo1">
    <git url="git://127.0.0.1/precommit.git" branch="1.3branch" checkoutSubmodules="false" />
</config-repo>
```
By default it would be true, to keep current behavior.

> It is possible to circumvent this by setting individual GoCD YAML files patterns for each config repo. We often have pipeline definitions that are in directories and not directly in the root folder of each repo, so we have to include subdirectories for most repositories

@dziemba I could recommend you a workaround, which does not require to change GoCD. I have some repositories like that, but we keep a pattern of putting all gocd files into `./gocd` folder of each repository. If you would adopt such practice then you could set the yaml pattern to `gocd/*.gocd.yml` at the **plugin level**, once for all repositories.

> Since we deal with hundreds of pipelines and config repos, it would be a manual and error-prone process to configure individual patterns for each repo.

Then, you could write a script which would
1. Clone each repo
2. Detect all `*.gocd.yml` files which are not in `./gocd` and move  config files to it.
3. Commit and push

**Comment by dziemba** [comment]
Thanks for the quick replies!

The `checkoutSubmodules` flag makes a lot of sense to me, we'd love to see that implemented like that.

I have considered the workaround you proposed and we would most likely implement that if necessary. We do have a bunch of monorepo-like repos that have multiple components in them, each in a single subdirectory. So there is `component-foo/...` and `component-bar/...` etc., where each component has all required files including the pipeline definitions in its own subdirectory. Moving the pipeline definitions out of that into a shared toplevel directory would be possible, but not very nice.

**Comment by arvindsv** [comment]
@tomzo What would happen if there's also a material with the same details?

```
<config-repo pluginId="json.config.plugin" id="repo1">
    <git url="git://127.0.0.1/precommit.git" branch="1.3branch" checkoutSubmodules="false" />
</config-repo>

...

<pipeline>
  <materials>
    <git url="git://127.0.0.1/precommit.git" branch="1.3branch" />
  </materials>
</pipeline>
```

I hope it won't be another flag like `autoUpdate` which needs to be consistent across the config, since it causes a lot of confusion. If it's only at the config repo level, I can understand. Though I still think the right way to handle it is using file patterns. That's why they're there.

**Comment by tomzo** [comment]
> What would happen if there's also a material with the same details?
> [..consistent across the config]

You're right. If both are treated as the same material (the fingerprint is the same) then server would have to checkout and cleanup submodules in subsequent material updates.
Having a different fingerprint would not be ideal neither.

> Though I still think the right way to handle it is using file patterns. 

I agree with that. I just wanted to think on an alternative.

**Comment by mcico** [comment]
We had a similar situation. Some projects are shared as git submodules and we agreed that those which provie such a way to share code *must* use a different file name pattern. We deliberately picked a different name pattern and not the location so that the files can be put wherever necessary. This worked out pretty well, but we only have a few repositories are reference as git submodules.

Where I see the benefit of this approach is, that the owners of the sub modules have to deal with this specific configuration and *not* the repositories referencing the submodules.

**Comment by dziemba** [comment]
Okay, I guess we'll have to configure the file patterns properly then. I see why this would be difficult to implement correctly without creating other surprises for different use cases. Thanks for your help!
