### ISSUE TITLE
PaC - toggle between diagrams and config

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6436]
> Migrated from [Trello Card 121](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;oKWGNx1r)

**Comment by arvindsv** [comment]
Context: Since there is the existing create pipeline page (without PaC) and now this create pipeline page (with PaC), how do we show them both?

Option 1: Since the new page uses the right-half of the page to show the PaC, and the old page uses the right-half of the page to show the diagrams, we could have a toggle to switch between the two views.

Pros:
  - Single page, user doesn't need to choose.

Cons:
  - Maybe PaC is not discoverable. Defeats the whole purpose of this work then.

<hr>

Option 2: Use a drop-down on the "Add Pipeline" button, which switches between the pages.

Pros:
  - Two separate pages. It's clear what the user is going to do.

Cons:
  - Two separate pages.

<hr>

As of Sep 9, 2019: We are working with Option 2 for now.
