### ISSUE TITLE
Spike - PaC infer a repo-id based on the material config and/or detected pipeline definitions files.

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6456]
> Migrated from [Trello Card 123](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;4BHqMq4w)

The business case for this spike is so that we can generate a sensible config repo repo-id from the material (and any other info we have at this point) so that we can streamline/automate the creation of the "link" from the user's repo to GoCD.

**Comment by kierarad** [comment]
Results:
Creating a sensible config repo repo-id will likely get ugly once we account for making sure it's unique (we were looking toward url + branch)
Since the value of the config repo repo-id for the user identify repos, this could be done by way of an optional description as done with secrets config and plugin profiles.

Therefore, I would suggest continue with adding an optional description field to the config repo config and then generating a UUID for the config repo id.
