### ISSUE TITLE
Running direct shell command without bash fails

### ISSUE THREAD

**Issue by manojtr** [gocd/gocd#6594]
##### Issue Type
- Bug Report

##### Summary
```
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="/usr/bin/true">
                <runif status="passed" />
              </exec>
              <exec command="/bin/echo">
                <arg>$?</arg>
                <arg>&gt;</arg>
                <arg>stage_exit_status.txt</arg>
                <runif status="any" />
              </exec>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>cat stage_exit_status.txt</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <artifacts>
              <artifact src="stage_exit_status.txt" dest="stage_exit_status.txt" />
            </artifacts>
          </job>
        </jobs>
      </stage>
```

###### Basic environment details
Go Version: 16.12
Java Version: 1.8 open jdk
OS: CentOS
Browser: Chrome

##### Steps to Reproduce

1. Put the above stage in a pipeline
2. Run it and see if it fails

##### Expected Results

It should create an artefact file called `stage_exit_status.txt` with the content as `0`

##### Actual Results

The echo command succeeded but the `cat stage_exit_status.txt` failed with a message `cat: stage_exit_status.txt: No such file or directory`

**Comment by ketan** [comment]
This is as designed. GoCD uses the java [`exec`](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#exec(java.lang.String[],%20java.lang.String[],%20java.io.File)) API to run each task.

If you're looking to write a shell script, please commit a shell script into source control and execute that. Alternatively, you may be able to execute each command by wrapping them using `bash -c` like you did in your last task. Please note that running `bash -c "export FOO=bar"` and `bash -c "echo $FOO"` in different tasks will not work as expected, because they run in different processes.
