### ISSUE TITLE
Ability to enable server logging from dashboard

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#6664]
##### Issue Type

- Feature proposal

##### Summary

Currently, to enable server logging, user needs to add a logback-include.xml file onto the server. More info about logging can be found [here](https://docs.gocd.org/current/advanced_usage/logging.html). 
Having a toggle or an entry under "server configuration" would ease this process. With this user can enable/disable debug, web-request, etc from the UI itself.  

![Screenshot 2019-07-23 at 12 46 18](https://user-images.githubusercontent.com/6838313/61742418-ee12bf00-ad47-11e9-8adf-9707dce365dd.png)

**Comment by arvindsv** [comment]
I think it'll be easier to implement if the state is not persisted across restarts. Something to consider.

**Comment by GaneshSPatil** [comment]
@arvindsv -- 
> I think it'll be easier to implement if the state is not persisted across restarts. Something to consider.

I agree with you from the implementation perspective. 
Just a question, What happens in a scenario where we want to get the debug logs from the server during server startup?
Even after implementing this feature (without configuration persistence), we won't be able to get the debug logs from the server during the time window of server-startup and changing-these-configuration-fields.

I would prefer to persist these configurations, as we might need the debug logs during server startup in the following cases:
- Dashboard Cache Issue
- Postgres Addon Issue (Generally happens due to different jar, DB migration failures)
- Server startup Issues.
