### ISSUE TITLE
Ability to compress / extract artifacts

### ISSUE THREAD

**Issue by mehmetcavus** [gocd/gocd#6874]
##### Issue Type

- Feature proposal

##### Summary

Fetching artifacts and opening task details page takes too long (even for local environment) compared to tar / untar for publish / fetch artifact. To shorten this time and improve duration for file transfer between server agents, depending on user preference:

- Add compress ability for build arfifact
- Add extract ability for fetch artifact

Task details page: `http://localhost:8153/go/tab/build/detail/build/97/packing/1/pack`

Approach:
- Using identical deployment environments for DEV, TEST, PROD (only resource limits may change like memory, storage). Not fetching or building repos twice for any reason.
- Build pipeline: Fetch once from git repository, install dependencies `npm install`, publish artifact (all files and folders).
- Test pipeline: Fetch artifact from build pipeline, run test scripts.
- Deploy pipeline: Fetch artifact from build pipeline, run deployment scripts.

###### Basic environment details

* Go Version: `19.7.0`
* JAVA Version: `OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing) 2019-04-16`
* OS: `Ubuntu 18.04.2 LTS (bionic)`

###### Additional Environment Details

Both GoCD Server and Agent run on docker containers in local environment.

##### Steps to Reproduce

Slow:
1. Create a nodejs project with express module (code snippet below), push to git repo
2. Create two GoCD pipelines: `build` (material is the git repo) and `deploy` (downstream pipeline of build pipeline)
3. In build pipeline, create a task running this script: `npm install` (this will create "node_modules" folder having all dependencies of the nodejs project, a lot of files and folders)
4. In build pipeline, create build artifact publishing `* to dist`(whole source directory to dist directory in destination)
5. In deploy pipeline, fetch the artifact from build pipeline (as directory)

Fast: (After the same steps 1-to-3 above)

4. Create a task to tar working directory and output: `source.tar` in `dist` directory under working directory
5. In build pipeline, create build artifact publishing `dist to dist` (dist directory in source to dist directory in destination)
6. In deploy pipeline, fetch the artifact from build pipeline (as directory): `dist`

##### Expected Results

- Ability to tar / zip published artifacts, and untar / unzip fetched artifacts.
- Improving time for fetching artifacts from other pipelines.
- Opening task details should not hang even if there are many published artifacts (> 10k).

##### Actual Results

Using scripts to tar/untar.
Tested with an almost empty nodejs project for this (code snippets and detailed steps below):
`1373 files (and some folders), compressed: 88.1 MB to 3.5MB (dist-v1.0.2.tar file)`

Before:
Fetching `dist`directory having 1373 files and some folders takes `40 to 60 seconds`.
Task details page: `takes ~1 min` (This might be a bug during populating file tree for Artifacts tab)

After:
Fetching single `dist-v1.0.2.tar` file under dist folder takes `3.5 to 7 seconds`.
Task details page: `immediately opening/loading`

##### Code snippets/Screenshots

index.js
```
var express = require("express");
var app = express();
const PORT = process.env.PORT || 5000;

app.get("/", (req, res) => {
 res.send("hello world");
});
const server = app.listen(PORT, () => {
  console.log(`Started on port: ${PORT}`);
});

module.exports = app;
```
package.json
```
{
  "name": "myapp",
  "dependencies": {
    "express": "^4.17.1"
  },
  "devDependencies": {
    "dotenv": "^8.0.0",
    "mocha": "^6.2.0",
    "nodemon": "^1.19.1",
    "supertest": "^4.0.2"
  }
}

```

**Comment by adityasood** [comment]
@mehmetcavus thank you for such a detailed issue and providing benchmarks. 

just a brief on how this currently works

1. The agent is asked to upload a directory as an artifact.
2. Agent zips it and uploads it as a directory artifact.
3. Server realizes it's a directory artifact (and not just a zip file artifact)
4. It unzips it and stores in on the server side (so that any files in it can be fetched)
5. (Possibly another) agent now has a job which needs to fetch a directory artifact. So, it asks for a "zip" of that artifact.
6. Server zips up the directory and then sends it.
7. Agent unzips it.


The directory is unzipped to allow for any file to be fetched in the downstream jobs.

The immediate workaround would be to tar the directory and then push it as an artifact.

This is near to what is being discussed on this issue https://github.com/gocd/gocd/issues/464. If you think it's the same we can close this and follow this up on the same thread.
