### ISSUE TITLE
Look into issue with Test drive hanging for Windows users

### ISSUE THREAD

**Issue by loudaTW** [gocd/gocd#6909]
(Christopher/Steven)

**Comment by marques-work** [comment]
From what I've seen in the videos, I'm not sure of how to fix these issues where the download seems to hang at 100% on windows.

Sometimes it could be antivirus scanning the file and taking forever (might have been the case for Stephen). For the Chrome issue that Christopher faced, I've actually seen that randomly on my Mac before. I usually just rename the temp file to what the downloaded file should be and it works, but that's not a great hack to ask ppl to do and may not work for everyone. Noteworthy that it also didn't work in Edge.

The internets gave some generic workarounds that I haven't verified. Most of them sound like canned solutions, but they include:

- disabling web scans on antivirus (some folks may be hesitant to do this)
- download in incognito mode (so as to exclude third party plugins)
- reinstall browser (gah!)

I'll post the headers we receive while downloading the installers in case there are clues in there.

**Comment by arvindsv** [comment]
We might need to try and reproduce it, with proxies from different locations (safely, in a VM).

**Comment by marques-work** [comment]
```http
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe500006600)
> GET /test-drive/installers/19.8.0/9915/gocd-19.8.0-9915-482-windows.zip HTTP/2
> Host: download.gocd.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< content-type: application/zip
< content-length: 250211920
< date: Wed, 11 Sep 2019 20:48:19 GMT
< cache-control: max-age=
< last-modified: Fri, 06 Sep 2019 14:16:18 GMT
< etag: "df25ae3109d7108496296aaf2b72a1f3-30"
< server: AmazonS3
< x-cache: Hit from cloudfront
< via: 1.1 4a55d86b7263f73c6817c7c25d4b3643.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO20
< x-amz-cf-id: _a4t2FwsrZRQjV_Of4KMOS7fnvnmTv0_LTQinjNjnqB8MWiBxbZB3g==
< age: 54
```

**Comment by marques-work** [comment]
@arvindsv I'm pretty sure I've seen this on the big windows TV in SF. And not only with our installers. Doesn't happen every time though.

**Comment by kierarad** [comment]
I want to call out that there are actually 2 different issues that are part of this.

1 - Both Christopher & Steven had issues downloading the test drive (per @marques-work and @arvindsv comments above)

2 - The executable appear to hang for Christopher

I took a closer look at the second issue. I turns out that Christopher paused the execution unintentionally when he was clicking around in the command prompt (see 21:08 of the interview, right after running the executable he clicks into the command prompt - we can see the white highlight)
https://medium.com/@harshg0910/click-to-pause-execution-in-windows-powershell-b451044501ac

When we asked him to try running the executable again he click ctrl-C which unpaused the process and it therefore continued on and started up as expected. 

I suspect he may not be the only Windows user who might accidentally do this. I don't know that there is much we can do to prevent/stop a user from doing this, but we may want to consider a "Troubleshooting" guide for the test drive which includes this. It could be as simple as a link (from the landing page) to a Github issue which describes common problems such as this one

**Comment by marques-work** [comment]
In relation to the download hanging on Windows, I haven't reproduced it lately, though I've seen it before in the past on my own with random downloads. I'll keep trying and see if I can come up with something better than "just restart Windows and try again"

**Comment by marques-work** [comment]
Something that _ought_ to get folks past the download if the browser hangs during the Windows security scan is this powershell snippet (of course replacing the URL and filename):

```powershell
(New-Object System.Net.WebClient).DownloadFile('https://download.gocd.org/test-drive/installers/19.9.0/10151/gocd-19.9.0-10151-521-windows.zip', 'gocd-19.9.0-10151-521-windows.zip')
```

Assuming, of course, people feel ok about pasting arbitrary snippets in their console. They trust us right 😇?

**Comment by marques-work** [comment]
sweet-baby-jesus-on-a-pogo-stick Windows Defender nearly halted my VM!

![image](https://user-images.githubusercontent.com/723642/65207751-9d69ca80-da47-11e9-967a-e9d5c64b14bc.png)

#### Observations

- It takes a while to scan archives with lots of files (like this one). I almost thought it was stuck. but after several minutes it completed.
- You can't kill the Windows Defender process (by design, or malware could do that too).
- It can also happen with other browsers besides MSEdge and IE.

Luckily it doesn't seem to apply to `System.Net.WebClient` in powershell.

Here's a "one-liner" (sarcasm, but technically true since I removed all the newlines from this beast of a cmdlet) that lets you download with a progress bar (a la `wget`):

```powershell
&{ param($url) $file = [io.path]::GetFileName($url); "Fetching $url"; $uri = New-Object "System.Uri" "$url"; $req = [System.Net.HttpWebRequest]::Create($uri); $req.set_Timeout(15000); $res = $req.GetResponse(); $total = [System.Math]::Floor($res.get_ContentLength()/1024); $rstr = $res.GetResponseStream(); $dst = New-Object -TypeName System.IO.FileStream -ArgumentList $file, Create; $buf = New-Object byte[] 10KB; $len = $rstr.Read($buf, 0, $buf.length); $soFar = $len; while ($len -gt 0) { $dst.Write($buf, 0, $len); $len = $rstr.Read($buf, 0, $buf.length); $soFar = $soFar + $len; Write-Progress -activity "  -> '$file'" -status "Downloaded ($([System.Math]::Floor($soFar/1024))K of $($total)K): " -PercentComplete ((([System.Math]::Floor($soFar/1024)) / $total)  * 100); } "`nDownload complete: $file"; $dst.Flush(); $dst.Close(); $dst.Dispose(); $rstr.Dispose(); } 'https://download.gocd.org/test-drive/installers/19.9.0/10153/gocd-19.9.0-10153-523-windows.zip'
```

**Comment by marques-work** [comment]
![image](https://user-images.githubusercontent.com/723642/65212197-18d27880-da56-11e9-8a47-7fbf73a51265.png)

How fun is that?

**Comment by marques-work** [comment]
DOS?

```batch
powershell -Commamd "& { param($url) $file = [io.path]::GetFileName($url); ""Fetching $url""; $uri = New-Object ""System.Uri"" ""$url""; $req = [System.Net.HttpWebRequest]::Create($uri); $req.set_Timeout(15000); $res = $req.GetResponse(); $total = [System.Math]::Floor($res.get_ContentLength()/1024); $rstr = $res.GetResponseStream(); $dst = New-Object -TypeName System.IO.FileStream -ArgumentList $file, Create; $buf = New-Object byte[] 10KB; $len = $rstr.Read($buf, 0, $buf.length); $soFar = $len; while ($len -gt 0) { $dst.Write($buf, 0, $len); $len = $rstr.Read($buf, 0, $buf.length); $soFar = $soFar + $len; Write-Progress -activity ""  -> '$file'"" -status ""Downloaded ($([System.Math]::Floor($soFar/1024))K of $($total)K): "" -PercentComplete ((([System.Math]::Floor($soFar/1024)) / $total)  * 100); } ""`nDownload complete: $file""; $dst.Flush(); $dst.Close(); $dst.Dispose(); $rstr.Dispose(); } 'https://download.gocd.org/test-drive/installers/19.9.0/10153/gocd-19.9.0-10153-523-windows.zip'"
```

**Comment by marques-work** [comment]
DOS

```batch
PowerShell -Command "& { param($url) $file = [io.path]::GetFileName($url); "^""Fetching $url"^""; $uri = New-Object "^""System.Uri"^"" "^""$url"^""; $req = [System.Net.HttpWebRequest]::Create($uri); $req.set_Timeout(15000); $res = $req.GetResponse(); $total = [System.Math]::Floor($res.get_ContentLength()/1024); $rstr = $res.GetResponseStream(); $dst = New-Object -TypeName System.IO.FileStream -ArgumentList $file, Create; $buf = New-Object byte[] 10KB; $len = $rstr.Read($buf, 0, $buf.length); $soFar = $len; while ($len -gt 0) { $dst.Write($buf, 0, $len); $len = $rstr.Read($buf, 0, $buf.length); $soFar = $soFar + $len; Write-Progress -activity "^""  -> '$file'"^"" -status "^""Downloaded ($([System.Math]::Floor($soFar/1024))K of $($total)K): "^"" -PercentComplete ((([System.Math]::Floor($soFar/1024)) / $total)  * 100); } "^""`nDownload complete: $file"^""; $dst.Flush(); $dst.Close(); $dst.Dispose(); $rstr.Dispose(); } 'https://download.gocd.org/test-drive/installers/19.9.0/10153/gocd-19.9.0-10153-523-windows.zip'"
```
