### ISSUE TITLE
Add :latest  tag to gocd/gocd-agent-alpine-3.10

### ISSUE THREAD

**Issue by danielsetreus** [gocd/gocd#6931]
##### Summary

Please add a `latest` tag to the latest relase of the gocd-agent at docker hub. Makes it a lot more clear when trying to pull the image. Also - I'm pretty sure the current tag names does not follow the tag name convention for docker images. Skip the prepended `v` - the tag name should be only the version number - or a version name.

You could also create tags for each environment (centos, alpine etc), instead of keeping them all in different image repos. This would also make it much easier. For some inspiration - see how php does it at docker hub. They keep both cli, fpm, and on all different machines, in the same repo but under different tags.

**Comment by adityasood** [comment]
@danielsetreus We don't publish the latest tag as providing a specific version number on the docker image makes it easier to know deprecations and features added removed as part of these versions and work with them accordingly. 

There are some posts which people have written about (not) using the latest tag.
http://container-solutions.com/docker-latest-confusion/
http://blog.benhall.me.uk/2015/01/dockerfile-latest-tag-anti-pattern/

It is like force pushing, every time, and seems to cause more confusion than it is worth.

I hear you on the convenience part regarding the `v`. Though our docker tag matches the regex (https://github.com/docker/distribution/blob/master/reference/regexp.go#L37) the tag is expected to be in.

> You could also create tags for each environment (centos, alpine etc), instead of keeping them all in different image repos. This would also make it much easier. For some inspiration - see how php does it at docker hub. They keep both cli, fpm, and on all different machines, in the same repo but under different tags.

With our monthly release cadence and the number of agent images we have, adding them in one repo with different tags might just make the maintainability and discoverability of these images harder. 

Keeping separate image repos helps us in many ways. Some of the distributions can be deprecated and it's easier for the end-users to know when we stop publishing releases for that distribution. We have a single server image. Each agent is separate since users might want to run environment-specific builds and keeping them in a separate repo provides easier visibility.

**Comment by adityasood** [comment]
@danielsetreus I am closing this for now. Please feel free to re-open in case you have anything to add.
