### ISSUE TITLE
Proxy gocd-server Docker Image through nginx subfolder

### ISSUE THREAD

**Issue by richjyoung** [gocd/gocd#7061]
##### Issue Type

- Documentation Report

##### Summary

https://docs.gocd.org/current/installation/configure-reverse-proxy.html#gocd-with-nginx explains how to use NGINX, however I cannot find documentation on how to use a location directive other than '/'

##### Environment

gocd-server Docker image, in Kubernetes environment fronted by NGINX.

###### Basic environment details

Docker Hub gocd-server v19.9.0

##### Steps to Reproduce

1. Configure NGINX reverse proxy with a location other than '/' (e.g. '/gocd')

##### Expected Results
GoCD UI served correctly from URL specified by location and server.

##### Actual Results
UI fails to load as redirects to '/go' occur.

**Comment by arvindsv** [comment]
@richjyoung I think it expects it to be `/`. It cannot be server under a different location (mostly because the expectation of `/go` is not configurable). So, I'll close this issue for now. Happy to re-open it if someone finds out anything different. Thank you.

**Comment by matt-lethargic** [comment]
Can the expectation of `/go` be changed? Do we have to open a separate issue / feature request to make this configurable?

**Comment by arvindsv** [comment]
@matt-lethargic There was an attempt to remove the hardcoding in https://github.com/gocd/gocd/issues/4558, but I believe @GaneshSPatil felt that it wasn't easy. @GaneshSPatil might have more info.

**Comment by GaneshSPatil** [comment]
@matt-lethargic
As @arvindsv has mentioned, there was an attempt to change the hardcoded `/go` and make it configurable via `cruise.server.context` system property. 

Due to following reasons it was harder to change:
- so many occurrences of `/go` within the application itself. 
- Plugins. Many of the GoCD plugins requires GoCD Server Url (Example: All Elastic Agent Plugins), and these plugins expect the server url to end with `/go`.
- External Tools. Multiple GoCD based tools such as [gomatic](https://github.com/gocd-contrib/gomatic), [GoCD CLI](https://github.com/gocd-contrib/gocd-cli/), [GoCD Monitor](https://github.com/karmats/gocd-monitor) would need to work with user provided webapp-context.

**Comment by matt-lethargic** [comment]
That is a shame as this means that I cannot use GoCD for my particular situation.
Would this be something that could be considered for version 20? Hard coding URLs like this seems like a problem that is very solvable going into a new version

**Comment by GaneshSPatil** [comment]
Hi @matt-lethargic,

I can understand why configuring the webapp context from `/go` to something else is required for some applications.
As of now there are no plans of picking up this story on the near-term roadmap. 
However, GoCD is an open-source project and you can always contribute to it. If you're willing to help GoCD with this feature request, do let me know, someone from the team would help you to get started on it.

**Comment by sriramnrn** [comment]
On Fri, 24 Jan 2020 at 7:28 PM, Matt Lethargic <notifications@github.com>
wrote:

> That is a shame as this means that I cannot use GoCD for my particular
> situation
>

Could hosting the reverse proxy on a subdomain help?

I don't have access to a computer at the moment so I can't try this myself,
but could you explore URL rewriting from a domain that's intended only for
humans? The agents could continue to access at /go on some other domain.

Ram

>
