### ISSUE TITLE
Make preview pane look less "editable"

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#7111]
Maybe center (vertically - and maybe horizontally) the initial text or make it look like a watermark.

**Comment by ibnc** [comment]
@marques-work found a styling oddity:

<img width="1253" alt="Screen Shot 2019-11-25 at 11 02 49" src="https://user-images.githubusercontent.com/5726224/69569798-43b7dc00-0f73-11ea-8d93-0f8ee182a328.png">

Was this intentional? I ask because I noticed the z-index was added, but I can't see any use for it beyond making this happen.
