### ISSUE TITLE
Missing 'etag' Header in version 19.10

### ISSUE THREAD

**Issue by donita85** [gocd/gocd#7210]
##### Issue Type

- Bug Report

##### Summary

The API 'admin/packages' endpoint is not returning any 'etag' Header in version 19.10.

##### Environment

```
GoCD Version: 19.10.0 (10357-44d61cc733a94287979f1fb99583d69139f386e4).
```

###### Basic environment details

* Go Version: `19.10.0-10357`
* JAVA Version: `openjdk 13 2019-09-17`
* OS: `Alpine Linux`

##### Steps to Reproduce

1. A GoCD server is running in version 19.10
2. An API call towards api/admin/packages endpoint is being made

##### Expected Results
The API call on version 19.9 returns:
```
curl -k -I 'https://localhost:8154/go/api/admin/packages'       -u 'admin:*************'       -H 'Accept:application/vnd.go.cd.v1+json'
HTTP/1.1 200 OK
Date: Mon, 11 Nov 2019 09:47:31 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node079xpy3rd8vtn9iintsl83epo30.node0; Path=/go; Expires=Mon, 25-Nov-2019 09:47:31 GMT; Max-Age=1209600; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
ETag: "67a74306b06d0c01624fe0d0249a570f"
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 452f0300-0c69-48c4-adda-cf49a9b6d5f7
X-Runtime: 0.048835
Vary: Accept-Encoding, User-Agent
Content-Length: 0
```

##### Actual Results
```
curl -k -I 'https://localhost:8154/go/api/admin/packages'       -u 'admin:*************'       -H 'Accept:application/vnd.go.cd.v1+json'
HTTP/1.1 200 OK
Date: Mon, 11 Nov 2019 09:49:32 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node05k9xkkt1ph1w1llirif5gswbg51.node0; Path=/go; Expires=Mon, 25-Nov-2019 09:49:32 GMT; Max-Age=1209600; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v1+json;charset=utf-8
X-Runtime: 36
Vary: Accept-Encoding, User-Agent
Transfer-Encoding: chunked
```

**Comment by akshaydewan** [comment]
We've migrated the API from [rails to spark](https://github.com/gocd/gocd/issues/6655) in 19.10. There wasn't supposed to be any difference in behaviour, but it looks like there are a few changes (which would apply to all APIs migrated from rails to spark):
- The etag header is served only when fetching a specific entity. So you won't get it for `/packages`, but you'll get it for `/packages/[package-id]`
- We haven't explicitly added support for `HEAD` requests in any of the spark APIs. And `-I` option with curl doesn't give the etag, presumably because we're adding it manually in the code while processing the request. We could consider adding the etag for HEAD requests, if it makes sense as per the HTTP spec. I'll let other comment on this.

**Comment by akshaydewan** [comment]
Since this behaviour wasn't documented, I'll close this issue for now. We can reconsider if anyone has strong opinions or arguments about it.
