### ISSUE TITLE
Weird lines on agents table

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#7285]
##### Issue Type

- Bug Report

##### Summary

See screenshot. The table rows seem to contain some weird white separator lines.

![Screenshot 2019-11-21 at 3 15 06 PM](https://user-images.githubusercontent.com/10598/69326592-10730580-0c72-11ea-83ab-993dba5b00fa.png)

**Comment by kritika-singh3** [comment]
@ketan can you please specify the browser version.
I was viewing https://build.gocd.org/go/agents on my browser: `Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)` :
 
<img width="1680" alt="Screen Shot 2019-11-22 at 12 38 35 PM" src="https://user-images.githubusercontent.com/41165891/69405245-2a215500-0d25-11ea-896f-2d2e83c5fed0.png">

**Comment by arvindsv** [comment]
@kritika-singh3 This happens on Firefox. I'm using Firefox 70.0.1.

**Comment by kritika-singh3** [comment]
Verified that the issue exists on Firefox. I have pushed a fix in PR #7294. 
Browser version the fix was tested on:
 - Google Chrome version 78.0.3904.97 (Official Build) (64-bit)
 - Firefox browser 70.0.1 (64-bit)
 - Safari Version 13.0.2 (13608.2.40.1.2)

Agents SPA before fix:

![agents_spa_before_fix_lines](https://user-images.githubusercontent.com/41165891/69420368-8e9fdc80-0d44-11ea-9a59-fe228047a6fc.gif)


Agents SPA after the fix:

![agents_spa_after_fix_lines](https://user-images.githubusercontent.com/41165891/69420391-9c556200-0d44-11ea-85a2-16e663053884.gif)

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10683-fc7710d5f3ada94af6cce76a704b224f79a86cf7)
