### ISSUE TITLE
[Pipeline Config] Project Management configurations are lost on editing any other parts of pipeline config

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7373]
##### Issue Type

- Bug Report

##### Summary

Project Management Configurations are lost when other parts of the pipeline configurations are edited.
###### Basic environment details

* Go Version: `19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)`

##### Steps to Reproduce

1.  Click on edit pipeline configurations of a pipeline
2. Go to Project Management Tab
3. Specify values for `Pattern` and `URI` and Hit Save.
4. Verify Project Management configurations are saved (in cruise-config.xml or by refreshing the page)
5. Visit the Parameters tab of the same pipeline
6. Add a new parameter and Hit Save.
7. Visit Project Management, the previously configured `Pattern` and `URI` is lost.

**Comment by GaneshSPatil** [comment]
This issue occurs when the `fast_pipeline_save` toggle is on.

**Comment by akshaydewan** [comment]
I'm seeing this with `fast_pipeline_save` toggled off as well, and also checked on 19.10.

The issue seems to be in [PipelineConfig.setConfigAttributes](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/config/PipelineConfig.java#L793). We check if the attributes are present in the map before setting them, and I think we should do the same for tracking tool.

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10877-76d1b6c0b4bddb7bf445744d2cf92292d967233e)
