### ISSUE TITLE
Config Repositories don't refresh when an Elastic profile is added

### ISSUE THREAD

**Issue by maheshmadpathi** [gocd/gocd#7509]
##### Issue Type

- Bug Report

##### Summary

We added a config repo and realised that one of Elastic agent profile is missed through reportes error at right corner, hence we created the same manually but config repo doesn't seem to refresh unless server is restarted, or config repo recreated.

##### Environment
all

###### Basic environment details

* Go Version: `19.12.0`
* JAVA Version: `13.0.1`
* OS: `Linux 4.14.138-114.102.amzn2.x86_64`
* Browser vendor and version (if relevant): `Chrome`

##### Steps to Reproduce

1.  create a config repo, miss one of elastic-profile in one of the pipelines intentionally
2. look for errors at right top corner
3. create missing elastic-profile manually
4. see if the error goes away even after refreshing config repo.

##### Expected Results

The error should go away and config repo should pick up the changes.

##### Actual Results

The Error didnt go away, Config repo didn't refresh

**Comment by kritika-singh3** [comment]
Thanking for reporting this issue. I have verified that it exists on `GoCD Version: 20.1.0 (10922-dcb56e317d31b72929b2bd0c725e74f75a931427)`. We will look into it.

For now, there is a workaround this issue:

1. Go to `Admin` -> `Config XML`
2. Click on `Edit`.
3. Without making any change, click on `Save`.
4. Go to Config Repo SPA, wait for few minutes so that the reparse happens. The error should go away.

Please try this out and let me know if it works for you.

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11109-7a59f0f111d0d51960d0e3105d85d6e9585cb940)
