### ISSUE TITLE
Fan-In not working with git feature branch plugin

### ISSUE THREAD

**Issue by MaoChhaya** [gocd/gocd#7703]
##### Issue Type

- Feature enhancement

##### Summary

GoCD Fan-In is not working with **Git-Feature-Branch Plugin** when pipelines trigger multiple branches. I'm seeing a pipeline B trigger run before its upstream pipeline A is completed when I push to one of branches-whitelist of pipeline A and the branch trigger pipeline B. branches-whitelist of pipeline B is presented in pipeline A. 

###### Basic environment details

* Go Version: `19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11)`
* JAVA Version: `13.0.1`
* OS: `Docker debian-9`

###### Additional Environment Details

* VM OS: `Ubuntu 18.04`

##### Steps to Reproduce

1. Using `gocd-yaml-config-plugin` with `git-feature-branch-plugin` to create pipeline A trigger by branches: `development` and `release`
2. Create pipeline B is downstream of pipeline A, and trigger by branch: `release`
3. Pipeline A and B are using the same git repository url and trigger type is auto

##### Expected Results

1. Push commit to branch `release`
2. Pipeline A is started to run and complete, and pipeline B will not trigger immediately
3. Once pipeline A is completed, pipeline B will be scheduled to run

##### Actual Results

1. Push commit to branch `release`
2. Pipeline A and B trigger build at the same time 
3. Once pipeline A is completed, pipeline B will be scheduled to run again due to its upstream pipeline A

**Comment by arvindsv** [comment]
This seems to be a special case of the fan-in limitations mentioned in the documentation: https://docs.gocd.org/current/advanced_usage/fan_in.html#limitations

Unfortunately, there is a lot of history behind why it is a limitation and it is unlikely to be changed (not for not wanting to, but because opens up another can of worms around correctness).

So, I'm closing this as wont-fix.
