### ISSUE TITLE
Go Server URL cannot be blank (but it should be allowed to be)

### ISSUE THREAD

**Issue by nush-1qb** [gocd/gocd#7704]
##### Issue Type

- Bug Report

##### Summary

When I try to create a Cluster Profile without specifying a Go Server URL, I get an error that I need to specify one. This is at odds with the description below that field that says: "Defaults to GoCD Secure site URL if not specified."
###### Basic environment details

* Go Version: v20.1.0
* JAVA Version: 13.0.1
* OS: Linux 4.19.76

##### Steps to Reproduce

1. Try and create a cluster profile without specifying Go Server URL

##### Expected Results

Should be able to leave the field blank

##### Actual Results

The UI says I have to specify the Go Server URL
##### Code snippets/Screenshots
<img width="455" alt="Screen Shot 2020-02-04 at 2 25 04 PM" src="https://user-images.githubusercontent.com/14079635/73793039-6841e880-475a-11ea-8e0d-5e55d2474795.png">

**Comment by arvindsv** [comment]
Hmm. Strange. I don't know how the plugin can work with it being blank (and unsure it has access to the secure site URL somehow). @GaneshSPatil or @kritika-singh3 might know.

**Comment by GaneshSPatil** [comment]
Hi @nush-1qb @arvindsv 

`GoCD Server URL`  is a mandatory field and has to be provided. However, the description needs to be changed to remove `Defaults to GoCD Secure site URL if not specified.`

There was some work happening to make _Site URL_ and _Secure Site URL_ information available to plugins via Request Processor, But I doubt if thats being merged.
\cc: @bdpiparva

**Comment by bdpiparva** [comment]
@nush-1qb - All the validation happens at the plugin side. By looking at the old code I can see that it was making use of the secure site URL when available or show the error `Secure site url is not configured. Please specify Go Server Url.` . [The method](https://github.com/gocd/kubernetes-elastic-agents/blob/d812b4c9837a3f4fc68b069f006fb2a6893b75b0/src/main/java/cd/go/contrib/elasticagent/executors/ValidateConfigurationExecutor.java#L99-L107) was performing the validation which got removed during [elastic agent v4 => v5 migration](https://github.com/gocd/kubernetes-elastic-agents/commit/54388f8443166fb5a0d924ce59898768515e3fc6).

@GaneshSPatil - I am not sure why validation is removed. If it was intentional then we should remove it from UI as well.

**Comment by GaneshSPatil** [comment]
@bdpiparva - Thanks for the update. Will check and update it soon.

**Comment by GaneshSPatil** [comment]
Hi @nush-1qb @arvindsv @bdpiparva - As mentioned by @bdpiparva in https://github.com/gocd/gocd/issues/7704#issuecomment-617560734 comment. It was a bug with Kubernetes Elastic Agent Plugin which is fixed as part of https://github.com/gocd/kubernetes-elastic-agents/pull/185. A new [release of the Kubernetes Elastic Agent Plugin](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.7.0-217) is available which contains the fix.

I will be closing this issue marking as fixed. Please do reach out to us if you've any further questions.

Thank you very much @nush-1qb for reporting the bug!!
