### ISSUE TITLE
Policy improvements for better team isolation

### ISSUE THREAD

**Issue by Bewalticus** [gocd/gocd#7769]
##### Issue Type

- Feature proposal

##### Summary

When using a GoCD server in a shared service-like approach there are some flaws which makes management difficult or at least unsafe.

###### Static Agents

There is a sophisticated management for elastic agents with policies but if you have static agents for the teams it is not possible to restrict access to the agents.
What can be achieved with current implementation:
- Give a team admin control over a pipeline group
- Create evironments for the team and assign static agents. Give only view access to environment. With admin access the team is able to assign agents of other teams to the environment.
- Team has to ask service provider for the following tasks (no self service possible):
  - add new pipeline to the environment
  - modify resources on the agents
  - modify environment variables on the environment 

When introducing policies for static agents the team can get admin access to the environment and do all the things in self-service.

###### Package Repositories

Currently package repositories and the contained packages are shared resources and visible for all users. When one team creates a package in a package repository it can be used by all other teams. So it is possible to read out credentials for this using a simple custom command task.

By introducing policies for package repositories it would be possible to create some kind of namespaces for different teams, e.g. allow access to package repository "Application1-*" the team could create own repositories, e.g. "Application1-Artifactory", which is hidden from other teams.

Another solution would be introduction of pipeline local package repositories.

###### Artifact Stores

Here applies the same as for Package Repositories. They are shared between all teams.

**Comment by arvindsv** [comment]
@Bewalticus Thank you for taking the time to write this down.

1. When you say that it is not possible to modify environment variables on the environment, do you mean that it's not possible for someone with admin permissions to the environment? Similarly, adding a pipeline to the environment. Both should be possible for environment admins.

2. When you say policies for static agents, do you envision them as: "Assign this agent to team X and they can assign it only to environments they have permission to administer?"

For the other entities, granular auth will be introduced slowly. We struggled with the balance between granularity and ease of use and settled on the view and administer concepts.

For your particular case, where you are thinking about more granularity, [config repo rules](https://github.com/gocd/gocd/issues/7605) in one of the upcoming releases might work better. Take a look and please provide feedback.

**Comment by Bewalticus** [comment]
@arvindsv Thanks for commenting on my suggestions.

1. In the current implementation there are 2 actions you can choose from for environment policies: "View" and"Administer". So you can modify nothing on the environment or all aspects (pipelines, agents and environment variables). From a perspective of a shared service the teams should be able to assign pipelines and define environment variables by themselves but not assign the agents. This would allow a team to extend their "scope" to agents (VMs) of other teams. This implies rejecting "administer" permission for development teams. But this is very cumbersome for both -- development and service teams.
2. From my point of view it is relatively easy to define and use policies for static agents. As used for the other types there are the two actions "View" and "Administer" and you can select agents by hostname (and maybe by IP and/or IP range).
    - View: User can see the agent(s) and assign them to environments (if he or she has "administer" permission on the environment)
    - Administer: User can additionally define resources for the given agent(s) and enable or disable them. Deletion of agents should only be possible for system admins.

In my opinion the agent policies are the most important ones for establishing a shared service. For package repositories and artifact stores the development teams should have the awareness of the implications and then they can care about it themselves.

I had a look at the config repo rules and think that they go in the right direction but the "refer environment" permission bundles pipelines and agent assignments. So additional restrictions on agents are mandatory for a shared service approach. Will those rules be administratable via GUI too?

**Comment by arvindsv** [comment]
@Bewalticus I understood what you're saying. I don't know whether we would go to that granularity. There might be more questions/conversation once @kritika-singh3 is back from vacation in a couple of weeks. Thanks!

**Comment by Bewalticus** [comment]
@arvindsv I don't think that this feature would introduce to much granularity because it is similar to the already implemented policies for cluster and elastic profiles. I would like to spent some time for implementing it because it is somewhat mandatory for my use case. What do you think?

**Comment by arvindsv** [comment]
@Bewalticus Here was a recent discussion around granular auth. Feel free to put together a proposal with similar details and let's discuss it. Would need to understand how the interplay between environments and agents will go and what happens when there are (possibly) conflicting permissions, etc. I wouldn't use hostnames or IP ranges. Hostnames, especially, can be controlled by whoever brings up an agent.

**Comment by Bewalticus** [comment]
@arvindsv Sorry for the long delay but I was a little bit busy these days. Here is a proposal for the feature. Please have a look.

# Agent permissions feature

## Introduction

In GoCD agents are assigned to environments and pipelines are assigned to environments too. Pipelines are grouped in pipeline groups. The pipeline groups allow to assign permissions to users or roles.

With pipeline group permissions an isolation of teams can be done to define responsibilities for pipelines. But the teams need some permissions on environment and agent level to be able to define all aspects of their pipelines:

1. Assign pipelines to environments (covered by environment "Administer" permission)
2. Define environment variables on environments (covered by environment "Administer" permission)
3. Define resources on agents to control job execution (not covered yet)

Unfortunately the permission "Administer" on environments permit assigment of agents. So it is possible for some member of team A to assign agents of team B to own environments. This is a possible security issue.

This only applies to static agents. For elastic agents a comprehensive permission implementation already exists.

## Solution

To give team members full control over own CD infrastructure a restriction of access to agents is needed. So access to team members can be restricted to agents which belongs to that team.

### Permission set

Agent permissions can be defined equivalent to permissions to environments:

| Action | Effect |
|------------|--------|
| View | Ability to view agents and their job run history |
| Administer | All from View action permission and additionally ability to enable / disable agents and to assign resources and environments to agents |

Deletion of agents is still only possible for system admins.

The evaluation of the permissions is done equivalent to the other permissions which are already implemented.

### Use Cases to be modified

#### Add and Edit role dialogue [GUI]

In the drop-down list of column "TYPE" in the "Policy" table add a new entry called "Agent".

#### Agents page [GUI]

The list of shown agents is restricted to the agents which are permitted due to the "View" and "Administer" actions. System admins can see all agents.

The following GUI actions on the agents are restricted:

| GUI action | Permitted for |
|------------|---------------|
| DELETE | System admins only |
| ENABLE | System admins and users having permission for "Administer" action |
| DISABLE | System admins and users having permission for "Administer" action |
| ENVIRONMENTS | System admins and users having permission for "Administer" action |
| RESOURCES | System admins and users having permission for "Administer" action |

If the GUI action is not permitted a proper error message is shown.

#### Admin > Environments page [GUI]

In the "Edit agents associations" dialogue only agents are shown where the user has permissions because of "Administer" actions. System admins can see all agents.

#### Stage details [GUI]

On the list of Jobs there is a link on the agent name opening the Job run history. This can opened by users having "View" or "Administer" action permission and system admins only.

#### Job details [GUI]

in the "Job details" page there is a link on the agent name opening the Job run history. This can opened by users having "View" or "Administer" action permission and system admins only.

#### Runtime Agents [API]

The following API call restrictions apply:

| API Call | Restriction |
|----------|-------------|
| Get all agents | Only agents are returned where the user has "View" or "Administer" action permission. All agents are returned for system admins. |
| Get one agent | Agent is returned only if the user has "View" or "Administer" action permission for the agent or if user is system admin. |
| Update an agent | Agent can only modified by system admins and users having "Administer" action permission |
| Delete an agent | Agent can only be deleted by system admins |
| Bulk update agents | If user is no system admin and call references at least one agent where the user does not have "Administer" action permission, then the call is rejected |
| Bulk delete agents | Can only executed by system admins |
| Agent job run history | Only for system admins and users having "View" or "Administer" action permission. |

**Comment by arvindsv** [comment]
Oh. I missed this. I'll take a look tomorrow and respond.

cc: @kritika-singh3

**Comment by arvindsv** [comment]
Hello @Bewalticus. Apologies for the delay.

1. What is the [resource identifier](https://docs.gocd.org/current/configuration/policy_in_gocd.html) to be used? Agent GUID? Or, does it apply to all static agents? I mean:

    ```xml
    <role name="my_team">
      <users>
        <user>bob</user>
      </users>
      <policy>
        <allow action="administer" type="agent">WHAT_GOES_HERE</allow>
      </policy>
    </role>
    ```

2. About deletion only by super admins:

   This is different, compared to other entities. I assume that's because bringing up an agent should also be an admin activity, unlike with the other entities. What would happen if we allowed delete? Just asking to see if we cannot be consistent.
   
3. I assume, if someone has to edit an environment and assign agents, you expect that they will have an `administer` capability for agents, in their role. Right? That will change existing behavior of the `administer` action for environment, I suppose. Not that it can't be changed. Just saying.

**Comment by arvindsv** [comment]
@kritika-singh3 tells me there's a problem with point 3 above. Regarding the recent GoCD change to move agents out of the config. Might need to discuss next week.

**Comment by Bewalticus** [comment]
@arvindsv Here are some remarks for your questions:
> 1. What is the resource identifier to be used? Agent GUID? Or, does it apply to all static agents? 

The GUID would be the best choice for implementation because it is used in API calls. But the GUID is not visible to the user and so no good choice. Best solution for end user is name of agent.

>2. About deletion only by system admins:

We currently use auto registration of agents during server launch process and so do not need someone to activate the agents manually but you are right, this should be admin activity too. I'm not sure but what is the behaviour when deleting an agent, which has auto registration configuration? Does it reregister automatically or is the deletion permanent?

> 3. I assume, if someone has to edit an environment and assign agents, you expect that they will have an administer capability for agents, in their role. Right? That will change existing behavior of the administer action for environment, I suppose. Not that it can't be changed. Just saying.

Yes, this is a little bit difficult to explain. If you look at the API the assignment of agents to environments is part of the agent API and therefore part of agent permissions. But on the GUI there are 2 places to assign agents: on the agents page and on the environment configuration page.

What is it about the recent GoCD change?

**Comment by arvindsv** [comment]
About 1: The name is decided by a property decided [during auto-registration](https://docs.gocd.org/current/advanced_usage/agent_auto_register.html) and it can subsequently be [updated via the API](https://api.gocd.org/current/#update-an-agent), causing whoever had permissions to lose it. How about if the GUID was more easily visible or accessible?

About 2: I think the deletion is permanent. The auto-register key is removed from the autoregister.properties file, after a successful registration.

About 3: I think @kritika-singh3 has some thoughts.

> What is it about the recent GoCD change?

Sorry, we can ignore that. It's probably not relevant to this discussion.

**Comment by Bewalticus** [comment]
About 1: Using the GUID would be possible if somewhere shown but not very intuitive. For my usecase it is ok because we have the following approach:
 - Assign the agent to environment via auto registration.
 - When having the environment assignment I can adjust permissions using API calls.

When you look at the permissions of environments then you have the same problem. You can change the name of the environment subsequently via API calls.

About 2: If deletion is permanent then it should be restricted to system admins because a deletion by accident will involve manual intervention on the server where the agent is located.

**Comment by kritika-singh3** [comment]
@Bewalticus The idea is very similar to what you have proposed in the comment above.

### Current Static Agent Permissions:

  - view: all
  - update (resources and envs): system admins
  - enable/disable: system admins
  - delete: system admins

Proposal: Introduce RBAC for static agents which will govern only the view and update of the agents specified.
    The enable/disable/delete will remain will the system admins.
    Reason: Enable is similar to adding an agent and hence, restricted to system admins only

Policy: two types
 - deny: default policy for all users
 - allow: allow a particular action for the given resource identifier i.e. **Agent GUID**

**Note:** deny will take more precedence over allow

| Action       | Description                                                                                            |
|------------- | --------                                                                                               |
| view         | Ability to view agent and their job run history                                                        |
| administer   | Ability to view agent, their job history and additionally ability to edit hostname, assign resources and environments |

#### Impact on API

The Agents API v6 will now provide access based on the current user permissions.
**Note:** *By default, the system admin is allowed access to all*

| Endpoint              | Can be used by            |
|---------------------  |-----------------          |
| Get all agents        | Can be used by any authorized user. The result will contain only the agents that the current user is allowed to view  |
| Get an agent          | Can be used by user who have view access to it. Otherwise will return 403    |
| Update an agent       | Can be used by user who have administer access to it. Otherwise will return 403  |
| Bulk update agent     | Can be used by any authorized user. The list of agents will be validated for administer access if hostname, resources or environments are being updated. It is enable/disabling, 403 will be returned |
| Agent job run history | Can be used by user who have view access to it. Otherwise will return 403   |
| Delete an agent       | Can only be used by system admins. Otherwise will return 403                 |
| Bulk delete agent     | Can only be used by system admins. Otherwise will return 403                  |

The Permissions API will be updated to know the permissions attached to agents

#### Impact on SPA

The Agents SPA was available for all users as view only. The changes needed would be

 - The resources and environments need to be enabled for all users

##### To decide
 - resources can be created by all?
 - The Environments SPA has an option to update env-agent association. Now, since we can do so from Agents SPA - should we remove that from Envs SPA?

cc:\ @gocd/committers

**Comment by arvindsv** [comment]
About 1: That's true that it's similar with other entities. However, with an agent, anyone can then bring up another agent (even with the same name as an existing one) and that could be a problem in some cases. It's unlike other entities.

> About 2: If deletion is permanent then it should be restricted to system admins because a deletion by accident will involve manual intervention on the server where the agent is located.

Ok, makes sense.

**Comment by arvindsv** [comment]
@kritika-singh3 To your questions:

1. I think resources should be able to be created by everyone. They're just tags anyway and they need control over jobs to be able to create matching resources anyway.

2. I think we should keep that ability to associate in the envs SPA as well. A decision about removing it should be made based on the user experience, rather than a permissions/policy change, I feel.

**Comment by kritika-singh3** [comment]
@arvindsv The reason being remove the edit env-agent association option from Env SPA is that in all our SPAs - all the operations are dependent on that entity's permissions. Since, the association depends on agent's permission - thought we could remove the same from Envs SPA.

**Comment by Bewalticus** [comment]
@kritika-singh3 Thank you for your update to the proposal. I fully agree with that.

Here my thoughts to the 2 "to decide" topics:
>  resources can be created by all?

This is the primary tool to steer where the jobs will be executed and in my opinion is mostly used by the application dev teams. So it should be possible for any agent administrator to define a new resource for some special agent selection needs.

> The Environments SPA has an option to update env-agent association. Now, since we can do so from Agents SPA - should we remove that from Envs SPA?

When removing the ability to add/remove agents from the envs SPA the display of the associated agents should remain to give the user a quick overview of the environments. Maybe we can insert some info box or a link "Add/remove agents" to direct users to the agents page.

**Comment by arvindsv** [comment]
> Since, the association depends on agent's permission - thought we could remove the same from Envs SPA.

Well, it should all come down to what the person using it will expect, I suppose. If it is not too jarring to have to go somewhere else, just to associate agents, then ok. If not, then the fact that the association is based on a different entity's permissions is just an implementation detail, isn't it?

**Comment by kritika-singh3** [comment]
Yes, @arvindsv you are right. These are all internal implementations.
@Bewalticus thanks for your feedback. The display of association agents in an environment will be there. Was just thinking of removing the edit functionality bit.
But I think the scenarios I had in mind can be taken care of internally.
Will update the comment above with the results. :)
