### ISSUE TITLE
Limit size of material modification list

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#7788]
##### Issue Type

- Feature enhancement

##### Summary

Recently, one of our teams had to do a complete history rewrite in their quite large Git repository. This was a special case - I'm aware that such rewrites are not recommended.
This caused some issues in our GoCD instance (19.12), because on the next pipeline run, it considered the entire history of over 10k commits to be changed and generated an enormous modification list that eventually caused a heap error and a restart of the server.

While this is an edge case, and there are ways to mitigate the problem, it got me wondering if it wouldn't make sense in general to have some sort of limit to the modification lists. Even disregarding memory issues, it's not really useful to display a modification list in the GUI that's thousands of entries long.

So my suggestion is to limit modification lists to either a fixed or configurable value. The earlier in the material update process, the better (at least for resource consumption). For example in the git material, `git log --max-count=n ...` could be used.
It would probably be good to make users aware that not all modifications are displayed when viewing a modification list that was cut off.

**Comment by arvindsv** [comment]
@sandro-h Yes. This is similar to (duplicate of?) #443. There is a consequence of ignoring commits, which is why it is open. It can cause some obscure problem with scheduling that I don't recall the exact details of. However, I think it would be useful to put a limit on it, like you mention.

Maybe @GaneshSPatil or @maheshp have some thoughts.
