### ISSUE TITLE
Cannot search when type config repo name in the search box

### ISSUE THREAD

**Issue by ngoclamnn** [gocd/gocd#7853]
##### Issue Type
- Bug Report
##### Summary
Cannot search when type in the config repo search box
![image](https://user-images.githubusercontent.com/29177632/76586233-e68c6a00-6512-11ea-9c24-f24500a20091.png)

##### Environment
* Go Version: 20.1
* JAVA Version: Not sure
* OS: Go server image Docker Ubuntu 18.04
* Browser vendor and version (if relevant): All
##### Steps to Reproduce
1. Go to gocd server web
2. Click on menu Admin/Config repository
3. Search a config repo by typing the name on the search box
##### Expected Results
Should show the filtered results
##### Actual Results
Do not show filtered results
##### Possible Fix
Fix the search script (javascript?)
##### Log snippets
Not available
##### Any other info
Not available

**Comment by GaneshSPatil** [comment]
Hi @ngoclamnn ,

Thanks for reporting the issue. I can confirm the issue is reproducible on GoCD v20.1.0.


Just a small update/correction:

### Actual Result:
**Search results are updated after 10 secs of updating the search field.**

### Expected Result:
Search results should be updated instantly, as soon as the search box is updated.

**Comment by kritika-singh3** [comment]
Verified on `GoCD Version: 20.2.0 (11342-a1132a62554a4682eeef7889651b0acd2dfe3031)`
