### ISSUE TITLE
Changes to GoCD's SSL/TLS support from 20.2.0 onwards

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7872]
### TLS support and limitations of that support in GoCD releases _before_ 20.1.0

The GoCD server (<= 20.1.0) uses a self-signed certificate for the TLS port on 8154.

The GoCD Server and Agent communication is over HTTPS and uses self-signed certificates for authentication and authorization. Users don't have an ability to use their own certs and private keys for agent-server authentication and authorization.

Since they relied on a self-signed certificate setting up mutual TLS was quite involved.

The support for TLS configuration was controlled by Jetty (web server embedded with GoCD), and the configuration was not exposed to administrators in an easy manner.

Considering the above limitations, changes were made in GoCD 20.2.0 to simplify the TLS setup. The intention is to allow GoCD System Admins to setup TLS in a manner that is simple and secure. In that direction, GoCD Server's Jetty instance will stop listening on the SSL/TLS endpoint (port 8154) going forward.

To set up TLS for GoCD, system admins will be required to front the GoCD server with a reverse proxy that supports TLS (like Apache, NGINX). Any existing agents that are using TLS, can connect to this reverse proxy. Reverse proxies have the advantage that they make it a lot easier and more convenient to setup and configure various TLS connection parameters. Refer the [GoCD documentation](https://docs.gocd.org/current/installation/configure-reverse-proxy.html)  to setup a reverse proxy.

For system admins that want to additionally set up mutual TLS between the server and agents, GoCD agents will allow configuring a private key, certificate and an optional passphrase, which the agent will use to authenticate with the reverse proxy.

To minimize disruptions, GoCD temporarily (until version GoCD 20.4.0) will provide an option to enable TLS on 8154.

The changes are part of this [PR](https://github.com/gocd/gocd/pull/7669). 

#### New installation of GoCD (>= 20.2)
 - GoCD will not bring up TLS port 8154. There will be no way for such users to configure built-in TLS.
 - To enable secure connection a reverse proxy needs to be configured which supports TLS and will need to be the one terminating TLS if needed.
 
#### Upgrading from GoCD 20.1.0  or lower
 - GoCD Server changes
     - GoCD will not bring up TLS on port 8154.
     - To enable secure connection a reverse proxy needs to be configured which supports TLS. The reverse proxy should be the one terminating TLS if needed. Refer to [this](https://docs.gocd.org/20.2.0/installation/configure-reverse-proxy.html) to configure a reverse proxy for GoCD.
 - GoCD Agent changes
   - Since existing agents connect to the server through port 8154, they need to be reconfigured to use 8153.
   - Elastic Agents: If the elastic profile was configured with 8154, they need to be updated to use the 8153 port.
 - Temporarily make GoCD open 8154
    - GoCD will temporarily allow opening of port 8154. This option will be allowed in GoCD versions 20.2.0 to 20.4.0. From GoCD 20.5.0, the server will no longer contain any functionality to configure TLS. At this point, users will be expected to terminate TLS using a reverse proxy.
    - To enable TLS on 8154 you would need to configure a system property in the file `wrapper-properties.conf` with the value `-Dgo.server.enable.tls=true`. The location of the `wrapper-properties.conf` file depends on the OS used. Please refer to the [GoCD installation docs](https://docs.gocd.org/current/installation/installing_go_server.html) to find the location.

**Comment by hokadiri** [comment]
Is there a working helm chart with this change?
https://github.com/gocd/helm-chart doesn't seem to work right off the bat.

A user created 
https://github.com/gocd/helm-chart/issues/12 but no one has looked into it.

**Comment by foretspaisibles** [comment]
> New installation of GoCD (>= 20.2)

> GoCD will not bring up TLS port 8154. There will be no way for such users to configure built-in TLS.
> To enable secure connection a reverse proxy needs to be configured which supports TLS and will need to be the one
> terminating TLS if needed.

As a user deploying GoCD server behind a reverse proxy terminating SSL and using a self-signed certificated I am unable to setup agents so that they can register to the server and I am also unable to find relevant bit of documentations that give me directions on how to achieve a working setup.

I am using latest (21.4.0) official docker images for the server and the agent, but I do not believe might be the problem related to the docker setup.

Using curl in the agent container I can easily validate the agent container has network connectivity to the reverse proxy I use and that the reverse proxy answers HTTPS requests using the provided self-signed certificate. I am also confident that the connectivity between the server and the reverse proxy is working as expected and I can use and configure the GoCD server over the web interface.

Unfortunately, the docker agent is unable to register, the GO_SERVER_URL is set as:

~~~
GO_SERVER_URL: https://gocd.gocdserver/go
~~~

The agent logs mention the error:

~~~
jvm 1    | 2022-03-09 12:25:17,265 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error: 
jvm 1    | javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
jvm 1    | 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
jvm 1    | 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
~~~

which seems to say that the SSL trust path is broken, which is expected with a self-signed certificate.

How can I teach the gocd agent to trust the self-signed certificate? How to add a root certificate to the gocd agent trusted roots? (These questions might be elementary to Java platform users, but GoCD is generally useful to non-Java developers and these questions should be answered by the documentation to make the audience of GoCD as large as possible.)

**Comment by foretspaisibles** [comment]
@chadlwilson Thank you for your quick reply, then en to end transport security link looks very yummy, I'll try it very soon!

My understanding is that the current typical deployment scenario makes the SSL configuration mandatory, so that this page could be referred to in the “Installing GoCD agent” sections, so that users have better chances to create an operational deployment. I was not able to recognise the SSL/TLS End-to-end security headline into a “this is where you need to look at to configure the GoCD agent.”

Thank you for your help!
