### ISSUE TITLE
Feature Request: support multiple CONFIG_GIT_REPO in docker image

### ISSUE THREAD

**Issue by HariSekhon** [gocd/gocd#7929]
##### Issue Type

- Feature proposal

##### Summary

Request `gocd/gocd-server` docker image support multiple config git repos, eg. having `CONFIG_GIT_REPO` split on commas and load each of the repos.

**Comment by varshavaradarajan** [comment]
`CONFIG_GIT_REPO` stores `cruise-config.xml`, `cipher.aes`, logback configurations etc. So, all these gocd server related configurations are expected to be present in a single repo. CONFIG_GIT_REPO overwrites  `/godata/config` on the docker container so that you can start a gocd server using an existing configuration. 

Are you perhaps referring to the pipeline as code configurations when you say you want to load from multiple config repos?
 
Related docs: 
https://docs.gocd.org/current/advanced_usage/config_repo.html#gocd-configuration-repository
https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html

**Comment by HariSekhon** [comment]
Yes that's what I mean, I load pipelines as code from a git repo, but each of my github repo's contains their own pipeline `.gocd.yml` so I have to create several config repositories to get them all loaded.

Since the docker image doesn't seem to support pre-loading multiple of them I work around this currently using a script to call the rest API.

**Comment by arvindsv** [comment]
You could add them to the cruise-config.xml file and mount `/godata/config`, can't you?

**Comment by HariSekhon** [comment]
I am doing this dynamically where I boot GoCD server and agent and then load one or more repos pipelines, so a static xml doesn't really solve this use case.

When doing Dockerize things it's convenient to pass environment variables to configure the container during initialization, which is why I was asking if having some environment variable were possible to load pipelines from more than one repo.
