### ISSUE TITLE
Performance issues with cctray

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#795]
<details to be filled>

**Comment by arvindsv** [comment]
Some details and ideas [here](https://groups.google.com/d/topic/go-cd-dev/0zw0mHEqlVk/discussion).

**Comment by arvindsv** [comment]
I've run some performance benchmarks on the code of this pull request. The benchmark data and graphs are available [here](https://gist.github.com/arvindsv/b44d181d45133a4224f5/) and for download in the [tar.gz file](https://gist.github.com/arvindsv/b44d181d45133a4224f5/raw/bb54840d4cfb962a1f5fec3ea0de1756f302fa3c/cctray.profile.tar.gz). Some context of the information:

* The microbenchmark code, used to generate the graphs, is in the [profile tar.gz file](https://gist.github.com/arvindsv/b44d181d45133a4224f5/raw/bb54840d4cfb962a1f5fec3ea0de1756f302fa3c/cctray.profile.tar.gz) (0001-CCTray-perf-benchmark.patch). It uses JUnit, stubs out the database meaningfully and brings up a few different threads: One which keeps changing the config, and three which keep fetching CCTray requests. It runs this for 30 seconds at a time.
* When the config changes (to add or remove stages and jobs), the stubs change (while those threads are running). So, sometimes, there are exceptions in the output. I didn't want to setup locking, because that might affect the timings. The exception calls are ignored for timing. Since it runs many times every run, it's ok.
* The initial number of groups used is 20, with 50 pipelines each, with 3 stages each and 5 jobs each (leading to 15000 CCTray projects). This config is changed every few milliseconds, to either add a couple of stages and jobs (up to 20 * 50 * 5 * 7 = 35000 projects) or to remove a couple of stages and jobs (down to 20 * 50 * 1 * 3 = 3000 projects). These config changes are done continuously, about once in every 800 milliseconds.
* As mentioned, the DB is stubbed out (to make it easier to be able to change config). But, the effect of the DB should be minimal in both the old and new code.
* The total run is for 30 seconds. This is done three times for each of the old CCTray code and the new CCTray code.

Some interesting points: Comparing [new.3.png](https://gist.github.com/arvindsv/b44d181d45133a4224f5/#file-new-3-data-png) and [old.1.png](https://gist.github.com/arvindsv/b44d181d45133a4224f5/#file-old-1-data-png) (they're all using logarithmic scale):

1. The new code is able to fetch CCTray XML in the 10^6 range (time), whereas the old code was in the range of 10^8. [New is better]

2. The new code was able to fetch about 1500 CCTray XMLs, while the old one, in the same time, did about 500. [New is better]

3. The new config change handler has a range of about 10^8, whereas the old one is at about 10^7. The old code was doing nothing special on config change. This one does. [New is a little worse, old is better]

4. Memory usage is not significantly different. The old one seems to have a tendency to go higher and higher (going towards 10^9 in the graph), whereas the newer one seems to be more stable, and able to come down. This is not very conclusive, but new code is not worse.

So, I think performance-wise, the new code is decent and can be used.

**Comment by arikagoyal** [comment]
cctray functionality works fine. Verified on 15.1.0(1594-db70c652aa3804)

**Comment by arikagoyal** [comment]
Actually 15.1.0(1632-d41a824d8f5c5d) is the right build number and not 15.1.0(1594-db70c652aa3804)
