### ISSUE TITLE
Run a stage on ANY condition

### ISSUE THREAD

**Issue by maxbalan** [gocd/gocd#8195]
##### Issue Type

- Feature proposal

##### Summary
We are building a dynamic environment where every pipeline when it is triggered has to spin up all the resources it needs in order to run all its stages, and by resources I mean VMs, DBs etc. Currently it is  our first stage in a pipeline, after all the test are done our last stage is the cleanup stage where we destroy all the VMs we spin up in the first stage, the issue we are facing is that if one of the stage fails, the resources are not cleaned up, and we end up manually cleaning up those resources.

All the stages have 2 triggers `On Success` and `Manual` and having the flexibility here to run a stage on `ANY` condition, I think should solve this issue, or are we approaching it from a wrong direction?

**Comment by arvindsv** [comment]
@maxbalan Yes, stages are not meant to continue, once one of them fails.

You could look to see if ["Run if conditions"](https://docs.gocd.org/current/advanced_usage/dev_conditional_task_execution.html) at a task level work for you. In that case, as a job is failing, the cleanup task runs.

If not, you might need to [use the APIs](https://api.gocd.org/current/#run-stage) on a timer or something, to force the stage to run.

If not, another option is to cleanup before starting, so that it is idempotent and doesn't depend on the cleanup stage having run.

I'm closing this since "GitHub issues" is not the right place to ask a question. The [mailing list](https://groups.google.com/forum/?oldui=1#!forum/go-cd) or the Gitter channel are probably better.
