### ISSUE TITLE
Feature proposal - Re-run failure tasks should be a must have feature

### ISSUE THREAD

**Issue by veeramanikandanvv** [gocd/gocd#8214]
- Feature proposal

Feature to Re-run failure tasks.

We are using Version 19.6

**Comment by kritika-singh3** [comment]
Do you mean for a particular stage? It is supported - https://api.gocd.org/19.6.0/#run-failed-jobs

**Comment by veeramanikandanvv** [comment]
Hi Kritika,

Thanks for addressing this feature. I am in need of feature for running the
failed tasks alone.

Example: in a stage I have a job and in turn that job has 5 tasks. If there
are any failure in the tasks I want to Re-run that particular task alone.

**Comment by arvindsv** [comment]
Hello @veeramanikandanvv.

Thanks for this. There's no plan to introduce a feature such as this. GoCD's philosophy (and that of CD in general) is that your CD tool (including GoCD) should not decide _how_ something is done, but only what to do. So, it's a better practice in general, in my opinion, to put that behaviour in your build scripts, rather than in a CD tool. That way it is more generic and you can easily move to a different CD tool, without having to have this be a problem.

If I needed the ability to re-run a task if it fails, I would do something like:

```
Command: /bin/bash
Arguments:
    -c
    ./task.sh || ./task.sh
```

That way, if `./task.sh` fails (and _only_ if it fails), it'll run `./task.sh` again. This approach is usable across different tools.

Since there is no plan to have this feature be in GoCD, I'm going to close this issue. Cheers.
