### ISSUE TITLE
User with View access can't access exist pipelines in deafault view.

### ISSUE THREAD

**Issue by colachg** [gocd/gocd#8219]
##### Issue Type

- Bug Report

##### Summary
User can't access the pipelines even given the permission.

##### Environment

```plain
{
  "Timestamp": "2020-06-10T01:25:43Z",
  "Go Server Information": {
    "Version": "20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9)"
  },
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 25,
      "Number of environments": 0,
      "Number of agents": 2,
      "Number of unique materials": 24,
      "Number of schedulable materials": 16
    },
    "Security": {
      "Plugins": [
        {
          "Password File Authentication Plugin for GoCD": false
        },
        {
          "LDAP Authentication Plugin for GoCD": true
        }
      ],
      "Enabled": true
    }
  },
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "4.15.0-91-generic",
    "System Architecture": "amd64",
    "Available Processors": 1,
    "Average System Load": 0.11
  },
```
-->

###### Basic environment details

Browser: Firefox

###### Additional Environment Details

I set LDAP as the Authorization Configurations

##### Steps to Reproduce

1. Admin-> Role Configuration -> Add -> (allow view ALL *)
2. Assign this role to a user
3. Login in and then there is nothing in default view.
4. If give the user admin permission, all pipelines comes out.

##### Expected Results

user with 'View' access should access exist pipelines
##### Actual Results

there is no pipelines.

**Comment by colachg** [comment]
![Screenshot from 2020-06-10 09-46-53](https://user-images.githubusercontent.com/6825116/84217706-6f5d7680-aaff-11ea-8155-6a6fa1f76588.png)
![Screenshot from 2020-06-10 09-47-01](https://user-images.githubusercontent.com/6825116/84217722-75ebee00-aaff-11ea-8b54-3e6ee191f752.png)

**Comment by kritika-singh3** [comment]
Hello @colachg, the permissions using role is a feature in GoCD known as [policy](https://docs.gocd.org/current/configuration/policy_in_gocd.html). The policy currently extends only to `environment, config_repo, cluster_profile, elastic_agent_profile`.

In order to give `view` access of a pipeline to a user, you would need to update the pipeline group authorization. You can either add the user or a role to the same. Please read the [docs]( https://docs.gocd.org/current/configuration/dev_authorization.html#specifying-permissions-for-pipeline-groups) for more information.
You can either update the same via API or UI.

**Comment by arvindsv** [comment]
Based on that response, I'm going to close this issue for now. Happy to reopen it later if needed.

**Comment by arvindsv** [comment]
Oh, also: This behaviour changed in 20.4.0: https://www.gocd.org/releases/#20-4-0

**Comment by colachg** [comment]
Thanks for your good job :)
