### ISSUE TITLE
Plugin reload issue on agent side

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#825]
If pluginLocationMonitor.sleepTimeInSecs env variable is set, a new plugin added gets reloaded on Go server side dynamically (without needing a Go server restart) but the plugin does not get passed onto agent

**Comment by arvindsv** [comment]
@mdaliejaz, have you considered trying to remove the plugins zip itself, and send agents plugins individually?

**Comment by mdaliejaz** [comment]
@arvindsv I think that could be done but I would rather wait for #118 to be played before :)
What do you think?

**Comment by arvindsv** [comment]
Ok. I think they're two different things, though.

**Comment by zabil** [comment]
@mdaliejaz @arvindsv 
Was thinking more about this. I think the implementation is slightly weird.

Does anybody have context/history onto why we are not using 304 (not modified) status but instead  have two separate urls where we pass and receive checksums in the header and then hit the destination url?

We need only one url for e.g
/agents.zip

which returns 200 if we are to download the zip file or 304 if we are to keep the local copy.

**Comment by zabil** [comment]
Maybe to reduce the chattiness?
There'll be 3 requests (/agent, /agent-launcher, /agent-plugins) instead of one (/latest-agent.status)

**Comment by mdaliejaz** [comment]
> Ok. I think they're two different things, though.

I might have understood it wrong then. I think what you meant was to send plugins individually on the agents instead of zipping it. But I thought you meant to pass agent side plugins (not passing the server side plugins) individually. My mistake.
I think it makes sense on what you are saying. This would mean we wouldn't have to pass all the existing plugins every time due to a plugin addition/update/deletion.

@zabil Initially there was only the agent jar and the checksum was checked so that the jar is not downloaded unless there is a change in the checksum. Later with the introduction of bootstrapper and launcher extra checksums were introduced. As part of this change the new URl */latest-agent.status* was introduced to reduce the chattiness (as you said). And I think to keep it same when */agent-plugins.zip* URL was added it also became a part of */latest-agent.status*.

**Comment by mdaliejaz** [comment]
Have created #996 to take care of individual plugins download. 
Thought it's an enhancement and should be done separately :)

**Comment by arikagoyal** [comment]
Verified. Closing on behalf of Srini
