### ISSUE TITLE
git username not picked up while cloning the repo

### ISSUE THREAD

**Issue by singhalss** [gocd/gocd#8349]
Hi,

I have configured gocd-agent and server (latest versions 20.5.0) on AWS EC2 instances and hooked up the agent with gocd-server. 

I created a config repository in go console which points to my **https://github.com/../...git** repository URL. On the gocd-agent, I configured git credentials helper (store) and populated .git-credentials with **https://singhalss:my-personal-access-token@github.com**. 

Now, when I am running the pipeline, I can see go-agent is starting a process where git clone is happening for **https://:my-personal-access-token@github.com/../...git** and I see my username (singhalss) is missing from remote URL. git clone fails with stderr because of this.

Appreciate if you can please share the resolution for this issue if you have has faced and fixed it.

**Comment by arvindsv** [comment]
Hello. The forum for questions are the mailing list or the gitter channel. I'll close this issue.

However, since you've asked: Have you added the credential helper on the agent side as well? GoCD just calls out to git and does nothing special. So you just need to make sure that the _user_ that the agent and server processes are running as have git config setup properly. You could just log in as them and see if you can run the same clone.
