### ISSUE TITLE
Fix cruise config xml save performance issues

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#838]
Go currently has 1 cruise-config.xml and with time the size tends to become very big. This tends to slow down config saves and starts effecting the performance. 
This issue is a placeholder to start thinking about potential solutions for the same. Details would be updated as we get more clarity around this.

**Comment by zabil** [comment]
Initial observations while profiling 
https://github.com/gocd/gocd/blob/master/server/test/performance/com/thoughtworks/go/config/MagicalCruiseConfigXmlPerformanceTest.java

*shouldReadQuickly*

| Name                                                                                                                                       | Time (ms) | 
|--------------------------------------------------------------------------------------------------------------------------------------------|-----------| 
| com.thoughtworks.go.config.GoConfigGraphWalker.walkFields(Object, ValidationContext, GoConfigGraphWalker$Handler) GoConfigGraphWalker.java | 11639     | 
| com.thoughtworks.go.config.parser.GoConfigClassLoader.parse() GoConfigClassLoader.java                                                     | 10210     | 
| com.thoughtworks.go.config.CruiseConfig$ErrorCollectingHandler.handle(Validatable, ValidationContext) CruiseConfig.java                    | 10127     | 
| com.thoughtworks.go.config.parser.GoConfigFieldLoader.parse() GoConfigFieldLoader.java                                                     | 10034     | 
| com.thoughtworks.go.config.CruiseConfig$5.handleValidation(Validatable, ValidationContext) CruiseConfig.java                               | 9987      | 
| com.thoughtworks.go.config.parser.GoConfigClassLoader.parseCollection(Collection) GoConfigClassLoader.java                                 | 9923      | 



*shouldWriteQuickly*

| Name                                                                                                                                                     | Time (ms) | 
|----------------------------------------------------------------------------------------------------------------------------------------------------------|-----------| 
| com.thoughtworks.go.config.GoConfigGraphWalker.walkFields(Object, ValidationContext, GoConfigGraphWalker$Handler) GoConfigGraphWalker.java               | 11082     | 
| com.thoughtworks.go.config.GoConfigGraphWalker.walkCollection(Object, ValidationContext, GoConfigGraphWalker$Handler) GoConfigGraphWalker.java           | 10854     | 
| com.thoughtworks.go.config.CruiseConfig$5.handleValidation(Validatable, ValidationContext) CruiseConfig.java                                             | 9716      | 
| com.thoughtworks.go.config.ValidationContext.getAllMaterialsByFingerPrint(String) ValidationContext.java                                                 | 6488      | 
| com.thoughtworks.go.config.ValidationContext.primeForMaterialValidations() ValidationContext.java                                                        | 6465      | 
| com.thoughtworks.go.domain.packagerepository.PackageDefinition.getFingerprint(String) PackageDefinition.java                                             | 5156      | 
| com.thoughtworks.go.config.materials.PackageMaterialConfig.getFingerprint() PackageMaterialConfig.java                                                   | 5109      | 
| com.thoughtworks.go.config.MagicalGoConfigXmlWriter$CollectionXmlFieldWithValue.populate() MagicalGoConfigXmlWriter.java                                 | 4882      | 
| com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ExplicitCollectionXmlFieldWithValue.populate(Element) MagicalGoConfigXmlWriter.java                  | 4882      | 
| org.jdom2.xpath.jaxen.JDOMXPath.selectNodes(Object) JDOMXPath.java                                                                                       | 4609      | 
| com.rits.cloning.Cloner.cloneInternal0(Object, Map, Class) Cloner.java                                                                                   | 4521      | 
| org.jaxen.expr.DefaultLocationPath.evaluate(Context) DefaultLocationPath.java                                                                            | 4187      | 
| java.lang.System.identityHashCode(Object) System.java (native)                                                                                           | 3170      | 
| org.jaxen.expr.DefaultStep.evaluate(Context) DefaultStep.java                                                                                            | 3051      | 
| com.thoughtworks.go.config.parser.GoConfigFieldLoader.parse() GoConfigFieldLoader.java                                                                   | 2761      | 
| com.thoughtworks.go.config.parser.GoConfigClassLoader.parseCollection(Collection) GoConfigClassLoader.java                                               | 2701      | 
| com.thoughtworks.go.domain.packagerepository.PackageDefinition.handleProperty(List, PackageConfigurations, ConfigurationProperty) PackageDefinition.java | 2631      | 
| com.thoughtworks.go.domain.config.ConfigurationProperty.forFingerprint() ConfigurationProperty.java                                                      | 2606      | 
| com.thoughtworks.go.config.parser.GoConfigSubtagLoader.parse() GoConfigSubtagLoader.java                                                                 | 2573      | 
| com.thoughtworks.go.config.preprocessor.ParamResolver.resolveCollection(Object, ParamResolver) ParamResolver.java                                        | 2441      |

**Comment by zabil** [comment]
Possible conclusion

There's a bottleneck while walking all the fields and validating them on large cruise config files on load and write. There are no more optimizations that can yield significant improvements (caching etc are already in place).

Can we look at breaking down the monolith config instead?

**Comment by srinivasupadhya** [comment]
My thoughts on config splitting:

I think splitting the agents tag from config into separate file is first best move?

- `<agents />` has almost no dependency on other parts of config so very little XSD validations to take care of. I think environment & resources are the only ones. will check & confirm.
- editing agents is done only in one page - enable, disable, delete, assign resources, assign environments which should be easy to migrate.
- every time agent status changes - causes config read/write & commit in config repo blocking other user config changes. this could be aggravated in cases where agents are brought up & shutdown based on requirement. so there will be some perf improvement since only agents.xml read-write would happen & not full config.xml.
- once we move `<agents />` to say agents.xml which we will add to config repo & start auto backup we will know what it takes to split other parts.

Also, may be we should not split pipeline, stage, job into separate files. Just all the <stage/> bit of each pipeline & template into one file (if we do it at all). That way the logic for file read write remains same for pipeline & template & should provide good enough performance. We can then give UI to edit that whole file for pipeline group admin etc.

**Comment by arvindsv** [comment]
Let's move this, with a summary, to go-cd-dev?

**Comment by mrmanc** [comment]
Hello

@zabil Interesting results! Am I reading correctly that those operations tend to take around 11 seconds? You mention that there are no more significant improvements, but it _felt_ to me like there was a lot of locking going on during purely read operations which should not be affected by config changes. We have also seen a very linear trend with blocked threads around config changes, where the number of blocked threads steadily increased by one a minute, and then suddenly starting to decrease by one a second when things had died down. We have noticed that since throttling back out requests to the XML feeds APIs, we get a lot less of this contention, which seems strange as finding the status of a pipeline / stage / job doesn’t feel like it should require synchronization.

@srinivasupadhya I think moving agents out makes a lot of sense. After that Pipelines and Templates feel like the right units of storage for the configuration… and there is unlikely to be conflicts within those units. The performance should scale well as the size of single pipelines is unlikely to be a constraint (whereas the number of pipelines tends to grow and grow).

@arvindsv / all, I’m massively interested in this and would love the conversation to stay on GitHub, but I will join go-cd-dev to stay involved if you feel it would be best talked about with all of the other contributors.

**Comment by mrmanc** [comment]
One more thought… I think it is really important to keep it possible for users to edit the pipelines etc in a text format—I know people have expressed strong feelings about this in the past—but I don’t think people are in love with the XML syntax. If you are drastically changing how the config is persisted, then it might be worth decoupling the language you use to serialise it to disk, and the language which you present to the end user on the front end. That way there should be less XML parsing to do, and although you would have to replace it with some other parsing, you would then be free to choose the most efficient format to persist it to disk without impacting the front end experience. Meanwhile the users could have a pleasant DSL to work in when editing pipelines / templates. Just a thought I had, which might not seem sensible to anyone else ;)

**Comment by zabil** [comment]
@mrmanc the time is a total of 11 operations each on loading and writing the config file. I haven't profiled for multiple threads yet but, as you mentioned, io operations will be blocking. Before getting to optimizations for io, I'd like to consider this a design issue? The size of the file (not commited) used for this test is 3mb, 65500 lines and in production, there's a use case. We need to avoid posting, parsing, synchronizing and saving the entire file for every config change.  

Also yes! I'm for moving away from XML as the source of truth. There's a lot value in not having to deal with the UI to set up pipelines but I think decoupling and exposing an API will allow use of the right tools and DSL's. Of-course, these are ideas but maybe a step in the right direction after we start the break down?

@srinivasupadhya I agree with pulling agents. Something which does not hold context or refer other tags.

@arvindsv I would like to use markdown for tables images etc. Will drop in a note to go-cd-dev and let people subscribe to this if they are interested.

**Comment by mrmanc** [comment]
@zabil I completely agree that this is a design issue requiring the problem to be broken down. We have a similar sized config: 68k lines and 2.9MB. I expect once the problem is broken down there will be no problems with synchronization, although I’m almost certain there is unnecessary synchronisation in the code at the moment.

What do you think the API should look like here? I’ve a feeling that making it as granular as the GUI is isn’t the way to go, and that loading / saving a whole pipeline / template is a better idea. That is the level at which versioning should happen, and it avoids having to deal with reloading parts of a pipeline someone else has changed whilst you’re working on it. Either your change would succeed or fail. This goes against the existing functionality around magically merging changes but I don’t think there’s much a problem with that if the conflict only happens at the pipeline level.

**Comment by matt-richardson** [comment]
We have to keep in mind that whatever solution is come up with, it needs to be backwards compatible.
I'm assuming that we are not alone in having different scripts / apps that edit the xml directly (due to a historical lack of nice api endpoints).

**Comment by mrmanc** [comment]
Oof… I wondered if it was the case that people have existing integrations with the XML! Sounds like that will make any change of definition language complicated.

We have considered trying to update the XML automagically before (to update the material a pipeline looks at) but shyed away from it as it seemed risky working with the whole file at once.

**Comment by arvindsv** [comment]
Slightly late to the party. I found my sheet of paper with my thoughts on this. Before I get to that, I think that XML as a source of truth was a huge mistake done many, many years ago. I believe that was because of the influence of CruiseControl and the way the world was at that time. It should have been proper IaC (Infrastructure as Code) and not Infrastructure as a config file. However, that decision has happened, and I think we cannot break that now. So, I think whatever approach we take, existing configuration should not be made invalid. The breaking of config should be an option.

My thought is that we should provide an option to break up all the stages-jobs-tasks into a different file (all stages in a pipeline, into one file). Today, the [XML structure](http://www.go.cd/documentation/user/current/configuration/configuration_reference.html) looks like this:

```
<pipeline name=...>
  <materials>
    <git name="code" .../>
  </materials>

  <params>
    ...
  </params>

  <environmentvariables>
    ...
  </environmentvariables>

  <stage>
    <jobs>
      <job>
        <tasks>
         ...
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

I think the option should be to convert that to something like this:


```
<pipeline name=...>
  <materials>
    <git name="code" .../>
    <git name="scripts" .../>
  </materials>

  <include file="my-file.xml" repo="scripts" type="go-xml" />
</pipeline>
```

or

```
<pipeline name=...>
  <materials>
    <git name="code" .../>
  </materials>

  <include file="my-file.xml" repo="GLOBAL" type="go-xml" />
</pipeline>
```

The reasons for the attributes are:

1. **file**: Obvious. Is a file which has this information.

2. **repo**: A lot of people want to be able to manage the configuration by checking in configuration, rather than maintaining it inside Go. I think that's reasonable. The option should be to either use a repo used by the pipeline, in its materials tags or to use a global repo that Go server maintains.

3. **type**: I see the included file as not necessarily only XML. I see it as anything that a plugin might want to provide.  It could be some kind of integration with [Walter](http://ainoya.io/walter) or a completely custom DSL which makes sense to you. Another reason to have the type and this be pluginized is versioning and updates. I mention some of this below as well. What happens is that we lose the ability to upgrade a config, through XSL transforms if we do this.


Some questions and thoughts I have about this (or any approach at splitting):

1. How does this behave with templates and parameters? I suppose if the file includes params, it should be ok.

2. How do we store this config? To make the build repeatable (and to maintain history). Today the config repository contains one file. Presumably it can now contain many files. There is effort here. There are some features (like config diff) which use the current config git repo. This will need to change.

3. Is "correctness" of the config sacrosanct? Till now, the Go config stored in the git repo is always a valid file.  Now, that guarantee might not be true, any more. Depending on how we store it. I mean, some of the included files could be "invalid", because of missing param definitions and other validations which might not have run yet.

4. There definitely has to be a cache which brings all the pieces together and presents it to Go Server itself as a single config. Implementation detail. Consider performance impacts to the Go Server itself, too.

5. What about the fetch artifact task? Today, the correctness of the fetch artifact task is verified at config save time. If we provide a way to have this information in an included file, then issues like invalid fetch artifact will be found closer to pipeline schedule time. How will these be handled? I think these have to be handled by showing server level error messages. Actually, even more ideal, it should be shown against every pipeline that is affected, on the dashboard.

6. Should the information about what configuration was used to schedule a pipeline be stored in the DB? I think it should. I should be able to see a building pipeline and trace it down to the correct commit in the repository which was used to build this. Presumably this repository (internal config repo maintained by Go) has multiple files.

   I was thinking something like:

   Pipeline run table

   | ... | ... | config_sha
   | --- | --- | ----------
   | ... | ... | SHA_123


   A new config snippets table?

   config_sha | config repo commit SHA | file
   ---------- | ---------------------- | --------
   SHA_123    | SHA_456_in_config_repo | filename

   Might be too complicated, but I think it's worth thinking about traceability of a build to a config, even in this multi-file repo world.

7. Versioning and XSLT (updation): We lose the ability to make updates to the config at one shot, during startup. That's why I mentioned a plugin earlier. I think that each snippet (included file) has to have a version, and the plugin has to be responsible for updating the configuration it stores. Suppose we (as Go developers) want to make a change, to say, add an attribute called "allow_n_jobs_to_fail" to every stage, then today, it is easy. Just need to write an XSL transform and then, it gets applied to the config, during upgrade. Since stages can now be in both the big config, as well as the smaller snippets, this approach won't work. We will need the XSL transform, to make the old configs, which are not using snippets, have this new attribute. But, the plugin (which manages the snippet of type "go-xml" mentioned above) will need to be aware of this change, and have a smaller XSL transform, which does this.

8. Editing and UI: Users will need to be provided with a UI to update all of the snippets within Go, I presume. Mostly for validation. Also some users prefer that. So, I see the config edit screen have a main part, and then show all the snippets individually, for editing. Sort of like how the pipeline group admin XML edit works. However, if you agree with my local and GLOBAL repo mentioned above, this cannot be provided for snippets which are in a local repo (within a material which is defined at pipeline level), since the source of truth of those is a repository which is not maintained by Go.

9. If we go with a local repo option, then it becomes easier for projects to define their own structure for how they want their build to happen. It's like travis.yml, for instance, but can be much more powerful, and allow your whole pipeline to be setup using it.

**Comment by arvindsv** [comment]
Also, agree that we can pick agents as a first piece to get some of this backup infrastructure in place.

Also, would need to provide APIs at the level of the snippets. Kind of like how Mark says above.

**Comment by mrmanc** [comment]
> Slightly late to the party. I found my sheet of paper with my thoughts on this. Before I get to that, I think that exposing internals as an XML, as a source of truth was a huge mistake done many, many years ago. I believe that was because of the influence of CruiseControl and the way the world was at that time. 
...
> However, that decision has happened, and I think we cannot break that now. 

Here here. It is a decision that has worked until now… nothing wrong with that :)

> So, I think whatever approach we take, existing configuration should not be made invalid. The breaking of config should be an option.

I might be misunderstanding but I wasn't clear whether you feel configuration should be backwards compatible? Not making existing config invalid and breaking config seem opposite to me. 

> My thought is that we should provide an option to break up all the stages-jobs-tasks into a different file (all stages in a pipeline, into one file). Today, the XML structure looks like this:
...
> How do we store this config? To make the build repeatable (and to maintain history). Today the config repository contains one file. Presumably it can now contain many files. There is effort here. There are some features (like config diff) which use the current config git repo. This will need to change.

I was originally thinking about each pipeline being a DB record, but after reading this thread I agree that separate files are a good idea. Easy to backup, to diff, to version. *And* compatible with Go's private Git repo. 

> Is "correctness" of the config sacrosanct? Till now, the Go config stored in the git repo is always a valid file. Now, that guarantee might not be true, any more. Depending on how we store it. I mean, some of the included files could be "invalid", because of missing param definitions and other validations which might not have run yet.

Yes, it is absolutely sacrosanct. I believe integrity of the CD environment is an important concern, and a key feature of Go, where there is an organic mesh of dependant units without restricting how each unit changes. Removing that integrity risks unrepeatable builds, secretly broken pipeline and artifact dependencies and fear of changing things. I think this is more important than accommodating external versioning of configuration.

I think the motivation to tackle the monolithic config is performance and ability to make changes, not convenience. An API which accepts submissions for changes to a pipelines tasks, rejects changes which introduce inconsistency and notifies subscribers about changes is perfectly convenient for teams who wish to manage their configuration externally.

Of course, that API *could* look like a Git remote… but that feels like a lot of effort to implement a full Git interface complete with integrity checking behind the scenes.

> There definitely has to be a cache which brings all the pieces together and presents it to Go Server itself as a single config. Implementation detail. Consider performance impacts to the Go Server itself, too.

Yep, Go as a source of truth. :+1: 

> What about the fetch artifact task? Today, the correctness of the fetch artifact task is verified at config save time. If we provide a way to have this information in an included file, then issues like invalid fetch artifact will be found closer to pipeline schedule time. How will these be handled?

I believe it is best to deal with these inconsistencies at the point the user who understands is making the change. I doubt anyone wants to have to deal with a missing artefact at the point at which they come to need it :wink: 

Part of this problem is really a symptom of Connascence Of Value between the pipeline and stage names. If these relationships were encapsulated internally as an identifier and simply mapped to human readable names for presentation purposes then changing the name of a pipeline or a stage would not be problematic.

> Should the information about what configuration was used to schedule a pipeline be stored in the DB? I think it should. I should be able to see a building pipeline and trace it down to the correct commit in the repository which was used to build this. Presumably this repository (internal config repo maintained by Go) has multiple files.

Yes, I think that is a great idea, and totally achievable with a Git repo as the source of truth for all of the config.

I think it is great to have visibility of config change within the build. I've found it useful to be able to change the config for a build in progress, and I think that is worth the trade off against repeatable builds to be able to fix something in flight with visibility of the change. 

> Versioning and XSLT (updation): We lose the ability to make updates to the config at one shot, during startup.

I can't really speak of changes like these as we have never really needed to do them often. When we have we have done them externally with the whole XML file in a decent editor.

> Editing and UI: Users will need to be provided with a UI to update all of the snippets within Go, I presume. Mostly for validation. Also some users prefer that. So, I see the config edit screen have a main part, and then show all the snippets individually, for editing. Sort of like how the pipeline group admin XML edit works. However, if you agree with my local and GLOBAL repo mentioned above, this cannot be provided for snippets which are in a local repo (within a material which is defined at pipeline level), since the source of truth of those is a repository which is not maintained by Go.

I think this is a very good argument for keeping Go as the source of truth for a pipeline’s configuration. It certainly the case that users find it useful to be able to make changes to a pipeline group, but I think most of the time this is to rename a pipeline, or copy and paste some jobs, stages or whole pipelines. If that is the case then this can be accommodated within a pipeline by editing the code. Duplication is already supported by the UI. 

Thanks for reading!

**Comment by arvindsv** [comment]
> Here here. It is a decision that has worked until now… nothing wrong with that :)

:) Yes. I'm a *little* irritated that an internal representation is so willingly exposed outside, without APIs, making it really hard to change it.

> I might be misunderstanding but I wasn't clear whether you feel configuration should be backwards compatible? Not making existing config invalid and breaking config seem opposite to me. 

I feel that breaking up of the config should be an option. Meaning, each and every existing config today, should continue to be a valid one. Without providing more of a warning to people, we cannot just break up their config and break all their XML-writing scripts in the process, I feel.

However, if we do it properly, and all pipeline XMLs will always be in a broken up config, then, we can provide a legacy API, which brings the XML snippets together into one big XML (just for reading and writing). Does that make it more clear?

> Yes, it is absolutely sacrosanct. I believe integrity of the CD environment is an important concern ... I think this is more important than accommodating external versioning of configuration.

I hear you saying that the Go should be the only source of truth (you mention that later as well) and is the only system where all the config snippets are kept. They cannot (should not be able to be) checked into a repository, along with the code that it is related to.

Of course, that is an opinion. I have heard other opinions about wanting to go the other way as well (like travis.yml, as I mentioned). It's not that either opinion is wrong. We might or might not want to club these two together.

> > What about the fetch artifact task?

> I believe it is best to deal with these inconsistencies at the point the user who understands is making the change. 

Yes, that would be ideal. This is possible if Go is the only "holder" of the smaller config snippets. It's not possible if that snippet is checked in into some repo, as I mention above.

> ... If these relationships were encapsulated internally as an identifier and simply mapped to human readable names for presentation purposes then changing the name of a pipeline or a stage would not be problematic.

Well, that identifier could still be pointing nowhere, like a broken sym link. It might be slightly easier to validate, sure.

> > Versioning and XSLT (updation): We lose the ability to make updates to the config at one shot, during startup.

> I can't really speak of changes like these as we have never really needed to do them often. When we have we have done them externally with the whole XML file in a decent editor.

This XSLT update happens between releases of Go, when the config needs to be updated to provide more features or fix issues. So, you wouldn't have directly been able to use it. However, as a continuously evolving product, it's a necessary development feature. The ability to update config and DB, during Go Server upgrade.

**Comment by zabil** [comment]
@arvindsv I now think splitting up the XML with external file references will make things tougher. 

One problem is locating files without referring to it's context. In the example you mentioned

```
<pipeline name=...>
  <materials>
    <git name="code" .../>
    <git name="scripts" .../>
  </materials>
  <include file="my-file.xml" repo="scripts" type="go-xml" />
</pipeline>
```
We'll have to refer this file to know the pipeline for the configuration in *my-file.xml*. People can introduce conventions, like directories, but that's overhead to refactoring.

We'll also will run into our original set of performance issues because of the extra parsing, loading and validation.

Like @mrmanc mentioned maintenance will be easier with a first class API. For instance, adding a builder for 

https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/config/CruiseConfig.java

So that it's DSL friendly and callable from other JVM languages 

Or exposing a REST API for all the operations we permit on UI and the config XML. Teams choose how to maintain these as migrations.

We'll have to slowly move out of using XML as our config database to remove the current synchronization framework we out in place because of it. For backward compatibility have an export to or import from XML instead.

Again a lot of this is long term. I am not sure what we can achieve in this release in terms of performance :-( but I am gonna spend some more time profiling before I give up on short term gains.

**Comment by arvindsv** [comment]
> One problem is locating files without referring to it's context. In the example you mentioned
> We'll have to refer this file to know the pipeline for the configuration in *my-file.xml*.

True. We could also completely make the XML snippets be handled by Go, as Marc was saying. Then, the user would not need to worry about directories. Something like ```<include file="SOME-LONG-SHA.xml"/>```. That file would be unique and maintained by Go.

> We'll also will run into our original set of performance issues because of the extra parsing, loading and validation.

Yes, if we plan to bring them all together all the time, then it will. However, an edit of a snippet need not mean re-parsing the rest of the snippets. There can be some intelligent caching done, when the snippets are small and often unrelated.

> Like @mrmanc mentioned maintenance will be easier with a first class API. 
> Or exposing a REST API for all the operations we permit on UI and the config XML. Teams choose how to maintain these as migrations.

> We'll have to slowly move out of using XML as our config database to remove the current synchronization framework we out in place because of it. For backward compatibility have an export to or import from XML instead.

Assuming that whatever backend format we use (Protobuf?) is much faster at parsing and validating a huge file (as big as the XML you used), then exposing a better API is definitely a good idea. The only think we'd miss is that users would still need to keep the whole context in their heads, if they're editing the XML directly. However, as you say, if we slowly move out of using XML, then this is lesser of a concern.


Changing the backend/storing format from XML to something faster is easier than splitting it up. I agree. As long as we can find something which is fast enough for our purposes, then it makes sense. But, we need to consider/help with user frustration at having to deal with a huge config. Better APIs might be a step towards this.

**Comment by zabil** [comment]
Performance numbers with these fixes.

| Name                                                                                                                     | Time Diff (ms) | With fix (ms) | Without fix (ms) |
|--------------------------------------------------------------------------------------------------------------------------|----------------|---------------|---------------|
| GoConfigDataSource.writeWithLock(UpdateConfigCommand, GoConfigHolder) GoConfigDataSource.java | 38688          | 126358        | 165047        |
| CachedGoConfig.writeWithLock(UpdateConfigCommand) CachedGoConfig.java                         | 38675          | 127088        | 165764        |

**Comment by ciotlosm** [comment]
Our config file has 47k lines of code. Interface is really slow during day time when everyone is using the server.
Worst usage at the moment is:
You have a pipeline which relies on a template. You have a job with 6 tasks and you need to add a new task which has to be the first. One action takes around 10 seconds. Creating this task will eat you around 1.5 minutes. If you have do this to update 5-6 templates which have 4 jobs like this, without messing with XML, it is really annoying.

**Comment by zabil** [comment]
Spawned out #911

**Comment by ciotlosm** [comment]
To improve XML editing capabilities for Go System Administrator, would it be possible to have a view with tabs (like non System Admins) where you view smaller chunks of XML?

XML per pipeline group and XML per template. 

At the moment I end up asking someone to cut my System Admin rights and getting specific Admin rights on groups and templates to edit the XML easier. 

I know this is not going to improve performance, but will improve usability and performance hit won't be as bad for System Admins (Which are usually required to fix things)

**Comment by jyotisingh** [comment]
A link to edit config xml per pipeline group is currently available for pipeline group admins only. The url is accessible by Go system admins as well, just that there is no link in the app that takes you to that view, you could directly navigate to it using : https://<go-server:8153>/go/admin/pipelines/snippet/. This could possibly be added as a link for system admins if people find this more usable. 

As far as I know, xml per template is not available, how do you access it?
Xml view per entity was available in early versions of Go, but was then deprecated in favour of UI.

**Comment by mrmanc** [comment]
I think while it is possible to see the whole XML file, it can be useful to just see / edit one group, especially with large configs!

**Comment by ciotlosm** [comment]
@jyotisingh I didn't know I could access the groups like that (I appreciate the URL). I think this would be a good enhancement for a Pull Request. 
I was suggesting the views (pipeline groups and templates with XML) as feature request, but it's nice to see that one is already available!

**Comment by arikagoyal** [comment]
Verified config save functionality. Works fine on 15.1.0(1594-db70c652aa3804)

**Comment by zabil** [comment]
Hey Arika,  There are a few more changes that needs to be done to improve the performance. This issue is too broad. I think we need to break it down to smaller issues and close them instead of this one. Shouldn't we leave this open till all those fixes go in?

Sent from Outlook




On Mon, Mar 16, 2015 at 2:48 AM -0700, "arikagoyal" <notifications@github.com> wrote:












Closed #838.

**Comment by arikagoyal** [comment]
@zabil sure makes sense. Reopening it.

**Comment by cholmes1111** [comment]
Has there been any significant progress made on this enhancement? It seems that it continues to be bumped into future releases but this is an issue we're running into and may determine if we can stick with GO long term.

**Comment by arvindsv** [comment]
[Here's](https://groups.google.com/d/topic/go-cd/fA8zCr-OM58/discussion) an update about what is going on in the development of the upcoming 15.3 release. If you see the issues referenced just above your comment, on GitHub (#1404 and #1417), you will see commits going into those issues. Seeing progress (as in a release with improved speed) might take a little while though. I don't know when, yet.

**Comment by FredrikWendt** [comment]
One config file for disaster recovery (export, backup, import) is a USP compared to Bamboo, where we have a four year old ticket still open with Atlassian (asking for "export plan to some file/forat we can backup"). Restoring Jenkins servers are a mess (with plugins, plugin versions, plugin config). Depending on SQL databases in Bamboo is not reassuring. The one config in GoCD is a bottleneck, but can also be a "lifesaver". The fact that you can easily clone your server (with zero agents attached = safe, as nothing is being executed) and start playing with the config to re-arrange things, is one I've used a number of times. (I might be the only person in the world doing that though :-)

**Comment by grahamc** [comment]
@FredrikWendt++ I've done the same, it can be very helpful.

**Comment by lenucksi** [comment]
@FredrikWendt @grahamc The bespoke cloning actually is nice indeed. However as long as every change leads to a full validation of config.xml and config.git commit this seriously impacts the ability to scale Go beyond a certain limit.

If you rolled your own "autoscaling agents" solution scaling events can bring your Go server to a grinding halt.
Thus I think extending the approach of partial validation is a good one, and may actually be good for the agent issues discussed in #1498 too.

Also as mentioned in #1567 if staying with a file based config.xml the garbage collection and current jgit situation should be given another look...

**Comment by FredrikWendt** [comment]
I don't mind internal representation being something else, as long as there's an dead easy way to recover from whatever disaster you need to recover from. (We had the weirdest hardware failure I've ever seen just weeks ago, and had to move Jenkins servers. Oh the pain.)

**Comment by grahamc** [comment]
I'm not sure what you mean by bespoke.

We run immutable infrastructure -- including our GoCD server. Deploying a config change (other than agents) means we make a brand new server. It makes this process pretty easy when you need to copy around a config.xml and a few keys.


That is my use case at least, and having this remain possible is important to me.

**Comment by lenucksi** [comment]
@grahamc a good false friend indicating my origin...What was actually meant was "aforementioned".

The copying is also useful to template Go servers and create more fresh Go Servers plus / minus a few changes that can be templated.

**Comment by zabil** [comment]
```
   GoFileConfigDataSource:271 - [Config Save] ==-- Getting modified config
   GoFileConfigDataSource:284 - [Config Save] Checking whether config should be merged
   GoFileConfigDataSource:279 - [Config Save] ==-- Done getting modified config
   GoFileConfigDataSource:347 - [Config Save] === Converting config to XML
   MagicalGoConfigXmlWriter:72 - [Serializing Config] Starting to write. Validation skipped? false
   MagicalGoConfigXmlLoader:96 - [Config Save] In preprocessAndValidate: Cloning.
   MagicalGoConfigXmlLoader:98 - [Config Save] In preprocessAndValidate: Validating.
   MagicalGoConfigXmlLoader:118 - [Config Save] In validateCruiseConfig: Starting.
   CachedFileGoConfig:98 - Config file (on disk) update check is in queue
   MagicalGoConfigXmlLoader:124 - [Config Save] In validateCruiseConfig: Running validate.
   MagicalGoConfigXmlLoader:129 - [Config Save] In validateCruiseConfig: Done.
   MagicalGoConfigXmlLoader:100 - [Config Save] In preprocessAndValidate: Done.
   MagicalGoConfigXmlWriter:83 - [Serializing Config] Done with cruise config validators.
   MagicalGoConfigXmlWriter:88 - [Serializing Config] XSD and DOM validation.
   MagicalGoConfigXmlWriter:91 - [Serializing Config] Generating config partial.
   MagicalGoConfigXmlWriter:93 - [Serializing Config] Finished writing config partial.
   GoFileConfigDataSource:350 - [Config Save] === Done converting config to XML
   GoFileConfigDataSource:248 - [Configuration Changed] Saving updated configuration.
   GoFileConfigDataSource:284 - [Config Save] Checking whether config should be merged
   MagicalGoConfigXmlLoader:75 - [Config Save] Loading config holder
   MagicalGoConfigXmlLoader:78 - [Config Save] Updating config cache with new XML
   MagicalGoConfigXmlLoader:96 - [Config Save] In preprocessAndValidate: Cloning.
   MagicalGoConfigXmlLoader:98 - [Config Save] In preprocessAndValidate: Validating.
   MagicalGoConfigXmlLoader:118 - [Config Save] In validateCruiseConfig: Starting.
   MagicalGoConfigXmlLoader:124 - [Config Save] In validateCruiseConfig: Running validate.
   MagicalGoConfigXmlLoader:129 - [Config Save] In validateCruiseConfig: Done.
   MagicalGoConfigXmlLoader:100 - [Config Save] In preprocessAndValidate: Done.
   GoFileConfigDataSource:262 - [Config Save] Done writing with lock
   CachedFileGoConfig:187 - [Config Save] Saving config to the cache
```

From the logs we run validations twice before we save the config file.
Once while writing it out to xml (in memory) and the other while reloading it back if there's a merge or not. Cutting it down to one validate operation will save time.

**Comment by varshavaradarajan** [comment]
Time indicates the total time take for adding an agent to a config 4.4M in size, using the ```goConfigService.updateConfig``` method.
Before removing the extra validation
```
before-removing-validation.txt:write with lock total: 10379
before-removing-validation.txt:write with lock total: 9960
before-removing-validation.txt:write with lock total: 9722
before-removing-validation.txt:write with lock total: 10034
before-removing-validation.txt:write with lock total: 9340
before-removing-validation.txt:write with lock total: 9499
before-removing-validation.txt:write with lock total: 9575
before-removing-validation.txt:write with lock total: 8836
before-removing-validation.txt:write with lock total: 9127
before-removing-validation.txt:write with lock total: 9873
```

After removing the extra validation
``` 
after-removing-valdation.txt:write with lock total: 9966
after-removing-valdation.txt:write with lock total: 9479
after-removing-valdation.txt:write with lock total: 9391
after-removing-valdation.txt:write with lock total: 9414
after-removing-valdation.txt:write with lock total: 9150
after-removing-valdation.txt:write with lock total: 9632
after-removing-valdation.txt:write with lock total: 9449
after-removing-valdation.txt:write with lock total: 9790
after-removing-valdation.txt:write with lock total: 9296
after-removing-valdation.txt:write with lock total: 8960
```

**Comment by varshavaradarajan** [comment]
For a config of size 4.4M, the difference in the config save times for the merge flow: 

Before removing the extra validation:
```
Total time for merge flow: 15120
Total time for merge flow: 15311
Total time for merge flow: 17033
Total time for merge flow: 17284
Total time for merge flow: 14801
Total time for merge flow: 14991
Total time for merge flow: 15032
Total time for merge flow: 14681
Total time for merge flow: 14736
Total time for merge flow: 15166
```
After removing the extra validation:
```
Total time for merge flow: 11343
Total time for merge flow: 10956
Total time for merge flow: 11408
Total time for merge flow: 11342
Total time for merge flow: 10584
Total time for merge flow: 10531
Total time for merge flow: 11206
Total time for merge flow: 10821
Total time for merge flow: 10417
Total time for merge flow: 10907
```
