### ISSUE TITLE
Remove Stage Details Page from GoCD

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8506]
##### Issue Type

- Feature proposal
- Feature enhancement

##### Summary

As part of GoCD release v20.7.0, GoCD introduced stage overview, an ability to see overview of the stage and the belonging jobs' information in a modal on the dashboard itself. Which in-turn reduces the need of user visiting the stage details page.

Most of the information of the stage details page is added on the stage overview, and such page can be removed.

##### Stage Details Page contains the following unique information, which needs to available somewhere within the application:

1. Within stage details page header:
	- [ ] the CCTray link
	- [ ] force trigger next stage (when previous stage has failed, similar to manual approval)
	- [ ] Ability to see overview of older stage instance (in case of rerun, it says Run: 2 of 2 with a dropdown, where we can click and choose Run 1 of 2)

2. Stage history
	- [ ] all stage history
	- [ ] the config diff between two stage instances

3. Materials Tab
	- [ ] Detailed materials information for the current instance - contains modification and modified files.
	
4. Config Tab
	- [ ] The `cruise-config.xml` configuration used for the stage instance.
	- [ ] the configuration edited by username and time.

5. Graph Tab
	- [ ] the stage duration graph.

**Comment by MPV** [comment]
Will you still be able to bookmark/send a link to someone else which will directly show a particular stage instance and it’s status?

**Comment by sriramnrn** [comment]
I request that the stage detail page _not_ be removed. In fact, I am putting together a request to provide more info in the current stage overview which I currently find to be limiting in proper insight (we realised this during a recent "build pipelines" course that I ran).

There are many comparisons, poking about, and insights that the stage details page provides which helps the user understand the stage and the details better. During discussions, the stage details page becomes a single point of view for various insights. This greatly sets GoCD apart from Team City, Bamboo and Jenkins.

**Comment by maheshp** [comment]
The Stage overview was introduced to improve the UX around accessing the stage and job details quickly with minimal clicks. Now with the Stage overview in place, the thought was whether the Stage details page is redundant and hence this issue was  added to think about possible improvements.

Guess this requires some more thought, we are not looking at changing or removing this page in near future.

**Comment by chadlwilson** [comment]
While I do really like the new UX (makes it far easier to re-trigger a failed job; be able to watch jobs-in-progress at a glance among other things) I agree with @sriramnrn that I still find myself using stage details a lot. Here are a few specific comments on gaps with the new overlays:

* not enough places in the rest of the UI that have the all-important "compare" button. This is basically only available on stage details currently when you need to compare a "not latest" VSM, since the "history" page shows you no. The VSM display doesn't allow you to go to a compare. Neither do any of the new stage overviews.
* I find myself wishing to have a way to go straight to stage details somehow; this overview has added an extra click + mouse move to achieve this. Sometimes I already know I can't get the info I need from the overview.
* a common pattern we use is Stage 1: parallel plans/diffs >> (Manual) Stage 2: apply parallel. When using this flow, it's really annoying that each job console log (where you might review a plan/diff) opens in a new tab. Going iteratively through each job's log from the Stage Details page is much more convenient to avoid getting lost in a sea of tabs.
* Not possible to promote/trigger a manual approval stage from the overview (i think this may be the same as force-trigger next stage as mentioned in description)

I would suggest investing in the VSM display/UX (possibly via this new overview) to make it even more useful. It is one of the key amazing things about GoCD that is hard to leave behind when considering other tools, but feel it could also do with some love.
