### ISSUE TITLE
AdoptOpenJdk version support

### ISSUE THREAD

**Issue by LukeCarrier** [gocd/gocd#8736]
##### Issue Type

Bug Report/Policy Change

##### Summary

GoCD has been shipping an embedded AdoptOpenJDK build of a JRE, since a version no longer visible in the changelog, to work around Oracle's asinine licensing changes. Support for the currently shipped version (14.0.2) only lasted six months, expiring in September according to [their support policy](https://adoptopenjdk.net/support.html).

Weirdly it doesn't look as though any headroom is given to allow upgrades on non-LTS releases, with the release of the next version starting from the end of the current version. This suggests they're intended for development use, but not deployment to production environments.

##### Environment

```console
$ dpkg -l | grep ^ii | awk '{print $2" "$3}' | grep ^go-
go-agent 20.8.0-12213
go-server 20.8.0-12213

$ cat /usr/share/go-agent/jre/release
IMPLEMENTOR="AdoptOpenJDK"
IMPLEMENTOR_VERSION="AdoptOpenJDK"
JAVA_VERSION="14.0.2"
JAVA_VERSION_DATE="2020-07-14"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.vm.ci jdk.management jdk.unsupported jdk.internal.vm.compiler jdk.aot jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.httpserver jdk.incubator.foreign jdk.internal.opt jdk.jdeps jdk.jlink jdk.incubator.jpackage jdk.internal.ed jdk.internal.le jdk.internal.vm.compiler.management jdk.jdwp.agent jdk.jfr jdk.jsobject jdk.localedata jdk.management.agent jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.xml.dom jdk.zipfs"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:920d9ca23c31"
```

###### Basic environment details

N/A

###### Additional Environment Details

N/A

##### Steps to Reproduce

N/A

##### Expected Results

JRE versions shipped as part of the GoCD distribution should be supported for at least the lifetime of the GoCD release, allowing enough headroom for users to migrate to supported versions.

##### Actual Results

GoCD ships a JRE that's actively maintained for just six months.

##### Possible Fix

Adopt a policy of shipping AdoptOpenJDK LTS releases.

##### Log snippets

N/A

##### Code snippets/Screenshots

N/A

##### Any other info

N/A

**Comment by arvindsv** [comment]
The way I thought about it: The shipped JRE is now as an internal component of GoCD and it is tested etc. The shipped version should not affect anyone else looking to use their own JRE for running jobs etc. Given that, I think it's ok for it to be shipped with whatever version it does.

Supporting LTS versions: While that makes sense, the speed at which everything is moving makes it harder to do. Sometimes libraries stop supporting older (even LTS) JRE versions and newer releases of those libraries contain security fixes which are necessary.

Something very similar to what I said here is laid out in this GoCD blog post: https://www.gocd.org/2019/05/21/official-stance-on-java/

**Comment by arvindsv** [comment]
Also: I think Oracle suggested not all security fixes will be backported to the LTS version, though I might be wrong about that.

**Comment by LukeCarrier** [comment]
@arvindsv I appreciate that this is an embedded component and that from a functional perspective it doesn't matter, but I'm not sure is good security hygeine. Unfortunately the security fixes from later releases don't appear to be backported after the six months of active support ends.

We identified this as a problem because a security audit flagged the JRE as being a source of possible security issues due to the lack of support. Any of your customers using tools like Nessus/Tenable will be bitten by this, and I don't think it's reasonable to tell our customers (who often request these audits) that "we have to have it installed because the vendor said it was OK".

**Comment by arvindsv** [comment]
@LukeCarrier I'm thinking about security as well. It isn't clear that LTS versions get all the security fixes backported. Oracle hasn't, as far as I know, committed to that -- and I believe they've handed over stewardship of  LTS to RedHat, which has _claimed_ that in some places, but I'm not sure.

What I do know is that it is expected that security fixes will be made available on the latest JRE (LTS or not), and GoCD's stance is that the latest available JRE will be used in the latest release of GoCD. From a seecurity point of view, that's the right thing to do, isn't it?

Now, your thought might be: I wish to use an LTS version of the JRE, while upgrading to a newer release of GoCD. As mentioned in the blog post I linked to, it says:

> The compiler target will be adjusted every 6 months when a new Java release is out. The compiler target will be (LATEST_VERSION - 2). For example: if the current GA Java version is 15, the compiler target will be set to 13.

I'm not entirely sure that's being followed. Someone like @maheshp might know best. But, that should mean you should be able to use a slightly older version of the JRE (one which is 18 months old). But since LTS is supported for 3 years, that strategy will stop working.

Overall: My opinion is that staying with the latest GoCD release should give you the most up-to-date version of the JRE. If you do decide to move to an older version of the JRE, it _might_ work, but it won't be tested rigourously. Given that JRE versions are changing quickly and features are introduced quickly as well, setting the compiler target to (eventually) a 3-year old JRE will cause issues such as the one I mentioned with libraries earlier. I understand neither choice is perfect, but one seems to have been made for now.

I tried to find out what the newest information regarding security updates is,  but it is still not clear to me. Some information I  looked at:
  - https://stackoverflow.com/questions/60689292/security-updates-with-openjdk-distribution
  - https://blog.joda.org/2018/08/java-is-still-available-at-zero-cost.html (which does suggest that with RedHat  + AdoptOpenJDK,  LTS will mean security patches for Java 11 for 3 years)
  - AdoptOpenJDK's stance on security updates: https://adoptopenjdk.net/faq.html ["We just build upstream OpenJDK"]
  - RedHat's stance on security updates: https://access.redhat.com/articles/1299013 [See question: "How can I install multiple minor releases on the same server?". Answer seems to be: "Stay on latest (minor?) version"]
  - https://www.reddit.com/r/java/comments/cwta5r/confused_about_adoptopenjdk_and_more/
  - https://dzone.com/articles/eliminating-java-update-confusion [It didn't :)]
  - https://blogs.oracle.com/java-platform-group/update-and-faq-on-the-java-se-release-cadence

**Comment by LukeCarrier** [comment]
@arvindsv I don't agree that aiming for the latest release is always a good idea, given the 6 month support lifespan of each non-LTS release. Personally I'd rather GoCD bundled an LTS release which will outlive each release, and based on the support dates listed on the AdoptOpenJDK website those are the LTS releases, not the others.

Case in point: right now support for the currently shipping JVM expired at the end of October, and GoCD is now shipping with a baked in dependendy on an obsolete programming runtime.

I no longer work for the organisation I raised this issue for so I'll bow out of the discussion, but I hope this at least gives some insight into the problem.

**Comment by maheshp** [comment]
For the record, the latest GoCD 20.9.0 is bundled with latest JRE 15.

**Comment by marques-work** [comment]
Really late to the discussion, but AFAIK, our compiler targets are still set to 11, which is LTS, so we haven't been following "LATEST - 2"; that's only been on the source targets.

**Comment by marques-work** [comment]
Pretty sure we're not changing our JRE packaging to include JDK 11 instead.

**Comment by principiojohn** [comment]
Can help to know if this means that GoCD will be compiled with Java 11 instead of Java 15?
