### ISSUE TITLE
API Returns scheduled jobs not visible in the API

### ISSUE THREAD

**Issue by njsaunders** [gocd/gocd#8739]
##### Issue Type

- Bug Report

##### Summary

If I create a view to show all building jobs, it doesn't show all the jobs returned if you go directly to the "scheduled jobs" API. 

This resulted in a very hard to track down issue where multiple jobs got scheduled as far back as July, but due to the configuration of the ECS plugin could never be fulfilled (MinMemory < Spot instance size used).

It also appears that a scheduled job caches the configuration of the ECS plugin. This meant that even after we increased the instance size and changed the AMI ID of the ECS container instance GoCD kept launching spot instances for an old configuration that would never have jobs assigned - Really, really confusing.

###### Basic environment details

* Go Version: `20.8.0 (12213-1e23a06e496205ced5f1a8e83d9b209fc0a290cb)`
* JAVA Version: `14.0.2`
* OS: `Linux 4.15.0-1037-aws`
* Browser vendor and version (if relevant):  Not relevant

##### Steps to Reproduce

I'm not sure, but I'd guess:

1. Using the Elastic agent plugin, create a profile that has a minimum memory size of 32Gb 
2. Configure the plugin to use an instance size of 15Gb
3. Run the task
4. Wait.... a few hours? (In our case 4 months)
5. Restart go server
6. Create a view that shows "All building" jobs
7. Curl the scheduled jobs API

##### Expected Results

The number of "building" jobs shown in the UI matches that returned from the API

##### Actual Results

There are "hidden" jobs returned by the API not shown in the UI

##### Possible Fix

Guessing the query for building jobs is time limited?

##### Any other info

Related issue: https://github.com/gocd/gocd-ecs-elastic-agent/issues/4

**Comment by kritika-singh3** [comment]
> It also appears that a scheduled job caches the configuration of the ECS plugin

Yes, every job that gets scheduled has a copy of elastic agent configurations (if configured with). Even if the elastic configurations were changed, the scheduled job will still take the older configs.
You would need to cancel the current job/s and reschedule them in order for your changes to reflect. The new job/s that will be scheduled will take the newer configurations.

> There are "hidden" jobs returned by the API not shown in the UI

The extra jobs returned by the API might be:
 - pipelines which might not have been present when the specified view was created, or
 - pipelines which the current user does not have view permissions for.

The Scheduled job API had a bug which did not honor the view permissions for the pipelines and has been fixed in #8594 which will be a part of GoCD 20.9.0 release.

**Comment by njsaunders** [comment]
Understood - Thanks @kritika-singh3 - Closing issue.
