### ISSUE TITLE
Manually triggered upstream pipeline could use different revision to pipeline label

### ISSUE THREAD

**Issue by Ftelf** [gocd/gocd#8802]
Hi,
We are on GoCD 20.9.0. In one in our service pipelines I have observed very uneasy behavior.
We have three pipeline stages: DEV, STAGE and PROD. DEV and STAGE pipelines have several stages like deploy, tests, tag. There were a situation where on DEV pipelines the instance with label 2209 was completely green and tagged. But there was also new instance running but in early stages, not tagged yet, with label 2210.
The 2209 instance was revision: 330e507ba862c167785c34670936e68c4e17b069
The 2210 instance was revision: 172cb734c94822ee1cd0f10575ebfbc19104f4f3

Now we wanted new Instance on STAGE pipeline to be deployed, so we triggered pipeline manually without parametes. It was expected to took the latest tagged version, but in fact the latest started pipeline was deployed.
The version which was deployed was: 172cb734c94822ee1cd0f10575ebfbc19104f4f3
But the funny stuff, gocd says that the DEV pipeine label is 2209
'GO_DEPENDENCY_LABEL_BUILDUPSTREAM' to value '2209'
'GO_DEPENDENCY_LOCATOR_BUILDUPSTREAM' to value 'DEV-deploy-price-optimization/2209/taggingStage/1'
'GO_REVISION_OUR_SERVICE' to value '172cb734c94822ee1cd0f10575ebfbc19104f4f3'

Also the VSM says that the Instance was 2209, and it shows: "Built from incompatible revisions."
![image](https://user-images.githubusercontent.com/12624859/100617764-3d450880-331b-11eb-8882-3041801cfc48.png)

**Comment by arvindsv** [comment]
This seems to be working as intented (and that's also why the warning shows). When you force trigger (manually click the "Play" button), [fan-in](https://docs.gocd.org/current/advanced_usage/fan_in.html) does not apply and it is forced to take the latest of all its dependent materials, even if they might be incompatible.

In your case, it looks like 2209 was the latest of `Dev-deploy-price-optimization` and another SCM material it had (called "our_service"?) had its latest version as `172cb734c94822ee1cd0f10575ebfbc19104f4f3`. So, when you force triggered, it ran with those two.

It also showed the right environment variables (`GO_DEPENDENCY_LOCATOR_BUILDUPSTREAM` and `GO_REVISION_OUR_SERVICE`). And since they were forced, they were incompatible.

If you do want it to take the "correct" versions, you shouldn't force trigger. An approach to handle this properly is mentioned at the end of [this blog post](https://www.gocd.org/2017/05/23/control-deployments-manual-approvals/#a-gocd-pro-tip-for-manual-pipelines). It's part of [this blog series](https://www.gocd.org/tags/modeling-deployment-pipelines.html).

Based on that understanding of your description, I'm going to close this issue. Happy to reopen it, if I've understood this wrong.
