### ISSUE TITLE
Unpause should build latest revision

### ISSUE THREAD

**Issue by benjamin671** [gocd/gocd#8803]
##### Issue Type

- Feature enhancement

##### Summary

If I am planning multiple commits, I'd like to pause the pipeline, do the commits, then unpause the pipeline and expect the last commit to be built. Today, I unpaused the pipeline after 11 commits. The pipeline built the first 9 commits. Then the pipeline started again with the last 2 commits.

I experienced things like that with Jenkins if Subversion server and Jenkins server hat different system time, because Jenkins asked for (give me the revsion at <now>). That's why I checked the system time on Subversion server and gocd server, and they have at least the same second. Multiple seconds passed between commit and unpause pipeline.

##### Environment

GoCD server 20.9.0. Pipeline with Subversion material.

###### Basic environment details

* Go Version: 20.9.0
* JAVA Version: 15
* OS: Linux 4.4.179-99-default
* Browser vendor and version (if relevant): Google Chrome (not that it matters)

###### Additional Environment Details

Don't know

##### Steps to Reproduce

1. Create pipeline with subversion material
2. Pause pipeline
3. Make multiple commits
4. Wait a few seconds, then unpause pipeline

##### Expected Results

First build after unpause should fetch latest Subversion revision.

##### Actual Results

First build of pipeline doesn't fetch latest Subversino revision. Next build start automatically after first build and fetches latest revision.

##### Possible Fix

Don't know

##### Log snippets

Please advise what you need

##### Code snippets/Screenshots

Please advise what you need

##### Any other info

Please advise what you need

**Comment by arvindsv** [comment]
I think step 4 ("Wait a few seconds, then unpause pipeline") is what causes this. GoCD checks for new commits about once every minute. It's possible that your last two commits were missed in that check and happened in the next check.

One option is to use "Trigger with options" to see if all commits have been seen, before unpausing.

<img width="190" alt="2020_12_01_10-57-23" src="https://user-images.githubusercontent.com/172235/100732125-3920f580-33c4-11eb-948d-2f539f2408c0.png">

Other option is to click on the "Force trigger" (play button) immediately after unpausing. Force trigger will always get the latest commit (meaning, it does a material update before starting the pipeline).

Since this is behaviour that is core to how GoCD works and changing it changes too many assumptions, this is unlikely to be changed. So, I will close this issue, but happy to reopen if anything changes / we discuss something different. Thank you!

**Comment by benjamin671** [comment]
Waiting at least a minute is certainly an option.

Checking "Trigger with Options" is not, as it is disabled if pipeline is paused:

![image](https://user-images.githubusercontent.com/74495961/101458531-49dae980-3937-11eb-9405-3ca829fbada5.png)

"Force trigger" is also disabled if pipeline is paused. So it is a race between the unpause triggering the next automatic build and me pressing the "force trigger" button. On the first try, I won!

Thank you for your help.
