### ISSUE TITLE
Update material extension points to call plugin validations

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#883]
1) At present the onus is on plugin to call validations defined in the plugin. But this responsibility should move to material extension points (SCM and package repository) instead.

2) Go should validate required fields at least (just like it does from UI) and rest of it could be taken care by plugin validations

3) Currently if metadata for plugin is available, and an additional key is added to the config, then in absence of plugin validations (to validate spurious keys) the additional key gets added as part of identity causing change in fingerprint of material and leads to unexpected behaviour (like pipeline triggers again, last revision appears as changed, additional key shows up on ui etc). 
   Adding spurious keys as part of identity makes sense in scenario when plugin is missing and hence no metadata information is present but not in the case mentioned above

**Comment by arvindsv** [comment]
Isn't think true for

**Comment by arvindsv** [comment]
Isn't think true for package too? I mean, when updated through the UI, it is called. But, when updated through the XML, it is not. Right?

**Comment by arikagoyal** [comment]
@arvindsv Yes that is right

**Comment by arvindsv** [comment]
This was a performance-related decision that was taken, because a config edit would mean that every configured package repository material, every task, etc. would need to be revalidated. Might be worth thinking about it again.

It might make sense to validate on use, and cache that it is valid (or invalid), in that object, so that a change of config removes that "valid" flag.
