### ISSUE TITLE
[Q] Is it safe to remove cruise-config.xml archive files

### ISSUE THREAD

**Issue by soakes** [gocd/gocd#8896]
Hi Guys,

Just a quick question as I can't seem to find in your documentation that it's safe to remove these archive config files with a standard `rm` or if there is some specific process which you should do in order to house tidy these?

**/etc/go**
```
cruise-config.xml.7095.2018-11-02@14:37:22~
cruise-config.xml.7118.2020-02-13@10:59:54~
cruise-config.xml.7150.2018-06-26@11:59:21~
cruise-config.xml.7276.2017-05-30@15:38:03~
cruise-config.xml.7381.2018-07-06@15:58:20~
cruise-config.xml.7638.2018-07-31@10:59:11~
cruise-config.xml.7653.2018-09-12@10:18:23~
cruise-config.xml.7671.2017-10-19@12:27:03~
cruise-config.xml.7713.2018-07-31@10:59:18~
cruise-config.xml.7740.2019-03-08@09:25:29~
cruise-config.xml.776.2018-05-28@12:39:10~
cruise-config.xml.7817.2020-04-17@07:53:04~
cruise-config.xml.7895.2018-02-19@16:59:42~
cruise-config.xml.7990.2020-04-24@06:57:31~
cruise-config.xml.8044.2018-02-22@13:54:58~
cruise-config.xml.8338.2019-12-16@13:10:20~
cruise-config.xml.8365.2017-12-11@09:21:52~
cruise-config.xml.8427.2020-09-10@08:59:31~
cruise-config.xml.8462.2017-10-19@14:43:44~
..  SNIP
```
Looking forward to hearing form someone who knows :) Thanks.

Kind Regards,

Simon

**Comment by arvindsv** [comment]
@soakes Yes, it is safe to remove these files. They're _mostly_ supposed to be created during upgrades, but the format of these file names seems different. They might not be created by GoCD. However, it should be safe to remove them.

Questions like this are best asked on the [mailing list](https://groups.google.com/forum/#!forum/go-cd), since there will be more users of GoCD who would know about this.

Closing this issue.

**Comment by soakes** [comment]
Thanks for the info @arvindsv - I also wasn't aware of the mailing list.
