### ISSUE TITLE
Skip commit message regex 

### ISSUE THREAD

**Issue by Mike-Dax** [gocd/gocd#8901]
##### Issue Type

- Feature proposal

##### Summary

It's relatively common for CD systems to mutate the git repository, adding a commit with updated version numbers. It's useful to be able to skip the pipelines for this commit. Whether that be with a magic string check, a custom magic string check or a regex match.

In many ecosystems the file that contains a project version also contains dependency information, or other information that results in an inability to simply ignore any changes to that file. 

Sometimes we will have errors in the pipeline very late in the stage, but the versioning commit will have already gone out. GoCD will process that version commit next, and that commit will pass. From a cursory look of the latest pipeline run, it looks like the build succeeded when it did not. This kind of thing can be avoided with a commit message based skip.

This is a very common feature with other CI / CD systems, to name a few, [Bitbucket Pipelines](https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-faqs/), [Semaphore CI](https://docs.semaphoreci.com/essentials/skip-building-some-commits-with-ci-skip/), [GitLab](https://docs.gitlab.com/ee/ci/yaml/#skipping-jobs), [CircleCI](https://circleci.com/docs/2.0/skip-build/), [AppVeyor](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message), [Travis](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build), and [Concourse ](https://libraries.io/github/concourse/git-resource#check-check-for-new-commits)support this kind of feature.

I'd be willing to contribute for this feature, unfortunately my Java isn't strong. If this can't be added by core contributors, would it be possible to have some pointers on the best place in the code to conduct this kind of check? Thanks.

**Comment by maheshp** [comment]
This feature can be useful. I would look at adding this check when we create a [BuildCause](https://github.com/gocd/gocd/blob/fa1c20b7450a60af1434b0dcb4f473f6fa14ff18/server/src/main/java/com/thoughtworks/go/server/scheduling/BuildCauseProducerService.java#L151), during [this](https://github.com/gocd/gocd/blob/fa1c20b7450a60af1434b0dcb4f473f6fa14ff18/server/src/main/java/com/thoughtworks/go/server/scheduling/BuildCauseProducerService.java#L243) check.

We might need to consider couple of scenarios and decide on the behavior.
- GoCD does not run a build for each commit. At the time of generating the BuilCause, a pipeline can be scheduled with changes coming from one or multiple commits. What should be the behavior when a BuildCause has multiple commits where one of them needs to be skipped.
- On similar lines, a pipeline can be configured with multiple materials. We can have a BuildCause where one of the materials could have a commit which needs to be skipped.

IMO, in either case we should schedule a pipeline if the BuildCause has at least a single non-skippable commit.

**Comment by arvindsv** [comment]
> IMO, in either case we should schedule a pipeline if the BuildCause has at least a single non-skippable commit.

I agree.

**Comment by Mike-Dax** [comment]
I assume in a situation with multiple commits it would build the latest commit that isn't skipped by this filter.

With a pipeline with multiple materials, if the git commit is the singular cause for the build and it matches, the build should be skipped, otherwise continue building.

I would have thought this would be simpler to do closer to the git material itself, since commit messages are tightly bound to git?

https://github.com/gocd/gocd/blob/2451a0c4b9a8de819ac4b01e8e32afbf04dc086a/domain/src/main/java/com/thoughtworks/go/domain/materials/git/GitCommand.java#L152-L153

If this function returned the latest commit that wasn't a skipped commit, I think that would work?

I'm not sure what version of Git is used internally by GoCD, but if it uses Git 2.4+, adding `--invert-grep` and `--grep="pattern"` would do this?

It would probably be relatively simple to add the inverse of this, a feature to only build on commits that match a regex, it would require roughly the same UI changes?

Yeah just looking for this has shown me I'm very bad at reading Java codebases, I wouldn't have a clue where to start the plumbing for the UI side changes, and getting that into the above function call.

**Comment by arvindsv** [comment]
> I assume in a situation with multiple commits it would build the latest commit that isn't skipped by this filter.

If a pipeline is going to be triggered, I'd expect it would be triggered with the latest commit, even if that commit is to be skipped. I mean, if the changed commits since the last time they were checked is:

1. C1_skip (at time 10:00:00): Then, don't run the pipeline.
2. C1_skip (at time 10:00:00), C2_normal (at time 10:00:15): Then, run the pipeline with C2_normal as the latest commit.
3. C1_normal (at time 10:00:00), C2_skip (at time 10:00:15): Then, run the pipeline with C2_skip as the latest commit. [I suspect your opinion differs here.
4. C1_skip (at time 10:00:00), C2_skip (at time 10:00:15): Then, don't run the pipeline.

For scenario 3, I don't see `C2_skip` as a commit which says: "Never run against this commit", but as one which says: "Never run against _only_ this commit".

> If this function returned the latest commit that wasn't a skipped commit, I think that would work?

Yes, it would. But, the side effect would that it will look like GoCD _never_ saw that commit (till a newer commit comes on top of this). It wouldn't show in the trigger with options modal as well. It would be very hard to differentiate between a material check failing and this. It would be nice if it showed in the trigger with options, but did not run the pipeline.

> Yeah just looking for this has shown me I'm very bad at reading Java codebases, I wouldn't have a clue where to start the plumbing for the UI side changes, and getting that into the above function call.

More than just the UI, you'd need to think about where that is stored. If it's in the config, then you'll need to see if it affects the JSON/YAML pipelines as code stuff. Maybe just adding it to `SystemEnvironment` as a non-UI, changeable property will be enough.

**Comment by Mike-Dax** [comment]
> C1_normal (at time 10:00:00), C2_skip (at time 10:00:15): Then, run the pipeline with C2_skip as the latest commit. [I suspect your opinion differs here.

Yeah - that would break our workflow, this rarely happens so it would be quite surprising when finding out about it. I'm pretty sure that behaviour would be different to all the CI solutions mentioned above?

**Comment by arvindsv** [comment]
> I'm pretty sure that behaviour would be different to all the CI solutions mentioned above?

I don't know for sure.


> Would it be that surprising for a material check to display the last non-skipped commit, even in a situation like 3. above?

I would be more comfortable with changing scenario 3 to be what you expect, than to have the commit not seen at all (at the `git log` level).
