### ISSUE TITLE
Severe:  git material is causing pipeline to execute when checkin to repo occurs, even when "Poll for new changes" is unchecked 

### ISSUE THREAD

**Issue by jefftrimm** [gocd/gocd#893]
We're seeing that git materials on our pipeline are causing the pipeline to execute when a checkin to the git repo occurs, even when "Poll for new changes" is unchecked.  This is causing inappropriate executions of our deployment pipelines.

Similarly, we are seeing that if multiple pipelines have a material defined for the same git repo with "Poll for new changes" unchecked, all of these pipelines will execute if just one of the pipelines is manually executed.  There are no pipeline dependencies that would cause the other pipelines to run.

**Comment by arvindsv** [comment]
Yes, the second paragraph you mention is right. Unfortunately, that's the "expected behavior". I say, unfortunately, because I think it's confusing as well. But, people have been using it like that for years. :( You should set the first stage of a deployment pipeline that you do not want triggered by material changes, to be manual. Then, it will never be triggered, whatever happens, unless someone manually triggers it.

Can you let me know whether that works for you?

By the way, FYI, the behavior you see happens because the polling subsystem and the scheduling subsystem are different. The "Poll for new changes" is for the polling subsystem. Once someone triggers another pipeline with the same material, the scheduling system sees that a new commit exists, and it starts a pipeline run. For it, it does not care about the "Poll for new changes" flag. It cannot, because if it does, then a manual trigger would not work as well. It looks at the "manual" part of a stage approval configuration, to decide whether a pipeline should be triggered. As I said, I know it is confusing.

Ref: Info about setting stage to manual: [This](http://www.go.cd/documentation/user/current/configuration/pipeline_scheduling.html#disable-automatic-scheduling) and [this](http://www.go.cd/documentation/user/current/configuration/dev_choose_when_stage_runs.html).

**Comment by jefftrimm** [comment]
We have DEV/TST/PRD deployment pipelines all extending the same template and being automatically triggered by upstream pipelines (ex: DEV deploy: triggered by upstream pipeline executing unit/integration/acceptance tests, TST deploy: triggered by upstream release-build pipeline execution, PRD deploy: triggered by upstream manual approval pipeline)  For PRD, we have a manual approval, but it is on an upstream pipeline for PRD (this is so that the deployment pipelines can extend the same template).  

The ability to checkout SCM materials (either svn or git) without impacting execution of any pipelines is pretty important, and I can't imagine we are unique in this need.  The Materials model seems broken in this respect... if the materials model is unfixable, then it almost begs the need for Git/Svn Go Task(s) that can save credentials/URL/destination-folder for SVN/Git repos and checkout SCM artifacts with zero polling and zero impact on causing other pipelines to execute.

**Comment by srinivasupadhya** [comment]
This is being discussed on [this](https://groups.google.com/d/topic/go-cd/2d5SPXoKB3Y/discussion) thread. [This](https://groups.google.com/d/topic/go-cd/jVNNMYEgM4I/discussion) thread could be related as well.

**Comment by marcelboettcher** [comment]
find this really confusing as well. Hope that options will change in the future.
