### ISSUE TITLE
Git Material Credentials can't be changed

### ISSUE THREAD

**Issue by D3luxee** [gocd/gocd#9153]
##### Issue Type
Bug Report

##### Summary

If you try to change the user / password of an git material the checkout is still using the old user but with the password of the new user. The connection test passes while updating the material config.

##### Environment
Docker based setup tested with gocd/gocd-server:21.1.0 and 21.2.0

###### Basic environment details
* Stock gocd docker image with h2 database
* Only docker and docker swarm elastic agents

##### Steps to Reproduce

1. Create new Pipeline and define a git material with basic authentication 
2. Run Pipeline -> Success (at least the checkout)
3. Edit Pipeline and change the User + Password to another user with access to the Repository
4. Click Check Connection (will succeed)
5. Save and run the Pipeline again
Now it will fail on checkout and you will see that its using the username that you configured in the beginning but the password you set in step 3

##### Expected Results
GoCD should be able to update the credentials of git materials

##### Actual Results
GoCD does only update the password used on the material but not the user which causes the checkout to fail.

##### Any other info
This might be related to https://github.com/gocd/gocd/issues/8986

**Comment by sriramnrn** [comment]
Reopen

**Comment by gosszhang** [comment]
i have the same problem?
how to fix it?

**Comment by craig-tx** [comment]
Does anyone know of any hack to get GoCD 20.1.0 to stop using a previously configured credential for a material? I am seeing the problem reported in this ticket on 90 pipelines that are using an account that we need to change away from. Our provider [Bitbucket is deprecating support](https://bitbucket.org/blog/deprecating-atlassian-account-password-for-git-and-bitbucket-api-activity) on March 1, 2022 for using account passwords to access git, and account password is how the pipelines are currently configured.  I even tried changing the password for the "stuck" account to an app password, but that fails authentication too. I think that may be because it using the email address and not the username, and app passwords might require the username.

I have tried everything I can think of to get GoCD to stop using the old username. I stopped all agents and GoCD server, edited the config.xml so that all the pipelines using that material are set to the new credentials, restarted everything and still I can see (using Process Monitor to watch the Create Process events) that the git clone command line is using the old username and new password. I tried cloning new pipelines.  I setup a brand new agent to see if the caching was happening on the agent side, no joy.  I can only assume that the caching is happening somewhere in the H2 db, which I did not have much success trying to explore with https://razorsql.com/ .

My last resort is to setup a brand new GoCD server and recreate everything, which seems like a drastic measure.

**Comment by wkul9429** [comment]
Any update on this issue when updating username and password. I'm also facing the same issue as @craig-tx [Github has deprecated support for account passwords](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)

**Comment by chadlwilson** [comment]
@wkul9429 can you try the workaround of changing the material case as suggested in https://groups.google.com/g/go-cd/c/z-g1hqX0XGA ?

I hope to take a look at this at some point but haven't had a chance yet.

**Comment by wkul9429** [comment]
@chadlwilson we faced this issue when migrating our old repos from Enterprise Server to new repos in Github.com and material URL case modification didn't work.

I think token-based authentication, such as a personal access token (for developers) or an OAuth or GitHub App installation token (for integrators) for all authenticated Git operations on GitHub.com is required from goCD

**Comment by chadlwilson** [comment]
Other than ensuring your credential/token is correct and had the right access to the repos (using git command line), I would try brute force changing every material for that repo listed under 'Materials' (perhaps with different branches) as well as any you have encrypted as secrets (perhaps in config repositories).

There's not a fundamental problem with usage of tokens in GoCD (build.gocd.org uses these itself), just some issue with it somehow using the 'wrong' one, and you possible having an 'old' credential for a different material that it is using instead. From the perspective of Git it's just a password, and GoCD uses the git binary to do everything like this.

Alternatively you could switch to SSH based materials, but that requires mounting a private key in GoCD server and agents so not so convenient for some use cases.

**Comment by pthreat** [comment]
Dude you are literally saying you can easily edit a material for a pipeline. Setting authentication on this was an asolute PITA I see no added value out of this as the a value a merge hook would give me running a bash script behind the lines. It's no excuse that "it's free software"
