### ISSUE TITLE
Vulnerability in commons-io use by agent-bootstrapper.jar

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#9397]
##### Issue Type

When running a vulnerability scanner against gocd - https://github.com/aquasecurity/trivy in my case - it finds a **MEDIUM** vulnerability in the `commons-io` package used by `agent-bootstrapper.jar`:

```
$ trivy image --ignore-unfixed gocd/gocd-agent-docker-dind:v21.2.0

...

go-agent/lib/agent-bootstrapper.jar
===================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)

+-----------------------+------------------+----------+-------------------+---------------+---------------------------------------+
|        LIBRARY        | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+-----------------------+------------------+----------+-------------------+---------------+---------------------------------------+
| commons-io:commons-io | CVE-2021-29425   | MEDIUM   |               2.6 |           2.7 | apache-commons-io: Limited            |
|                       |                  |          |                   |               | path traversal in Apache              |
|                       |                  |          |                   |               | Commons IO 2.2 to 2.6                 |
|                       |                  |          |                   |               | -->avd.aquasec.com/nvd/cve-2021-29425 |
+-----------------------+------------------+----------+-------------------+---------------+---------------------------------------+
```

##### Summary

The agent's bootstrapper depends on a vulnerable version of `commons-io`.

##### Environment

In any of the official docker containers for version `21.2.0`.

##### Possible Fix

Update `commons-io` to version `2.7`.

**Comment by arvindsv** [comment]
Looks like this was upgraded (https://github.com/gocd/gocd/pull/8833) and then reverted (https://github.com/gocd/gocd/pull/8962). Maybe there was an incompatibility. @marques-work might know.

**Comment by chadlwilson** [comment]
Original bump to `2.8.0` was pushed in [this build](https://build.gocd.org/go/materials/value_stream_map/ef3435cfc409267ee25e484f77c3fd852eba8f5459005ff93764677728eacbcd/cffed8f8ba222f7e84e9073778b0d905622feb95) which had tests failing on Windows (example [here](https://build.gocd.org/go/tab/build/detail/build-windows/5219/build-non-server/1/FastTests-runInstance-1)).

Seemed to be some errors in `P4Material.cleanDirectoryIfRepoChanged` which uses Commons IO `FileUtils.cleanDirectory` and relies internally on `FileUtils.forceDelete`.

Accord to Commons IO changelog, `2.9.0` fixes:
> FileUtils.forceDelete(File) actually forces deletion of read-only files as it did in version 2.6. Thanks to Gary Gregory."

A whole lot of refactoring was done in `2.8` to introduce `PathUtils` and I think this was a regression from that fixed in https://github.com/apache/commons-io/commit/8ae947bcc796d73b0eab7d94f10a002f66896af3

Give Perforce checks out files in read-only unless "edit mode", I suspect it caused these failing tests, and was due to this that it got reverted?

**Comment by marques-work** [comment]
Yes, I believe that was the general issue if I recall correctly. If this is finally fixed, we should try this and merge if successful.

If you'd like to enable a windows build for the PR pipelines, you can flip a setting on the config repo `pr-pipelines`: https://build.gocd.org/go/admin/config_repos

1. Edit the `pr-pipelines` config repo settings
2. Scroll down to the section where you can define user variables
3. Change the `include.windows.pipelines` value from `false` to `true` and save

**Comment by chadlwilson** [comment]
Thanks @marques-work - I don't have GoCD admin on `build.gocd.org` just yet so can't view or edit the config repo settings at the moment, but that's useful info.
