### ISSUE TITLE
When a job is run on multiple agents or run x instances option is selected, the job details do not show up on cctray feed

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#953]
Steps to Reproduce -

1) For a pipeline, have jobs A , B and C.
2) For job A, in job settings page, select 'run on all agents' option
3) For job B, in job settings page, select 'run 3 instances' option
4) Run the pipeline. 

Note that the multiple job instances created for job A and B, do not have an entry in cctray feed while there is an entry present for job C which seems incorrect.

**Comment by arvindsv** [comment]
This is an existing issue in the current cctray implementation as well, right? I'm not going to work on it, at this point in time. It is happening because the config [is used](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/domain/cctray/CcTrayConfigChangeHandler.java#L106) when deciding the valid jobs for a stage. In the config, those instances obviously don't show. I'm marking this a low priority since the bug has existed for a long time and doesn't seem to have bothered many people.
