### ISSUE TITLE
Ability to run jobs in sequential order in addition to parallel 

### ISSUE THREAD

**Issue by bignay2000** [gocd/gocd#9549]
##### Issue Type
- Feature enhancement

GoCD Version: 21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)
##### Summary

Please add the ability to have jobs in a stage run in sequential order as an option in additon to parallel (default of parallel).

For example if stage 2 has 3 jobs, job 1 set to parallel, job 2 set to parallel and job 3 set to sequential then the third job would wait for both job 1 and job 2 to complete.  Job 1 and Job 2 would be kicked off at the same time (assuming enough slave executors are available.)

In the picture below we have stages "Continuous Integration", "https://development.example.com", "https://test.example.com", preproduction, and production.  Only a few jobs are able to be parallel in the https://development.example.com and https://test.example.com. (denoted by *).  Note that we have 100 developers and 50 testers working on a large java application currently using Jenkins with Delivery Pipeline (https://github.com/Diabol/delivery-pipeline-plugin).  Trying to port this pipeline to GoCD.  

Trying to build this with many stages each with one build to gain sequential order seems like this would not fit on a dashboard with a lot of horizontal scrolling? 

![example_pipeline](https://user-images.githubusercontent.com/11713022/127758115-c220479e-be3c-4aa1-9ec8-26d599ed0cbb.JPG)

**Comment by arvindsv** [comment]
Unfortunately that's a very fundamental decision in GoCD. That pipeline-stage-job-task are executed serial-parallel-serial. This has been brought up a couple of times:

https://groups.google.com/g/go-cd/c/laKYkq3uTyY/m/XcdQ2POLSiYJ
https://github.com/gocd/gocd/issues/3232

If I were to model this, I would look at "Pull Artifact", "Startup Application" etc as tasks within the 4 jobs denoted by `*`. Those would run serially for each of those jobs.

Since the fundamental decision is unlikely to change, I'll close this issue. But, it's possible to continue the discussion and reopen if needed.
