### ISSUE TITLE
Junit Failures not showing up on the Failures Tab

### ISSUE THREAD

**Issue by elaruwan** [gocd/gocd#9578]
##### Summary
Despite showing that there are failures on the tests tab...
![image](https://user-images.githubusercontent.com/68737042/129114621-9b35b2ef-0bf4-4b72-8c66-424f11626548.png)
No failures are displayed in the failures tab.
![image](https://user-images.githubusercontent.com/68737042/129114677-fb1138a0-5821-40c1-9ed7-747f57c17a7a.png)

##### Environment

WinSrv2019 GoCD 21.2.0
```plain
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="440" tests="1170" time="182.609375">
	<testsuite assertions="56" disabled="0" errors="0" failures="34" name="Files" skipped="0" tests="90" time="14.046875" hostname="linux-64-centos-60" id="linux-64-centos-60">
```

###### Basic environment details

* Go Version: 21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)
* JAVA Version: 15.0.2
* OS: winsrv2019 
* Browser vendor and version (if relevant): Tested on a few browsers.

##### Steps to Reproduce
1.  Generating JunitXML using python plugin https://pypi.org/project/junit-xml/
2.  Output as a TEST artifact in GoCD - ends up in testoutput
3. 
4. 

##### Expected Results
Failures are listed in the failures tab.

##### Actual Results
Nada

**Comment by chadlwilson** [comment]
Hi there - could you please include an example full JUnit XML generated? You can perhaps redact any internal information or include an example generated with your particular tool. Just looking for the structure which will make it easy to replicate.

**Comment by elaruwan** [comment]
Hi @chadlwilson, is there an example of the xml structure available somewhere that gocd takes as input?

The example below is obviously a simplified version.  The code that generates this was designed to work with Jenkins appropriate JUnit XML files.

Thanks!

```
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="440" tests="1170" time="169.34375">
	<testsuite assertions="56" disabled="0" errors="0" failures="34" name="Files" skipped="0" tests="90" time="13.03125" hostname="redacted" id="redacted">
		<testcase name="redacted" time="0.140625" classname=" redacted" file="redacted">
			<failure type="failure" message=""/>
			<system-out>File Entry Not Found in Viewer CSV From Files Test</system-out>
		</testcase>
		<testcase name="redacted" assertions="1" time="0.140625" classname=" file="redacted">
			<system-out>Scanned</system-out>
		</testcase>
	</testsuite>
</testsuites>
```

**Comment by chadlwilson** [comment]
After a bit of digging, it looks to me like this functionality (to parse JUnit output and show individual failures on this tab) may have been infrequently used and perhaps no longer be supported, maybe since GoCD `19.10`. Personally I've never used it, but I'll see if I can dig a bit to confirm.

I'd suggest that for looking at the detail of test failures, you could perhaps look at generating an HTML artifact from your build and uploading that, if the console log doesn't give you sufficient easily explored detail. You can use a custom tab to link to that artifact to explore the failures, similar to how it is done at https://build.gocd.org/go/tab/build/detail/build-linux/5537/build-server/2/ServerIntegrationTests-runInstance-1# (this is a Gradle test report artifact in this case)
