### ISSUE TITLE
Config Repos hung in updating state 

### ISSUE THREAD

**Issue by adarshk-rapido** [gocd/gocd#9588]
Would like to start by thanking you folks for the community support and the new releases/features that are happening. 

##### Summary

we have 3 gocd instances running in k8s (GKE). And the SCM we use is Github (hosted). From last few days we notice all 3 gocd in a hung state and we see all 3 stuck in material refresh. During this time we see a lot of following log

```
gocd-data-server-8444c4b66c-cqvhf gocd-server jvm 1    | 2021-08-12 14:10:10,504 WARN  [ThreadPoolTaskScheduler-4] MaterialUpdateService:188 - [Material Update] Skipping update of material GitMaterial{url=git@github.com:XXXXXXX.git, branch='master', submoduleFolder='null', shallowClone=false} which has been in-progress since Thu Aug 12 13:58:40 GMT 2021
```

We use the same github ssh key /user across all 3 instances and we have
gocd 01 - 70 config-repos
gocd 02 - 24 config-repos
gocd 03 - 33 config-repo

What we have noticed is all 3 gocd becoming slow, no new pipeline trigger during this time, even if force run them.

`GoCD Version = 20.5.0` database we use is postgres

Is it the large number of config-repo causing this issues or do we get rate limited by github if we use same ssh-key | user  ? I tried to exec to the pod and clone a repo during this time and it worked fine. 

This is not printed anywhere in log. Have you folks came across any such issues before ?

Regards
Adarsh

**Comment by chadlwilson** [comment]
A couple of preface questions
- Is there a reason you're focusing on the config repos rather than regular git materials?
- How many different normal git materials do you have defined by pipelines in these config repos?
- And are your regular materials also GitHub-hosted repos?

In a general sense _as a user_ I have seen GoCD end up in a "go-slow" state when things end up blocked on database connections, **or** when material updates are too slow (sometimes these have been related). If it's the DB the whole UI might feel laggy. If it's materials, pipelines will generally fail to trigger in a timely fashion and not give you great UI feedback. The whole UI going slow is what I saw in #8730 although that was related to regular materials and a bug specific to H2 database connections available to GoCD, but it created a backlog of material updates as a side effect. Subsequent to upgrading and fixing this issue, in one environment I was using GoCD we focused on trying to improve clone/fetch speed to reduce pressure on the material subsystem.

Pipelines will appear to not trigger when there is contention on material updates because GoCD needs to check the latest revision before it kicks off the pipeline, and thus relies on a material update.

That sure is a lot of config repos (and I imagine you have a lot of materials also using GitHub?), and getting rate limited by GitHub is certainly a possibility, although I'm not personally sure if that would manifest in errors, or just "go-slow" when using ssh. When you execed into the pod, 
- did you clone using the same user/key as GoCD is using? If so, that's a bit weird
- did you notice how many `git`|`ssh` processes were running at that time?

It may be that you just have contention. The default polling interval is 60s, I believe for both regular materials and config materials/repos (someone can correct me if I am wrong). If the average time for a fetch is too great, you can effectively have a backlog (or growing trigger latency) forming.

I may not have the math quite right, but I believe to avoid such a backlog forming, I think a constraint like the below must be formed
```
meanTImePerMaterialUpdateSecs * numberOfPollingMaterials / numberOfmaterialCheckThreads(def=10) < materialUpdateIdleInterval(def=60s) 
```
I believe there is a similar calculation for config repos, and think there are fewer threads checking these by default (see below).

The way I think about it, you can either
- take pressure off the polling part of the material subsystem by moving to webhooks as suggested by Mahesh at https://github.com/gocd/gocd/issues/8862#issuecomment-750043197
- increase the minimum idle interval and get less frequent triggers after commits (`material.update.idle.interval`). I am not 100% sure if this affects config repos, however.
- try and increase parallelism (`material.check.threads` (default=10) and `material.config.check.threads` (default=2) but that may be inadvisable and just push the problem elsewhere, so should probably be done carefully and step-by-step.
- try and reduce time taken per update/clone/fetch
    - running mirrors of your repositories locally if the GitHub time is what's causing it?
    - improve performance of the disk it's cloning/fetching onto (can be relevant in some cloud environments and with some repo types)

**Comment by adarshk-rapido** [comment]
Thanks @chadlwilson we have upgraded the version of GoCD also we noticed some errors in our NAT Gateway as we are running GoCD in a private k8s cluster. We have scaled up our NAT Gateway and the issue seems to be have resolved for now. Moving to webhook is definitely an option and thanks for the detailed response appreciate.

**Comment by chadlwilson** [comment]
Potentially related to #9692, #8565
