### ISSUE TITLE
GOCD new version with build-in Java 15.0.3+

### ISSUE THREAD

**Issue by principiojohn** [gocd/gocd#9635]
Issue Type
Summary
Let us know which GOCD version support the Java 15.0.3.

After install GOCD 21.2.0 , GOCD build-in Java version is 15.0.2.
To fix Java vulnerability with Java 15.0.2, we would like to know the GOCD new version.
Kindly advise us.

Basic environment details
Go Version: 21.2.0
JAVA Version: 15.0.2
OS: Linux 3.10.0-1160.36.2.el7.x86_64
Browser vendor and version : Google chrome 86.0

is it possible that we use a LTS version of java, like java 11?

**Comment by chadlwilson** [comment]
Some discussion regarding the LTS policy is on #8736.

There appear to be additional challenges regarding `15.0.3` because
- GoCD bundles AdoptOpenJDK, per https://www.gocd.org/2019/05/21/official-stance-on-java/
- AdoptOpenJDK is in the middle of moving to Eclipse Adoptium
- There appears to be no AdoptOpenJDK `15.0.3` builds. I don't really know why; maybe mixed up in the move to Eclipse Adoptium or technically past their [support policy](https://adoptopenjdk.net/support.html#roadmap) (since they had `16.x.y` builds already available by [April 20 when `15.0.3` was released](https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2021-April/005848.html)).
- Moving to Java 16 is the only option while staying with AdoptOpenJDK/Adoptium I believe. Need to address #9469 (and possibly other aspects) to do so.
