### ISSUE TITLE
Agent intermittently fails when checking if a job isIgnored

### ISSUE THREAD

**Issue by goeranu** [gocd/gocd#9641]
##### Issue Type
Bug Report

##### Summary
We occasionally see the error message

    org.apache.http.NoHttpResponseException: gocd.service.cloud.jeppesensystems.com:443 failed to respond

and jobs fails because of this.

##### Environment

```json
{
  "Go Server Information": {
    "Version": "21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)"
  },
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "4.18.0-305.el8.x86_64",
    "System Architecture": "amd64",
    "Available Processors": 12,
    "Average System Load": 15.23
  },
  "Runtime Information": {
    "Name": "137@gocd-server-7db754cd5c-skzb2",
    "Uptime (in Time Format)": "[About 236 hours, 58 minutes, 0 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "15",
    "Input Arguments": [
      "-Xms512m",
      "-Xmx1024m",
      "-XX:MaxMetaspaceSize\u003d400m",
      "-Duser.language\u003den",
      "-Duser.country\u003dUS",
      "-Djruby.rack.request.size.threshold.bytes\u003d30000000",
      "-Dplugin.cd.go.contrib.elastic-agent.openstack.log.level\u003dinfo",
      "-Dplugin.cd.go.contrib.elasticagent.kubernetes.log.level\u003dinfo",
      "-Dgo.config.repo.gc.periodic\u003dY",
      "-Dgo.config.repo.gc.aggressive\u003dY",
      "-Dgo.config.repo.gc.cron\u003d0 10 * * * ?",
      "-Duser.timezone\u003dEurope/Stockholm",
      "-Xmx15g",
      "-Dgo.console.stdout\u003dtrue",
      "-Djava.library.path\u003dwrapper",
      "-Dwrapper.key\u003dITPRkOpCvNt7QpD-8g2t3xtOmi8uWKCy",
      "-Dwrapper.port\u003d32000",
      "-Dwrapper.jvm.port.min\u003d31000",
      "-Dwrapper.jvm.port.max\u003d31999",
      "-Dwrapper.pid\u003d118",
      "-Dwrapper.version\u003d3.5.41-st",
      "-Dwrapper.native_library\u003dwrapper",
      "-Dwrapper.arch\u003dx86",
      "-Dwrapper.cpu.timeout\u003d10",
      "-Dwrapper.jvmid\u003d1",
      "-Dwrapper.lang.domain\u003dwrapper",
      "-Dwrapper.lang.folder\u003d../lang"
    ]
  }
}
```

##### Steps to Reproduce

We have no reliable reproducer. It just happens occasionally.

##### Expected Results
The job should complete.

##### Actual Results
The job fails.

##### Possible Fix
We tried the below patch (on after commit 15cf8df9e6f97aeb168a80fe131ea02833ed94b6), and it seems to fix the problem. We see log entries with the logs, typically a burst during the same second. Our reasoning for returning _false_ on communication failure is that this is the common case, and will in any case not make things worse.

```
--- a/agent/src/main/java/com/thoughtworks/go/agent/RemotingClient.java
+++ b/agent/src/main/java/com/thoughtworks/go/agent/RemotingClient.java
@@ -97,7 +97,12 @@ public class RemotingClient implements BuildRepositoryRemote {
     @Override
     public boolean isIgnored(AgentRuntimeInfo info, JobIdentifier jobId) {
         // Boolean.parseBoolean is JSON compatible for this specific case, but probably faster/simpler than Gson
-        return Boolean.parseBoolean(post("is_ignored", new IsIgnoredRequest(info, jobId)));
+        try {
+            return Boolean.parseBoolean(post("is_ignored", new IsIgnoredRequest(info, jobId)));
+        } catch (RuntimeException e) {
+            LOG.warn("RuntimeException in isIgnored");
+            return false;
+        }
     }
```

**Comment by goeranu** [comment]
Thanks for a quick reply. Here comes a not as quick follow up:

- We have not seen any of the errors in any other context, only in this "isIgnored" place.
- We have not seen any traces of the problem in the logs on the server or reverse nginx proxy.
- By googling the combination of the Java HTTP client and nginx, we have added a configuration in the Kubernetes annotations for nginx
  ```
  nginx.ingress.kubernetes.io/configuration-snippet: |
         keepalive_timeout 0;
  ```
  This appears to be another way to work around the problem; we have not seen the issue after this change.
- We attach a log excerpt illustrating the error from the agent with debug logging enabled. The error appears on line 89.

[gocd-agent-log.txt](https://github.com/gocd/gocd/files/7089980/gocd-agent-log.txt)

**Comment by chadlwilson** [comment]
Right!

Although I'm still not sure why it might only affect `isIgnored`, I wonder if what is happening is that some kind of load balancer (or NGINX itself) is dropping long-lived connections in a way that the agents don't know about it and/or don't retry, e.g a network load balancer in front, depending on your approach to getting traffic into your cluster, and approach to getting traffic out of wherever your agents are. The GoCD agent does appear to enable TCP keepalives on sockets, however I think it is taking the system level interval which might be larger than that for some component on your traffic path.

In any case, when you disable keepalives via NGINX like that it'll be single request per connection, which if it prevents errors, does imply something network level might be going on. NGINX also has `keepalive_requests` which will close connections eventually regardless of their lifetime, however normally that would mean an appropriate response header would be sent back to the agent and it'd know its connection is gone, so it wouldn't try to use it for requests. 

If you wanted to dig further, you could determine from your logs when `http-outgoing-273` was first created/initiated and when it was last used prior you might be able to compare to the error timestamp of `2021-07-01 09:58:21,751` and determine whether it looks like a max connection or max connection **idle** lifetime has been hit due to not being used for a while.

I believe the client inside the agent will retry 3 times by default, but **not** if it has already sent the request (i.e not in your cause where it looks like it has gone into a black hole with no TCP ack/response). It's also possible to disable the keepAlives on agent/client side I believe, but I'm not sure it is possible to alter the "max idle time" of a connection by config, e.g to ensure it doesn't try to use a connection that hasn't been used for a while.

I imagine disabling the keepAlives might have other downsides for you, such as possibly making it laggier to watch build output logs and such?

**Comment by goeranu** [comment]
To explain the routing a bit better, we are running GoCD in a Kubernetes cluster. The nginx ingress mentioned above is Kubernetes' _ingress_. That is the ingress we have modified. That ingress will then forward the connection to the GoCD server over Kubernetes' internal network.

Looking at `http-outgoing-273` in the log file, it first appears `09:58:10`, 11 seconds before the problem occurs. The request sent at that time gets a reply `09:58:21,211`. Then, half a second later, at `09:58:21,750` the next request is done, the request that fails.

We note that the _end of stream_ reply to the second request comes at the same millisecond the request is sent. My guess would be that the connection is already closed on the OS level at that time, but the Java library doesn't discover or handle the situation correctly.

We are indeed a little concerned our workaround with no keepalive will have negative impact in other ways. We haven't seen anything obvious yet, but we would prefer not to have to use it.

I attach the complete log in case you might be able to figure out anything more.
[gocd-log.gz](https://github.com/gocd/gocd/files/7098609/gocd-log.gz)

**Comment by chadlwilson** [comment]
From the fuller logs there are quite a few errors (I/O timeouts, ping timeouts, failed uploads of console logs to the server etc) so I think at root cause of the problem is some kind of networking issue between your agent and the server. If you search for `end of stream` you will see a few of these subsequent errors, most of which are being retried depending on when they are being detected. I'm also a bit surprised by how many `end of stream`s there are given keepalives are on, but I haven't dug into a lot of agent logs like this to know what is "normal".

I was running GoCD in a previous setup with long-running static agents in one cluster and server in a different cluster (different VPCs, both AWS), coming through an AWS NLB to a `NodePort` service for the NGINX ingress controller (with TLS terminating at the ingress) and didn't observe such problems. 

Personally, I would be trying to run my own simple tests through to the server from the agent environment/host (from curl, or something like that with both keep-alived and single-shot requests) and trying to establish how reliable the connectivity is to try and trace where the problem is, and where connections are being dropped/requests timing out etc - perhaps correlate to ingress logs etc.

Having said this, it'd probably be better if the agent didn't behave in such a way under unreliable network conditions and was able to recover more cleanly without failing jobs. I'm just not personally sure of the consequences of changing the code to do so :-)

**Comment by goeranu** [comment]
There are indeed more errors than we had realised in the log. Thank you for taking the time to analyse it further.

We are trying to reproduce the problem without involving the GoCD agent. We couldn't figure out a way to use `curl` which would expose the reuse of a connection kept alive after 10 seconds or so, but we have made a Python script doing so. So far we haven't been able to see anything out of the ordinary; the connection lives and works until the keepalive timeout (or request count, whichever comes first) is reached. After that time the connection is closed as expected, and the script creates a new. This method does seem to trigger anything strange in the network. We will continue trying, and report back if we succeed in finding anything.
