### ISSUE TITLE
XUnit test artifact doesn't get parsed when it is not formatted 

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#983]
Specifically, it does not work when the XML prolog line (`<?xml ...>`) is in the same line as the rest of the file. For instance, a file like this:

```
<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="test" skips="0" tests="1" time="0.1"><testcase classname="class1" name="test_class1" time="0.01"/></testsuite>
```

This happens because the [UnitTestReportGenerator](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java#L158) skips the prolog line in a bad way, skipping the whole file, in this case.

**Comment by arvindsv** [comment]
Here's a failing test for it (for [UnitTestReportGeneratorTest](https://github.com/gocd/gocd/blob/master/common/test/unit/com/thoughtworks/go/domain/UnitTestReportGeneratorTest.java)):

```
@Test
public void shouldParseXUnitFileWhenPrologTagIsInSameLineAsRestOfFile() throws Exception {
    context.checking(new Expectations() {
        {
            one(publisher).upload(with(any(File.class)), with(any(String.class)));
            one(publisher).setProperty(new Property(TOTAL_TEST_COUNT, "1"));
            one(publisher).setProperty(new Property(FAILED_TEST_COUNT, "0"));
            one(publisher).setProperty(new Property(IGNORED_TEST_COUNT, "0"));
            one(publisher).setProperty(new Property(TEST_TIME, "0.010"));
        }
    });

    String validXUnitXMLInOneLine = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
            "<testsuite errors=\"1\" failures=\"0\" name=\"test\" skips=\"0\" tests=\"1\" time=\"0.1\">" +
            "<testcase classname=\"class1\" name=\"test_class1\" time=\"0.01\"/>" +
            "</testsuite>\n";
    InputStream input = new ByteArrayInputStream(validXUnitXMLInOneLine.getBytes(StandardCharsets.UTF_8));;
    copyAndClose(input, target("test-result.xml"));

    generator.generate(testFolder.listFiles());
}
```

The test succeeds if you put a ```\n``` after the prolog tag.

**Comment by RehanSaeed** [comment]
+1

**Comment by thepirat000** [comment]
This is very annoying bug.
At least you should output somewhere that the result xml has no data or cannot be parsed.

I was using a transformation provided by xUnit, to convert xUnit xml format to NUnit format (so go cd can parse the result):
https://raw.githubusercontent.com/xunit/xunit/master/src/xunit.console/NUnitXml.xslt

But since it generates the xml as a single line, it is silently ignored by go cd, and I just see the message "This project doesn't have any tests" on the Tests tab.

The solution was to add the new line on the transformation.
Here is the final xslt working:
https://github.com/thepirat000/Go-CD-Tools/blob/master/NUnitXml.xslt

Now I see the tests on the corresponding tab.

**Comment by ketan** [comment]
Closing as dup of #266

**Comment by androiddrew** [comment]
So I have been cruising around on this issue and @ketan keeps closing as dupe(s), but referencing different tickets. I keep circling around the same issue posts, and there never seems to be a fixed merged that works. JUnit XMl is still being skipped if it's minified even in v20.2.0.
