### ISSUE TITLE
Set environment variables before fetching git/scm materials

### ISSUE THREAD

**Issue by badbort** [gocd/gocd#9887]
##### Summary

As title. I have a massive repo with GIT LFS enabled and only want to clone what I need.  I ended up testing locally and confirming that settings the env var GIT_LFS_SKIP_SMUDGE to 1 would skip all loading of lfs content. 

This reduces a cloning time down significantly. I can then run git tasks to pull lfs content with specific filters.

A local experient running these commands in powershell showed success, so I started adding this env var in my pipelines along with some additional powershell scripts.

However, this had no effect I found environment variables are set after the git material is cloned.

```
[go] Start to update materials.

[go] Start updating CadModels at revision 50e35008a9341c3fdff543f4ed83ea9fbec644aa from <git repo>
STDERR: Cloning into 'D:\Agents\go-agent-20.6.0-1\pipelines\<snip>

<snip>
[go] setting environment variable 'GO_MATERIAL_BRANCH_INDIPUBLISH' to value 'main'
[go] setting environment variable 'GO_MATERIAL_INDIPUBLISH_HAS_CHANGED' to value 'true'
[go] setting environment variable 'GIT_LFS_SKIP_SMUDGE' to value '1'
```

Is this something that can be changed without any repercussions?

###### Basic environment details

```
Server Info
Go Server Version:20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9)
JVM version:13.0.2
OS Information:Windows 10 10.0
Usable space in artifacts repository:211.38 GB
Pipelines Count:225
```

**Comment by chadlwilson** [comment]
Let me preface this by saying that I am not deeply familiar with Git LFS - so you can take my thoughts with a grain of salt. Generally I recommend people use dedicated artifact stores for artifacts (whether internal GoCD artifacts or external stores such as Nexus, Artifactory, S3 etc etc) rather than git LFS, as I've seen folks tie themselves in knots with managing it in deploy/build automation systems with scripting and such.

> However, this had no effect I found environment variables are set after the git material is cloned.

Putting that aside, if you want your env var to take effect, the env var should work fine if you set it in the process context where GoCD Server (if relevant) and the agents are running, i.e it should propagate through the environment to all git commands they run. But that makes it a global setting, so must be the default behaviour you want for all pipelines and clones on those agents.

I believe another alternative is `git lfs install --skip-smudge`, i.e setting it as the default when you install `git lfs` on your hosts, which I believe preconfigures the global git config.

Another 3rd alternative is presumably manually configuring the git config. If you are running your server or agents as docker containers (inside or outside a cluster) you can mount the `.gitconfig` into them.

If it's only relevant to the agents (server clones are `--no-checkout` by default, so possibly avoid the lfs overhead?) and you are concerned about setting it globally for your existing agents you could consider using "resources" or "environments" to separate groups of agents that either have the smudge filter disabled vs enabled.

> Is this something that can be changed without any repercussions?

If your question is whether it will have any repercussions to change the ordering of clone vs set env vars in GoCD code itself, I imagine it will. For a start, there's no way to make such a change backward compatible in the general sense, and it would change the permissions model to allow someone with access to edit a pipeline's env vars, to also have permission to change the way the agent clones/fetches that repo. Since you can do some pretty funky stuff with `GIT_` env vars (let alone others) that control the clone process and do script stuff, I imagine that's not something to take likely. With an attacker mindset I would be thinking about whether there is a way I could potentially use the `GIT_*` env vars to exfiltrate the secrets used to authenticate with the repo; which may not be visible to an end user normally (keeping in mind that access to run arbitrary commands/scripts on an agent can give you a lot of access anyway)

**Comment by badbort** [comment]
> Putting that aside, if you want your env var to take effect, the env var should work fine if you set it in the process context where GoCD Server (if relevant) and the agents are running, i.e it should propagate through the environment to all git commands they run. But that makes it a global setting, so must be the default behaviour you want for all pipelines and clones on those agents.

Ah yes, this is a great idea, thanks for your input.

Using a separate artifact store or custom approach is on the roadmap for me, just low on the list as gocd has been working nicely so far
