### ISSUE TITLE
There is a vulnerability in  jQuery 2.2.4,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [gocd/gocd#9891]
https://github.com/gocd/gocd/blob/86b555e57daccec6b53b246f0dcdd4d0090566ef/server/src/main/webapp/WEB-INF/rails/package.json#L32

CVE-2019-5428 CVE-2020-11022 CVE-2020-11023 CVE-2015-9251 CVE-2016-10707

Recommended upgrade version：3.5.0

**Comment by chadlwilson** [comment]
I have gone through and reviewed these vulnerabilities in #10673 and none aloearnto be exploitable on GoCDa with its usage. Obviously the libraries are EOL and need to be upgraded or removed, however the risk here appears to be low so closing this since it doesn't add any additional information above our OWASP dependency check reports.
