### ISSUE TITLE
There is a vulnerability in AngularJS 1.0.8,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [gocd/gocd#9892]
https://github.com/gocd/gocd/blob/86b555e57daccec6b53b246f0dcdd4d0090566ef/server/src/main/webapp/WEB-INF/rails/yarn.lock#L1778

CVE-2019-10768 SCA-2021-990 SCA-2021-961 CVE-2020-7676 CVE-2019-14863

Recommended upgrade version：
1.8.0

**Comment by chadlwilson** [comment]
I have gone through and reviewed these vulnerabilities in #10673 and none aloearnto be exploitable on GoCDa with its usage. Obviously the libraries are EOL and need to be upgraded or removed, however the risk here appears to be low so closing this since it doesn't add any additional information above our OWASP dependency check reports.
