### ISSUE TITLE
autoregister.properties and environment variable support

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#992]
autoregister.properties file does not appear to support environment variables. If it did, this would make configuring agents much simpler.

**Comment by ketan** [comment]
Could you provide an example of some of the things you're looking to do?

**Comment by benzvan** [comment]
Sure,

Every one of our agents gets two resources based on the first part of their hostname so that we can identify the actual host or host group individually. So being able to set agent.auto.register.resources=${HOSTNAME%%.*} would allow us to use the same autoregister.properties by default and without using puppet to edit an .erb file.

**Comment by ntnn** [comment]
We require this as well. We have multiple agents per machine, some for different GoCD masters.

Putting the file in the installation directory renders it useless for us, since then all agents on the same machine would use the same properties - even though they are for different masters.

Making the agents configurable via parameters, environment variables or to allow more paths (e.g. in the home directory of the user) would make it much more useful.
