### ISSUE TITLE
Pipeline Approvals

### ISSUE THREAD

**Issue by djdta** [gocd/gocd#9926]
##### Issue Type

- Security issue? [**DO NOT** report it here. Please use [hackerone](https://hackerone.com/gocd) to report the issue.]
- Bug Report
- **Feature proposal**
- Feature enhancement
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

##### Summary

Currently, there is no ability to have pipelines be manually approved before moving to a different stage of the deployment.

##### Environment
Kubernetes KinD
Deploy through Helm
Server
Agent

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1.  Configure a Pipeline
2. See if you can have a approver to the pipeline before moving to the next stage
3. 
4.

**Comment by chadlwilson** [comment]
The GoCD approach to this is to mark stages as "manual" as in https://docs.gocd.org/current/configuration/dev_choose_when_stage_runs.html and https://www.gocd.org/2017/05/23/control-deployments-manual-approvals.html by removing automatically triggering and then configure _pipeline group_ or _stage_ **permissions**. Similarly if using pipelines-as-code with JSON or YAML definitions, the section is even called Approval: https://github.com/tomzo/gocd-yaml-config-plugin#approval

This works because a manual stage requires a real user with "operate" permissions to trigger it via the UI or API - that triggering is considered "approval". And you can either control these permissions at pipeline group level, or make the "approval" stage have separate roles or users.

GoCD does not model a special approval role or any kind of "two people need to approve" - you just construct your permission roles, pipeline groups and stage "operate" permissions to achieve that.

Closing this as GoCD does support this - let me know if it doesn't meet your needs and we can possibly re-open a more specific ticket.
