### ISSUE TITLE
Replace Centos8 images because of EOL

### ISSUE THREAD

**Issue by fire** [gocd/gocd#9940]
##### Issue Type

Bug Report

##### Summary

CentOS Linux 8 will reach End Of Life (EOL) on December 31st, 2021. 

https://www.centos.org/news-and-events/1322-october-centos-dojo-videos/

##### Environment

Docker / Kubernetes

###### Basic environment details

All

###### Additional Environment Details

All

##### Steps to Reproduce

On December 31st, 2021, Centos becomes end of life. Unclear if updates of docker images will occur.

##### Expected Results

Centos becomes end of life. https://github.com/gocd/docker-gocd-server-centos-8 becomes EOL.

##### Actual Results

It has not happened yet.

##### Possible Fix

Replace Centos with Rocky Linux. See https://github.com/gocd/docker-gocd-server-centos-8

##### Any other info

https://hub.docker.com/r/rockylinux/rockylinux

Can work on this, but need guidance.

**Comment by chadlwilson** [comment]
Yeah, this is a valid concern.

Rocky Linux is one option. Switching to CentOS Stream 8 and being a bit further on "the edge" of RHEL than with the old Centos is another option. And then there's AlmaLinux. Personally, I'm not really sure what is best, but personally I think we already maintain too many Docker images (mainly in agent variants) 😓

One annoyance is the existing official CentOS Stream 8 Docker images are rather bloated compared to the old ones. (231MB vs 422 MB uncompressed currently). I note the base rockylinux distro is 205MB so closer to original.

Would you have a particular reason to choose Rocky vs CentOS Stream vs other options?

**Comment by fire** [comment]
Well I wouldn't pick CentOS Stream 8 because it introduces new untested features / code.

You could pick AlmaLinux and RockyLinux, but the main problem is Centos Stream 8.

**Comment by chadlwilson** [comment]
> Well I wouldn't pick CentOS Stream 8 because it introduces new untested features / code.

I don't think it's accurate to describe it as having "untested" features. It's just a more regular stream of smaller changes tested via automated pipeline in continuous delivery style, rather than a big batch all hitting the GoCD docker images every time a point release comes out (and GoCD also releases after that point release). Since GoCD don't currently do daily/weekly rebuilds of docker images against the upstream base image, even *if* there is some instability introduced, chances are the bulk of that isn't hitting GoCD server or agent images due to our own infrequent rebuilds.

> You could pick AlmaLinux and RockyLinux, but the main problem is Centos Stream 8.

The trade-off at the moment seems to be a question of whether we think there is higher likelihood of Stream surviving with an active user and maintenance base, or something like Rocky/Alma. Probably that will take time to know.

It's a little discouraging though that the initial Stream 8 docker image seem to have so much more stuff in them than the original Centos 8, makes it less of a drop-in replacement. Stream 9 seems small though (150MB unpacked), so it's confusing. The interest here for a Docker image that really only needs what is required to run a JVM (and have a packaging system to allow users to layer on top on the agent side) so generally have a relatively low attack surface area.

> After something thinking, I think you need to support every one of them :(. Whatever there are people using it.

That's probably not realistic. GoCD does not have a lot of active maintainers right now, and arguably even the existing set of agent image variations is a bit too much to maintain. If people have their own requirements, they can always build their own Docker images with a `sed` on one of the official [server](https://github.com/gocd/docker-gocd-server-centos-8) or [agent](https://github.com/gocd/docker-gocd-agent-centos-8) Dockerfiles anyway.

**Comment by fire** [comment]
I agree that picking one of the choices is better than all of them. Please pick one before then.
