### ISSUE TITLE
Can't add user into a GoCD role behind CloudFlare minification proxy

### ISSUE THREAD

**Issue by leowwang** [gocd/gocd#9964]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: 21.3.0 
* JAVA Version: 15.0.2
* OS: Linux 5.4.129+
* Browser vendor and version (if relevant): Chrome 96.0.4664.93

##### Steps to Reproduce

1. MainNavigation:ADMIN->Roles configuration
2. Add  a new GoCD Role.
3. Edit the role just created. Add a user and Save .

##### Expected Results

The user was added into the role.
##### Actual Results

An error showed up like:Someone has modified the configuration for role 'XXX'. Please update your copy of the config with the changes and try again.

##### Possible Fix

sorry

##### Log snippets

sorry

##### Code snippets/Screenshots

![image](https://user-images.githubusercontent.com/37366935/146535750-cc6ef3af-8ed6-4b3b-a835-cd1ec3a2d017.png)
##### Any other info

sorry

**Comment by chadlwilson** [comment]
This seems to be similar to that reported with #9405.

Unfortunately without some history of the edits made to that role/configuration from the logs or the GoCD configuration repository it's difficult to know what happened. Have you found any workaround to get past this error? That might give us a clue as to what happened?

**Comment by leowwang** [comment]
Sorry for the delay in posting a reply.

We can add users to groups using gocd GUI using User Management tab. 
![image](https://user-images.githubusercontent.com/37366935/147309283-980ce41f-6949-42a2-accb-177cdab7330f.png)
And we can update the configuration for config.xml without any issue.

Also we tried to call the api go/api/admin/security/roles/xxx with providing the  if-mathch without "W/" characters in request header and it worked.
![image](https://user-images.githubusercontent.com/37366935/147310682-5413d862-cad8-4e8f-bffb-e2de1af0438e.png)


Thanks for your quick response.

**Comment by chadlwilson** [comment]
Are you still getting errors editing that role via the UI after editing it via the API and config.xml as you mentioned above?

**Comment by leowwang** [comment]
Yes, the error still showed up.

**Comment by leowwang** [comment]
By the way , I didn't find any log when the error showed up .

**Comment by leowwang** [comment]
Sorry about the misoperation above.

**Comment by chadlwilson** [comment]
How did you find the correct ETAg to use for your API update call? Did you make a GET on the API directly to figure it out?

The error indicates the ETag that the UI is sending in its call to the API is wrong/out-of-date and not matching, so I am wondering how you found the correct one to use.

**Comment by chadlwilson** [comment]
I still cannot replicate this unfortunately. Which plugins do you have installed, in particular for role-based authorization?

**Comment by leowwang** [comment]
I got the whole request info using Chrome Developer Tools when I clicked save button . 
For example：
I got the ETag like this:if-match: W/"309989cb0de79371f62db15922b7edfd5d89a62ddaaaa02fa914dbc7f13855a9--gzip"  
I called API using this ETag:if-match: "309989cb0de79371f62db15922b7edfd5d89a62ddaaaa02fa914dbc7f13855a9--gzip" ,I deleted the "W/" characters.

**Comment by leowwang** [comment]
Please check the plugins we installed.
![image](https://user-images.githubusercontent.com/37366935/147328900-c43aef9d-dc6c-4404-830d-e006c4cacf82.png)

**Comment by chadlwilson** [comment]
Interesting, so the theory is that the ETag has the correct hash value from the server (`"3099..."` etc), but the problem is that somehow it is a "weak" ETag with the `W/` prefix that is being sent, whereas it should be sending it as a strong ETag to have the API accept it.

Are you able to see with the developer tools if the ETag value coming back from the `GET` request for that role also includes the `W/` in the response headers? If you are able to share the JSON content of the role (redacted) that might help me figure out what is going on also.

**Comment by leowwang** [comment]
Yeah,I got it.
![image](https://user-images.githubusercontent.com/37366935/147330786-a29e9871-d6db-46f3-a318-f7f2a0de1d56.png)
Here is the response:
![image](https://user-images.githubusercontent.com/37366935/147330986-1d7507c8-0bda-47a9-8488-132890cca646.png)
I hope it can be helpful.

**Comment by chadlwilson** [comment]
Interesting, I am not sure how that became a weak etag. I don't think GoCD ever creates those.

Also, do you have a CDN or some sort of other caching proxy between your browser and the GoCD server? CloudFlare? Some reverse proxy?

**Comment by chadlwilson** [comment]
Based on the `cf-ray` response headers, looks like Cloudflare is there. I might need to re-read https://support.cloudflare.com/hc/en-us/articles/218505467-Using-ETag-Headers-with-Cloudflare and think about the consequences

**Comment by leowwang** [comment]
Thank you for your time. If you need more info , please tell me.

**Comment by arvindsv** [comment]
Maybe the conversation in https://github.com/gocd/gocd/issues/6278 will help (at least around whether GoCD should consider weak == strong).

**Comment by chadlwilson** [comment]
Thanks @arvindsv - I just came across that. I think the challenge here is that some proxies reserve the right to change the strong etags to weak (especially if they recompress responses), indeed that's what Cloudflare's documentation says they do without a page rule requiring enterprise plan, and is probably in line with the RFCs. However it says

> Without a Page Rule, Cloudflare preserves strong ETags set by the origin web server if:
>  * the content is gzipped on the origin server,
>  * the origin sends the gzipped content with a strong ETag header, and
>  * Rocket Loader, Minification, Email Obfuscation, and Railgun features are disabled.

The first two we should be doing sufficiently to stop it being the reason for conversion, but the 3rd point is out of our control and seems legit use of Cloudflare. My guess is Cloudflare minification is the main thing that might cause this (if it does so for JSON); I believe quite a lot of GoCD JSON is not pre-minified, so there is capacity for a proxy to minify and recompress.

Updating by Users Management probably works because these updates are a bulk `PATCH` and there is no ETag or race-condition detection involved. I suspect this problem might occur on most of the CRUD APIs though, so it's curious it's been reported mainly against role edits and plugin settings (#9405), not other APIs.

I am thinking that 
* possibly the UI should convert any weak etags to strong before including in `If-Match` headers if we are to continue with strong etags and strong etag validation on the backend, but need to think through the consequences of this.
* could experiment with `[Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control): no-transform`, but need to be able to replicate somehow - and it seems to be legit for an intermediary to transform/minify/recompress anyway.

**Comment by leowwang** [comment]
Indeed, we use cloudflare as a proxy.
I created a  Respect Strong ETags page role ,and it worked. 
Thanks again.
