### ISSUE TITLE
Allow passing execution status of previous step into scripts

### ISSUE THREAD

**Issue by keithy** [gocd/gocd#9975]
##### Issue Type

- Feature proposal

as per request https://groups.google.com/g/go-cd/c/yxvyHbEf3H0/m/K-W0e0I2aB8J

##### Summary

We collect metadata on PASS/FAIL but we have to work-around the fact that the previous exec step status is not provided.

##### Environment

This is our workaround.

```
              <exec command="bash" workingdir="Build">
                <arg>add-pipeline-step-to-metadata.sh</arg>
                <arg>#{build_pipeline}</arg>
                <arg>FAIL</arg>
                <runif status="failed" />
              </exec>
              <exec command="bash" workingdir="Build">
                <arg>add-pipeline-step-to-metadata.sh</arg>
                <arg>#{build_pipeline}</arg>
                <arg>PASS</arg>
                <runif status="passed" />
              </exec>
```

##### Possible Fix

Provide the previous status via an environment variable GO_EXEC_STATUS

**Comment by chadlwilson** [comment]
I would generally suggest folks use something like the https://github.com/gocd-contrib/script-executor-task for things like this rather than consecutive tasks that depend on one another, allowing all of the logic to be source controlled in one place; allowing you to add `trap`s and handle exit codes however you like, rather than relying on the pipeline and pipeline config to manage.

https://github.com/tomzo/gocd-yaml-config-plugin also has first class support for script tasks if you're using YAML pipelines-as-code.

I am curious how you collect this metadata however, that seems interesting. Obviously if you combined tasks, GoCD itself wouldn't have such metadata.
