### ISSUE TITLE
UI-based programs are not shown up after executed by a Custom Command task on Windows Agents

### ISSUE THREAD

**Issue by VanDng** [gocd/gocd#9990]
##### Issue Type

- Bug Report

##### Summary

I have a command task to execute a command which executes another program.
The command is executed successfully, the program is started/running successfully but its windows/UI is not shown up.

###### Basic environment details

* Go Version: `21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f).`
* JAVA Version: `15.0.2`
* OS: `Windows 10 10.0`

##### Steps to Reproduce

Create a `Custom Command` task with the following details:
- Command: start
- Arguments: "InstanceReference" /d "D:\Apps\InstanceReference" InstanceReference.exe

![image](https://user-images.githubusercontent.com/20492454/147405997-9c7e6090-fb0b-4600-8194-815632968432.png)

##### Expected Results

`InstanceReference.exe` will be running and showing up with a window.

##### Actual Results

`InstanceReference.exe` was running but **its window did NOT show up**.

![image](https://user-images.githubusercontent.com/20492454/147405764-9127920b-a73d-4bf4-9f84-736aeaf3f02b.png)
![image](https://user-images.githubusercontent.com/20492454/147405792-59cdf7c6-89eb-4025-afe9-4339ea40f0f2.png)

##### Possible Fix

N/A

##### Code snippets/Screenshots

There was no error or exception.

![image](https://user-images.githubusercontent.com/20492454/147406071-65da9e5b-7e6b-4f4f-af48-fb7e6fb78f4a.png)

##### Any other info

-  `InstanceReference.exe` is a UI program built with `.NET Core 3.1`. It has no problem if I execute the exact same command with `cmd` by myself. The program is executed successfully and its main window shows up normally.

- I tried with a different program `Calc` which is a built-in calculator on Windows. The issue also happened.

- I believe the problem is somewhere on the way the command proceeded, I do not know how Java so I can not go further.

**Comment by chadlwilson** [comment]
Did you install the agent via the installer, and is it running as a service? If so, the agent will probably be running as `SYSTEM`, not as your normal login user (I don't know the history of why the services are installed as SYSTEM rather than current user).

If you want to see a UI while jobs/tasks are running, you will probably need the agent to be running as your current user.

To do so, you could either 
* play around with changing which user the agent service runs as. I'm not sure the consequences of this, and it seems likely there will be issues with folders or files your user account needs access to that only `SYSTEM` has access to with the default installer. I am not sure on this part though - you could experiment.
* instead of using the installer/service, run the agent as [a generic zip](https://www.gocd.org/download/#zip) with `bin/go-agent.bat`. You'd need a Java runtime environment 13-15 installed and on the path or with `JAVA_HOME` specified but can run it anywhere.

**Comment by arvindsv** [comment]
Yes, @chadlwilson's response is right. There is some documentation mentioning this, but it is likely out of date (Windows menus, startup etc): https://docs.gocd.org/current/advanced_usage/ui_testing.html

I would suggest going with the second option as well.

**Comment by VanDng** [comment]
I made it work as expected.
@chadlwilson's response is right.
Thank you @chadlwilson and @arvindsv .

**Comment by VanDng** [comment]
For those who are curious to know what the root problem is, read the following references:
1/ https://stackoverflow.com/questions/11549881/java-service-wrapper-to-create-service-for-java-ui-application
2/ https://wrapper.tanukisoftware.com/doc/english/prop-ntservice-interactive.html
